CREATE index opinion_category_id_idx on wf_def_opinion_category(id);

DROP INDEX ACL_ENTRY_IDX_OBJECT;
DROP INDEX ACL_ENTRY_BATCH_IDX_OBJECT;
DROP INDEX ACL_ENTRY_IDX_MASK ;
DROP INDEX ACL_ENTRY_BATCH_IDX ;
DROP INDEX obj_id_iden_gran_mask_idx ;
CREATE index ACL_ENTRY_BATCH_IDX_OBJECT on acl_entry(OBJECT_ID_IDENTITY, SID, MASK,GRANTING);

DROP INDEX WF_DO_BATCH_IDX ;
CREATE index WF_DO_BATCH_IDX on wf_def_opinion(CREATOR,FLOW_DEF_ID,TASK_ID,content,MODIFY_TIME);