
-- Create/Recreate indexes
ALTER TABLE LOG_BUSINESS_OPERATION ADD INDEX LOG_BUSINESS_OPERATION_UNITID ( system_unit_id );

ALTER TABLE LOG_BUSINESS_OPERATION ADD INDEX LOG_BUSINESS_OPERATION_CTIME ( create_time );

-- Create/Recreate indexes
ALTER TABLE LOG_BUSINESS_DETAILS ADD INDEX LOG_BUSINESS_LOG_ID ( log_id );
