 CREATE TABLE BATCH_DATA_IMPORT_DETAILS_HIS (
  UUID NUMBER(20) PRIMARY KEY,
  ROW_INDEX NUMBER(10) DEFAULT NULL  ,
  STATUS NUMBER(1) DEFAULT NULL,
  BATCH_DATA_IMPORT_UUID NUMBER(20) ,
  IMPORT_DATA CLOB,
  ERROR_MSG CLOB,
  CREATE_TIME TIMESTAMP(6) DEFAULT NULL,
  MODIFY_TIME TIMESTAMP(6) DEFAULT NULL,
  CREATE_BY VARCHAR2(64) DEFAULT NULL,
  MODIFY_BY VARCHAR2(64) DEFAULT NULL
) ;


CREATE TABLE BATCH_DATA_IMPORT_HIS (
  UUID NUMBER(20) PRIMARY KEY,
  DATA_IMPORT_TYPE NUMBER(1) DEFAULT NULL  ,
  CREATE_TIME TIMESTAMP(6) DEFAULT NULL,
  MODIFY_TIME TIMESTAMP(6) DEFAULT NULL,
  CREATE_BY VARCHAR2(64) DEFAULT NULL,
  MODIFY_BY VARCHAR2(64) DEFAULT NULL

) ;

CREATE TABLE OAUTH_ACCESS_TOKEN (
  TOKEN_ID VARCHAR2(256) DEFAULT NULL,
  TOKEN BLOB,
  AUTHENTICATION_ID VARCHAR2(256) NOT NULL PRIMARY KEY,
  USER_NAME VARCHAR2(256) DEFAULT NULL,
  CLIENT_ID VARCHAR2(256) DEFAULT NULL,
  AUTHENTICATION BLOB,
  REFRESH_TOKEN VARCHAR2(256) DEFAULT NULL
) ;


CREATE TABLE OAUTH_CLIENT_DETAILS (
  UUID NUMBER(20) PRIMARY KEY,
  CLIENT_ID VARCHAR2(256) NOT NULL,
  CLIENT_NAME VARCHAR2(256) DEFAULT NULL,
  RESOURCE_IDS VARCHAR2(256) DEFAULT NULL,
  CLIENT_SECRET VARCHAR2(256) DEFAULT NULL,
  SCOPE VARCHAR2(256) DEFAULT 'READ,WRITE',
  AUTHORIZED_GRANT_TYPES VARCHAR2(256) DEFAULT NULL,
  WEB_SERVER_REDIRECT_URI VARCHAR2(256) DEFAULT NULL,
  AUTHORITIES VARCHAR2(256) DEFAULT NULL,
  ACCESS_TOKEN_VALIDITY NUMBER(11) DEFAULT NULL,
  REFRESH_TOKEN_VALIDITY NUMBER(11) DEFAULT NULL,
  ADDITIONAL_INFORMATION VARCHAR2(4000) DEFAULT NULL,
  AUTOAPPROVE VARCHAR2(256) DEFAULT NULL,
  CREATE_TIME TIMESTAMP(6) DEFAULT NULL,
  MODIFY_TIME TIMESTAMP(6) DEFAULT NULL,
  CREATE_BY VARCHAR2(64) DEFAULT NULL,
  MODIFY_BY VARCHAR2(64) DEFAULT NULL,
  LOGIN_PAGE VARCHAR2(256)
) ;


CREATE TABLE OAUTH_CLIENT_TOKEN (
  TOKEN_ID VARCHAR2(256) DEFAULT NULL,
  TOKEN BLOB,
  AUTHENTICATION_ID VARCHAR2(256) NOT NULL   PRIMARY KEY,
  USER_NAME VARCHAR2(256) DEFAULT NULL,
  CLIENT_ID VARCHAR2(256) DEFAULT NULL
) ;

CREATE TABLE OAUTH_CODE (
  CODE VARCHAR2(256) DEFAULT NULL,
  AUTHENTICATION BLOB
) ;


CREATE TABLE OAUTH_REFRESH_TOKEN (
  TOKEN_ID VARCHAR2(256) DEFAULT NULL,
  TOKEN BLOB,
  AUTHENTICATION BLOB
) ;



CREATE TABLE USER_ACCOUNT
(
  UUID           NUMBER(20) NOT NULL,
  ACCOUNT_NUMBER VARCHAR2(64) NOT NULL,
  PASSWORD       VARCHAR2(120),
  ENABLED        NUMBER(1) DEFAULT '1',
  CREATE_TIME    TIMESTAMP(6),
  MODIFY_TIME    TIMESTAMP(6),
  CREATE_BY      VARCHAR2(64),
  MODIFY_BY      VARCHAR2(64)
);

ALTER TABLE USER_ACCOUNT
  ADD PRIMARY KEY (UUID) ;
ALTER TABLE USER_ACCOUNT
  ADD UNIQUE (ACCOUNT_NUMBER) ;

INSERT INTO USER_ACCOUNT VALUES ('1136554904711593984', 'admin', '$2a$10$7xxw2wHkjG64lI8PocGDh.2gol9eQfjNsc1Alfe4nn0aLvJpL8p1y', '1', '2019-10-19 13:33:37', '2019-10-19 13:33:37', 'anonymousUser', 'anonymousUser');



CREATE TABLE USER_AUTHORITIES (
  UUID NUMBER(20) PRIMARY KEY,
  AUTHORITY VARCHAR2(50) NOT NULL,
  ACCOUNT_NUMBER VARCHAR2(64) NOT NULL,
  CREATE_TIME TIMESTAMP(6) DEFAULT NULL,
  MODIFY_TIME TIMESTAMP(6) DEFAULT NULL,
  CREATE_BY VARCHAR2(64) DEFAULT NULL,
  MODIFY_BY VARCHAR2(64) DEFAULT NULL
) ;

INSERT INTO USER_AUTHORITIES VALUES ('0', 'ROLE_USER', 'admin', NULL, NULL, NULL, NULL);
INSERT INTO USER_AUTHORITIES VALUES ('1', 'ROLE_ADMIN', 'admin', NULL, NULL, NULL, NULL);


CREATE TABLE USER_EXT_ACCOUNT (
  UUID NUMBER(20) PRIMARY KEY,
  ACCOUNT_UUID NUMBER(20)  ,
  SOURCE VARCHAR2(120) NOT NULL,
  EXT_ACCOUNT_NUMBER VARCHAR2(120) NOT NULL ,
  CREATE_TIME TIMESTAMP(6) DEFAULT NULL,
  MODIFY_TIME TIMESTAMP(6) DEFAULT NULL,
  CREATE_BY VARCHAR2(64) DEFAULT NULL,
  MODIFY_BY VARCHAR2(64) DEFAULT NULL

) ;

CREATE TABLE USER_INFO (
  UUID NUMBER(20) PRIMARY KEY,
  ACCOUNT_NUMBER VARCHAR2(64) NOT NULL,
  USER_NAME VARCHAR2(120) NOT NULL,
  IDENTIFIED_CODE VARCHAR2(64) DEFAULT NULL,
  GENDER NUMBER(1) DEFAULT NULL,
  BIRTH_DATE TIMESTAMP(6) DEFAULT NULL,
  CELLPHONE_NUMBER VARCHAR2(15) DEFAULT NULL,
  CREATE_TIME TIMESTAMP(6) DEFAULT NULL,
  MODIFY_TIME TIMESTAMP(6) DEFAULT NULL,
  CREATE_BY VARCHAR2(255) DEFAULT NULL,
  MODIFY_BY VARCHAR2(255) DEFAULT NULL

) ;

INSERT INTO USER_INFO VALUES ('1136554904711593985', 'admin', '系统管理员', NULL, NULL, NULL, '', '2019-10-19 13:33:37', '2019-10-19 13:33:37', 'ANONYMOUSUSER', 'ANONYMOUSUSER');
