CREATE TABLE CD_MATERIAL_DEFINITION
(
    "UUID"                  NUMBER(20, 0) NOT NULL,
    "CREATOR"               VARCHAR2(20 CHAR),
    "CREATE_TIME"           TIMESTAMP(6),
    "MODIFIER"              VARCHAR2(20 CHAR),
    "MODIFY_TIME"           TIMESTAMP(6),
    "REC_VER"               NUMBER(10, 0),
    "NAME"                  VARCHAR2(100 CHAR),
    "CODE"                  VARCHAR2(50 CHAR),
    "MEDIUM_TYPE"           VARCHAR2(20 CHAR),
    "FORMAT"                VARCHAR2(100 CHAR),
    "SAMPLE_REPO_FILE_UUID" VARCHAR2(200 CHAR),
    "DESCRIPTION"           VARCHAR2(1000 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE CD_MATERIAL_DEFINITION IS '材料定义';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION.CREATOR IS '创建人';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION.MODIFIER IS '修改人';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION.REC_VER IS '版本号';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION.NAME IS '材料名称';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION.CODE IS '材料编号';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION.MEDIUM_TYPE IS '材料形式：10原件、20复印件、30电子文档';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION.FORMAT IS '电子文档格式';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION.SAMPLE_REPO_FILE_UUID IS '样例文件UUID';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION.DESCRIPTION IS '材料说明';


CREATE TABLE CD_MATERIAL_DEFINITION_HIS
(
    "UUID"                  NUMBER(20, 0) NOT NULL,
    "CREATOR"               VARCHAR2(20 CHAR),
    "CREATE_TIME"           TIMESTAMP(6),
    "MODIFIER"              VARCHAR2(20 CHAR),
    "MODIFY_TIME"           TIMESTAMP(6),
    "REC_VER"               NUMBER(10, 0),
    "MATERIAL_DEF_UUID"     NUMBER(20, 0),
    "NAME"                  VARCHAR2(100 CHAR),
    "CODE"                  VARCHAR2(20 CHAR),
    "MEDIUM_TYPE"           VARCHAR2(20 CHAR),
    "FORMAT"                VARCHAR2(100 CHAR),
    "SAMPLE_REPO_FILE_UUID" VARCHAR2(200 CHAR),
    "DESCRIPTION"           VARCHAR2(1000 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE CD_MATERIAL_DEFINITION_HIS IS '材料定义历史信息';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.CREATOR IS '创建人';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.MODIFIER IS '修改人';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.REC_VER IS '版本号';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.MATERIAL_DEF_UUID IS '材料定义UUID';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.NAME IS '材料名称';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.CODE IS '材料编号';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.MEDIUM_TYPE IS '材料形式：10原件、20复印件、30电子文档';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.FORMAT IS '电子文档格式';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.SAMPLE_REPO_FILE_UUID IS '样例文件UUID';
COMMENT
ON COLUMN CD_MATERIAL_DEFINITION_HIS.DESCRIPTION IS '材料说明';


CREATE TABLE CD_MATERIAL
(
    "UUID"              NUMBER(20, 0) NOT NULL,
    "CREATOR"           VARCHAR2(20 CHAR),
    "CREATE_TIME"       TIMESTAMP(6),
    "MODIFIER"          VARCHAR2(20 CHAR),
    "MODIFY_TIME"       TIMESTAMP(6),
    "REC_VER"           NUMBER(10, 0),
    "MATERIAL_DEF_UUID" NUMBER(20, 0),
    "MATERIAL_NAME"     VARCHAR2(100 CHAR),
    "MATERIAL_CODE"     VARCHAR2(50 CHAR),
    "BIZ_TYPE"          VARCHAR2(20 CHAR),
    "BIZ_ID"            VARCHAR2(50 CHAR),
    "DATA_UUID"         VARCHAR2(50 CHAR),
    "PURPOSE"           VARCHAR2(50 CHAR),
    "OWNER_ID"          VARCHAR2(50 CHAR),
    "VERSION"           NUMBER(10, 1),
    "REPO_FILE_UUIDS"   VARCHAR2(4000 CHAR),
    "VALIDATION_FLAG"   VARCHAR2(2 CHAR),
    "ATTRIBUTES"        CLOB,
    "REMARK"            VARCHAR2(500 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE CD_MATERIAL IS '材料实例化数据';
COMMENT
ON COLUMN CD_MATERIAL.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN CD_MATERIAL.CREATOR IS '创建人';
COMMENT
ON COLUMN CD_MATERIAL.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN CD_MATERIAL.MODIFIER IS '修改人';
COMMENT
ON COLUMN CD_MATERIAL.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN CD_MATERIAL.REC_VER IS '版本号';
COMMENT
ON COLUMN CD_MATERIAL.MATERIAL_DEF_UUID IS '材料定义UUID';
COMMENT
ON COLUMN CD_MATERIAL.MATERIAL_NAME IS '材料名称';
COMMENT
ON COLUMN CD_MATERIAL.MATERIAL_CODE IS '材料编号';
COMMENT
ON COLUMN CD_MATERIAL.BIZ_TYPE IS '所在业务类型';
COMMENT
ON COLUMN CD_MATERIAL.BIZ_ID IS '所在业务ID';
COMMENT
ON COLUMN CD_MATERIAL.DATA_UUID IS '所在业务数据UUID';
COMMENT
ON COLUMN CD_MATERIAL.PURPOSE IS '所在业务场景';
COMMENT
ON COLUMN CD_MATERIAL.OWNER_ID IS '所有者ID';
COMMENT
ON COLUMN CD_MATERIAL.VERSION IS '版本号';
COMMENT
ON COLUMN CD_MATERIAL.REPO_FILE_UUIDS IS '材料附件UUID列表，多个以分号隔开';
COMMENT
ON COLUMN CD_MATERIAL.VALIDATION_FLAG IS '材料有效标识，1有效，0无效';
COMMENT
ON COLUMN CD_MATERIAL.ATTRIBUTES IS '材料附件扩展属性信息';
COMMENT
ON COLUMN CD_MATERIAL.REMARK IS '备注';


CREATE TABLE CD_MATERIAL_HIS
(
    "UUID"              NUMBER(20, 0) NOT NULL,
    "CREATOR"           VARCHAR2(20 CHAR),
    "CREATE_TIME"       TIMESTAMP(6),
    "MODIFIER"          VARCHAR2(20 CHAR),
    "MODIFY_TIME"       TIMESTAMP(6),
    "REC_VER"           NUMBER(10, 0),
    "BIZ_MATERIAL_UUID" NUMBER(20, 0),
    "MATERIAL_DEF_UUID" NUMBER(20, 0),
    "MATERIAL_NAME"     VARCHAR2(100 CHAR),
    "MATERIAL_CODE"     VARCHAR2(20 CHAR),
    "BIZ_TYPE"          VARCHAR2(20 CHAR),
    "BIZ_ID"            VARCHAR2(50 CHAR),
    "DATA_UUID"         VARCHAR2(50 CHAR),
    "PURPOSE"           VARCHAR2(50 CHAR),
    "OWNER_ID"          VARCHAR2(50 CHAR),
    "VERSION"           NUMBER(10, 1),
    "REPO_FILE_UUIDS"   VARCHAR2(4000 CHAR),
    "VALIDATION_FLAG"   VARCHAR2(20 CHAR),
    "ATTRIBUTES"        CLOB,
    "REMARK"            VARCHAR2(500 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE CD_MATERIAL_HIS IS '材料实例化数据历史版本';
COMMENT
ON COLUMN CD_MATERIAL_HIS.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN CD_MATERIAL_HIS.CREATOR IS '创建人';
COMMENT
ON COLUMN CD_MATERIAL_HIS.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN CD_MATERIAL_HIS.MODIFIER IS '修改人';
COMMENT
ON COLUMN CD_MATERIAL_HIS.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN CD_MATERIAL_HIS.REC_VER IS '版本号';
COMMENT
ON COLUMN CD_MATERIAL_HIS.BIZ_MATERIAL_UUID IS '业务材料数据UUID';
COMMENT
ON COLUMN CD_MATERIAL_HIS.MATERIAL_DEF_UUID IS '材料定义UUID';
COMMENT
ON COLUMN CD_MATERIAL_HIS.MATERIAL_NAME IS '材料名称';
COMMENT
ON COLUMN CD_MATERIAL_HIS.MATERIAL_CODE IS '材料编号';
COMMENT
ON COLUMN CD_MATERIAL_HIS.BIZ_TYPE IS '所在业务类型';
COMMENT
ON COLUMN CD_MATERIAL_HIS.BIZ_ID IS '所在业务ID';
COMMENT
ON COLUMN CD_MATERIAL_HIS.DATA_UUID IS '所在业务数据UUID';
COMMENT
ON COLUMN CD_MATERIAL_HIS.PURPOSE IS '所在业务场景';
COMMENT
ON COLUMN CD_MATERIAL_HIS.OWNER_ID IS '所有者ID';
COMMENT
ON COLUMN CD_MATERIAL_HIS.VERSION IS '版本号';
COMMENT
ON COLUMN CD_MATERIAL_HIS.REPO_FILE_UUIDS IS '材料附件UUID列表，多个以分号隔开';
COMMENT
ON COLUMN CD_MATERIAL_HIS.VALIDATION_FLAG IS '材料有效标识，1有效，0无效';
COMMENT
ON COLUMN CD_MATERIAL_HIS.ATTRIBUTES IS '材料附件扩展属性信息';
COMMENT
ON COLUMN CD_MATERIAL_HIS.REMARK IS '备注';