CREATE TABLE "WF_TASK_BRANCH" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "PARALLEL_TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "PARALLEL_TASK_ID" VARCHAR2(255 CHAR), 
  "INIT_TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "CURRENT_TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "JOIN_TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "TODO_ID" VARCHAR2(500 CHAR), 
  "TODO_NAME" VARCHAR2(500 CHAR), 
  "BRANCH_TYPE" VARCHAR2(2 CHAR), 
  "IS_MERGE" NUMBER(1,0), 
  "IS_SHARE" NUMBER(1,0), 
  "COMPLETED" NUMBER(1,0), 
  "COMPLETION_STATE" NUMBER(10,0) DEFAULT 0, 
  "SORT_ORDER" NUMBER(10,0), 
   PRIMARY KEY ("UUID")
   ) ;
 
   COMMENT ON COLUMN "WF_TASK_BRANCH"."UUID" IS 'UUID，系统字段';
 
   COMMENT ON COLUMN "WF_TASK_BRANCH"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "WF_TASK_BRANCH"."CREATOR" IS '创建人';
 
   COMMENT ON COLUMN "WF_TASK_BRANCH"."MODIFIER" IS '修改人';
 
   COMMENT ON COLUMN "WF_TASK_BRANCH"."MODIFY_TIME" IS '修改时间';
 
   COMMENT ON COLUMN "WF_TASK_BRANCH"."REC_VER" IS '版本号';
 
   COMMENT ON COLUMN "WF_TASK_BRANCH"."FLOW_INST_UUID" IS '流程实例UUID';

   COMMENT ON COLUMN "WF_TASK_BRANCH"."PARALLEL_TASK_INST_UUID" IS '发起并行任务的环节实例UUID';
   
   COMMENT ON COLUMN "WF_TASK_BRANCH"."PARALLEL_TASK_ID" IS '发起并行任务的环节ID';

   COMMENT ON COLUMN "WF_TASK_BRANCH"."INIT_TASK_INST_UUID" IS '并行任务的第一个环节实例UUID';

   COMMENT ON COLUMN "WF_TASK_BRANCH"."CURRENT_TASK_INST_UUID" IS '当前并行分支所在的环节实例UUID';

   COMMENT ON COLUMN "WF_TASK_BRANCH"."JOIN_TASK_INST_UUID" IS '聚合的环节实例UUID';

   COMMENT ON COLUMN "WF_TASK_BRANCH"."TODO_ID" IS '办理对象ID';
   
   COMMENT ON COLUMN "WF_TASK_BRANCH"."TODO_NAME" IS '办理对象名称';
 
   COMMENT ON COLUMN "WF_TASK_BRANCH"."BRANCH_TYPE" IS '0、静态分支;1、独立分支;2、主办分支;3、协办分支';
   
   COMMENT ON COLUMN "WF_TASK_BRANCH"."IS_MERGE" IS '是否合并';

   COMMENT ON COLUMN "WF_TASK_BRANCH"."IS_SHARE" IS '是否共享';
 
   COMMENT ON COLUMN "WF_TASK_BRANCH"."COMPLETED" IS '标记分支是否已经完成';
 
   COMMENT ON COLUMN "WF_TASK_BRANCH"."COMPLETION_STATE" IS '完成状态 0运行中、1正常结束、2终止、3撤销、4退回';
 
   COMMENT ON COLUMN "WF_TASK_BRANCH"."SORT_ORDER" IS '排序';

   
-- Create/Recreate indexes 
create index WF_TB_PL_TASK_INST_UUID_IDX on WF_TASK_BRANCH (parallel_task_inst_uuid);
create index WF_TB_CR_TASK_INST_UUID_IDX on WF_TASK_BRANCH (current_task_inst_uuid);
create index WF_TB_FLOW_INST_UUID_IDX on WF_TASK_BRANCH (flow_inst_uuid);

