-- 部门下增加分管领导 相关需求
COMMENT ON COLUMN MULTI_ORG_ELEMENT_LEADER.LEADER_TYPE IS '领导类型 0：负责人，1：分管领导，2，管理员';

-- 先备份
create table MULTI_ORG_ELEMENT_LEADER_BAK as select * from MULTI_ORG_ELEMENT_LEADER;

-- 调整分管领导值  不可重复执行
UPDATE MULTI_ORG_ELEMENT_LEADER SET ELE_ID = TARGET_OBJ_ID, TARGET_OBJ_ID = ELE_ID, ELE_ORG_VERSION_ID = TARGET_OBJ_ORG_VERSION_ID, TARGET_OBJ_ORG_VERSION_ID = ELE_ORG_VERSION_ID WHERE LEADER_TYPE=1;

