-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
CREATE TABLE "BOOK_HISTORY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ACTION_NAME" VARCHAR2(255 CHAR), 
  "APPLICANT" VARCHAR2(255 CHAR), 
  "APPLICANT_ID" VARCHAR2(255 CHAR), 
  "OPERATOR" VARCHAR2(255 CHAR), 
  "OPERATOR_ID" VARCHAR2(255 CHAR), 
  "REMARKS" VARCHAR2(255 CHAR), 
  "TASK_NAME" VARCHAR2(255 CHAR)
   ) ;
   
CREATE TABLE "CALENDAR_EMPLOY_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BEGIN_TIME" TIMESTAMP (6), 
  "EMPLOY_NAME" VARCHAR2(255 CHAR), 
  "EMPLOY_WORK" VARCHAR2(255 CHAR), 
  "END_TIME" TIMESTAMP (6), 
  "FLOW_UUID" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "RESOURCE_NAME" VARCHAR2(255 CHAR), 
  "RESOURCE_PLACE" VARCHAR2(255 CHAR), 
  "RESOURCE_PRE_EMPLOY" VARCHAR2(255 CHAR), 
  "TASK_UUID" VARCHAR2(255 CHAR), 
  "EMPLOY_LEADER" VARCHAR2(255 CHAR), 
  "EMPLOY_PHONE_NUMBER" VARCHAR2(255 CHAR)
   ) ;
   
CREATE TABLE "GOODS_ATTR" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ALLOW_ALL_USER_APPLY" NUMBER(1,0), 
  "ALLOW_READ_USERS_NAME" VARCHAR2(255 CHAR), 
  "ALLOW_READ_USERS_VALUE" VARCHAR2(255 CHAR), 
  "BS_FLOW_ID" VARCHAR2(255 CHAR), 
  "BS_FLOW_NAME" VARCHAR2(255 CHAR), 
  "CX_FLOW_ID" VARCHAR2(255 CHAR), 
  "CX_FLOW_NAME" VARCHAR2(255 CHAR), 
  "LOWEST_NUM" NUMBER(10,0), 
  "LOWEST_WARNING" NUMBER(1,0), 
  "LY_FLOW_ID" VARCHAR2(255 CHAR), 
  "LY_FLOW_NAME" VARCHAR2(255 CHAR), 
  "RK_FLOW_ID" VARCHAR2(255 CHAR), 
  "RK_FLOW_NAME" VARCHAR2(255 CHAR), 
  "USE_PASS_WORD" NUMBER(1,0)
   ) ;