CREATE TABLE "APP_WIDGET_DEFINITION" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"ID" VARCHAR2(255 CHAR), 
	"WTYPE" VARCHAR2(255 CHAR), 
	"DEFINITION_JSON" CLOB, 
	"REF_WIDGET_DEF_UUID" VARCHAR2(255 CHAR), 
	"APP_PAGE_UUID" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "APP_WIDGET_DEFINITION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "APP_WIDGET_DEFINITION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "APP_WIDGET_DEFINITION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "APP_WIDGET_DEFINITION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "APP_WIDGET_DEFINITION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "APP_WIDGET_DEFINITION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "APP_WIDGET_DEFINITION"."NAME" IS '名称';
   COMMENT ON COLUMN "APP_WIDGET_DEFINITION"."ID" IS 'ID';
   COMMENT ON COLUMN "APP_WIDGET_DEFINITION"."WTYPE" IS '组件类型';
   COMMENT ON COLUMN "APP_WIDGET_DEFINITION"."DEFINITION_JSON" IS '定义JSON信息';
   COMMENT ON COLUMN "APP_WIDGET_DEFINITION"."REF_WIDGET_DEF_UUID" IS '引用的组件定义UUID, 为空表示没引用';
   COMMENT ON COLUMN "APP_WIDGET_DEFINITION"."APP_PAGE_UUID" IS '组件定义所在的页面定义UUID';
