CREATE TABLE "APP_APPLICATION" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"NAME" VARCHAR2(255), 
	"ID" VARCHAR2(255), 
	"CODE" VARCHAR2(255), 
	"ENABLED" NUMBER(1,0), 
	"CONFIGURABLE" NUMBER(1,0), 
	"TYPE" NUMBER(10,0), 
	"JS_MODULE" VARCHAR2(255), 
	"REMARK" VARCHAR2(255), 
	 PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "APP_APPLICATION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "APP_APPLICATION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "APP_APPLICATION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "APP_APPLICATION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "APP_APPLICATION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "APP_APPLICATION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "APP_APPLICATION"."NAME" IS '名称';
   COMMENT ON COLUMN "APP_APPLICATION"."ID" IS 'ID';
   COMMENT ON COLUMN "APP_APPLICATION"."CODE" IS '编号';
   COMMENT ON COLUMN "APP_APPLICATION"."ENABLED" IS '是否启用';
   COMMENT ON COLUMN "APP_APPLICATION"."CONFIGURABLE" IS '标识该应用对于普通用户是否可配置';
   COMMENT ON COLUMN "APP_APPLICATION"."TYPE" IS '应用类别 1(静态元素) 、2 (URL页面)、3(JavaScript脚本)、4(视图) 、5(报表)、6(工作台)';
   COMMENT ON COLUMN "APP_APPLICATION"."JS_MODULE" IS '加载自定义JavaScript模块，以模块化的形式开发JavaScript，多个以逗号隔开';
   COMMENT ON COLUMN "APP_APPLICATION"."REMARK" IS '备注';
   
   
   
CREATE TABLE "APP_MODULE" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"CODE" VARCHAR2(255 CHAR), 
	"ENABLED" NUMBER(1,0), 
	"ID" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"REMARK" VARCHAR2(255 CHAR), 
	"JS_MODULE" VARCHAR2(255), 
	"PARENT_UUID" VARCHAR2(255), 
	 PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "APP_MODULE"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "APP_MODULE"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "APP_MODULE"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "APP_MODULE"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "APP_MODULE"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "APP_MODULE"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "APP_MODULE"."CODE" IS '编号';
   COMMENT ON COLUMN "APP_MODULE"."ENABLED" IS '是否启用';
   COMMENT ON COLUMN "APP_MODULE"."ID" IS 'ID';
   COMMENT ON COLUMN "APP_MODULE"."NAME" IS '名称';
   COMMENT ON COLUMN "APP_MODULE"."REMARK" IS '备注';
   COMMENT ON COLUMN "APP_MODULE"."JS_MODULE" IS '加载自定义JavaScript模块，以模块化的形式开发JavaScript，多个以逗号隔开';
   COMMENT ON COLUMN "APP_MODULE"."PARENT_UUID" IS '上级模块UUID';
   
   
   
CREATE TABLE "APP_MODULE_APPLICATION" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"APP_MODULE_UUID" VARCHAR2(255 CHAR), 
	"APP_APPLICATION_UUID" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "APP_MODULE_APPLICATION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "APP_MODULE_APPLICATION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "APP_MODULE_APPLICATION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "APP_MODULE_APPLICATION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "APP_MODULE_APPLICATION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "APP_MODULE_APPLICATION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "APP_MODULE_APPLICATION"."APP_MODULE_UUID" IS '模块UUID';
   COMMENT ON COLUMN "APP_MODULE_APPLICATION"."APP_APPLICATION_UUID" IS '应用UUID';
   
   
   
CREATE TABLE "APP_PAGE_CONFIGURATION" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"OWNER_ID" VARCHAR2(255 CHAR), 
	"APP_TYPE" NUMBER(10,0), 
	"APP_UUID" VARCHAR2(255 CHAR), 
	"PAGE_UUID" VARCHAR2(255 CHAR), 
	"PAGE_INHERITING" NUMBER(1,0), 
	"TARGET_VIEWPORT" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "APP_PAGE_CONFIGURATION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "APP_PAGE_CONFIGURATION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "APP_PAGE_CONFIGURATION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "APP_PAGE_CONFIGURATION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "APP_PAGE_CONFIGURATION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "APP_PAGE_CONFIGURATION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "APP_PAGE_CONFIGURATION"."OWNER_ID" IS '系统页面所有者';
   COMMENT ON COLUMN "APP_PAGE_CONFIGURATION"."APP_TYPE" IS '应用类型1、系统；2、模块；3、应用';
   COMMENT ON COLUMN "APP_PAGE_CONFIGURATION"."APP_UUID" IS '应用UUID';
   COMMENT ON COLUMN "APP_PAGE_CONFIGURATION"."PAGE_UUID" IS '页面UUID';
   COMMENT ON COLUMN "APP_PAGE_CONFIGURATION"."PAGE_INHERITING" IS '页面继承';
   COMMENT ON COLUMN "APP_PAGE_CONFIGURATION"."TARGET_VIEWPORT" IS '目标窗口，1、无；2、新页面；3、页面默认工作区; 4、页面位置;';
   
   
   
CREATE TABLE "APP_PAGE_DEFINITION" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"ID" VARCHAR2(255 CHAR), 
	"CODE" VARCHAR2(255 CHAR), 
	"CATEGORY_CODE" VARCHAR2(255 CHAR), 
	"CATEGORY_NAME" VARCHAR2(255 CHAR), 
	"SHARED" NUMBER(1,0), 
	"INHERITING_PAGE_UUID" VARCHAR2(255 CHAR), 
	"DEFINITION_JSON" CLOB, 
	"REMARK" VARCHAR2(255 CHAR), 
	"HTML" CLOB, 
	 PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."NAME" IS '名称';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."ID" IS 'ID';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."CODE" IS '编号';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."CATEGORY_CODE" IS '分类代码';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."CATEGORY_NAME" IS '分类名称';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."SHARED" IS '是否共享的页面';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."INHERITING_PAGE_UUID" IS '继承的页面UUID';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."DEFINITION_JSON" IS '定义JSON信息';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."REMARK" IS '备注';
   COMMENT ON COLUMN "APP_PAGE_DEFINITION"."HTML" IS 'JSON定义生成的HTML';
   
   
   
CREATE TABLE "APP_SYSTEM" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"CODE" VARCHAR2(255 CHAR), 
	"ENABLED" NUMBER(1,0), 
	"ID" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"REMARK" VARCHAR2(255 CHAR), 
	"THEME" VARCHAR2(255), 
	"JS_MODULE" VARCHAR2(255), 
	 PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "APP_SYSTEM"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "APP_SYSTEM"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "APP_SYSTEM"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "APP_SYSTEM"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "APP_SYSTEM"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "APP_SYSTEM"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "APP_SYSTEM"."CODE" IS '编号';
   COMMENT ON COLUMN "APP_SYSTEM"."ENABLED" IS '是否启用';
   COMMENT ON COLUMN "APP_SYSTEM"."ID" IS 'ID';
   COMMENT ON COLUMN "APP_SYSTEM"."NAME" IS '名称';
   COMMENT ON COLUMN "APP_SYSTEM"."REMARK" IS '备注';
   COMMENT ON COLUMN "APP_SYSTEM"."THEME" IS '系统默认主题';
   COMMENT ON COLUMN "APP_SYSTEM"."JS_MODULE" IS '加载自定义JavaScript模块，以模块化的形式开发JavaScript，多个以逗号隔开';
   
   

CREATE TABLE "APP_SYSTEM_APPLICATION" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"APP_SYSTEM_UUID" VARCHAR2(255 CHAR), 
	"APP_APPLICATION_UUID" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "APP_SYSTEM_APPLICATION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "APP_SYSTEM_APPLICATION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "APP_SYSTEM_APPLICATION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "APP_SYSTEM_APPLICATION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "APP_SYSTEM_APPLICATION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "APP_SYSTEM_APPLICATION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "APP_SYSTEM_APPLICATION"."APP_SYSTEM_UUID" IS '系统UUID';
   COMMENT ON COLUMN "APP_SYSTEM_APPLICATION"."APP_APPLICATION_UUID" IS '应用UUID';
   
   
   
CREATE TABLE "APP_SYSTEM_MODULE" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"APP_SYSTEM_UUID" VARCHAR2(255 CHAR), 
	"APP_MODULE_UUID" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "APP_SYSTEM_MODULE"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "APP_SYSTEM_MODULE"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "APP_SYSTEM_MODULE"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "APP_SYSTEM_MODULE"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "APP_SYSTEM_MODULE"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "APP_SYSTEM_MODULE"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "APP_SYSTEM_MODULE"."APP_SYSTEM_UUID" IS '系统UUID';
   COMMENT ON COLUMN "APP_SYSTEM_MODULE"."APP_MODULE_UUID" IS '模块UUID';
