CREATE TABLE "APP_PRODUCT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "APP_PRODUCT"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "APP_PRODUCT"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "APP_PRODUCT"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "APP_PRODUCT"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "APP_PRODUCT"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "APP_PRODUCT"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "APP_PRODUCT"."CODE" IS '编号';
   COMMENT ON COLUMN "APP_PRODUCT"."ID" IS 'ID';
   COMMENT ON COLUMN "APP_PRODUCT"."NAME" IS '名称';
   COMMENT ON COLUMN "APP_PRODUCT"."REMARK" IS '备注';
   


CREATE TABLE "APP_PRODUCT_INTEGRATION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "APP_PRODUCT_UUID" VARCHAR2(255 CHAR),
  "DATA_UUID" VARCHAR2(255 CHAR), 
  "DATA_NAME" VARCHAR2(255 CHAR), 
  "DATA_ID" VARCHAR2(255 CHAR), 
  "DATA_TYPE" VARCHAR2(255 CHAR), 
  "SORT_ORDER" NUMBER(10,0),
  "PARENT_UUID" VARCHAR2(255 CHAR),
   PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."APP_PRODUCT_UUID" IS '产品UUID';
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."DATA_UUID" IS '数据UUID';
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."DATA_NAME" IS '数据名称';
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."DATA_ID" IS '数据ID';
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."DATA_TYPE" IS '数据类型，1(系统)、2(模块)、3(应用)、4(功能)';
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."SORT_ORDER" IS '排序号';
   COMMENT ON COLUMN "APP_PRODUCT_INTEGRATION"."PARENT_UUID" IS '上级数据UUID';
   