

CREATE TABLE "CD_DATA_MAPPER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "MAP_ID" VARCHAR2(4000 CHAR), 
  "VERSION" FLOAT, 
  "MAPPING" CLOB, 
   PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "CD_DATA_MAPPER"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "CD_DATA_MAPPER"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "CD_DATA_MAPPER"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "CD_DATA_MAPPER"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "CD_DATA_MAPPER"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "CD_DATA_MAPPER"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "CD_DATA_MAPPER"."NAME" IS '名称';
   COMMENT ON COLUMN "CD_DATA_MAPPER"."MAP_ID" IS 'ID';
   COMMENT ON COLUMN "CD_DATA_MAPPER"."VERSION" IS '版本号';
   COMMENT ON COLUMN "CD_DATA_MAPPER"."MAPPING" IS '配置';