CREATE TABLE "BIZP_PROCESS_CATEGORY" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"ID" VARCHAR2(255 CHAR), 
	"CODE" VARCHAR2(255 CHAR), 
	"REMARK" VARCHAR2(255 CHAR), 
	"PARENT_UUID" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("UUID")
   );
   COMMENT ON COLUMN "BIZP_PROCESS_CATEGORY"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "BIZP_PROCESS_CATEGORY"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "BIZP_PROCESS_CATEGORY"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "BIZP_PROCESS_CATEGORY"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "BIZP_PROCESS_CATEGORY"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "BIZP_PROCESS_CATEGORY"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "BIZP_PROCESS_CATEGORY"."NAME" IS '名称';
   COMMENT ON COLUMN "BIZP_PROCESS_CATEGORY"."ID" IS 'ID';
   COMMENT ON COLUMN "BIZP_PROCESS_CATEGORY"."CODE" IS '编号';
   COMMENT ON COLUMN "BIZP_PROCESS_CATEGORY"."REMARK" IS '备注';
   COMMENT ON COLUMN "BIZP_PROCESS_CATEGORY"."PARENT_UUID" IS '上级分类UUID';
   COMMENT ON TABLE "BIZP_PROCESS_CATEGORY"  IS '业务过程分类';
   
   

CREATE TABLE "BIZP_PROCESS_DEFINITION" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"ID" VARCHAR2(255 CHAR), 
	"CODE" VARCHAR2(255 CHAR), 
	"REMARK" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(10,1), 
	"IS_ENABLED" NUMBER(1,0), 
	"CATEGORY" VARCHAR2(255 CHAR), 
	"DEFINITION_JSON" CLOB, 
	 PRIMARY KEY ("UUID")
   );
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."NAME" IS '名称';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."ID" IS 'ID';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."CODE" IS '编号';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."REMARK" IS '备注';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."VERSION" IS '版本';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."IS_ENABLED" IS '是否启用';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."CATEGORY" IS '业务流程分类ID';
   COMMENT ON COLUMN "BIZP_PROCESS_DEFINITION"."DEFINITION_JSON" IS '定义JSON信息';
   COMMENT ON TABLE "BIZP_PROCESS_DEFINITION"  IS '业务过程定义';
   
   
   
CREATE TABLE "BIZP_PROCESS_INSTANCE" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"ID" VARCHAR2(255 CHAR), 
	"TITLE" VARCHAR2(255 CHAR), 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"TIME_LIMIT_TYPE" NUMBER(10,0), 
	"TIME_LIMIT" NUMBER(10,1), 
	"CURRENT_STATE" VARCHAR2(255 CHAR), 
	"MAJOR_ORG_IDS" VARCHAR2(255 CHAR), 
	"MINOR_ORG_IDS" VARCHAR2(255 CHAR), 
	"SUPERVISE_ORG_IDS" VARCHAR2(255 CHAR), 
	"PARENT_PROCE_INST_UUID" VARCHAR2(255 CHAR), 
	"PROC_DEF_UUID" VARCHAR2(255 CHAR), 
	"TIMING_STATE" NUMBER(1,0), 
	"OVER_DUE_STATE" NUMBER(1,0), 
	"DUE_TIME" TIMESTAMP (6), 
	"COMPLETED_STATE" NUMBER(10,0), 
	"BUSINESS_DATA_UUID" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."NAME" IS '名称';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."ID" IS 'ID';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."TITLE" IS '标题';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."START_TIME" IS '开始时间';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."END_TIME" IS '结束时间';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."TIME_LIMIT_TYPE" IS '时限类型1、工作日，2、日历日';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."TIME_LIMIT" IS '时限';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."CURRENT_STATE" IS '当前状态';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."MAJOR_ORG_IDS" IS '主办ID，多个以分号隔开';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."MINOR_ORG_IDS" IS '协办ID，多个以分号隔开';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."SUPERVISE_ORG_IDS" IS '督办ID，多个以分号隔开';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."PARENT_PROCE_INST_UUID" IS '上级过程实例UUID';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."PROC_DEF_UUID" IS '过程定义UUID';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."TIMING_STATE" IS '计时状态';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."OVER_DUE_STATE" IS '逾期状态';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."DUE_TIME" IS '到期时间';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."COMPLETED_STATE" IS '完成状态，0未完成，1已完成';
   COMMENT ON COLUMN "BIZP_PROCESS_INSTANCE"."BUSINESS_DATA_UUID" IS '业务数据UUID';
   COMMENT ON TABLE "BIZP_PROCESS_INSTANCE"  IS '业务过程实例';
   
   
   
CREATE TABLE "BIZP_TASK_INSTANCE" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"ID" VARCHAR2(255 CHAR), 
	"OWNER" VARCHAR2(255 CHAR), 
	"START_TIME" TIMESTAMP (6), 
	"END_TIME" TIMESTAMP (6), 
	"TIME_LIMIT_TYPE" NUMBER(10,0), 
	"TIME_LIMIT" NUMBER(10,1), 
	"CURRENT_STATE" VARCHAR2(255 CHAR), 
	"CURRENT_RATIO" NUMBER(5,2), 
	"COMPLETED_STATE" NUMBER(1,0), 
	"FRONT_TASK_ID" VARCHAR2(255 CHAR), 
	"TIMING_STATE" NUMBER(1,0), 
	"OVER_DUE_STATE" NUMBER(1,0), 
	"DUE_TIME" TIMESTAMP (6), 
	"PARENT_TASK_INST_UUID" VARCHAR2(255 CHAR), 
	"PROC_INST_UUID" VARCHAR2(255 CHAR), 
	"PROC_DEF_UUID" VARCHAR2(255 CHAR), 
	"MILESTONE" NUMBER(10,0), 
	 PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."NAME" IS '名称';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."ID" IS 'ID';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."OWNER" IS '任务所有者ID，多个以分号隔开';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."START_TIME" IS '开始时间';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."END_TIME" IS '结束时间';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."TIME_LIMIT_TYPE" IS '时限类型1、工作日，2、日历日';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."TIME_LIMIT" IS '时限';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."CURRENT_STATE" IS '当前状态';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."CURRENT_RATIO" IS '当前任务完成进度';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."COMPLETED_STATE" IS '完成状态，0未完成，1已完成';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."FRONT_TASK_ID" IS '前置任务ID，多个以分号隔开';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."TIMING_STATE" IS '计时状态';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."OVER_DUE_STATE" IS '逾期状态';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."DUE_TIME" IS '到期时间';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."PARENT_TASK_INST_UUID" IS '上级任务的UUID';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."PROC_INST_UUID" IS '任务所在过程的过程UUID';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."PROC_DEF_UUID" IS '过程定义UUID';
   COMMENT ON COLUMN "BIZP_TASK_INSTANCE"."MILESTONE" IS '里程碑，0不标记，1决定性里程碑，2全部标记里程碑';
   COMMENT ON TABLE "BIZP_TASK_INSTANCE"  IS '业务过程任务实例';
   
   
   
CREATE TABLE "BIZP_TASK_OPERATION" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"OPERATOR" VARCHAR2(255 CHAR), 
	"OPERATE_TIME" TIMESTAMP (6), 
	"TASK_ID" VARCHAR2(255 CHAR), 
	"TASK_INST_UUID" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("UUID")
   );
   COMMENT ON COLUMN "BIZP_TASK_OPERATION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "BIZP_TASK_OPERATION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "BIZP_TASK_OPERATION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "BIZP_TASK_OPERATION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "BIZP_TASK_OPERATION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "BIZP_TASK_OPERATION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "BIZP_TASK_OPERATION"."OPERATOR" IS '操作人ID';
   COMMENT ON COLUMN "BIZP_TASK_OPERATION"."OPERATE_TIME" IS '操作时间';
   COMMENT ON COLUMN "BIZP_TASK_OPERATION"."TASK_ID" IS '任务ID';
   COMMENT ON COLUMN "BIZP_TASK_OPERATION"."TASK_INST_UUID" IS '任务实例UUID';
   COMMENT ON TABLE "BIZP_TASK_OPERATION"  IS '业务过程任务操作表';
   
   
   
CREATE TABLE "BIZP_PROCESS_FLOW_RELATION" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"BIZP_PROC_DEF_UUID" VARCHAR2(255 CHAR), 
	"BIZP_PROC_DEF_ID" VARCHAR2(255 CHAR), 
	"BIZP_TASK_ID" VARCHAR2(255 CHAR), 
	"BIZP_TASK_NAME" VARCHAR2(255 CHAR), 
	"WF_FLOW_DEF_ID" VARCHAR2(255 CHAR), 
	"WF_FLOW_DEF_UUID" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "BIZP_PROCESS_FLOW_RELATION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "BIZP_PROCESS_FLOW_RELATION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "BIZP_PROCESS_FLOW_RELATION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "BIZP_PROCESS_FLOW_RELATION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "BIZP_PROCESS_FLOW_RELATION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "BIZP_PROCESS_FLOW_RELATION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "BIZP_PROCESS_FLOW_RELATION"."BIZP_PROC_DEF_UUID" IS '业务流程定义UUID';
   COMMENT ON COLUMN "BIZP_PROCESS_FLOW_RELATION"."BIZP_PROC_DEF_ID" IS '业务流程定义ID';
   COMMENT ON COLUMN "BIZP_PROCESS_FLOW_RELATION"."BIZP_TASK_ID" IS '业务流程任务ID';
   COMMENT ON COLUMN "BIZP_PROCESS_FLOW_RELATION"."BIZP_TASK_NAME" IS '业务任务名称';
   COMMENT ON COLUMN "BIZP_PROCESS_FLOW_RELATION"."WF_FLOW_DEF_ID" IS '流程定义UUID';
   COMMENT ON COLUMN "BIZP_PROCESS_FLOW_RELATION"."WF_FLOW_DEF_UUID" IS '流程定义ID';
   
   
   
CREATE TABLE "BIZP_PROCESS_TASK_FLOW_INST" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"BIZP_PROC_INST_UUID" VARCHAR2(255 CHAR), 
	"BIZP_TASK_INST_UUID" VARCHAR2(255 CHAR), 
	"WF_FLOW_INST_UUID" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("UUID") 
   ) ;
   COMMENT ON COLUMN "BIZP_PROCESS_TASK_FLOW_INST"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "BIZP_PROCESS_TASK_FLOW_INST"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "BIZP_PROCESS_TASK_FLOW_INST"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "BIZP_PROCESS_TASK_FLOW_INST"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "BIZP_PROCESS_TASK_FLOW_INST"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "BIZP_PROCESS_TASK_FLOW_INST"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "BIZP_PROCESS_TASK_FLOW_INST"."BIZP_PROC_INST_UUID" IS '业务流程实例UUID';
   COMMENT ON COLUMN "BIZP_PROCESS_TASK_FLOW_INST"."BIZP_TASK_INST_UUID" IS '业务任务实例UUID';
   COMMENT ON COLUMN "BIZP_PROCESS_TASK_FLOW_INST"."WF_FLOW_INST_UUID" IS '表单流程实例UUID';
   