-- 产品集成系统表
ALTER TABLE "APP_SYSTEM"
ADD ( "SYSTEM_UNIT_ID" VARCHAR2(12) DEFAULT ''  NULL  ) ;
COMMENT ON COLUMN "APP_SYSTEM"."SYSTEM_UNIT_ID" IS '归属系统单位ID';

-- 插入初始值
UPDATE APP_SYSTEM set SYSTEM_UNIT_ID = 'S00000000';
-- 添加systemUnitId字段不能为空的约束
ALTER TABLE "APP_SYSTEM"
MODIFY ( "SYSTEM_UNIT_ID" VARCHAR2(12 BYTE) DEFAULT ''  NOT NULL  ) ;



-- 产品集成模块表
ALTER TABLE "APP_MODULE"
ADD ( "SYSTEM_UNIT_ID" VARCHAR2(12) DEFAULT ''  NULL  ) ;
COMMENT ON COLUMN "APP_SYSTEM"."SYSTEM_UNIT_ID" IS '归属系统单位ID';

-- 插入初始值
UPDATE APP_MODULE set SYSTEM_UNIT_ID = 'S00000000';
-- 添加systemUnitId字段不能为空的约束
ALTER TABLE "APP_MODULE"
MODIFY ( "SYSTEM_UNIT_ID" VARCHAR2(12 BYTE) DEFAULT ''  NOT NULL  ) ;




-- 产品集成应用表
ALTER TABLE "APP_APPLICATION"
ADD ( "SYSTEM_UNIT_ID" VARCHAR2(12) DEFAULT ''  NULL  ) ;
COMMENT ON COLUMN "APP_SYSTEM"."SYSTEM_UNIT_ID" IS '归属系统单位ID';

-- 插入初始值
UPDATE APP_APPLICATION set SYSTEM_UNIT_ID = 'S00000000';
-- 添加systemUnitId字段不能为空的约束
ALTER TABLE "APP_APPLICATION"
MODIFY ( "SYSTEM_UNIT_ID" VARCHAR2(12 BYTE) DEFAULT ''  NOT NULL  ) ;
