-- new object type path: SCHEMA_EXPORT/SEQUENCE/SEQUENCE
-- CONNECT SYSTEM
 CREATE SEQUENCE  "HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
 CREATE SEQUENCE  "SEQ_NAVIGATOR"  MINVALUE 5 MAXVALUE 99999995 INCREMENT BY 5 START WITH 205 CACHE 20 NOORDER  NOCYCLE ;
 
-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
CREATE TABLE "ACL_ENTRY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "GRANTING" NUMBER(1,0) NOT NULL ENABLE, 
  "MASK" NUMBER(10,0) NOT NULL ENABLE, 
  "ACL_OBJECT_IDENTITY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "SID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "OBJECT_ID_IDENTITY" VARCHAR2(64 CHAR), 
  "REC_VER" NUMBER, 
  "CREATOR" VARCHAR2(255 BYTE), 
  "CREATE_TIME" TIMESTAMP (6), 
  "MODIFIER" VARCHAR2(255 BYTE), 
  "MODIFY_TIME" TIMESTAMP (6)
   ) ;
CREATE TABLE "ACL_OBJECT_IDENTITY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ENTRIES_INHERITING" NUMBER(1,0) NOT NULL ENABLE, 
  "OBJECT_ID_IDENTITY" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
  "OBJECT_ID_CLASS" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "PARENT_OBJECT" VARCHAR2(255 CHAR), 
  "OWNER_SID" VARCHAR2(255 CHAR), 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" NVARCHAR2(255), 
  "MODIFIER" VARCHAR2(255 BYTE), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER
   ) ;
CREATE TABLE "ACL_SID_MEMBER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "MEMBER" VARCHAR2(255 CHAR), 
  "MODULE_ID" VARCHAR2(255 CHAR), 
  "OWNER_SID" VARCHAR2(255 CHAR), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "CREATE_TIME" TIMESTAMP (6), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0)
   ) ;
CREATE TABLE "WF_TASK_SUB_FLOW_RELATION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ALLOW_SUBMIT" NUMBER(1,0), 
  "FRONT_NEW_FLOW_ID" VARCHAR2(255 CHAR), 
  "FRONT_NEW_FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "FRONT_NEW_FLOW_NAME" VARCHAR2(255 CHAR), 
  "FRONT_TASK_ID" VARCHAR2(255 CHAR), 
  "FRONT_TASK_NAME" VARCHAR2(255 CHAR), 
  "NEW_FLOW_ID" VARCHAR2(255 CHAR), 
  "NEW_FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "NEW_FLOW_NAME" VARCHAR2(255 CHAR), 
  "SUBMIT_STATUS" NUMBER(10,0), 
  "TASK_ID" VARCHAR2(255 CHAR), 
  "TASK_NAME" VARCHAR2(255 CHAR), 
  "TASK_SUB_FLOW_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;

CREATE TABLE "WF_TASK_DELEGATION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "COMPLETION_STATE" NUMBER(10,0), 
  "CONSIGNOR" VARCHAR2(255 CHAR), 
  "CONSIGNOR_NAME" VARCHAR2(255 CHAR), 
  "DUE_TO_TAKE_BACK_WORK" NUMBER(1,0), 
  "DUTY_AGENT_UUID" VARCHAR2(255 CHAR), 
  "FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "FROM_TIME" TIMESTAMP (6), 
  "TASK_IDENTITY_UUID" VARCHAR2(255 CHAR), 
  "TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "TO_TIME" TIMESTAMP (6), 
  "TRUSTEE" VARCHAR2(255 CHAR), 
  "TRUSTEE_NAME" VARCHAR2(255 CHAR)
   ) ;

CREATE TABLE "WF_DEF_CATEGORY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "PARENT_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "WF_DEF_FORMAT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "IS_CLEAR" NUMBER(1,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "VALUE" VARCHAR2(2000 CHAR)
   ) ;
CREATE TABLE "WF_DEF_OPINION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "CONTENT" VARCHAR2(4000 CHAR), 
  "OPINION_CATEGORY_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "WF_DEF_OPINION_CATEGORY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "WF_FLOW_INSTANCE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ALARM_TIME" TIMESTAMP (6), 
  "DATA_UUID" VARCHAR2(255 CHAR), 
  "DUE_TIME" TIMESTAMP (6), 
  "DURATION" NUMBER(19,0), 
  "END_TIME" TIMESTAMP (6), 
  "FORM_UUID" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "IS_ACTIVE" NUMBER(1,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "OWNER_DEPARTMENT_ID" VARCHAR2(255 CHAR), 
  "OWNER_UNIT_ID" VARCHAR2(255 CHAR), 
  "RESERVED_DATE1" TIMESTAMP (6), 
  "RESERVED_DATE2" TIMESTAMP (6), 
  "RESERVED_NUMBER1" NUMBER(10,0), 
  "RESERVED_NUMBER2" FLOAT(126), 
  "RESERVED_NUMBER3" FLOAT(126), 
  "RESERVED_TEXT1" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT10" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT2" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT3" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT4" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT5" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT6" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT7" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT8" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT9" VARCHAR2(255 CHAR), 
  "START_DEPARTMENT_ID" VARCHAR2(255 CHAR), 
  "START_TIME" TIMESTAMP (6), 
  "START_UNIT_ID" VARCHAR2(255 CHAR), 
  "START_USER_ID" VARCHAR2(255 CHAR), 
  "TITLE" VARCHAR2(255 CHAR), 
  "FLOW_DEF_UUID" VARCHAR2(255 CHAR), 
  "PARENT_FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT11" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT12" VARCHAR2(255 CHAR), 
  "OWNER_ID" VARCHAR2(255 CHAR), 
  "IS_TIMING" NUMBER(1,0), 
  "IS_OVER_DUE" NUMBER(1,0)
   ) ;
CREATE TABLE "WF_FLOW_INSTANCE_PARAM" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "VALUE" VARCHAR2(255 CHAR), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "CREATE_TIME" TIMESTAMP (6), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0)
   ) ;
CREATE TABLE "WF_TASK_ACTIVITY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "END_TIME" TIMESTAMP (6), 
  "FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "PRE_TASK_ID" VARCHAR2(255 CHAR), 
  "PRE_TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "START_TIME" TIMESTAMP (6), 
  "TASK_ID" VARCHAR2(255 CHAR), 
  "TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "TRANSFER_CODE" NUMBER(10,0)
   ) ;
CREATE TABLE "WF_TASK_FORM_OPINION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CONTENT" VARCHAR2(4000 CHAR), 
  "DATA_UUID" VARCHAR2(255 CHAR), 
  "FIELD_NAME" VARCHAR2(255 CHAR), 
  "FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "ERROR_DATA" NUMBER(1,0)
   ) ;
CREATE TABLE "WF_TASK_IDENTITY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "SORT_ORDER" NUMBER(10,0), 
  "USER_ID" VARCHAR2(255 CHAR), 
  "TASK_INST_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "SUSPENSION_STATE" NUMBER(10,0), 
  "TODO_TYPE" NUMBER(10,0), 
  "SOURCE_TASK_IDENTITY_UUID" VARCHAR2(255 CHAR), 
  "OWNER_ID" VARCHAR2(255 CHAR), 
  "RELATED_TASK_OPERATION_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "WF_TASK_INSTANCE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ACTION" VARCHAR2(255 CHAR), 
  "ACTION_TYPE" VARCHAR2(255 CHAR), 
  "ALARM_TIME" TIMESTAMP (6), 
  "ASSIGNEE" VARCHAR2(255 CHAR), 
  "DATA_UUID" VARCHAR2(255 CHAR), 
  "DUE_TIME" TIMESTAMP (6), 
  "DURATION" NUMBER(19,0) NOT NULL ENABLE, 
  "END_TIME" TIMESTAMP (6), 
  "FORM_UUID" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "OWNER" VARCHAR2(4000 CHAR), 
  "SERIAL_NO" VARCHAR2(255 CHAR), 
  "START_TIME" TIMESTAMP (6), 
  "SUSPENSION_STATE" NUMBER(10,0) NOT NULL ENABLE, 
  "TYPE" NUMBER(10,0), 
  "FLOW_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "FLOW_INST_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "PARENT_TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "IS_PARALLEL" NUMBER(1,0), 
  "PARALLEL_TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "TODO_USER_ID" VARCHAR2(4000 CHAR), 
  "TODO_USER_NAME" VARCHAR2(4000 CHAR), 
  "ALARM_STATE" NUMBER(10,0), 
  "OVER_DUE_STATE" NUMBER(10,0), 
  "TIMING_STATE" NUMBER(10,0)
   ) ;
CREATE TABLE "WF_TASK_OPERATION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ACTION" VARCHAR2(255 CHAR), 
  "ACTION_TYPE" VARCHAR2(255 CHAR), 
  "ASSIGNEE" VARCHAR2(255 CHAR), 
  "COPY_USER_ID" VARCHAR2(2000 CHAR), 
  "FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "OPINION_LABEL" VARCHAR2(255 CHAR), 
  "OPINION_TEXT" VARCHAR2(4000 CHAR), 
  "OPINION_VALUE" VARCHAR2(255 CHAR), 
  "TASK_ID" VARCHAR2(255 CHAR), 
  "TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "USER_ID" VARCHAR2(4000 CHAR), 
  "ACTION_STATUS" VARCHAR2(255 CHAR), 
  "TASK_NAME" VARCHAR2(255 CHAR), 
  "EXTRA_INFO" VARCHAR2(4000 CHAR), 
  "ACTION_CODE" NUMBER(10,0), 
  "ASSIGNEE_NAME" VARCHAR2(255 CHAR), 
  "TASK_IDENTITY_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "WF_TASK_SUB_FLOW" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "COMPLETED" NUMBER(1,0), 
  "COPY_FIELDS" VARCHAR2(4000 CHAR), 
  "FLOW_ID" VARCHAR2(255 CHAR), 
  "FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "IS_MERGE" NUMBER(1,0), 
  "IS_SHARE" NUMBER(1,0), 
  "IS_WAIT" NUMBER(1,0), 
  "NOTIFY_DOING" NUMBER(1,0), 
  "PARENT_FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "PARENT_TASK_ID" VARCHAR2(255 CHAR), 
  "PARENT_TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "RETURN_ADDITION_FIELDS" VARCHAR2(4000 CHAR), 
  "RETURN_OVERRIDE_FIELDS" VARCHAR2(4000 CHAR), 
  "SORT_ORDER" NUMBER(10,0), 
  "TODO_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "WF_TASK_TIMER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "AFFECT_MAIN_FLOW" NUMBER(1,0), 
  "ALARM_DONE" NUMBER(1,0), 
  "ALARM_FLOW_ID" VARCHAR2(255 CHAR), 
  "ALARM_FLOW_STARTED" NUMBER(1,0), 
  "ALARM_FREQUENCY" NUMBER(10,0), 
  "ALARM_REPEAT_INTERVAL" NUMBER(19,0), 
  "ALARM_TIME" VARCHAR2(255 CHAR), 
  "ALARM_UNIT" NUMBER(10,0), 
  "DUE_ACTION" NUMBER(10,0), 
  "DUE_DOING_DONE" NUMBER(1,0), 
  "DUE_FLOW_ID" VARCHAR2(255 CHAR), 
  "DUE_FLOW_STARTED" NUMBER(1,0), 
  "DUE_FREQUENCY" NUMBER(10,0), 
  "DUE_TIME" VARCHAR2(255 CHAR), 
  "DUE_TO_TASK_ID" VARCHAR2(255 CHAR), 
  "DUE_UNIT" NUMBER(10,0), 
  "ENABLE_ALARM" NUMBER(1,0), 
  "ENABLE_DUE_DOING" NUMBER(1,0), 
  "FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "LAST_START_TIME" TIMESTAMP (6), 
  "LIMIT_TIME1" VARCHAR2(255 CHAR), 
  "LIMIT_TIME2" VARCHAR2(255 CHAR), 
  "LIMIT_TIME_TYPE" VARCHAR2(255 CHAR), 
  "LIMIT_UNIT" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "START_TIME" TIMESTAMP (6), 
  "STATUS" NUMBER(10,0), 
  "TASK_ALARM_TIME" TIMESTAMP (6), 
  "TASK_DUE_TIME" TIMESTAMP (6), 
  "TASK_ID" VARCHAR2(255 CHAR), 
  "TASK_IDS" VARCHAR2(255 CHAR), 
  "TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "TASK_LIMIT_TIME" FLOAT(126), 
  "TENANT_ID" VARCHAR2(255 CHAR), 
  "LISTENER" VARCHAR2(255 CHAR), 
  "TASK_INIT_LIMIT_TIME" FLOAT(126), 
  "ALARM_STATE" NUMBER(10,0), 
  "OVER_DUE_STATE" NUMBER(10,0)
   ) ;
CREATE TABLE "WF_TASK_TIMER_LOG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "LOG_TIME" TIMESTAMP (6), 
  "TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "TASK_TIMER_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "WF_TASK_TIMER_USER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ARG_VALUE" VARCHAR2(255 CHAR), 
  "TYPE" NUMBER(10,0), 
  "USER_TYPE" NUMBER(10,0), 
  "VALUE" VARCHAR2(255 CHAR), 
  "TASK_TIMER_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ACL_CLASS" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CLASS" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 BYTE), 
  "MODIFIER" VARCHAR2(255 BYTE), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER
   ) ;
CREATE TABLE "ACL_SID" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "PRINCIPAL" NUMBER(1,0) NOT NULL ENABLE, 
  "SID" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" NVARCHAR2(255), 
  "MODIFIER" VARCHAR2(255 BYTE), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER
   ) ;
CREATE TABLE "WF_FLOW_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CATEGORY" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "ENABLED" NUMBER(1,0), 
  "EQUAL_FLOW_ID" VARCHAR2(255 CHAR), 
  "FORM_NAME" VARCHAR2(255 CHAR), 
  "FORM_UUID" VARCHAR2(255 CHAR), 
  "FREEED" NUMBER(1,0), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "VERSION" FLOAT(126), 
  "FLOW_SCHEMA_UUID" VARCHAR2(255 CHAR), 
  "TITLE_EXPRESSION" VARCHAR2(255 BYTE), 
  "DEVELOP_JSON" VARCHAR2(1000 BYTE)
   ) ;
CREATE TABLE "WF_FLOW_MANAGEMENT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "FLOW_DEF_UUID" VARCHAR2(255 CHAR), 
  "ORG_ID" VARCHAR2(255 CHAR), 
  "TYPE" NUMBER(10,0)
   ) ;

CREATE TABLE "WF_TASK_FORM_OPINION_LOG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "FLOW_INST_UUID" VARCHAR2(255 CHAR), 
  "TASK_INST_UUID" VARCHAR2(255 CHAR), 
  "TASK_OPERATION_UUID" VARCHAR2(255 CHAR), 
  "TASK_FORM_OPINION_UUID" VARCHAR2(255 CHAR), 
  "FIELD_NAME" VARCHAR2(255 CHAR), 
  "CONTENT" VARCHAR2(2000 CHAR), 
  "RECORD_WAY" NUMBER(10,0)
   ) ;
   
CREATE TABLE "SYS_PARAM_ITEM" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "KEY" VARCHAR2(2048 CHAR), 
  "VALUE" VARCHAR2(2048 CHAR), 
  "NAME" VARCHAR2(2048 CHAR), 
  "SOURCETYPE" NUMBER, 
  "CODE" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR)
   ) ;   

CREATE TABLE "TASK_JOB_DETAILS" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "END_TIME" TIMESTAMP (6), 
  "EXPRESSION" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "JOB_CLASS_NAME" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "REPEAT_COUNT" NUMBER(10,0), 
  "REPEAT_DAY_OF_MONTH" VARCHAR2(255 CHAR), 
  "REPEAT_DAY_OF_SEASON" VARCHAR2(255 CHAR), 
  "REPEAT_DAY_OF_WEEK" VARCHAR2(255 CHAR), 
  "REPEAT_DAY_OF_YEAR" VARCHAR2(255 CHAR), 
  "REPEAT_INTERVAL" NUMBER(19,0), 
  "REPEAT_INTERVAL_TIME" VARCHAR2(255 CHAR), 
  "START_TIME" TIMESTAMP (6), 
  "TENANT_ID" VARCHAR2(255 CHAR), 
  "TIME_POINT" VARCHAR2(255 CHAR), 
  "TIMING_MODE" NUMBER(10,0), 
  "TYPE" VARCHAR2(255 CHAR)
   ) ;

CREATE TABLE "WF_FLOW_SCHEMA" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CONTENT" CLOB, 
  "NAME" VARCHAR2(255 CHAR)
   ) ;

CREATE TABLE "WF_TASK_DELETE_LOG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "TITLE" VARCHAR2(255 CHAR), 
  "SERIAL_NO" VARCHAR2(255 CHAR), 
  "TASK_NAME" VARCHAR2(255 CHAR), 
  "OPERATOR" VARCHAR2(255 CHAR), 
  "OPERATOR_NAME" VARCHAR2(255 CHAR), 
  "OPERATION" VARCHAR2(255 CHAR), 
  "OPERATE_TIME" TIMESTAMP (6), 
  "CONTENT" CLOB, 
  "REMARK" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "WF_FLOW_SCHEMA_LOG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CONTENT" CLOB, 
  "CREATE_TIME" TIMESTAMP (6), 
  "PARENT_FLOW_SCHEMAUUID" VARCHAR2(255 CHAR), 
  "LOG" VARCHAR2(2000 CHAR), 
  "FLOW_VERSION" NUMBER(10,0)
   ) ;
CREATE TABLE "APP_MODULE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ENABLED" NUMBER(1,0), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "APP_SYSTEM" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ENABLED" NUMBER(1,0), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR)
   ) ;
   
 
-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/INDEX
CREATE INDEX "ACL_ENTRY_BATCH_IDX" ON "ACL_ENTRY" ("GRANTING", "MASK", "ACL_OBJECT_IDENTITY", "SID");
ALTER INDEX "ACL_ENTRY_BATCH_IDX" NOPARALLEL;
CREATE INDEX "ACL_ENTRY_IDX_AOI" ON "ACL_ENTRY" ("ACL_OBJECT_IDENTITY");
ALTER INDEX "ACL_ENTRY_IDX_AOI" NOPARALLEL;
CREATE INDEX "ACL_ENTRY_IDX_OBJECT" ON "ACL_ENTRY" ("OBJECT_ID_IDENTITY");
ALTER INDEX "ACL_ENTRY_IDX_OBJECT" NOPARALLEL;
CREATE INDEX "ACL_ENTRY_IDX_MASK" ON "ACL_ENTRY" ("MASK");
ALTER INDEX "ACL_ENTRY_IDX_MASK" NOPARALLEL;
CREATE INDEX "ACL_SID_MEMBER_BATCH_IDX" ON "ACL_SID_MEMBER" ("MEMBER", "MODULE_ID", "OWNER_SID");
ALTER INDEX "ACL_SID_MEMBER_BATCH_IDX" NOPARALLEL;
CREATE INDEX "WF_DC_PARENT_UUID_IDX" ON "WF_DEF_CATEGORY" ("PARENT_UUID");
ALTER INDEX "WF_DC_PARENT_UUID_IDX" NOPARALLEL;
CREATE INDEX "WF_DO_OC_UUID_IDX" ON "WF_DEF_OPINION" ("OPINION_CATEGORY_UUID");
ALTER INDEX "WF_DO_OC_UUID_IDX" NOPARALLEL;
CREATE INDEX "WF_FI_FLOW_DEF_UUID_IDX" ON "WF_FLOW_INSTANCE" ("FLOW_DEF_UUID");
ALTER INDEX "WF_FI_FLOW_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "WF_FI_PFI_UUID_IDX" ON "WF_FLOW_INSTANCE" ("PARENT_FLOW_INST_UUID");
ALTER INDEX "WF_FI_PFI_UUID_IDX" NOPARALLEL;
CREATE INDEX "WF_TITI_UUID_IDX" ON "WF_TASK_IDENTITY" ("TASK_INST_UUID");
ALTER INDEX "WF_TITI_UUID_IDX" NOPARALLEL;
CREATE INDEX "WF_TIN_FLOW_INST_UUID_IDX" ON "WF_TASK_INSTANCE" ("FLOW_INST_UUID");
ALTER INDEX "WF_TIN_FLOW_INST_UUID_IDX" NOPARALLEL;
CREATE INDEX "WF_TIN_FLOW_DEF_UUID_IDX" ON "WF_TASK_INSTANCE" ("FLOW_DEF_UUID");
ALTER INDEX "WF_TIN_FLOW_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "WF_TIN_PTI_UUID_IDX" ON "WF_TASK_INSTANCE" ("PARENT_TASK_INST_UUID");
ALTER INDEX "WF_TIN_PTI_UUID_IDX" NOPARALLEL;
CREATE INDEX "WF_TTL_TASK_TIMER_UUID_IDX" ON "WF_TASK_TIMER_LOG" ("TASK_TIMER_UUID");
ALTER INDEX "WF_TTL_TASK_TIMER_UUID_IDX" NOPARALLEL;
CREATE INDEX "WF_TTU_TASK_TIMER_UUID_IDX" ON "WF_TASK_TIMER_USER" ("TASK_TIMER_UUID");
ALTER INDEX "WF_TTU_TASK_TIMER_UUID_IDX" NOPARALLEL;
CREATE INDEX "WF_FD_FLOW_SCHEMA_UUID_IDX" ON "WF_FLOW_DEFINITION" ("FLOW_SCHEMA_UUID");
ALTER INDEX "WF_FD_FLOW_SCHEMA_UUID_IDX" NOPARALLEL;


-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT
ALTER TABLE "WF_DEF_OPINION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_DEF_OPINION_CATEGORY" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_FLOW_INSTANCE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_FLOW_INSTANCE_PARAM" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_TASK_ACTIVITY" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_TASK_FORM_OPINION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_TASK_IDENTITY" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_TASK_INSTANCE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_TASK_OPERATION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_TASK_SUB_FLOW" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_TASK_TIMER" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_TASK_TIMER_LOG" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_TASK_TIMER_USER" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ACL_CLASS" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ACL_CLASS" ADD UNIQUE ("CLASS")
  USING INDEX  ENABLE;
ALTER TABLE "ACL_SID" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ACL_SID" ADD UNIQUE ("PRINCIPAL", "SID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_FLOW_DEFINITION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_FLOW_MANAGEMENT" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_TASK_FORM_OPINION_LOG" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_DEF_CATEGORY" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_DEF_FORMAT" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_TASK_DELEGATION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "SYS_PARAM_ITEM" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "TASK_JOB_DETAILS" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "APP_MODULE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "APP_SYSTEM" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;