
---------------------------------金格文件转换------------------------------
CREATE TABLE KING_GRID_FILE_CONVERT
(
  UUID             VARCHAR2(255) NOT NULL,
  REC_VER          NUMBER(10,2),
  SYSTEM_UNIT_ID   VARCHAR2(255),
  CREATE_TIME      TIMESTAMP(6),
  CREATOR          VARCHAR2(255),
  MODIFIER         VARCHAR2(255),
  MODIFY_TIME      TIMESTAMP(6),
  FILE_NAME        VARCHAR2(255),
  CONVERT_TYPE     VARCHAR2(255),
  SOURCE_FILE_PATH VARCHAR2(255),
  TARGET_FILE_PATH VARCHAR2(1000),
  STATUS           INTEGER,
  FILE_SIZE        NUMBER,
  ERROR_MSG        VARCHAR2(2000),
  CONSTRAINT PK_KING_GRID_FILE_CONVERT PRIMARY KEY (UUID)
);
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE KING_GRID_FILE_CONVERT
  IS '金格文件转换';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN KING_GRID_FILE_CONVERT.UUID
  IS '唯一主键';
COMMENT ON COLUMN KING_GRID_FILE_CONVERT.SYSTEM_UNIT_ID
  IS '系统单位ID';
COMMENT ON COLUMN KING_GRID_FILE_CONVERT.CREATE_TIME
  IS '创建时间';
COMMENT ON COLUMN KING_GRID_FILE_CONVERT.CREATOR
  IS '创建人';
COMMENT ON COLUMN KING_GRID_FILE_CONVERT.MODIFIER
  IS '更新人';
COMMENT ON COLUMN KING_GRID_FILE_CONVERT.MODIFY_TIME
  IS '更新时间';
