-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
CREATE TABLE "MSG_MESSAGE_CONTENT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BODY" VARCHAR2(255 CHAR), 
  "ISREAD" NUMBER(1,0), 
  "MESSAGE_ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "RECEIVED_TIME" TIMESTAMP (6), 
  "RECIPIENT" VARCHAR2(255 CHAR), 
  "RECIPIENT_NAME" VARCHAR2(255 CHAR), 
  "SENDER" VARCHAR2(255 CHAR), 
  "SENDER_NAME" VARCHAR2(255 CHAR), 
  "SENT_TIME" TIMESTAMP (6), 
  "SUBJECT" VARCHAR2(255 CHAR), 
  "TEMPLATE_ID" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "DATA_UUID" VARCHAR2(255 CHAR), 
  "NOTE" VARCHAR2(255 CHAR), 
  "VIEWPOINT" VARCHAR2(255 CHAR), 
  "OUTBOX_MSG_ID" VARCHAR2(255 CHAR), 
  "RELATED_URL" VARCHAR2(255 CHAR), 
  "SYSTEMID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MSG_WEBSERVICE_PARM" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "PARM_NAME" VARCHAR2(255 CHAR), 
  "PARM_VALUE" VARCHAR2(255 CHAR), 
  "PARMDESC" VARCHAR2(255 CHAR), 
  "MESSAGE_TEMPLATE_UUID" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR)
   ) ;

CREATE TABLE "MSG_MAS_CONFIG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "API_CODE" VARCHAR2(255 CHAR), 
  "DB_NAME" VARCHAR2(255 CHAR), 
  "IM_IP" VARCHAR2(255 CHAR), 
  "IS_OPEN" NUMBER(1,0), 
  "LOGIN_NAME" VARCHAR2(255 CHAR), 
  "LOGIN_PASSWORD" VARCHAR2(255 CHAR), 
  "SEND_LIMIT" NUMBER(10,0)
   ) ;
CREATE TABLE "MSG_MESSAGE_TEMPLATE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CATEGORY" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "EMAIL_BODY" VARCHAR2(255 CHAR), 
  "EMAIL_SUBJECT" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "MAPPING_RULE" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "ONLINE_BODY" VARCHAR2(255 CHAR), 
  "ONLINE_SUBJECT" VARCHAR2(255 CHAR), 
  "SEND_TIME" VARCHAR2(255 CHAR), 
  "SEND_WAY" VARCHAR2(255 CHAR), 
  "SMS_BODY" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "IS_ONLINE_POPUP" VARCHAR2(255 CHAR), 
  "MESSAGE_EVENT" VARCHAR2(255 CHAR), 
  "SHOW_VIEWPOINT" VARCHAR2(255 CHAR), 
  "VIEWPOINTN" VARCHAR2(255 CHAR), 
  "VIEWPOINT_NONE" VARCHAR2(255 CHAR), 
  "VIEWPOINTY" VARCHAR2(255 CHAR), 
  "PASSWORD_KEY" VARCHAR2(255 CHAR), 
  "PASSWORD_VALUE" VARCHAR2(255 CHAR), 
  "TENANTID_KEY" VARCHAR2(255 CHAR), 
  "TENANTID_VALUE" VARCHAR2(255 CHAR), 
  "USERNAME_KEY" VARCHAR2(255 CHAR), 
  "USERNAME_VALUE" VARCHAR2(255 CHAR), 
  "WEB_SERVICE_URL" VARCHAR2(255 CHAR), 
  "MESSAGE_EVENT_TEXT" VARCHAR2(255 CHAR), 
  "ASK_FOR_SCHEDULE" VARCHAR2(255 CHAR), 
  "FOREGROUND_EVENT" VARCHAR2(255 CHAR), 
  "FOREGROUND_EVENT_TEXT" VARCHAR2(255 CHAR), 
  "BACKGROUND_EVENT" VARCHAR2(255 CHAR), 
  "BACKGROUND_EVENT_TEXT" VARCHAR2(255 CHAR), 
  "SCHEDULE_TITLE" VARCHAR2(255 CHAR), 
  "SCHEDULE_DATES" VARCHAR2(255 CHAR), 
  "SCHEDULE_DATEE" VARCHAR2(255 CHAR), 
  "SCHEDULE_ADDRESS" VARCHAR2(255 CHAR), 
  "REMINDER_TIME" VARCHAR2(255 CHAR), 
  "SCHEDULE_BODY" VARCHAR2(255 CHAR), 
  "SRC_TITLE" VARCHAR2(255 CHAR), 
  "SRC_ADDRESS" VARCHAR2(255 CHAR), 
  "RELATED_TITLE" VARCHAR2(255 CHAR), 
  "RELATED_URL" VARCHAR2(255 CHAR), 
  "EMAIL_ATTACH" VARCHAR2(255 CHAR), 
  "ONLINE_ATTACH" VARCHAR2(255 CHAR), 
  "REPEAT_TYPE" VARCHAR2(100 CHAR), 
  "MESSAGE_INTEFACE" VARCHAR2(255 BYTE), 
  "MESSAGE_INTEFACE_TEXT" VARCHAR2(255 BYTE)
   ) ;
CREATE TABLE "MSG_SHORT_MESSAGE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BODY" VARCHAR2(255 CHAR), 
  "BUSINESS_LOGIC_ID" VARCHAR2(255 CHAR), 
  "IS_RE_SEND" NUMBER(1,0), 
  "ISREAD" NUMBER(1,0), 
  "REC_ID" NUMBER(10,0), 
  "REC_MSG" VARCHAR2(255 CHAR), 
  "RECEIVED" VARCHAR2(255 CHAR), 
  "RECEIVED_TIME" TIMESTAMP (6), 
  "RECIPIENT_MOBILE_PHONE" VARCHAR2(255 CHAR), 
  "RECIPIENT_NAME" VARCHAR2(255 CHAR), 
  "SEND" VARCHAR2(255 CHAR), 
  "SEND_MOBILE_PHONE" VARCHAR2(255 CHAR), 
  "SEND_STATUS" NUMBER(10,0), 
  "SEND_TIME" TIMESTAMP (6), 
  "SENDER_NAME" VARCHAR2(255 CHAR), 
  "SMID" NUMBER(19,0), 
  "TYPE" NUMBER(10,0), 
  "BUSINESSKEY1" VARCHAR2(255 CHAR), 
  "BUSINESSKEY2" VARCHAR2(255 CHAR), 
  "BUSINESSKEY3" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT1" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT2" VARCHAR2(255 CHAR), 
  "RESERVED_TEXT3" VARCHAR2(255 CHAR)
   ) ;

CREATE TABLE "MSG_MESSAGE_INBOX" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ISREAD" NUMBER(1,0), 
  "RECEIVED_TIME" TIMESTAMP (6), 
  "RECIPIENT" VARCHAR2(255 CHAR), 
  "RECIPIENT_NAME" VARCHAR2(255 CHAR), 
  "SENDER" VARCHAR2(255 CHAR), 
  "SENDER_NAME" VARCHAR2(255 CHAR), 
  "SENT_TIME" TIMESTAMP (6), 
  "SUBJECT" VARCHAR2(255 CHAR), 
  "MESSAGE_OUTBOX_UUID" VARCHAR2(255 CHAR), 
  "MESSAGE_PARM" CLOB, 
  "NOTE" VARCHAR2(255 CHAR), 
  "VIEWPOINT" VARCHAR2(255 CHAR), 
  "ISCANCEL" NUMBER(1,0), 
  "MARK_FLAG" VARCHAR2(255 CHAR), 
  "RELATED_URL" VARCHAR2(255 CHAR), 
  "BODY" CLOB, 
  "IS_ONLINE_POPUP" VARCHAR2(255 CHAR), 
  "ISSEND" NUMBER(1,0)
   ) ;
CREATE TABLE "MSG_MESSAGE_OUTBOX" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ISCANCEL" NUMBER(1,0), 
  "MESSAGE_ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "RECEIVED_TIME" TIMESTAMP (6), 
  "SENDER" VARCHAR2(255 CHAR), 
  "SENDER_NAME" VARCHAR2(255 CHAR), 
  "SENT_TIME" TIMESTAMP (6), 
  "SUBJECT" VARCHAR2(255 CHAR), 
  "SYSTEMID" VARCHAR2(255 CHAR), 
  "TEMPLATE_ID" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "MARK_FLAG" VARCHAR2(255 CHAR), 
  "RELATED_URL" VARCHAR2(255 CHAR), 
  "RELATED_TITLE" VARCHAR2(255 CHAR), 
  "RECIPIENT" CLOB, 
  "RECIPIENT_NAME" CLOB, 
  "BODY" CLOB, 
  "CORRELATION_ID" VARCHAR2(255 CHAR), 
  "ISSEND" NUMBER(1,0)
   ) ;
   
-- Create table
create table MSG_MESSAGE_OUTBOX_BAK
(
  UUID           VARCHAR2(255 CHAR) not null,
  CREATE_TIME    TIMESTAMP(6),
  CREATOR        VARCHAR2(255 CHAR),
  MODIFIER       VARCHAR2(255 CHAR),
  MODIFY_TIME    TIMESTAMP(6),
  REC_VER        NUMBER(10),
  ISCANCEL       NUMBER(1),
  MESSAGE_ID     VARCHAR2(255 CHAR),
  NAME           VARCHAR2(255 CHAR),
  RECEIVED_TIME  TIMESTAMP(6),
  SENDER         VARCHAR2(255 CHAR),
  SENDER_NAME    VARCHAR2(255 CHAR),
  SENT_TIME      TIMESTAMP(6),
  SUBJECT        VARCHAR2(255 CHAR),
  SYSTEMID       VARCHAR2(255 CHAR),
  TEMPLATE_ID    VARCHAR2(255 CHAR),
  TYPE           VARCHAR2(255 CHAR),
  MARK_FLAG      VARCHAR2(255 CHAR),
  RELATED_URL    VARCHAR2(255 CHAR),
  RELATED_TITLE  VARCHAR2(255 CHAR),
  RECIPIENT      CLOB,
  RECIPIENT_NAME CLOB,
  BODY           CLOB
);

-- Create table
create table MSG_MESSAGE_INBOX_BAK
(
  UUID                VARCHAR2(255 CHAR) not null,
  CREATE_TIME         TIMESTAMP(6),
  CREATOR             VARCHAR2(255 CHAR),
  MODIFIER            VARCHAR2(255 CHAR),
  MODIFY_TIME         TIMESTAMP(6),
  REC_VER             NUMBER(10),
  ISREAD              NUMBER(1),
  RECEIVED_TIME       TIMESTAMP(6),
  RECIPIENT           VARCHAR2(255 CHAR),
  RECIPIENT_NAME      VARCHAR2(255 CHAR),
  SENDER              VARCHAR2(255 CHAR),
  SENDER_NAME         VARCHAR2(255 CHAR),
  SENT_TIME           TIMESTAMP(6),
  SUBJECT             VARCHAR2(255 CHAR),
  MESSAGE_OUTBOX_UUID VARCHAR2(255 CHAR),
  MESSAGE_PARM        CLOB,
  NOTE                VARCHAR2(255 CHAR),
  VIEWPOINT           VARCHAR2(255 CHAR),
  ISCANCEL            NUMBER(1),
  MARK_FLAG           VARCHAR2(255 CHAR),
  RELATED_URL         VARCHAR2(255 CHAR),
  BODY                CLOB
);

 COMMENT ON COLUMN "MSG_MESSAGE_OUTBOX"."CORRELATION_ID" IS '客户端请求系列ID';
 COMMENT ON COLUMN "MSG_MESSAGE_OUTBOX"."ISSEND" IS '是否接收标识';   

-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/INDEX
 CREATE UNIQUE INDEX "UK_9AW03LATP4HX1T718KHVJP8KA" ON "MSG_MESSAGE_TEMPLATE" ("ID");
 ALTER INDEX "UK_9AW03LATP4HX1T718KHVJP8KA" NOPARALLEL;
 
 CREATE INDEX "MSG_MI_MESSAGE_OUTBOX_UUID_IDX" ON "MSG_MESSAGE_INBOX" ("MESSAGE_OUTBOX_UUID");
 ALTER INDEX "MSG_MI_MESSAGE_OUTBOX_UUID_IDX" NOPARALLEL;
 
 ALTER TABLE "MSG_MAS_CONFIG" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "MSG_MESSAGE_TEMPLATE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "MSG_MESSAGE_TEMPLATE" ADD CONSTRAINT "UK_9AW03LATP4HX1T718KHVJP8KA" UNIQUE ("ID")
  USING INDEX "UK_9AW03LATP4HX1T718KHVJP8KA"  ENABLE;
ALTER TABLE "MSG_SHORT_MESSAGE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE MSG_MESSAGE_INBOX_BAK
  ADD PRIMARY KEY (UUID);
ALTER TABLE MSG_MESSAGE_INBOX_BAK
  ADD CONSTRAINT FK_MSG_MESSAGE_INBOX_BAK FOREIGN KEY (MESSAGE_OUTBOX_UUID)
  REFERENCES MSG_MESSAGE_OUTBOX_BAK (UUID);
ALTER TABLE MSG_MESSAGE_OUTBOX_BAK
  ADD PRIMARY KEY (UUID);