-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
CREATE TABLE "VIEW_COLUMNCSS_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "COLUMN_CONDITION" VARCHAR2(255 CHAR), 
  "COLUMN_CONDITION_VALUE" VARCHAR2(255 CHAR), 
  "CSS_ID" VARCHAR2(255 CHAR), 
  "FONT_COLOR" VARCHAR2(255 CHAR), 
  "FONT_WIDE" VARCHAR2(255 CHAR), 
  "VIEW_COLUMN" VARCHAR2(255 CHAR), 
  "VIEW_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "VIEW_COLUMN_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "COLUMN_ALIASE" VARCHAR2(255 CHAR), 
  "COLUMN_DATA_TYPE" VARCHAR2(255 CHAR), 
  "COLUMN_TYPE" VARCHAR2(255 CHAR), 
  "DEFAULT_SORT" VARCHAR2(255 CHAR), 
  "ENTITY_NAME" VARCHAR2(255 CHAR), 
  "FIELD_NAME" VARCHAR2(255 CHAR), 
  "FIELD_PERMISSION" NUMBER(1,0), 
  "HIDDEN" NUMBER(1,0), 
  "OTHER_NAME" VARCHAR2(255 CHAR), 
  "PARSE_HTML" NUMBER(1,0), 
  "SHOW_LINE" VARCHAR2(255 CHAR), 
  "SORT_ABLE" NUMBER(1,0), 
  "SORT_ORDER" NUMBER(10,0), 
  "TITLE_NAME" VARCHAR2(255 CHAR), 
  "VALUE" VARCHAR2(255 CHAR), 
  "VALUE_TYPE" VARCHAR2(255 CHAR), 
  "WIDTH" VARCHAR2(255 CHAR), 
  "VIEW_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "DATA_DICT_NAME" VARCHAR2(255 CHAR), 
  "DATA_DICT_VALUE" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "VIEW_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BUTTON_PLACE" NUMBER(1,0), 
  "CATE_NAME" VARCHAR2(255 CHAR), 
  "CATE_UUID" VARCHAR2(255 CHAR), 
  "CHECK_KEY" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "DATA_MODULE_ID" VARCHAR2(255 CHAR), 
  "DATA_MODULE_NAME" VARCHAR2(255 CHAR), 
  "DEFAULT_CONDITION" VARCHAR2(4000 BYTE), 
  "ID" VARCHAR2(255 CHAR), 
  "IS_READ" NUMBER(1,0), 
  "JS_SRC" VARCHAR2(255 CHAR), 
  "LINE_TYPE" VARCHAR2(255 CHAR), 
  "MODULE_ID" VARCHAR2(255 CHAR), 
  "PAGE_ABLE" NUMBER(1,0) NOT NULL ENABLE, 
  "PAGE_ROW" NUMBER(10,0), 
  "READ_KEY" VARCHAR2(255 CHAR), 
  "REQUEST_PARAM_ID" VARCHAR2(255 CHAR), 
  "REQUEST_PARAM_NAME" VARCHAR2(255 CHAR), 
  "RESPONSE_PARAM_ID" VARCHAR2(255 CHAR), 
  "RESPONSE_PARAM_NAME" VARCHAR2(255 CHAR), 
  "SHOW_CHECK_BOX" NUMBER(1,0), 
  "SHOW_TITLE" NUMBER(1,0), 
  "SPECIAL_FIELD" NUMBER(1,0), 
  "SPECIAL_FIELD_METHOD" VARCHAR2(255 CHAR), 
  "TABLE_DEFINITION_ID" VARCHAR2(255 CHAR), 
  "TABLE_DEFINITION_TEXT" VARCHAR2(255 CHAR), 
  "URL" VARCHAR2(255 CHAR), 
  "VIEW_ID" VARCHAR2(255 CHAR), 
  "VIEW_NAME" VARCHAR2(255 CHAR), 
  "CLICK_EVENT" VARCHAR2(255 CHAR), 
  "ABSOLUTE_WIDTH" VARCHAR2(255 CHAR), 
  "DATA_INTERFACE_NAME" VARCHAR2(255 BYTE), 
  "DATA_INTERFACE_ID" VARCHAR2(255 BYTE)
   ) ;
CREATE TABLE "VIEW_FIELD_SELECT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CONTENT_FORMAT" VARCHAR2(255 CHAR), 
  "DEFAULT_VALUE" VARCHAR2(255 CHAR), 
  "DICT_CODE" VARCHAR2(255 CHAR), 
  "DICT_NAME" VARCHAR2(255 CHAR), 
  "EXACT_VALUE" VARCHAR2(255 CHAR), 
  "FIELD" VARCHAR2(255 CHAR), 
  "IS_AREA" NUMBER(1,0), 
  "IS_EXACT" NUMBER(1,0), 
  "IS_LIKE" NUMBER(1,0), 
  "OPTDATA" VARCHAR2(255 CHAR), 
  "OPTION_DATA_SOURCE" VARCHAR2(255 CHAR), 
  "ORG_INPUT_MODE" VARCHAR2(255 CHAR), 
  "SELECT_TYPE" VARCHAR2(255 CHAR), 
  "SELECT_TYPE_ID" VARCHAR2(255 CHAR), 
  "SHOW_NAME" VARCHAR2(255 CHAR), 
  "SELECT_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "SORT_ORDER" NUMBER(10,0), 
  "DATA_SOURCE_ID" VARCHAR2(255 CHAR), 
  "DATA_SOURCE_NAME" VARCHAR2(255 CHAR), 
  "SELECT_NAME_COLUMN" VARCHAR2(255 CHAR), 
  "SELECT_VALUE_COLUMN" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "VIEW_PAGE_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "IS_PAGING" NUMBER(1,0), 
  "PAGE_NUM" NUMBER(10,0), 
  "VIEW_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "IS_EVERY_PAGE" NUMBER(1,0), 
  "IS_CURRENT_PAGE" NUMBER(1,0), 
  "IS_OPEN_COMMON_BUTTON" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "VIEW_SELECT_CONDITION_TYPE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "APPOINT_COLUMN" VARCHAR2(255 CHAR), 
  "APPOINT_COLUMN_TYPE" VARCHAR2(255 CHAR), 
  "CONDITION_NAME" VARCHAR2(255 CHAR), 
  "CONDITION_SCOPE" VARCHAR2(255 CHAR), 
  "CONDITION_VALUE" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "SORT_ORDER" NUMBER(10,0), 
  "SELECT_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "VIEW_SELECT_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "FOR_CONDITION" NUMBER(1,0), 
  "FOR_FIELD_SELECT" NUMBER(1,0), 
  "FOR_KEY_SELECT" NUMBER(1,0), 
  "VIEW_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "VIEW_VIEW_CUSTOM_BUTTON" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BUTTON_GROUP" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "JS_CONTENT" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "PLACE" VARCHAR2(255 CHAR), 
  "RESAULT_NAME" VARCHAR2(255 CHAR), 
  "VIEW_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CONSTRAINT" VARCHAR2(255 BYTE)
   ) ;
CREATE TABLE "DYVIEW_COLUMNCSS_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "COLUMN_CONDITION" VARCHAR2(255 CHAR), 
  "COLUMN_CONDITION_VALUE" VARCHAR2(255 CHAR), 
  "CSS_ID" VARCHAR2(255 CHAR), 
  "FONT_COLOR" VARCHAR2(255 CHAR), 
  "FONT_WIDE" VARCHAR2(255 CHAR), 
  "VIEW_COLUMN" VARCHAR2(255 CHAR), 
  "VIEW_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "DYVIEW_COLUMN_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "COLUMN_ALIASE" VARCHAR2(255 CHAR), 
  "COLUMN_DATA_TYPE" VARCHAR2(255 CHAR), 
  "COLUMN_TYPE" VARCHAR2(255 CHAR), 
  "DEFAULT_SORT" VARCHAR2(255 CHAR), 
  "ENTITY_NAME" VARCHAR2(255 CHAR), 
  "FIELD_NAME" VARCHAR2(255 CHAR), 
  "FIELD_PERMISSION" NUMBER(1,0), 
  "HIDDEN" NUMBER(1,0), 
  "OTHER_NAME" VARCHAR2(255 CHAR), 
  "PARSE_HTML" NUMBER(1,0), 
  "SHOW_LINE" VARCHAR2(255 CHAR), 
  "SORT_ABLE" NUMBER(1,0), 
  "SORT_ORDER" NUMBER(10,0), 
  "TITLE_NAME" VARCHAR2(255 CHAR), 
  "VALUE" VARCHAR2(255 CHAR), 
  "VALUE_TYPE" VARCHAR2(255 CHAR), 
  "WIDTH" VARCHAR2(255 CHAR), 
  "VIEW_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "DATA_DICT_NAME" VARCHAR2(255 CHAR), 
  "DATA_DICT_VALUE" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "DYVIEW_PAGE_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "IS_PAGING" NUMBER(1,0), 
  "PAGE_NUM" NUMBER(10,0), 
  "VIEW_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "DYVIEW_SELECT_CONDITION_TYPE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "APPOINT_COLUMN" VARCHAR2(255 CHAR), 
  "APPOINT_COLUMN_TYPE" VARCHAR2(255 CHAR), 
  "CONDITION_NAME" VARCHAR2(255 CHAR), 
  "CONDITION_SCOPE" VARCHAR2(255 CHAR), 
  "CONDITION_VALUE" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "SORT_ORDER" NUMBER(10,0), 
  "SELECT_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "DYVIEW_SELECT_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "EXACT_KEY_SELECT" NUMBER(1,0), 
  "FOR_CONDITION" NUMBER(1,0), 
  "FOR_KEY_SELECT" NUMBER(1,0), 
  "FOR_TIME_SOLT" NUMBER(1,0), 
  "SEARCH_FIELD" VARCHAR2(255 CHAR), 
  "SELECT_SHOW" NUMBER(1,0), 
  "VAGUE_KEY_SELECT" NUMBER(1,0), 
  "VIEW_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "DYVIEW_SELECT_EXACTKEY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "KEY_NAME" VARCHAR2(255 CHAR), 
  "KEY_VALUE" VARCHAR2(255 CHAR), 
  "SELECT_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "DYVIEW_VIEW_CUSTOM_BUTTON" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BUTTON_GROUP" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "JS_CONTENT" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "PLACE" VARCHAR2(255 CHAR), 
  "RESAULT_NAME" VARCHAR2(255 CHAR), 
  "VIEW_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "DYVIEW_VIEW_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BUTTON_PLACE" NUMBER(1,0), 
  "CATE_NAME" VARCHAR2(255 CHAR), 
  "CATE_UUID" VARCHAR2(255 CHAR), 
  "CHECK_KEY" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "DATA_MODULE_ID" VARCHAR2(255 CHAR), 
  "DATA_MODULE_NAME" VARCHAR2(255 CHAR), 
  "DATA_SCOPE" NUMBER(10,0), 
  "DATA_UUID" VARCHAR2(255 CHAR), 
  "DEFAULT_CONDITION" VARCHAR2(255 CHAR), 
  "FORMUUID" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "IS_READ" NUMBER(1,0), 
  "JS_SRC" VARCHAR2(255 CHAR), 
  "LINE_TYPE" VARCHAR2(255 CHAR), 
  "MODULE_ID" VARCHAR2(255 CHAR), 
  "PAGE_ABLE" NUMBER(1,0) NOT NULL ENABLE, 
  "PAGE_ROW" NUMBER(10,0), 
  "READ_KEY" VARCHAR2(255 CHAR), 
  "REQUEST_PARAM_ID" VARCHAR2(255 CHAR), 
  "REQUEST_PARAM_NAME" VARCHAR2(255 CHAR), 
  "RESPONSE_PARAM_ID" VARCHAR2(255 CHAR), 
  "RESPONSE_PARAM_NAME" VARCHAR2(255 CHAR), 
  "ROLE_NAME" VARCHAR2(255 CHAR), 
  "ROLE_TYPE" VARCHAR2(255 CHAR), 
  "ROLE_VALUE" VARCHAR2(255 CHAR), 
  "SHOW_CHECK_BOX" NUMBER(1,0), 
  "SHOW_TITLE" NUMBER(1,0), 
  "SPECIAL_FIELD" NUMBER(1,0), 
  "SPECIAL_FIELD_METHOD" VARCHAR2(255 CHAR), 
  "TABLE_DEFINITION_NAME" VARCHAR2(255 CHAR), 
  "TABLE_DEFINITION_TEXT" VARCHAR2(255 CHAR), 
  "URL" VARCHAR2(255 CHAR), 
  "VIEW_ID" VARCHAR2(255 CHAR), 
  "VIEW_NAME" VARCHAR2(255 CHAR)
   ) ;   

CREATE TABLE "CMS_CATEGORY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "APPOINT_CATEGORY_ID" VARCHAR2(255 CHAR), 
  "APPOINT_CATEGORY_NAME" VARCHAR2(255 CHAR), 
  "APPOINT_PAGE_ELEMENT" VARCHAR2(255 CHAR), 
  "APPOINT_PAGE_ELEMENT_ID" VARCHAR2(255 CHAR), 
  "APPOINT_WINDOW" VARCHAR2(255 CHAR), 
  "APPOINT_WINDOW_ID" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "DIV_ID" VARCHAR2(255 CHAR), 
  "ECODE" VARCHAR2(255 CHAR), 
  "FULL_WINDOW" VARCHAR2(255 CHAR), 
  "ICON" VARCHAR2(255 CHAR), 
  "INPUT_URL" VARCHAR2(455 CHAR), 
  "JS_CONTENT" VARCHAR2(255 CHAR), 
  "MODULE_ID" VARCHAR2(255 CHAR), 
  "NEW_PAGE" VARCHAR2(255 CHAR), 
  "OPEN_SEARCH" NUMBER(1,0), 
  "OPEN_TYPE" VARCHAR2(255 CHAR), 
  "PAGE_URL" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "RESOURCES" VARCHAR2(255 CHAR), 
  "SHOW_NUM" NUMBER(1,0), 
  "SHOW_TITLE" VARCHAR2(255 CHAR), 
  "TITLE" VARCHAR2(255 CHAR), 
  "PARENT_UUID" VARCHAR2(255 CHAR), 
  "CATE_NAME" VARCHAR2(255 CHAR), 
  "CATE_UUID" VARCHAR2(255 CHAR), 
  "APPOINT_PAGE" VARCHAR2(255 CHAR), 
  "APPOINT_PAGE_ID" VARCHAR2(255 CHAR), 
  "INDEX_NUM" VARCHAR2(255 CHAR), 
  "INDEX_CODE" VARCHAR2(255 CHAR), 
  "IS_HIDDEN" NUMBER(1,0)
   ) ;
CREATE TABLE "CMS_PAGE_SORT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CMS_PAGE" RAW(255), 
  "CREAT_USER" RAW(255), 
  "SN" NUMBER(10,0)
   ) ;
CREATE TABLE "CMS_WIDGET" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "DEFAULT_ROWS" NUMBER(10,0), 
  "EDIT_RESOLUTION" NUMBER(10,0), 
  "HEIGHT" FLOAT(126), 
  "IS_MAX_WIDTH" NUMBER(1,0), 
  "IS_TAB" NUMBER(1,0), 
  "JS_CONTENT" VARCHAR2(255 CHAR), 
  "LEFTX" FLOAT(126), 
  "MORE_STYLE" VARCHAR2(255 CHAR), 
  "OPEN_SEARCH" NUMBER(1,0), 
  "PARA" VARCHAR2(255 CHAR), 
  "SHOW_BORDER" NUMBER(1,0), 
  "SHOW_MORE" NUMBER(1,0), 
  "SHOW_NUM" NUMBER(1,0), 
  "SHOW_TITLE" NUMBER(1,0), 
  "TAB_VAL" VARCHAR2(255 CHAR), 
  "THEME" VARCHAR2(255 CHAR), 
  "TITLE" VARCHAR2(255 CHAR), 
  "TOPY" FLOAT(126), 
  "WID" VARCHAR2(255 CHAR), 
  "WIDTH" FLOAT(126), 
  "PAGE_UUID" VARCHAR2(255 CHAR), 
  "MODULE_UUID" VARCHAR2(255 CHAR), 
  "TAB_TITLE" NUMBER(1,0)
   ) ;
CREATE TABLE "CMS_FREQUENCY_RECORD" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CLICK_CATEGORY_NAME" VARCHAR2(255 CHAR), 
  "CLICK_CATEGORY_UUID" VARCHAR2(255 CHAR), 
  "CLICK_PERSON" VARCHAR2(255 CHAR), 
  "CLICK_TIME" TIMESTAMP (6), 
  "CLICK_URL" VARCHAR2(255 CHAR), 
  "CLICK_YEAR_MONTH" TIMESTAMP (6)
   ) ;
CREATE TABLE "CMS_MODULE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BEAN_CLASS" VARCHAR2(255 CHAR), 
  "CATALOG" VARCHAR2(255 CHAR), 
  "CATE_NAME" VARCHAR2(255 CHAR), 
  "CATE_UUID" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "COLUMNS" VARCHAR2(255 CHAR), 
  "CONTROL_CLASS" VARCHAR2(255 CHAR), 
  "CONTROL_METHOD" VARCHAR2(255 CHAR), 
  "DEFAULT_HEIGHT" FLOAT(126), 
  "DEFAULT_ROWS" NUMBER(10,0), 
  "DEFAULT_TPL_STYLE" VARCHAR2(255 CHAR), 
  "DEFAULT_WIDTH" FLOAT(126), 
  "HTML_CONTENT" VARCHAR2(255 CHAR), 
  "IS_EDIT" VARCHAR2(255 CHAR), 
  "JS_DIR" VARCHAR2(255 CHAR), 
  "MODULE_ID" VARCHAR2(255 CHAR), 
  "MORE_URL" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "PATH" VARCHAR2(255 CHAR), 
  "ROLE" VARCHAR2(255 CHAR), 
  "TEMP" CLOB, 
  "TITLE" VARCHAR2(255 CHAR), 
  "TPL_DIR" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "CATEGORY_EFFECT" VARCHAR2(255 CHAR), 
  "CATEGORY_EFFECT_VALUE" VARCHAR2(255 CHAR), 
  "CATEGORY_NAME" VARCHAR2(255 CHAR), 
  "CATEGORY_PATH" VARCHAR2(255 CHAR), 
  "RESOURCES" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CMS_PAGE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "CSS_CONTENT" VARCHAR2(255 CHAR), 
  "HTML_CONTENT" CLOB, 
  "ID" VARCHAR2(255 CHAR), 
  "JS_CONTENT" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "PAGE_TYPE" VARCHAR2(255 CHAR), 
  "PAGE_WIDTH" NUMBER(10,0), 
  "SN" NUMBER(10,0), 
  "SYS_CODE" VARCHAR2(255 CHAR), 
  "SYS_NAME" VARCHAR2(255 CHAR), 
  "TITLE" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "USER_NAMES" CLOB, 
  "USERS" CLOB, 
  "REMARK" VARCHAR2(255 CHAR), 
  "CATE_UUID" VARCHAR2(255 CHAR), 
  "CATE_NAME" VARCHAR2(255 CHAR), 
  "PARAM" VARCHAR2(255 CHAR)
   ) ;
   
-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/INDEX
CREATE INDEX "VIEW_COL_D_VIEW_DEF_UUID_IDX" ON "VIEW_COLUMNCSS_DEFINITION" ("VIEW_DEF_UUID");
ALTER INDEX "VIEW_COL_D_VIEW_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "VIEW_CD_VIEW_DEF_UUID_IDX" ON "VIEW_COLUMN_DEFINITION" ("VIEW_DEF_UUID");
ALTER INDEX "VIEW_CD_VIEW_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "VIEW_FS_SELECT_DEF_UUID_IDX" ON "VIEW_FIELD_SELECT" ("SELECT_DEF_UUID");
ALTER INDEX "VIEW_FS_SELECT_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "VIEW_PD_VIEW_DEF_UUID_IDX" ON "VIEW_PAGE_DEFINITION" ("VIEW_DEF_UUID");
ALTER INDEX "VIEW_PD_VIEW_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "VIEW_SCT_SELECT_DEF_UUID_IDX" ON "VIEW_SELECT_CONDITION_TYPE" ("SELECT_DEF_UUID");
ALTER INDEX "VIEW_SCT_SELECT_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "VIEW_SD_VIEW_DEF_UUID_IDX" ON "VIEW_SELECT_DEFINITION" ("VIEW_DEF_UUID");
ALTER INDEX "VIEW_SD_VIEW_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "VIEW_VCB_VIEW_DEF_UUID_IDX" ON "VIEW_VIEW_CUSTOM_BUTTON" ("VIEW_DEF_UUID");
ALTER INDEX "VIEW_VCB_VIEW_DEF_UUID_IDX" NOPARALLEL;

CREATE INDEX "DYVIEW_COL_D_VIEW_DEF_UUID_IDX" ON "DYVIEW_COLUMN_DEFINITION" ("VIEW_DEF_UUID");
ALTER INDEX "DYVIEW_COL_D_VIEW_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "DYVIEW_PD_VIEW_DEF_UUID_IDX" ON "DYVIEW_PAGE_DEFINITION" ("VIEW_DEF_UUID");
ALTER INDEX "DYVIEW_PD_VIEW_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "DYVIEW_SD_VIEW_DEF_UUID_IDX" ON "DYVIEW_SELECT_DEFINITION" ("VIEW_DEF_UUID");
ALTER INDEX "DYVIEW_SD_VIEW_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "DYVIEW_SE_SELECT_DEF_UUID_IDX" ON "DYVIEW_SELECT_EXACTKEY" ("SELECT_DEF_UUID");
ALTER INDEX "DYVIEW_SE_SELECT_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "DYVIEW_VCB_VIEW_DEF_UUID_IDX" ON "DYVIEW_VIEW_CUSTOM_BUTTON" ("VIEW_DEF_UUID");
ALTER INDEX "DYVIEW_VCB_VIEW_DEF_UUID_IDX" NOPARALLEL;

CREATE INDEX "CMS_CATEGORY_PARENT_UUID_IDX" ON "CMS_CATEGORY" ("PARENT_UUID");
ALTER INDEX "CMS_CATEGORY_PARENT_UUID_IDX" NOPARALLEL;
CREATE INDEX "CMS_WIDGET_PAGE_UUID_IDX" ON "CMS_WIDGET" ("PAGE_UUID");
ALTER INDEX "CMS_WIDGET_PAGE_UUID_IDX" NOPARALLEL;
CREATE INDEX "CMS_WIDGET_MODULE_UUID_IDX" ON "CMS_WIDGET" ("MODULE_UUID");
ALTER INDEX "CMS_WIDGET_MODULE_UUID_IDX" NOPARALLEL;

-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT
ALTER TABLE "VIEW_COLUMNCSS_DEFINITION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "VIEW_COLUMN_DEFINITION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "VIEW_DEFINITION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "VIEW_FIELD_SELECT" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "VIEW_PAGE_DEFINITION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "VIEW_SELECT_CONDITION_TYPE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "VIEW_SELECT_DEFINITION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "VIEW_VIEW_CUSTOM_BUTTON" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
  
