ALTER TABLE MSG_MESSAGE_QUEUE ADD SYSTEM VARCHAR2(64);
ALTER TABLE MSG_MESSAGE_QUEUE ADD TENANT VARCHAR2(64);
COMMENT ON COLUMN MSG_MESSAGE_QUEUE.SYSTEM
  IS '归属系统';
COMMENT ON COLUMN MSG_MESSAGE_QUEUE.TENANT
  IS '归属租户';


 ALTER TABLE MSG_MESSAGE_INBOX ADD SYSTEM VARCHAR2(64);
ALTER TABLE MSG_MESSAGE_INBOX ADD TENANT VARCHAR2(64);
 COMMENT ON COLUMN MSG_MESSAGE_INBOX.SYSTEM
  IS '归属系统';
COMMENT ON COLUMN MSG_MESSAGE_INBOX.TENANT
  IS '归属租户';


 ALTER TABLE MSG_MESSAGE_OUTBOX ADD SYSTEM VARCHAR2(64);
ALTER TABLE MSG_MESSAGE_OUTBOX ADD TENANT VARCHAR2(64);
 COMMENT ON COLUMN MSG_MESSAGE_OUTBOX.SYSTEM
  IS '归属系统';
COMMENT ON COLUMN MSG_MESSAGE_OUTBOX.TENANT
  IS '归属租户';


