 
CREATE TABLE MSG_SMS_LOG  
(
  UUID                 NUMBER(20)           NOT NULL,
  PHONE_NUMBER VARCHAR2(24),
    SENDER_NUMBER VARCHAR2(24),

  MESSAGE_TYPE NUMBER(1) DEFAULT 0 ,
  STATUS NUMBER(1) DEFAULT  0,
    CONTENT CLOB,
   ERROR_CODE VARCHAR2(12),
   ERROR_MESSAGE VARCHAR2(300 CHAR),
     SEND_TIME          TIMESTAMP,
  RECEIVE_TIME          TIMESTAMP,
  USER_ID VARCHAR2(64 CHAR),
  BATCH_ID VARCHAR2( 32 CHAR),
  SMS_ID VARCHAR2(120 CHAR),
  REC_ID VARCHAR2(120 CHAR),
  IS_READ NUMBER(1) DEFAULT 0 , 
  CREATE_TIME          TIMESTAMP,
  CREATOR              VARCHAR2(64),
  MODIFIER             VARCHAR2(64),
  MODIFY_TIME          TIMESTAMP,
  REC_VER              FLOAT(3)             DEFAULT 1,
  SYSTEM               VARCHAR2(64),
  TENANT               VARCHAR2(64),

  CONSTRAINT PK_MSG_SMS_LOG PRIMARY KEY (UUID)
);

comment on table MSG_SMS_LOG  is
'短信日志';

 
COMMENT ON COLUMN MSG_SMS_LOG.PHONE_NUMBER IS '接收手机号码';
COMMENT ON COLUMN MSG_SMS_LOG.SENDER_NUMBER IS '发送方号码';
COMMENT ON COLUMN MSG_SMS_LOG.MESSAGE_TYPE IS '0 发送 1 接收';
COMMENT ON COLUMN MSG_SMS_LOG.STATUS IS '0 待发送 1 发送中 2 发送成功 3 发送失败 4 接收成功'; 
COMMENT ON COLUMN MSG_SMS_LOG.CONTENT IS '发送内容';
COMMENT ON COLUMN MSG_SMS_LOG.ERROR_CODE IS '错误编码';
COMMENT ON COLUMN MSG_SMS_LOG.ERROR_MESSAGE IS '错误信息';
COMMENT ON COLUMN MSG_SMS_LOG.RECEIVE_TIME IS '发送时间';
COMMENT ON COLUMN MSG_SMS_LOG.BATCH_ID IS '发送批次';
COMMENT ON COLUMN MSG_SMS_LOG.SMS_ID IS '短信ID';
COMMENT ON COLUMN MSG_SMS_LOG.REC_ID IS '短信回执ID';
COMMENT ON COLUMN MSG_SMS_LOG.IS_READ IS '0 未读 1 已读';
