CREATE DATABASE [oa_tenant2] ON  PRIMARY 
( NAME = N'oa_tenant2', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\oa_tenant2.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'oa_tenant2_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\oa_tenant2_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [oa_tenant2] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [oa_tenant2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [oa_tenant2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [oa_tenant2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [oa_tenant2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [oa_tenant2] SET ARITHABORT OFF 
GO
ALTER DATABASE [oa_tenant2] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [oa_tenant2] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [oa_tenant2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [oa_tenant2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [oa_tenant2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [oa_tenant2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [oa_tenant2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [oa_tenant2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [oa_tenant2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [oa_tenant2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [oa_tenant2] SET  DISABLE_BROKER 
GO
ALTER DATABASE [oa_tenant2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [oa_tenant2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [oa_tenant2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [oa_tenant2] SET  READ_WRITE 
GO
ALTER DATABASE [oa_tenant2] SET RECOVERY FULL 
GO
ALTER DATABASE [oa_tenant2] SET  MULTI_USER 
GO
ALTER DATABASE [oa_tenant2] SET PAGE_VERIFY CHECKSUM  
GO
USE [oa_tenant2]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [oa_tenant2] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
