-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
CREATE TABLE "DYFORM_SQL_LOG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATOR" VARCHAR2(255 CHAR), 
  "CREATE_TIME" TIMESTAMP (6), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "SQL_SCRIPT" VARCHAR2(2000 CHAR), 
  "TABLE_NAME" VARCHAR2(50 CHAR), 
  "FORM_UUID" VARCHAR2(50 CHAR)
   ) ;

CREATE TABLE "DYFORM_FORM_DEFINITION" 
   (  "UUID" VARCHAR2(50 BYTE), 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(50 BYTE), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "APPLY_TO" VARCHAR2(255 CHAR), 
  "OUTER_ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(50 CHAR), 
  "DISPLAY_NAME" VARCHAR2(100 CHAR), 
  "REMARK" VARCHAR2(500 CHAR), 
  "FORM_DISPLAY" VARCHAR2(255 CHAR), 
  "HTML" CLOB, 
  "MODULE_ID" VARCHAR2(255 CHAR), 
  "MODULE_NAME" VARCHAR2(255 CHAR), 
  "PRINT_TEMPLATE_ID" VARCHAR2(255 CHAR), 
  "PRINT_TEMPLATE_NAME" VARCHAR2(255 CHAR), 
  "DISPLAY_FORM_MODEL_NAME" VARCHAR2(255 CHAR), 
  "DISPLAY_FORM_MODEL_ID" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "VERSION" VARCHAR2(50 CHAR), 
  "ENABLE_SIGNATURE" VARCHAR2(255 CHAR), 
  "DEFINITION_JSON" CLOB, 
  "MODIFIER" VARCHAR2(50 BYTE), 
  "RELATION_TBL" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "DYFORM_DISPLAY_MODEL" 
   (  "UUID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(50 BYTE), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "OUTER_ID" VARCHAR2(255 CHAR), 
  "DISPLAY_NAME" VARCHAR2(100 CHAR), 
  "REMARK" VARCHAR2(500 CHAR), 
  "HTML" CLOB, 
  "REFERRED_FORM_ID" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(50 BYTE), 
  "PREVIEW" VARCHAR2(10 BYTE), 
  "OUTER_ID_BAK" VARCHAR2(255 CHAR), 
  "HTML_MOBILE_BAK" CLOB, 
  "HTML_MOBILE" CLOB
   ) ;
   
-- new object type path: SCHEMA_EXPORT/TABLE/COMMENT
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."APPLY_TO" IS '应用于';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."OUTER_ID" IS '表单属性id';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."NAME" IS '表名';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."DISPLAY_NAME" IS '显示名称';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."REMARK" IS '描述';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."FORM_DISPLAY" IS '表单显示形式 ： 两种 一种是可编辑展示、 一种是直接展示文本';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."HTML" IS '定义html模板';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."MODULE_ID" IS '模块ID';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."MODULE_NAME" IS '模块名';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."PRINT_TEMPLATE_ID" IS '打印模板的ID';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."PRINT_TEMPLATE_NAME" IS '打印模板的名称';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."DISPLAY_FORM_MODEL_NAME" IS '显示单据的名称';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."DISPLAY_FORM_MODEL_ID" IS '显示单据对应的表单uuid';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."CODE" IS '表单编号';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."VERSION" IS '版本 ,形式：1.0';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."ENABLE_SIGNATURE" IS '是否启用表单签名';
 COMMENT ON COLUMN "DYFORM_FORM_DEFINITION"."DEFINITION_JSON" IS '定义JSON';
 
 -- new object type path: SCHEMA_EXPORT/TABLE/INDEX/INDEX
 CREATE UNIQUE INDEX "DYFORM_FORM_DEFINITION" ON "DYFORM_FORM_DEFINITION" ("UUID");
 ALTER INDEX "DYFORM_FORM_DEFINITION" NOPARALLEL;
CREATE UNIQUE INDEX "DYFORM_DISPLAY_MODE_PK" ON "DYFORM_DISPLAY_MODEL" ("UUID");
ALTER INDEX "DYFORM_DISPLAY_MODE_PK" NOPARALLEL;