// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: iexportStorageData.proto

package com.wellsoft.pt.basicdata.iexport.protos;

public final class IexportStorageDataProto {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_IexportStorageDataCollection_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_IexportStorageDataCollection_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_IexportStorageDataCollection_IexportStorageData_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_IexportStorageDataCollection_IexportStorageData_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\030iexportStorageData.proto\"\214\002\n\034IexportSt" +
                        "orageDataCollection\022F\n\014iexportDatas\030\001 \003(" +
                        "\01320.IexportStorageDataCollection.Iexport" +
                        "StorageData\032\243\001\n\022IexportStorageData\022\014\n\004uu" +
                        "id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\022\n\n" +
                        "parentUuid\030\004 \001(\t\022\016\n\006recVer\030\005 \001(\005\022\017\n\007rowD" +
                        "ata\030\006 \001(\014\022\020\n\010priority\030\007 \001(\010\022\014\n\004data\030\010 \001(" +
                        "\014\022\016\n\006record\030\t \001(\014BC\n(com.wellsoft.pt.bas" +
                        "icdata.iexport.protosB\027IexportStorageDat" +
                        "aProtob\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_IexportStorageDataCollection_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_IexportStorageDataCollection_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_IexportStorageDataCollection_descriptor,
                new String[]{"IexportDatas",});
        internal_static_IexportStorageDataCollection_IexportStorageData_descriptor =
                internal_static_IexportStorageDataCollection_descriptor.getNestedTypes().get(0);
        internal_static_IexportStorageDataCollection_IexportStorageData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_IexportStorageDataCollection_IexportStorageData_descriptor,
                new String[]{"Uuid", "Name", "Type", "ParentUuid", "RecVer", "RowData", "Priority", "Data", "Record",});
    }
    private IexportStorageDataProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface IexportStorageDataCollectionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:IexportStorageDataCollection)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
         */
        java.util.List<IexportStorageDataCollection.IexportStorageData>
        getIexportDatasList();

        /**
         * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
         */
        IexportStorageDataCollection.IexportStorageData getIexportDatas(int index);

        /**
         * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
         */
        int getIexportDatasCount();

        /**
         * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
         */
        java.util.List<? extends IexportStorageDataCollection.IexportStorageDataOrBuilder>
        getIexportDatasOrBuilderList();

        /**
         * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
         */
        IexportStorageDataCollection.IexportStorageDataOrBuilder getIexportDatasOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code IexportStorageDataCollection}
     */
    public static final class IexportStorageDataCollection extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:IexportStorageDataCollection)
            IexportStorageDataCollectionOrBuilder {
        public static final int IEXPORTDATAS_FIELD_NUMBER = 1;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:IexportStorageDataCollection)
        private static final IexportStorageDataCollection DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<IexportStorageDataCollection>
                PARSER = new com.google.protobuf.AbstractParser<IexportStorageDataCollection>() {
            @Override
            public IexportStorageDataCollection parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new IexportStorageDataCollection(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new IexportStorageDataCollection();
        }

        private java.util.List<IexportStorageData> iexportDatas_;
        private byte memoizedIsInitialized = -1;

        // Use IexportStorageDataCollection.newBuilder() to construct.
        private IexportStorageDataCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private IexportStorageDataCollection() {
            iexportDatas_ = java.util.Collections.emptyList();
        }

        private IexportStorageDataCollection(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                iexportDatas_ = new java.util.ArrayList<IexportStorageData>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            iexportDatas_.add(
                                    input.readMessage(IexportStorageData.parser(), extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    iexportDatas_ = java.util.Collections.unmodifiableList(iexportDatas_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return IexportStorageDataProto.internal_static_IexportStorageDataCollection_descriptor;
        }

        public static IexportStorageDataCollection parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IexportStorageDataCollection parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IexportStorageDataCollection parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IexportStorageDataCollection parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IexportStorageDataCollection parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static IexportStorageDataCollection parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static IexportStorageDataCollection parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static IexportStorageDataCollection parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static IexportStorageDataCollection parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static IexportStorageDataCollection parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static IexportStorageDataCollection parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static IexportStorageDataCollection parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(IexportStorageDataCollection prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static IexportStorageDataCollection getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<IexportStorageDataCollection> parser() {
            return PARSER;
        }

        @Override
        @SuppressWarnings({"unused"})
        protected Object newInstance(
                UnusedPrivateParameter unused) {
            return new IexportStorageDataCollection();
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return IexportStorageDataProto.internal_static_IexportStorageDataCollection_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            IexportStorageDataCollection.class, Builder.class);
        }

        /**
         * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
         */
        public java.util.List<IexportStorageData> getIexportDatasList() {
            return iexportDatas_;
        }

        /**
         * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
         */
        public java.util.List<? extends IexportStorageDataOrBuilder>
        getIexportDatasOrBuilderList() {
            return iexportDatas_;
        }

        /**
         * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
         */
        public int getIexportDatasCount() {
            return iexportDatas_.size();
        }

        /**
         * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
         */
        public IexportStorageData getIexportDatas(int index) {
            return iexportDatas_.get(index);
        }

        /**
         * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
         */
        public IexportStorageDataOrBuilder getIexportDatasOrBuilder(
                int index) {
            return iexportDatas_.get(index);
        }

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < iexportDatas_.size(); i++) {
                output.writeMessage(1, iexportDatas_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < iexportDatas_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, iexportDatas_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof IexportStorageDataCollection)) {
                return super.equals(obj);
            }
            IexportStorageDataCollection other = (IexportStorageDataCollection) obj;

            if (!getIexportDatasList()
                    .equals(other.getIexportDatasList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getIexportDatasCount() > 0) {
                hash = (37 * hash) + IEXPORTDATAS_FIELD_NUMBER;
                hash = (53 * hash) + getIexportDatasList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<IexportStorageDataCollection> getParserForType() {
            return PARSER;
        }

        @Override
        public IexportStorageDataCollection getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        public interface IexportStorageDataOrBuilder extends
                // @@protoc_insertion_point(interface_extends:IexportStorageDataCollection.IexportStorageData)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>string uuid = 1;</code>
             *
             * @return The uuid.
             */
            String getUuid();

            /**
             * <code>string uuid = 1;</code>
             *
             * @return The bytes for uuid.
             */
            com.google.protobuf.ByteString
            getUuidBytes();

            /**
             * <code>string name = 2;</code>
             *
             * @return The name.
             */
            String getName();

            /**
             * <code>string name = 2;</code>
             *
             * @return The bytes for name.
             */
            com.google.protobuf.ByteString
            getNameBytes();

            /**
             * <code>string type = 3;</code>
             *
             * @return The type.
             */
            String getType();

            /**
             * <code>string type = 3;</code>
             *
             * @return The bytes for type.
             */
            com.google.protobuf.ByteString
            getTypeBytes();

            /**
             * <code>string parentUuid = 4;</code>
             *
             * @return The parentUuid.
             */
            String getParentUuid();

            /**
             * <code>string parentUuid = 4;</code>
             *
             * @return The bytes for parentUuid.
             */
            com.google.protobuf.ByteString
            getParentUuidBytes();

            /**
             * <code>int32 recVer = 5;</code>
             *
             * @return The recVer.
             */
            int getRecVer();

            /**
             * <code>bytes rowData = 6;</code>
             *
             * @return The rowData.
             */
            com.google.protobuf.ByteString getRowData();

            /**
             * <code>bool priority = 7;</code>
             *
             * @return The priority.
             */
            boolean getPriority();

            /**
             * <code>bytes data = 8;</code>
             *
             * @return The data.
             */
            com.google.protobuf.ByteString getData();

            /**
             * <code>bytes record = 9;</code>
             *
             * @return The record.
             */
            com.google.protobuf.ByteString getRecord();
        }

        /**
         * Protobuf type {@code IexportStorageDataCollection.IexportStorageData}
         */
        public static final class IexportStorageData extends
                com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:IexportStorageDataCollection.IexportStorageData)
                IexportStorageDataOrBuilder {
            public static final int UUID_FIELD_NUMBER = 1;
            public static final int NAME_FIELD_NUMBER = 2;
            public static final int TYPE_FIELD_NUMBER = 3;
            public static final int PARENTUUID_FIELD_NUMBER = 4;
            public static final int RECVER_FIELD_NUMBER = 5;
            public static final int ROWDATA_FIELD_NUMBER = 6;
            public static final int PRIORITY_FIELD_NUMBER = 7;
            public static final int DATA_FIELD_NUMBER = 8;
            public static final int RECORD_FIELD_NUMBER = 9;
            private static final long serialVersionUID = 0L;
            // @@protoc_insertion_point(class_scope:IexportStorageDataCollection.IexportStorageData)
            private static final IexportStorageData DEFAULT_INSTANCE;
            private static final com.google.protobuf.Parser<IexportStorageData>
                    PARSER = new com.google.protobuf.AbstractParser<IexportStorageData>() {
                @Override
                public IexportStorageData parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new IexportStorageData(input, extensionRegistry);
                }
            };

            static {
                DEFAULT_INSTANCE = new IexportStorageData();
            }

            private volatile Object uuid_;
            private volatile Object name_;
            private volatile Object type_;
            private volatile Object parentUuid_;
            private int recVer_;
            private com.google.protobuf.ByteString rowData_;
            private boolean priority_;
            private com.google.protobuf.ByteString data_;
            private com.google.protobuf.ByteString record_;
            private byte memoizedIsInitialized = -1;

            // Use IexportStorageData.newBuilder() to construct.
            private IexportStorageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
                super(builder);
            }

            private IexportStorageData() {
                uuid_ = "";
                name_ = "";
                type_ = "";
                parentUuid_ = "";
                rowData_ = com.google.protobuf.ByteString.EMPTY;
                data_ = com.google.protobuf.ByteString.EMPTY;
                record_ = com.google.protobuf.ByteString.EMPTY;
            }
            private IexportStorageData(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                this();
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                String s = input.readStringRequireUtf8();

                                uuid_ = s;
                                break;
                            }
                            case 18: {
                                String s = input.readStringRequireUtf8();

                                name_ = s;
                                break;
                            }
                            case 26: {
                                String s = input.readStringRequireUtf8();

                                type_ = s;
                                break;
                            }
                            case 34: {
                                String s = input.readStringRequireUtf8();

                                parentUuid_ = s;
                                break;
                            }
                            case 40: {

                                recVer_ = input.readInt32();
                                break;
                            }
                            case 50: {

                                rowData_ = input.readBytes();
                                break;
                            }
                            case 56: {

                                priority_ = input.readBool();
                                break;
                            }
                            case 66: {

                                data_ = input.readBytes();
                                break;
                            }
                            case 74: {

                                record_ = input.readBytes();
                                break;
                            }
                            default: {
                                if (!parseUnknownField(
                                        input, unknownFields, extensionRegistry, tag)) {
                                    done = true;
                                }
                                break;
                            }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(
                            e).setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return IexportStorageDataProto.internal_static_IexportStorageDataCollection_IexportStorageData_descriptor;
            }

            public static IexportStorageData parseFrom(
                    java.nio.ByteBuffer data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static IexportStorageData parseFrom(
                    java.nio.ByteBuffer data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static IexportStorageData parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static IexportStorageData parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static IexportStorageData parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static IexportStorageData parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static IexportStorageData parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static IexportStorageData parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            public static IexportStorageData parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input);
            }

            public static IexportStorageData parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
            }

            public static IexportStorageData parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input);
            }

            public static IexportStorageData parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3
                        .parseWithIOException(PARSER, input, extensionRegistry);
            }

            public static Builder newBuilder() {
                return DEFAULT_INSTANCE.toBuilder();
            }

            public static Builder newBuilder(IexportStorageData prototype) {
                return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
            }

            public static IexportStorageData getDefaultInstance() {
                return DEFAULT_INSTANCE;
            }

            public static com.google.protobuf.Parser<IexportStorageData> parser() {
                return PARSER;
            }

            @Override
            @SuppressWarnings({"unused"})
            protected Object newInstance(
                    UnusedPrivateParameter unused) {
                return new IexportStorageData();
            }

            @Override
            public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
                return this.unknownFields;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return IexportStorageDataProto.internal_static_IexportStorageDataCollection_IexportStorageData_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                IexportStorageData.class, Builder.class);
            }

            /**
             * <code>string uuid = 1;</code>
             *
             * @return The uuid.
             */
            public String getUuid() {
                Object ref = uuid_;
                if (ref instanceof String) {
                    return (String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    uuid_ = s;
                    return s;
                }
            }

            /**
             * <code>string uuid = 1;</code>
             *
             * @return The bytes for uuid.
             */
            public com.google.protobuf.ByteString
            getUuidBytes() {
                Object ref = uuid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    uuid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 2;</code>
             *
             * @return The name.
             */
            public String getName() {
                Object ref = name_;
                if (ref instanceof String) {
                    return (String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                }
            }

            /**
             * <code>string name = 2;</code>
             *
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string type = 3;</code>
             *
             * @return The type.
             */
            public String getType() {
                Object ref = type_;
                if (ref instanceof String) {
                    return (String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    type_ = s;
                    return s;
                }
            }

            /**
             * <code>string type = 3;</code>
             *
             * @return The bytes for type.
             */
            public com.google.protobuf.ByteString
            getTypeBytes() {
                Object ref = type_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    type_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string parentUuid = 4;</code>
             *
             * @return The parentUuid.
             */
            public String getParentUuid() {
                Object ref = parentUuid_;
                if (ref instanceof String) {
                    return (String) ref;
                } else {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    parentUuid_ = s;
                    return s;
                }
            }

            /**
             * <code>string parentUuid = 4;</code>
             *
             * @return The bytes for parentUuid.
             */
            public com.google.protobuf.ByteString
            getParentUuidBytes() {
                Object ref = parentUuid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    parentUuid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>int32 recVer = 5;</code>
             *
             * @return The recVer.
             */
            public int getRecVer() {
                return recVer_;
            }

            /**
             * <code>bytes rowData = 6;</code>
             *
             * @return The rowData.
             */
            public com.google.protobuf.ByteString getRowData() {
                return rowData_;
            }

            /**
             * <code>bool priority = 7;</code>
             *
             * @return The priority.
             */
            public boolean getPriority() {
                return priority_;
            }

            /**
             * <code>bytes data = 8;</code>
             *
             * @return The data.
             */
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            /**
             * <code>bytes record = 9;</code>
             *
             * @return The record.
             */
            public com.google.protobuf.ByteString getRecord() {
                return record_;
            }

            @Override
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1) return true;
                if (isInitialized == 0) return false;

                memoizedIsInitialized = 1;
                return true;
            }

            @Override
            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                if (!getUuidBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
                }
                if (!getNameBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
                }
                if (!getTypeBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
                }
                if (!getParentUuidBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 4, parentUuid_);
                }
                if (recVer_ != 0) {
                    output.writeInt32(5, recVer_);
                }
                if (!rowData_.isEmpty()) {
                    output.writeBytes(6, rowData_);
                }
                if (priority_ != false) {
                    output.writeBool(7, priority_);
                }
                if (!data_.isEmpty()) {
                    output.writeBytes(8, data_);
                }
                if (!record_.isEmpty()) {
                    output.writeBytes(9, record_);
                }
                unknownFields.writeTo(output);
            }

            @Override
            public int getSerializedSize() {
                int size = memoizedSize;
                if (size != -1) return size;

                size = 0;
                if (!getUuidBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
                }
                if (!getNameBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
                }
                if (!getTypeBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
                }
                if (!getParentUuidBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, parentUuid_);
                }
                if (recVer_ != 0) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32Size(5, recVer_);
                }
                if (!rowData_.isEmpty()) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBytesSize(6, rowData_);
                }
                if (priority_ != false) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBoolSize(7, priority_);
                }
                if (!data_.isEmpty()) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBytesSize(8, data_);
                }
                if (!record_.isEmpty()) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBytesSize(9, record_);
                }
                size += unknownFields.getSerializedSize();
                memoizedSize = size;
                return size;
            }

            @Override
            public boolean equals(final Object obj) {
                if (obj == this) {
                    return true;
                }
                if (!(obj instanceof IexportStorageData)) {
                    return super.equals(obj);
                }
                IexportStorageData other = (IexportStorageData) obj;

                if (!getUuid()
                        .equals(other.getUuid())) return false;
                if (!getName()
                        .equals(other.getName())) return false;
                if (!getType()
                        .equals(other.getType())) return false;
                if (!getParentUuid()
                        .equals(other.getParentUuid())) return false;
                if (getRecVer()
                        != other.getRecVer()) return false;
                if (!getRowData()
                        .equals(other.getRowData())) return false;
                if (getPriority()
                        != other.getPriority()) return false;
                if (!getData()
                        .equals(other.getData())) return false;
                if (!getRecord()
                        .equals(other.getRecord())) return false;
                if (!unknownFields.equals(other.unknownFields)) return false;
                return true;
            }

            @Override
            public int hashCode() {
                if (memoizedHashCode != 0) {
                    return memoizedHashCode;
                }
                int hash = 41;
                hash = (19 * hash) + getDescriptor().hashCode();
                hash = (37 * hash) + UUID_FIELD_NUMBER;
                hash = (53 * hash) + getUuid().hashCode();
                hash = (37 * hash) + NAME_FIELD_NUMBER;
                hash = (53 * hash) + getName().hashCode();
                hash = (37 * hash) + TYPE_FIELD_NUMBER;
                hash = (53 * hash) + getType().hashCode();
                hash = (37 * hash) + PARENTUUID_FIELD_NUMBER;
                hash = (53 * hash) + getParentUuid().hashCode();
                hash = (37 * hash) + RECVER_FIELD_NUMBER;
                hash = (53 * hash) + getRecVer();
                hash = (37 * hash) + ROWDATA_FIELD_NUMBER;
                hash = (53 * hash) + getRowData().hashCode();
                hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
                hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                        getPriority());
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getData().hashCode();
                hash = (37 * hash) + RECORD_FIELD_NUMBER;
                hash = (53 * hash) + getRecord().hashCode();
                hash = (29 * hash) + unknownFields.hashCode();
                memoizedHashCode = hash;
                return hash;
            }

            @Override
            public Builder newBuilderForType() {
                return newBuilder();
            }

            @Override
            public Builder toBuilder() {
                return this == DEFAULT_INSTANCE
                        ? new Builder() : new Builder().mergeFrom(this);
            }

            @Override
            protected Builder newBuilderForType(
                    BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            @Override
            public com.google.protobuf.Parser<IexportStorageData> getParserForType() {
                return PARSER;
            }

            @Override
            public IexportStorageData getDefaultInstanceForType() {
                return DEFAULT_INSTANCE;
            }

            /**
             * Protobuf type {@code IexportStorageDataCollection.IexportStorageData}
             */
            public static final class Builder extends
                    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:IexportStorageDataCollection.IexportStorageData)
                    IexportStorageDataOrBuilder {
                private Object uuid_ = "";
                private Object name_ = "";
                private Object type_ = "";
                private Object parentUuid_ = "";
                private int recVer_;
                private com.google.protobuf.ByteString rowData_ = com.google.protobuf.ByteString.EMPTY;
                private boolean priority_;
                private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
                private com.google.protobuf.ByteString record_ = com.google.protobuf.ByteString.EMPTY;

                // Construct using com.wellsoft.pt.basicdata.iexport.protos.IexportStorageDataProto.IexportStorageDataCollection.IexportStorageData.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(
                        BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
                    return IexportStorageDataProto.internal_static_IexportStorageDataCollection_IexportStorageData_descriptor;
                }

                @Override
                protected FieldAccessorTable
                internalGetFieldAccessorTable() {
                    return IexportStorageDataProto.internal_static_IexportStorageDataCollection_IexportStorageData_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(
                                    IexportStorageData.class, Builder.class);
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessageV3
                            .alwaysUseFieldBuilders) {
                    }
                }

                @Override
                public Builder clear() {
                    super.clear();
                    uuid_ = "";

                    name_ = "";

                    type_ = "";

                    parentUuid_ = "";

                    recVer_ = 0;

                    rowData_ = com.google.protobuf.ByteString.EMPTY;

                    priority_ = false;

                    data_ = com.google.protobuf.ByteString.EMPTY;

                    record_ = com.google.protobuf.ByteString.EMPTY;

                    return this;
                }

                @Override
                public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
                    return IexportStorageDataProto.internal_static_IexportStorageDataCollection_IexportStorageData_descriptor;
                }

                @Override
                public IexportStorageData getDefaultInstanceForType() {
                    return IexportStorageData.getDefaultInstance();
                }

                @Override
                public IexportStorageData build() {
                    IexportStorageData result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                @Override
                public IexportStorageData buildPartial() {
                    IexportStorageData result = new IexportStorageData(this);
                    result.uuid_ = uuid_;
                    result.name_ = name_;
                    result.type_ = type_;
                    result.parentUuid_ = parentUuid_;
                    result.recVer_ = recVer_;
                    result.rowData_ = rowData_;
                    result.priority_ = priority_;
                    result.data_ = data_;
                    result.record_ = record_;
                    onBuilt();
                    return result;
                }

                @Override
                public Builder clone() {
                    return super.clone();
                }

                @Override
                public Builder setField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        Object value) {
                    return super.setField(field, value);
                }

                @Override
                public Builder clearField(
                        com.google.protobuf.Descriptors.FieldDescriptor field) {
                    return super.clearField(field);
                }

                @Override
                public Builder clearOneof(
                        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                    return super.clearOneof(oneof);
                }

                @Override
                public Builder setRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        int index, Object value) {
                    return super.setRepeatedField(field, index, value);
                }

                @Override
                public Builder addRepeatedField(
                        com.google.protobuf.Descriptors.FieldDescriptor field,
                        Object value) {
                    return super.addRepeatedField(field, value);
                }

                @Override
                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof IexportStorageData) {
                        return mergeFrom((IexportStorageData) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(IexportStorageData other) {
                    if (other == IexportStorageData.getDefaultInstance()) return this;
                    if (!other.getUuid().isEmpty()) {
                        uuid_ = other.uuid_;
                        onChanged();
                    }
                    if (!other.getName().isEmpty()) {
                        name_ = other.name_;
                        onChanged();
                    }
                    if (!other.getType().isEmpty()) {
                        type_ = other.type_;
                        onChanged();
                    }
                    if (!other.getParentUuid().isEmpty()) {
                        parentUuid_ = other.parentUuid_;
                        onChanged();
                    }
                    if (other.getRecVer() != 0) {
                        setRecVer(other.getRecVer());
                    }
                    if (other.getRowData() != com.google.protobuf.ByteString.EMPTY) {
                        setRowData(other.getRowData());
                    }
                    if (other.getPriority() != false) {
                        setPriority(other.getPriority());
                    }
                    if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
                        setData(other.getData());
                    }
                    if (other.getRecord() != com.google.protobuf.ByteString.EMPTY) {
                        setRecord(other.getRecord());
                    }
                    this.mergeUnknownFields(other.unknownFields);
                    onChanged();
                    return this;
                }

                @Override
                public final boolean isInitialized() {
                    return true;
                }

                @Override
                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    IexportStorageData parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (IexportStorageData) e.getUnfinishedMessage();
                        throw e.unwrapIOException();
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                /**
                 * <code>string uuid = 1;</code>
                 *
                 * @return The uuid.
                 */
                public String getUuid() {
                    Object ref = uuid_;
                    if (!(ref instanceof String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        String s = bs.toStringUtf8();
                        uuid_ = s;
                        return s;
                    } else {
                        return (String) ref;
                    }
                }

                /**
                 * <code>string uuid = 1;</code>
                 *
                 * @param value The uuid to set.
                 * @return This builder for chaining.
                 */
                public Builder setUuid(
                        String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    uuid_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string uuid = 1;</code>
                 *
                 * @return The bytes for uuid.
                 */
                public com.google.protobuf.ByteString
                getUuidBytes() {
                    Object ref = uuid_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (String) ref);
                        uuid_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>string uuid = 1;</code>
                 *
                 * @param value The bytes for uuid to set.
                 * @return This builder for chaining.
                 */
                public Builder setUuidBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    uuid_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string uuid = 1;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearUuid() {

                    uuid_ = getDefaultInstance().getUuid();
                    onChanged();
                    return this;
                }

                /**
                 * <code>string name = 2;</code>
                 *
                 * @return The name.
                 */
                public String getName() {
                    Object ref = name_;
                    if (!(ref instanceof String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        String s = bs.toStringUtf8();
                        name_ = s;
                        return s;
                    } else {
                        return (String) ref;
                    }
                }

                /**
                 * <code>string name = 2;</code>
                 *
                 * @param value The name to set.
                 * @return This builder for chaining.
                 */
                public Builder setName(
                        String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    name_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string name = 2;</code>
                 *
                 * @return The bytes for name.
                 */
                public com.google.protobuf.ByteString
                getNameBytes() {
                    Object ref = name_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (String) ref);
                        name_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>string name = 2;</code>
                 *
                 * @param value The bytes for name to set.
                 * @return This builder for chaining.
                 */
                public Builder setNameBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    name_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string name = 2;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearName() {

                    name_ = getDefaultInstance().getName();
                    onChanged();
                    return this;
                }

                /**
                 * <code>string type = 3;</code>
                 *
                 * @return The type.
                 */
                public String getType() {
                    Object ref = type_;
                    if (!(ref instanceof String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        String s = bs.toStringUtf8();
                        type_ = s;
                        return s;
                    } else {
                        return (String) ref;
                    }
                }

                /**
                 * <code>string type = 3;</code>
                 *
                 * @param value The type to set.
                 * @return This builder for chaining.
                 */
                public Builder setType(
                        String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    type_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string type = 3;</code>
                 *
                 * @return The bytes for type.
                 */
                public com.google.protobuf.ByteString
                getTypeBytes() {
                    Object ref = type_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (String) ref);
                        type_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>string type = 3;</code>
                 *
                 * @param value The bytes for type to set.
                 * @return This builder for chaining.
                 */
                public Builder setTypeBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    type_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string type = 3;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearType() {

                    type_ = getDefaultInstance().getType();
                    onChanged();
                    return this;
                }

                /**
                 * <code>string parentUuid = 4;</code>
                 *
                 * @return The parentUuid.
                 */
                public String getParentUuid() {
                    Object ref = parentUuid_;
                    if (!(ref instanceof String)) {
                        com.google.protobuf.ByteString bs =
                                (com.google.protobuf.ByteString) ref;
                        String s = bs.toStringUtf8();
                        parentUuid_ = s;
                        return s;
                    } else {
                        return (String) ref;
                    }
                }

                /**
                 * <code>string parentUuid = 4;</code>
                 *
                 * @param value The parentUuid to set.
                 * @return This builder for chaining.
                 */
                public Builder setParentUuid(
                        String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    parentUuid_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string parentUuid = 4;</code>
                 *
                 * @return The bytes for parentUuid.
                 */
                public com.google.protobuf.ByteString
                getParentUuidBytes() {
                    Object ref = parentUuid_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b =
                                com.google.protobuf.ByteString.copyFromUtf8(
                                        (String) ref);
                        parentUuid_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>string parentUuid = 4;</code>
                 *
                 * @param value The bytes for parentUuid to set.
                 * @return This builder for chaining.
                 */
                public Builder setParentUuidBytes(
                        com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    parentUuid_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string parentUuid = 4;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearParentUuid() {

                    parentUuid_ = getDefaultInstance().getParentUuid();
                    onChanged();
                    return this;
                }

                /**
                 * <code>int32 recVer = 5;</code>
                 *
                 * @return The recVer.
                 */
                public int getRecVer() {
                    return recVer_;
                }

                /**
                 * <code>int32 recVer = 5;</code>
                 *
                 * @param value The recVer to set.
                 * @return This builder for chaining.
                 */
                public Builder setRecVer(int value) {

                    recVer_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>int32 recVer = 5;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearRecVer() {

                    recVer_ = 0;
                    onChanged();
                    return this;
                }

                /**
                 * <code>bytes rowData = 6;</code>
                 *
                 * @return The rowData.
                 */
                public com.google.protobuf.ByteString getRowData() {
                    return rowData_;
                }

                /**
                 * <code>bytes rowData = 6;</code>
                 *
                 * @param value The rowData to set.
                 * @return This builder for chaining.
                 */
                public Builder setRowData(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    rowData_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>bytes rowData = 6;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearRowData() {

                    rowData_ = getDefaultInstance().getRowData();
                    onChanged();
                    return this;
                }

                /**
                 * <code>bool priority = 7;</code>
                 *
                 * @return The priority.
                 */
                public boolean getPriority() {
                    return priority_;
                }

                /**
                 * <code>bool priority = 7;</code>
                 *
                 * @param value The priority to set.
                 * @return This builder for chaining.
                 */
                public Builder setPriority(boolean value) {

                    priority_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>bool priority = 7;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearPriority() {

                    priority_ = false;
                    onChanged();
                    return this;
                }

                /**
                 * <code>bytes data = 8;</code>
                 *
                 * @return The data.
                 */
                public com.google.protobuf.ByteString getData() {
                    return data_;
                }

                /**
                 * <code>bytes data = 8;</code>
                 *
                 * @param value The data to set.
                 * @return This builder for chaining.
                 */
                public Builder setData(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    data_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>bytes data = 8;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearData() {

                    data_ = getDefaultInstance().getData();
                    onChanged();
                    return this;
                }

                /**
                 * <code>bytes record = 9;</code>
                 *
                 * @return The record.
                 */
                public com.google.protobuf.ByteString getRecord() {
                    return record_;
                }

                /**
                 * <code>bytes record = 9;</code>
                 *
                 * @param value The record to set.
                 * @return This builder for chaining.
                 */
                public Builder setRecord(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    record_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>bytes record = 9;</code>
                 *
                 * @return This builder for chaining.
                 */
                public Builder clearRecord() {

                    record_ = getDefaultInstance().getRecord();
                    onChanged();
                    return this;
                }

                @Override
                public final Builder setUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.setUnknownFields(unknownFields);
                }

                @Override
                public final Builder mergeUnknownFields(
                        final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.mergeUnknownFields(unknownFields);
                }


                // @@protoc_insertion_point(builder_scope:IexportStorageDataCollection.IexportStorageData)
            }

        }

        /**
         * Protobuf type {@code IexportStorageDataCollection}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:IexportStorageDataCollection)
                IexportStorageDataCollectionOrBuilder {
            private int bitField0_;
            private java.util.List<IexportStorageData> iexportDatas_ =
                    java.util.Collections.emptyList();
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    IexportStorageData, IexportStorageData.Builder, IexportStorageDataOrBuilder> iexportDatasBuilder_;

            // Construct using com.wellsoft.pt.basicdata.iexport.protos.IexportStorageDataProto.IexportStorageDataCollection.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return IexportStorageDataProto.internal_static_IexportStorageDataCollection_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return IexportStorageDataProto.internal_static_IexportStorageDataCollection_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                IexportStorageDataCollection.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getIexportDatasFieldBuilder();
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                if (iexportDatasBuilder_ == null) {
                    iexportDatas_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    iexportDatasBuilder_.clear();
                }
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return IexportStorageDataProto.internal_static_IexportStorageDataCollection_descriptor;
            }

            @Override
            public IexportStorageDataCollection getDefaultInstanceForType() {
                return IexportStorageDataCollection.getDefaultInstance();
            }

            @Override
            public IexportStorageDataCollection build() {
                IexportStorageDataCollection result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public IexportStorageDataCollection buildPartial() {
                IexportStorageDataCollection result = new IexportStorageDataCollection(this);
                int from_bitField0_ = bitField0_;
                if (iexportDatasBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)) {
                        iexportDatas_ = java.util.Collections.unmodifiableList(iexportDatas_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.iexportDatas_ = iexportDatas_;
                } else {
                    result.iexportDatas_ = iexportDatasBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof IexportStorageDataCollection) {
                    return mergeFrom((IexportStorageDataCollection) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(IexportStorageDataCollection other) {
                if (other == IexportStorageDataCollection.getDefaultInstance()) return this;
                if (iexportDatasBuilder_ == null) {
                    if (!other.iexportDatas_.isEmpty()) {
                        if (iexportDatas_.isEmpty()) {
                            iexportDatas_ = other.iexportDatas_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureIexportDatasIsMutable();
                            iexportDatas_.addAll(other.iexportDatas_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.iexportDatas_.isEmpty()) {
                        if (iexportDatasBuilder_.isEmpty()) {
                            iexportDatasBuilder_.dispose();
                            iexportDatasBuilder_ = null;
                            iexportDatas_ = other.iexportDatas_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            iexportDatasBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getIexportDatasFieldBuilder() : null;
                        } else {
                            iexportDatasBuilder_.addAllMessages(other.iexportDatas_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                IexportStorageDataCollection parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (IexportStorageDataCollection) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private void ensureIexportDatasIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    iexportDatas_ = new java.util.ArrayList<IexportStorageData>(iexportDatas_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public java.util.List<IexportStorageData> getIexportDatasList() {
                if (iexportDatasBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(iexportDatas_);
                } else {
                    return iexportDatasBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public int getIexportDatasCount() {
                if (iexportDatasBuilder_ == null) {
                    return iexportDatas_.size();
                } else {
                    return iexportDatasBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public IexportStorageData getIexportDatas(int index) {
                if (iexportDatasBuilder_ == null) {
                    return iexportDatas_.get(index);
                } else {
                    return iexportDatasBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public Builder setIexportDatas(
                    int index, IexportStorageData value) {
                if (iexportDatasBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureIexportDatasIsMutable();
                    iexportDatas_.set(index, value);
                    onChanged();
                } else {
                    iexportDatasBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public Builder setIexportDatas(
                    int index, IexportStorageData.Builder builderForValue) {
                if (iexportDatasBuilder_ == null) {
                    ensureIexportDatasIsMutable();
                    iexportDatas_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    iexportDatasBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public Builder addIexportDatas(IexportStorageData value) {
                if (iexportDatasBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureIexportDatasIsMutable();
                    iexportDatas_.add(value);
                    onChanged();
                } else {
                    iexportDatasBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public Builder addIexportDatas(
                    int index, IexportStorageData value) {
                if (iexportDatasBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureIexportDatasIsMutable();
                    iexportDatas_.add(index, value);
                    onChanged();
                } else {
                    iexportDatasBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public Builder addIexportDatas(
                    IexportStorageData.Builder builderForValue) {
                if (iexportDatasBuilder_ == null) {
                    ensureIexportDatasIsMutable();
                    iexportDatas_.add(builderForValue.build());
                    onChanged();
                } else {
                    iexportDatasBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public Builder addIexportDatas(
                    int index, IexportStorageData.Builder builderForValue) {
                if (iexportDatasBuilder_ == null) {
                    ensureIexportDatasIsMutable();
                    iexportDatas_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    iexportDatasBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public Builder addAllIexportDatas(
                    Iterable<? extends IexportStorageData> values) {
                if (iexportDatasBuilder_ == null) {
                    ensureIexportDatasIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, iexportDatas_);
                    onChanged();
                } else {
                    iexportDatasBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public Builder clearIexportDatas() {
                if (iexportDatasBuilder_ == null) {
                    iexportDatas_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    iexportDatasBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public Builder removeIexportDatas(int index) {
                if (iexportDatasBuilder_ == null) {
                    ensureIexportDatasIsMutable();
                    iexportDatas_.remove(index);
                    onChanged();
                } else {
                    iexportDatasBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public IexportStorageData.Builder getIexportDatasBuilder(
                    int index) {
                return getIexportDatasFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public IexportStorageDataOrBuilder getIexportDatasOrBuilder(
                    int index) {
                if (iexportDatasBuilder_ == null) {
                    return iexportDatas_.get(index);
                } else {
                    return iexportDatasBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public java.util.List<? extends IexportStorageDataOrBuilder>
            getIexportDatasOrBuilderList() {
                if (iexportDatasBuilder_ != null) {
                    return iexportDatasBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(iexportDatas_);
                }
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public IexportStorageData.Builder addIexportDatasBuilder() {
                return getIexportDatasFieldBuilder().addBuilder(
                        IexportStorageData.getDefaultInstance());
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public IexportStorageData.Builder addIexportDatasBuilder(
                    int index) {
                return getIexportDatasFieldBuilder().addBuilder(
                        index, IexportStorageData.getDefaultInstance());
            }

            /**
             * <code>repeated .IexportStorageDataCollection.IexportStorageData iexportDatas = 1;</code>
             */
            public java.util.List<IexportStorageData.Builder>
            getIexportDatasBuilderList() {
                return getIexportDatasFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    IexportStorageData, IexportStorageData.Builder, IexportStorageDataOrBuilder>
            getIexportDatasFieldBuilder() {
                if (iexportDatasBuilder_ == null) {
                    iexportDatasBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            IexportStorageData, IexportStorageData.Builder, IexportStorageDataOrBuilder>(
                            iexportDatas_,
                            ((bitField0_ & 0x00000001) != 0),
                            getParentForChildren(),
                            isClean());
                    iexportDatas_ = null;
                }
                return iexportDatasBuilder_;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:IexportStorageDataCollection)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
