-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
CREATE TABLE "AUDIT_NESTED_ROLE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ROLE_UUID" VARCHAR2(255 CHAR)
   ) ;

CREATE TABLE "AUDIT_PRIVILEGE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ENABLED" NUMBER(1,0), 
  "NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "REMARK" VARCHAR2(255 CHAR), 
  "CATEGORY_UUID" VARCHAR2(255 CHAR), 
  "CATEGORY_NAME" VARCHAR2(255 CHAR)
   ) ;
   
CREATE TABLE "AUDIT_ROLE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "ISSYS" NUMBER(1,0), 
  "NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "REMARK" VARCHAR2(255 CHAR), 
  "SOURCE_UUID" VARCHAR2(255 CHAR), 
  "CATEGORY_UUID" VARCHAR2(255 CHAR), 
  "CATEGORY_NAME" VARCHAR2(255 CHAR)
   ) ;
   
CREATE TABLE "AUDIT_PRIVILEGE_OTHER_RESOURCE" 
   (  "PRIVILEGE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "RESOURCE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TYPE" VARCHAR2(255 CHAR), 
  "UUID" VARCHAR2(255 CHAR), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "CREATE_TIME" TIMESTAMP (6), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0)
   ) ;
   
CREATE TABLE "AUDIT_PRIVILEGE_RESOURCE" 
   (  "PRIVILEGE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "RESOURCE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
   
CREATE TABLE "AUDIT_RESOURCE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "APPLY_TO" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "DYNAMIC" NUMBER(1,0), 
  "ENABLED" NUMBER(1,0), 
  "IS_DEFAULT" NUMBER(1,0), 
  "ISSYS" NUMBER(1,0), 
  "NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "REMARK" VARCHAR2(255 CHAR), 
  "TARGET" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "URL" VARCHAR2(255 CHAR), 
  "PARENT_UUID" VARCHAR2(255 CHAR)
   ) ;
   
CREATE TABLE "AUDIT_ROLE_NESTED_ROLE" 
   (  "ROLE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "NESTED_ROLE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
   
CREATE TABLE "AUDIT_ROLE_PRIVILEGE" 
   (  "ROLE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "PRIVILEGE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
   
CREATE TABLE "LOG_USER_OPERATION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CONTENT" VARCHAR2(255 CHAR), 
  "CREATOR_NAME" VARCHAR2(255 CHAR), 
  "DETAILS" VARCHAR2(255 CHAR), 
  "MODULE_ID" VARCHAR2(255 CHAR), 
  "MODULE_NAME" VARCHAR2(255 CHAR), 
  "OPERATION" VARCHAR2(255 CHAR), 
  "USER_NAME" VARCHAR2(255 CHAR), 
  "CLIENT_IP" VARCHAR2(255 CHAR), 
  "CLIENT_BROWSER" VARCHAR2(255 CHAR)
   ) ;   
   
   
-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/INDEX
CREATE UNIQUE INDEX "UK_8C43GP1X16UR7NM6TJ5Q15O8F" ON "AUDIT_PRIVILEGE" ("NAME") ;
ALTER INDEX "UK_8C43GP1X16UR7NM6TJ5Q15O8F" NOPARALLEL;

CREATE UNIQUE INDEX "UK_8RY1RAJCN8M5P4GET4STEGV3I" ON "AUDIT_ROLE" ("NAME") ;
ALTER INDEX "UK_8RY1RAJCN8M5P4GET4STEGV3I" NOPARALLEL;

CREATE INDEX "AUDIT_PR_RESOURCE_UUID_IDX" ON "AUDIT_PRIVILEGE_RESOURCE" ("RESOURCE_UUID");
ALTER INDEX "AUDIT_PR_RESOURCE_UUID_IDX" NOPARALLEL;

CREATE INDEX "AUDIT_RESOURCE_PARENT_UUID_IDX" ON "AUDIT_RESOURCE" ("PARENT_UUID");
ALTER INDEX "AUDIT_RESOURCE_PARENT_UUID_IDX" NOPARALLEL;

CREATE INDEX "AUDIT_RP_PRIVILEGE_UUID_IDX" ON "AUDIT_ROLE_PRIVILEGE" ("PRIVILEGE_UUID");
ALTER INDEX "AUDIT_RP_PRIVILEGE_UUID_IDX" NOPARALLEL;

ALTER TABLE "AUDIT_PRIVILEGE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
  
ALTER TABLE "AUDIT_PRIVILEGE" ADD CONSTRAINT "UK_8C43GP1X16UR7NM6TJ5Q15O8F" UNIQUE ("NAME")
  USING INDEX "UK_8C43GP1X16UR7NM6TJ5Q15O8F"  ENABLE;
  
ALTER TABLE "AUDIT_ROLE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
  
ALTER TABLE "AUDIT_ROLE" ADD CONSTRAINT "UK_8RY1RAJCN8M5P4GET4STEGV3I" UNIQUE ("NAME")
  USING INDEX "UK_8RY1RAJCN8M5P4GET4STEGV3I"  ENABLE;
  