
CREATE TABLE `MULTI_USER_RELATION_ACCOUNT`
(
   `UUID`                 VARCHAR(64)    NOT NULL,
   `MASTER_ACCOUNT`       VARCHAR(255)    NOT NULL COMMENT '主账户',
   `RELATION_ACCOUNT`     VARCHAR(255)   COMMENT '关联账户',
   `RELATION_ACCOUNT_ID`  VARCHAR(255)   COMMENT '关联账户ID',
   `RELATION_SYSTEM_UNIT_ID`           VARCHAR(64)  COMMENT '关联账户系统单位ID',
   `IS_VALID`             CHAR(1) COMMENT '是否有效',     
   `REC_VER`       DECIMAL(10,2) COMMENT '版本',
   `SYSTEM_UNIT_ID` VARCHAR(255) COMMENT '系统单位ID',
   `CREATE_TIME`          TIMESTAMP COMMENT '创建时间',
   `CREATOR`              VARCHAR(255) COMMENT '创建人',
   `MODIFIER`            VARCHAR(255) COMMENT '修改人',
   `MODIFY_TIME`          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   PRIMARY KEY (`UUID`)
) COMMENT = '多组织用户关联表';











