
CREATE TABLE MULTI_USER_RELATION_ACCOUNT
(
   UUID                 VARCHAR2(64 BYTE)    NOT NULL,
   MASTER_ACCOUNT       VARCHAR2(255 BYTE)    NOT NULL,
   RELATION_ACCOUNT     VARCHAR2(255 BYTE),
   RELATION_ACCOUNT_ID     VARCHAR2(255 BYTE),
   RELATION_SYSTEM_UNIT_ID           VARCHAR2(64),
   IS_VALID             CHAR(1),     
   REC_VER       NUMBER(10,2),
   SYSTEM_UNIT_ID VARCHAR2(255 CHAR),
   CREATE_TIME          TIMESTAMP,
   CREATOR              VARCHAR2(255 BYTE),
   MODIFIER             VARCHAR2(255 BYTE),
   MODIFY_TIME          TIMESTAMP,
   CONSTRAINT PK_MULTI_USER_RELATION_ACCOUNT PRIMARY KEY (UUID)
);

COMMENT ON TABLE MULTI_USER_RELATION_ACCOUNT IS '多组织用户关联表';
COMMENT ON COLUMN MULTI_USER_RELATION_ACCOUNT.MASTER_ACCOUNT IS '主账户';
COMMENT ON COLUMN MULTI_USER_RELATION_ACCOUNT.RELATION_ACCOUNT IS '关联账户';
COMMENT ON COLUMN MULTI_USER_RELATION_ACCOUNT.RELATION_ACCOUNT_ID IS '关联账户ID';
COMMENT ON COLUMN MULTI_USER_RELATION_ACCOUNT.RELATION_SYSTEM_UNIT_ID IS '关联账户系统单位ID';
COMMENT ON COLUMN MULTI_USER_RELATION_ACCOUNT.IS_VALID IS '是否有效';

COMMENT ON COLUMN MULTI_USER_RELATION_ACCOUNT.REC_VER IS '版本';
COMMENT ON COLUMN MULTI_USER_RELATION_ACCOUNT.SYSTEM_UNIT_ID IS '系统单位ID';
COMMENT ON COLUMN MULTI_USER_RELATION_ACCOUNT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN MULTI_USER_RELATION_ACCOUNT.CREATOR IS '创建人';
COMMENT ON COLUMN MULTI_USER_RELATION_ACCOUNT.MODIFIER IS '修改人';
COMMENT ON COLUMN MULTI_USER_RELATION_ACCOUNT.MODIFY_TIME IS '修改时间';
