-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
CREATE TABLE "SYS_APP_MODULE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "SYS_APP_SYSTEM" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ENABLED" NUMBER(1,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "SYS_APP_SYSTEM_MODULE" 
   (  "APP_SYSTEM_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "APP_MODULE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "SYS_IP_CONFIG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "APPLY_TO" VARCHAR2(255 CHAR), 
  "DOMAIN_ADDRESS1" VARCHAR2(255 CHAR), 
  "DOMAIN_ADDRESS2" VARCHAR2(255 CHAR), 
  "IP_ADDRESS1" VARCHAR2(255 CHAR), 
  "IP_ADDRESS2" VARCHAR2(255 CHAR), 
  "VALID_PERIOD" NUMBER(10,0), 
  "SID" VARCHAR2(255 CHAR), 
  "SID_NAME" VARCHAR2(255 CHAR), 
  "ROLE_ID" VARCHAR2(255 CHAR), 
  "ROLE_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "SYS_IP_CONFIG_USER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "IP_SECURITY_CONFIG_UUID" VARCHAR2(255 CHAR), 
  "SORT_ORDER" NUMBER(10,0), 
  "USER_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "SYS_SYSTEM_ACCESS" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "PERMIT" NUMBER(1,0), 
  "SORT_ORDER" NUMBER(10,0), 
  "USER_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CHAT_MENU_INFO" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ID" VARCHAR2(255 CHAR), 
  "IS_DEFAULT" VARCHAR2(255 CHAR), 
  "TITLE" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "URL" VARCHAR2(255 CHAR), 
  "PARENT_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CHAT_VERSION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "APPTYPE" VARCHAR2(255 CHAR), 
  "ENABLED" VARCHAR2(255 CHAR), 
  "URL" VARCHAR2(255 CHAR), 
  "VERSION" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CHAT_USER_EXTEND" 
   (  "USER_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  "EXTEND1" VARCHAR2(255 BYTE), 
  "EXTEND2" VARCHAR2(255 BYTE), 
  "EXTEND3" VARCHAR2(255 BYTE), 
  "EXTEND4" VARCHAR2(255 BYTE), 
  "EXTEND5" VARCHAR2(255 BYTE), 
  "DEVICETYPE" VARCHAR2(255 BYTE)
   ) ;

-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT   
ALTER TABLE "SYS_IP_CONFIG" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "CHAT_USER_EXTEND" ADD PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE;