-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
CREATE TABLE "SCHEDULE_GROUP" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "GROUP_NAME" VARCHAR2(255 CHAR), 
  "USER_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "SCHEDULE_GROUP_USER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "GROUP_ID" VARCHAR2(255 CHAR), 
  "USER_ID" VARCHAR2(255 CHAR), 
  "USER_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "SCHEDULE_LEADER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "LEADER_USER_NAME" VARCHAR2(255 CHAR), 
  "LEADER_USER_NO" VARCHAR2(255 CHAR), 
  "LORDER" NUMBER(10,0), 
  "SECRETARY_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "SCHEDULE_SECRETARY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "SECRETARY_USER_NO" VARCHAR2(255 CHAR), 
  "USER_NAME" VARCHAR2(255 CHAR)
   ) ;

CREATE TABLE "SCHEDULE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ADDRESS" VARCHAR2(255 CHAR), 
  "COLOR" VARCHAR2(255 CHAR), 
  "DISPLAY_START_DATE" VARCHAR2(255 CHAR), 
  "END_DATE" TIMESTAMP (6), 
  "END_TIME" VARCHAR2(255 CHAR), 
  "END_TIME2" VARCHAR2(255 CHAR), 
  "HAS_TIP" VARCHAR2(255 CHAR), 
  "HINT_DAY" VARCHAR2(255 CHAR), 
  "HINT_HOUR" VARCHAR2(255 CHAR), 
  "HINT_MINUTE" VARCHAR2(255 CHAR), 
  "HINT_RESPON" VARCHAR2(255 CHAR), 
  "IS_COMPLETE" VARCHAR2(255 CHAR), 
  "IS_HINT" VARCHAR2(255 CHAR), 
  "IS_LEADER_VIEW" VARCHAR2(255 CHAR), 
  "IS_VIEW" VARCHAR2(255 CHAR), 
  "MAIL" VARCHAR2(255 CHAR), 
  "MOBIL" VARCHAR2(255 CHAR), 
  "ONLINE_MESSAGE" VARCHAR2(255 CHAR), 
  "REPEAT" VARCHAR2(255 CHAR), 
  "SCHEDULE_NAME" VARCHAR2(255 CHAR), 
  "SCHEDULE_TYPE" VARCHAR2(255 CHAR), 
  "START_DATE" TIMESTAMP (6), 
  "START_TIME" VARCHAR2(255 CHAR), 
  "START_TIME2" VARCHAR2(255 CHAR), 
  "STATUS" VARCHAR2(255 CHAR), 
  "TIP" VARCHAR2(255 CHAR), 
  "TIP_DATE" VARCHAR2(255 CHAR), 
  "TIP_METHOD" VARCHAR2(255 CHAR), 
  "TIP_TIME" VARCHAR2(255 CHAR), 
  "TIP_TIME2" VARCHAR2(255 CHAR), 
  "CONTENT" VARCHAR2(2047 CHAR), 
  "SOURCE_UUID" VARCHAR2(255 CHAR), 
  "NOTIC_METHOD" VARCHAR2(255 CHAR), 
  "SERIAL_NO" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "SCHEDULE_ATTENTION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ATTENTION_ID" VARCHAR2(255 CHAR), 
  "ATTENTION_NAME" VARCHAR2(255 CHAR), 
  "USER_ID" VARCHAR2(255 CHAR), 
  "TAG_ID" VARCHAR2(255 BYTE), 
  "TAG_NAME" VARCHAR2(255 BYTE)
   ) ;
CREATE TABLE "SCHEDULE_MENBER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "IS_RESPON" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "SCHEDULE_ID" VARCHAR2(255 CHAR), 
  "USER_NO" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "SCHEDULE_SETTING" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CONTENT" VARCHAR2(255 CHAR), 
  "SET_NO" NUMBER(10,0), 
  "SET_TYPE" VARCHAR2(255 CHAR), 
  "USER_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "SCHEDULE_TAG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "COLOR" VARCHAR2(255 CHAR), 
  "IS_LEADER_VIEW" VARCHAR2(255 CHAR), 
  "IS_VIEW" VARCHAR2(2 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "SORT" NUMBER(10,0), 
  "USER_ID" VARCHAR2(255 CHAR), 
  "VIEW_IDS" VARCHAR2(255 CHAR), 
  "VIEW_NAMES" VARCHAR2(255 CHAR), 
  "USER_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "SCHEDULE_TAG_MEMBER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "MEMBER_ID" VARCHAR2(255 CHAR), 
  "MEMBER_NAME" VARCHAR2(255 CHAR), 
  "MEMBER_TYPE" VARCHAR2(255 CHAR), 
  "TAG_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "SCHEDULE_TAG_SCHE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "SCHEDULE_ID" VARCHAR2(255 CHAR), 
  "TAG_ID" VARCHAR2(255 CHAR)
   ) ;

-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/INDEX
CREATE INDEX "SCHEDULE_M_SCHEDULE_ID_IDX" ON "SCHEDULE_MENBER" ("SCHEDULE_ID");
ALTER INDEX "SCHEDULE_M_SCHEDULE_ID_IDX" NOPARALLEL;


-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT
ALTER TABLE "SCHEDULE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "SCHEDULE_ATTENTION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "SCHEDULE_MENBER" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "SCHEDULE_SETTING" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "SCHEDULE_TAG" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "SCHEDULE_TAG_MEMBER" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "SCHEDULE_TAG_SCHE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;