-- Add/modify columns

alter table BUSINESS_CATEGORY_ORG add(
    MANAGE_USER VARCHAR2(255),
    MANAGE_USER_VALUE VARCHAR2(255)
    );

comment on column BUSINESS_CATEGORY_ORG.MANAGE_USER is '管理员key值';
comment on column BUSINESS_CATEGORY_ORG.MANAGE_USER_VALUE is '管理员value值';


-- 更新旧数据，填充管理员key值，管理员value值
UPDATE BUSINESS_CATEGORY_ORG a
SET a.MANAGE_USER = (
	SELECT
		ID
	FROM
		(
		SELECT
			ID,
			USER_NAME,
			SYSTEM_UNIT_ID
		FROM
			MULTI_ORG_USER_ACCOUNT
		WHERE
			ID IN ( SELECT MIN( ID ) AS ID FROM MULTI_ORG_USER_ACCOUNT WHERE SYSTEM_UNIT_ID IN ( SELECT UNIT FROM BUSINESS_CATEGORY_ORG ) AND IS_FORBIDDEN = 0 AND TYPE = 1 GROUP BY SYSTEM_UNIT_ID )
		) b
	WHERE
		a.UNIT = b.SYSTEM_UNIT_ID
	),
	a.MANAGE_USER_VALUE = (
	SELECT
		USER_NAME
	FROM
		(
		SELECT
			ID,
			USER_NAME,
			SYSTEM_UNIT_ID
		FROM
			MULTI_ORG_USER_ACCOUNT
		WHERE
			ID IN ( SELECT MIN( ID ) AS ID FROM MULTI_ORG_USER_ACCOUNT WHERE SYSTEM_UNIT_ID IN ( SELECT UNIT FROM BUSINESS_CATEGORY_ORG ) AND IS_FORBIDDEN = 0 AND TYPE = 1 GROUP BY SYSTEM_UNIT_ID )
		) b
	WHERE
		a.UNIT = b.SYSTEM_UNIT_ID
	)
WHERE
	a.MANAGE_USER IS NULL
	AND a.UNIT IS NOT NULL;


-- 用户UUID 改为 ID
UPDATE BUSINESS_CATEGORY b SET b.MANAGE_USER = (SELECT u.ID FROM MULTI_ORG_USER_ACCOUNT u WHERE u.UUID = b.MANAGE_USER )
