-- 添加表字段 WF_FLOW_DELEGATION_SETTINGS.DELEGATION_TASK_VISIBLE
ALTER TABLE "WF_FLOW_DELEGATION_SETTINGS"
ADD ( "DELEGATION_TASK_VISIBLE" NUMBER(1) NULL  ) ;

COMMENT ON COLUMN "WF_FLOW_DELEGATION_SETTINGS"."DELEGATION_TASK_VISIBLE" IS '是否可见委托待办';
