

-------------------------------
----     CMS 功能清理      ----
-------------------------------

DELETE FROM app_product WHERE ID NOT IN ('PRD_DEMO', 'PRD_PT');

DELETE FROM APP_SYSTEM
 WHERE ID NOT IN ('pt-demo', 'pt-app', 'pt-mobile', 'pt-mgr');

DELETE FROM APP_SYSTEM A
 WHERE NOT EXISTS (SELECT 1
          FROM app_product_integration i
         WHERE i.data_type = 1
           AND i.data_uuid = A.uuid);

DELETE FROM APP_PRODUCT_INTEGRATION i
 WHERE i.data_type = 1
   AND NOT EXISTS
 (SELECT 1 FROM app_system A WHERE A.UUID = i.data_uuid);

DELETE FROM app_module A
 WHERE NOT EXISTS (SELECT 1
          FROM app_product_integration i
         WHERE i.data_uuid = A.uuid
           AND i.data_type = 2);

DELETE FROM APP_PRODUCT_INTEGRATION E
 WHERE E.DATA_type = 2
   AND NOT EXISTS
 (SELECT 1 FROM app_module b WHERE b.uuid = E.data_uuid);

DELETE FROM APP_PRODUCT_INTEGRATION E
 WHERE E.DATA_type = 2
   AND NOT EXISTS (SELECT 1
          FROM APP_PRODUCT_INTEGRATION b
         WHERE b.uuid = E.parent_uuid
           AND data_type = 1);

DELETE FROM app_application A
 WHERE NOT EXISTS (SELECT 1
          FROM app_product_integration i
         WHERE i.data_uuid = A.uuid
           AND i.data_type = 3);

DELETE FROM APP_PRODUCT_INTEGRATION E
 WHERE E.data_type = 3
   AND NOT EXISTS (SELECT 1
          FROM app_application b
         WHERE b.uuid = E.data_uuid
           AND data_type = 3);

DELETE FROM APP_PRODUCT_INTEGRATION E
 WHERE E.data_type = 3
   AND NOT EXISTS (SELECT 1
          FROM APP_PRODUCT_INTEGRATION b
         WHERE b.uuid = E.parent_uuid
           AND data_type = 2);

DELETE FROM APP_PRODUCT_INTEGRATION E
 WHERE E.data_type = 4
   AND NOT EXISTS (SELECT 1
          FROM APP_PRODUCT_INTEGRATION b
         WHERE b.uuid = E.parent_uuid
           AND data_type = 3);

DELETE FROM app_page_definition A
 WHERE NOT EXISTS
 (SELECT 1 FROM app_product_integration i WHERE i.uuid = A.app_pi_uuid);

DELETE FROM APP_WIDGET_DEFINITION A
 WHERE NOT EXISTS
 (SELECT 1 FROM APP_PAGE_DEFINITION D WHERE D.uuid = A.APP_PAGE_UUID);

DELETE FROM app_page_resource A
 WHERE NOT EXISTS
 (SELECT 1 FROM app_page_definition i WHERE i.uuid = A.app_page_uuid);

DELETE FROM app_function A
 WHERE A.export_type = 'AppWidgetFunctionElement'
   AND NOT EXISTS
 (SELECT 1 FROM app_page_resource r WHERE r.app_function_uuid = A.uuid);

DELETE FROM app_function A
 WHERE A.export_type = 'appWidgetDefinition'
   AND NOT EXISTS
 (SELECT 1 FROM app_widget_definition r WHERE r. ID = A . ID);

DELETE FROM AUDIT_PRIVILEGE_OTHER_RESOURCE A
 WHERE A."TYPE" = 'appProductIntegration'
   AND A.RESOURCE_UUID NOT LIKE 'funcref_%'
   AND NOT EXISTS (SELECT *
          FROM APP_PRODUCT_INTEGRATION i
         WHERE A.RESOURCE_UUID = i.uuid);

DELETE FROM AUDIT_PRIVILEGE_OTHER_RESOURCE
 WHERE uuid IN (SELECT uuid
                  FROM (SELECT SUBSTR(SUBSTR(resource_uuid, 14),
                                      1,
                                      INSTR(SUBSTR(resource_uuid, 14), '_', 1) - 1) AS app_pi_uuid,
                               uuid
                          FROM AUDIT_PRIVILEGE_OTHER_RESOURCE
                         WHERE RESOURCE_UUID LIKE 'funcref_%') v
                 WHERE NOT EXISTS (SELECT 1
                          FROM app_product_integration i
                         WHERE i.uuid = v.app_pi_uuid));

-------------------------------
----     邮件模块清理      ----
-------------------------------
DELETE FROM WM_MAIL_CONFIG;

DELETE FROM WM_MAIL_FOLDER;

DELETE FROM WM_MAIL_RECENT_CONTACT;

DELETE FROM WM_MAIL_RELA_TAG;

DELETE FROM WM_MAIL_REVOCATION;

DELETE FROM WM_MAIL_SIGNATURE;

DELETE FROM WM_MAIL_TAG;

DELETE FROM WM_MAIL_TEMPLATE;

DELETE FROM WM_MAIL_USE_CAPACITY;

DELETE FROM WM_MAIL_USER;

DELETE FROM WM_MAIL_USER_CONTACT;

DELETE FROM WM_MAILBOX;

DELETE FROM UF_PT_MAIL_CONTACT_BOOK;

DELETE FROM UF_PT_MAIL_CONTACT_BOOK_GRP;

-------------------------------
----     权限资源清理      ----
-------------------------------
DELETE FROM AUDIT_ROLE
 WHERE ID NOT IN ('ROLE_UNIT_ADMIN',
                  'ROLE_DEVELOP',
                  'ROLE_TRUSTED_USER',
                  'ROLE_USER',
                  'ROLE_ANONYMOUS');

DELETE FROM AUDIT_ROLE_NESTED_ROLE;

DELETE FROM AUDIT_NESTED_ROLE;

DELETE FROM AUDIT_PRIVILEGE
 WHERE NAME NOT IN ('PT_标签权限',
                    '基础权限_前台主页权限',
                    'PT_通知公告(文件库)权限',
                    'PT_个人信息权限',
                    '平台演示系统权限',
                    '后台_组织管理权限',
                    '后台_权限管理权限',
                    '后台_基础数据管理权限',
                    '后台_流程管理权限',
                    '后台_表单管理权限',
                    '后台_模块设置权限',
                    '后台_系统设置权限',
                    '平台邮件-发件箱删除邮件权限',
                    '后台_数据管理权限',
                    '后台_日志管理权限',
                    '后台_数据交换权限',
                    'PT_我的日程权限',
                    '后台_产品集成开发与管理权限',
                    'PT_消息权限',
                    'PT_工作流程权限',
                    'PT_工作委托权限',
                    'PT_邮件权限',
                    'PT_个人文档权限',
                    'PT_文件管理权限',
                    'PT_新闻权限',
                    'PT_文档交换权限',
                    '后台_业务流程管理权限',
                    'PT_API管理权限');

DELETE FROM AUDIT_PRIVILEGE_RESOURCE P
 WHERE NOT EXISTS
 (SELECT 1 FROM AUDIT_PRIVILEGE i WHERE P.PRIVILEGE_UUID = i.uuid);

DELETE FROM AUDIT_ROLE_PRIVILEGE P
 WHERE NOT EXISTS (SELECT 1 FROM AUDIT_ROLE r WHERE r.uuid = P.ROLE_UUID);

DELETE FROM AUDIT_PRIVILEGE_OTHER_RESOURCE r
 WHERE NOT EXISTS
 (SELECT 1 FROM AUDIT_PRIVILEGE P WHERE P.uuid = r.PRIVILEGE_UUID);

DELETE FROM AUDIT_USER_ATTEMPTS;

DELETE FROM BOT_RULE_CONF;

DELETE FROM BOT_RULE_OBJ_MAPPING;

DELETE FROM BOT_RULE_OBJ_RELA;

DELETE FROM BOT_RULE_OBJ_RELA_MAPPING;

DELETE FROM BUSINESS_APPLICATION;

DELETE FROM BUSINESS_APPLICATION_CONFIG;

DELETE FROM BUSINESS_CATEGORY;

DELETE FROM BUSINESS_CATEGORY_ORG;

DELETE FROM BUSINESS_ROLE;

DELETE FROM BUSINESS_ROLE_ORG_USER;

DELETE FROM CD_CODE_GENERATOR_CONFIG;

DELETE FROM CD_DATA_DEPENDENCY;

-------------------------------
----     附件数据清理      ----
-------------------------------
DELETE FROM REPO_FILE;

DELETE FROM REPO_FILE_IN_FOLDER;

DELETE FROM REPO_FILE_UPLOAD;

DELETE FROM REPO_FOLDER_OPERATE_LOG;

DELETE FROM RP_FILE_REPOSITORY;

DELETE FROM REPO_FOLDER;

-------------------------------
----     数据交换数据清理      ----
-------------------------------
DELETE FROM IS_DATA_OPERATION_LOG;

DELETE FROM IS_DEL_DATA_LOG;

DELETE FROM IS_DX_EXCHANGE_BATCH;

DELETE FROM IS_DX_EXCHANGE_DATA;

DELETE FROM IS_DX_EXCHANGE_ROUTE;

DELETE FROM IS_EXCHANGE_DATA;

DELETE FROM IS_EXCHANGE_DATA_BATCH;

DELETE FROM IS_EXCHANGE_DATA_CALLBACK;

DELETE FROM IS_EXCHANGE_DATA_FILE_UPLOAD;

DELETE FROM IS_EXCHANGE_DATA_LOG;

DELETE FROM IS_EXCHANGE_DATA_MONITOR;

DELETE FROM IS_EXCHANGE_DATA_REPEST;

DELETE FROM IS_EXCHANGE_DATA_REPLY;

DELETE FROM IS_EXCHANGE_DATA_ROUTE;

DELETE FROM IS_EXCHANGE_DATA_TRANSFORM;

DELETE FROM IS_EXCHANGE_DATA_TYPE;

DELETE FROM IS_EXCHANGE_ROUTE;

DELETE FROM IS_EXCHANGE_SEND_MONITOR;

DELETE FROM IS_EXCHANGE_SG_SET;

DELETE FROM IS_EXCHANGE_SYSTEM;

DELETE FROM IS_GUANGDUN_ATTACHRMENT;

DELETE FROM IS_GUANGDUN_POINT;

DELETE FROM IS_GUANGDUN_RECEIVE;

DELETE FROM IS_GUANGDUN_SEND;

DELETE FROM IS_SYN_DATA_LOG;

DELETE FROM IS_SYNCHRONOUS_SOURCE_FIELD;

DELETE FROM IS_SYNCHRONOUS_SOURCE_TABLE;

DELETE FROM IS_SYS_PROPERTIES;

DELETE FROM DI_CALLBACK_REQUEST;

DELETE FROM DI_CALLBACK_REQUEST_HIS;

DELETE FROM DI_CONFIG;

DELETE FROM DI_DATA_CONSUMER_ENDPOINT;

DELETE FROM DI_DATA_INTERATION_LOG;

DELETE FROM DI_DATA_PROCESSOR;

DELETE FROM DI_DATA_PROCESSOR_LOG;

DELETE FROM DI_DATA_PRODUCER_ENDPOINT;

DELETE FROM DI_TABLE_COLUMN_DATA_CHANGE;

DELETE FROM DI_TABLE_DATA_CHANGE;

-------------------------------
----     组织数据清理      ----
-------------------------------
DELETE FROM org_user_property;

DELETE FROM MULTI_ORG_DUTY;

DELETE FROM MULTI_ORG_ELEMENT;

DELETE FROM MULTI_ORG_ELEMENT_ATTR;

DELETE FROM MULTI_ORG_ELEMENT_LEADER;

DELETE FROM MULTI_ORG_ELEMENT_ROLE;

DELETE FROM MULTI_ORG_GROUP;

DELETE FROM MULTI_ORG_GROUP_MEMBER;

DELETE FROM MULTI_ORG_GROUP_ROLE;

DELETE FROM MULTI_ORG_JOB_DUTY;

DELETE FROM MULTI_ORG_JOB_RANK;

DELETE FROM MULTI_ORG_OPTION WHERE SYSTEM_UNIT_ID <> 'S0000000000';

DELETE FROM MULTI_ORG_SYSTEM_UNIT;

DELETE FROM MULTI_ORG_SYSTEM_UNIT_MEMBER;

DELETE FROM MULTI_ORG_TREE_NODE;

DELETE FROM MULTI_ORG_TYPE;

DELETE FROM MULTI_ORG_USER_ACCOUNT;

DELETE FROM MULTI_ORG_USER_EXT_ACCOUNT;

DELETE FROM MULTI_ORG_USER_INFO;

DELETE FROM MULTI_ORG_USER_ROLE;

DELETE FROM MULTI_ORG_USER_TREE_NODE;

DELETE FROM MULTI_ORG_USER_WORK_INFO;

DELETE FROM MULTI_ORG_VERSION;

DELETE FROM org_user_login_log;

-------------------------------
----     消息数据清理      ----
-------------------------------
DELETE FROM MSG_HIS_MESSAGE_QUEUE;

DELETE FROM MSG_MAS_CONFIG;

DELETE FROM MSG_MESSAGE_CONTENT;

DELETE FROM MSG_MESSAGE_INBOX;

DELETE FROM MSG_MESSAGE_OUTBOX;

DELETE FROM MSG_MESSAGE_QUEUE;

DELETE FROM MSG_MESSAGE_RECENT_CONTACT;

DELETE FROM MSG_MESSAGE_TEMPLATE;

DELETE FROM MSG_MESSAGE_TEMPLATE_REF;

DELETE FROM MSG_SCHEDULE_MESSAGE_QUEUE;

DELETE FROM MSG_SCHEDULE_MESSAGE_QUEUE_HIS;

DELETE FROM MSG_SHORT_MESSAGE;

DELETE FROM MSG_WEBSERVICE_PARM;

-------------------------------
----     其他数据清理      ----
-------------------------------
DELETE FROM CD_CODE_GENERATOR_CONFIG;

DELETE FROM CD_DATA_DEPENDENCY;

DELETE FROM CD_DATA_IMPORT_LOG;

DELETE FROM CD_DATA_MAPPER;

DELETE FROM CD_EXCEL_COLUMN_DEFINITION;

DELETE FROM CD_EXCEL_IMPORT_RULE;

DELETE FROM CD_FIELD_EXT_DEFINITION;

DELETE FROM CD_FIELD_EXT_VALUE;

DELETE FROM CD_ID_GENERATOR;

DELETE FROM CD_KEY_STORE;

DELETE FROM CD_PINYIN;

DELETE FROM CD_PRINT_CONTENTS;

DELETE FROM CD_PRINT_RECORD;

DELETE FROM CD_PRINT_TEMPLATE;

DELETE FROM CD_PRINT_TEMPLATE_REF;

DELETE FROM CD_READ_MARKER;

DELETE FROM CD_RECENT_USE;

DELETE FROM CD_RTX;

DELETE FROM CD_SCRIPT_DEFINITION;

DELETE FROM CD_SERIAL_NUMBER;

DELETE FROM CD_SERIAL_NUMBER_MAINTAIN;

DELETE FROM CD_SYSTEM_TABLE_ENTITY;

DELETE FROM CD_SYSTEM_TABLE_ENTITY_ATTR;

DELETE FROM CD_SYSTEM_TABLE_RELATIONSHIP;

DELETE FROM CD_WORK_HOUR;

DELETE FROM CHAT_APNS_DEVICE_TOKEN;

DELETE FROM CHAT_APP_VERSION;

DELETE FROM CHAT_APPLY;

DELETE FROM CHAT_APPSTORE;

DELETE FROM CHAT_APPSTORE_LOG;

DELETE FROM CHAT_MENU_INFO;

DELETE FROM CHAT_RTX_CROWD;

DELETE FROM CHAT_RTX_CROWD_MEMBER;

DELETE FROM CHAT_RTX_GROUP;

DELETE FROM CHAT_RTX_GROUP_MEMBER;

DELETE FROM CHAT_RTX_MESSAGE;

DELETE FROM CHAT_RTX_OFFLINE;

DELETE FROM CHAT_USER;

DELETE FROM CHAT_USER_EXTEND;

DELETE FROM CHAT_USER_INFO_TIME;

DELETE FROM CHAT_VERSION;

DELETE FROM TIG_COLUMN_CLOB;

DELETE FROM TIG_COLUMN_DATA;

DELETE FROM TIG_DONT_DATA;

DELETE FROM TIG_TABLE_DATA;

DELETE FROM LOG_USER_OPERATION;

DELETE FROM BIZP_PROCESS_CATEGORY;

DELETE FROM BIZP_PROCESS_DEFINITION;

DELETE FROM BIZP_PROCESS_FLOW_RELATION;

DELETE FROM BIZP_PROCESS_INSTANCE;

DELETE FROM BIZP_PROCESS_TASK_FLOW_INST;

DELETE FROM BIZP_TASK_INSTANCE;

DELETE FROM BIZP_TASK_OPERATION;

DELETE FROM BOT_RULE_CONF;

DELETE FROM BOT_RULE_OBJ_MAPPING;

DELETE FROM BOT_RULE_OBJ_RELA;

DELETE FROM BOT_RULE_OBJ_RELA_MAPPING;

DELETE FROM BUSINESS_APPLICATION;

DELETE FROM BUSINESS_APPLICATION_CONFIG;

DELETE FROM BUSINESS_CATEGORY;

DELETE FROM BUSINESS_CATEGORY_ORG;

DELETE FROM BUSINESS_ROLE;

DELETE FROM BUSINESS_ROLE_ORG_USER;

DELETE FROM UF_PT_APP_NEWS;

DELETE FROM UF_PT_APP_NEWS_RL;

DELETE FROM UF_PT_APP_NOTICE;

DELETE FROM UF_PT_APP_NOTICE_RL;

DELETE FROM UF_PT_MAIL_CONTACT_BOOK;

DELETE FROM UF_PT_MAIL_CONTACT_BOOK_GRP;

DELETE FROM UF_PT_MAIL_CONTACT_BOOK_GRP_RL;

DELETE FROM UF_PT_MAIL_CONTACT_BOOK_RL;

DELETE FROM FRONT_DB_DATA;

DELETE FROM EXCEL_EXPORT_COLUMN_DEFINITION;

DELETE FROM EXCEL_EXPORT_DEFINITION;

DELETE FROM EXEC_SQL_DEFINITION;

-------------------------------
----     表单数据清理      ----
-------------------------------
DELETE FROM DYFORM_COMMON_FIELD_CATEGORY;

DELETE FROM DYFORM_COMMON_FIELD_DEFINITION;

DELETE FROM DYFORM_COMMON_FIELD_REF;

DELETE FROM DYFORM_CONTROL_ROLE;

DELETE FROM DYFORM_DISPLAY_MODEL;

delete from dyform_form_definition f
 where exists (select 1
          from all_tables a
         where upper(f.table_name) = upper(a.TABLE_NAME)
           and a.OWNER = (select user from dual)
           and f.table_name NOT LIKE 'uf_pt%');

DELETE FROM DYFORM_FORM_DEFINITION_REF;

DELETE FROM DYFORM_SQL_LOG;

-------------------------------
----     流程数据清理      ----
-------------------------------
DELETE FROM WF_DEF_CATEGORY;

DELETE FROM WF_DEF_FORMAT WHERE system_unit_id <> 'S0000000000';

DELETE FROM WF_DEF_OPINION;

DELETE FROM WF_DEF_OPINION_CATEGORY;

DELETE FROM WF_FLOW_DEFINITION;

DELETE FROM WF_FLOW_DEFINITION_REF;

DELETE FROM WF_FLOW_DELEGATION_SETTINGS;

DELETE FROM WF_FLOW_INSTANCE;

DELETE FROM WF_FLOW_INSTANCE_PARAM;

DELETE FROM WF_FLOW_MANAGEMENT;

DELETE FROM WF_FLOW_SCHEMA;

DELETE FROM WF_FLOW_SCHEMA_LOG;

DELETE FROM WF_TASK_ACTIVITY;

DELETE FROM WF_TASK_BRANCH;

DELETE FROM WF_TASK_DELEGATION;

DELETE FROM WF_TASK_DELETE_LOG;

DELETE FROM WF_TASK_FORM_ATTACHMENT;

DELETE FROM WF_TASK_FORM_ATTACHMENT_LOG;

DELETE FROM WF_TASK_FORM_OPINION;

DELETE FROM WF_TASK_FORM_OPINION_LOG;

DELETE FROM WF_TASK_IDENTITY;

DELETE FROM WF_TASK_INFO_DISTRIBUTION;

DELETE FROM WF_TASK_INSTANCE;

DELETE FROM WF_TASK_INSTANCE_TOPPING;

DELETE FROM WF_TASK_OPERATION;

DELETE FROM WF_TASK_SUB_FLOW;

DELETE FROM WF_TASK_SUB_FLOW_RELATION;

DELETE FROM WF_TASK_TIMER;

DELETE FROM WF_TASK_TIMER_LOG;

DELETE FROM WF_TASK_TIMER_USER;

-------------------------------
----     DMS 数据清理      ----
-------------------------------
DELETE FROM DMS_DATA_ATTENTION_MARK;

DELETE FROM DMS_DATA_CLASSIFY_RELA;

DELETE FROM DMS_DATA_COLLECT_MARK;

DELETE FROM DMS_DATA_LABEL;

DELETE FROM DMS_DATA_LABEL_RELA;

DELETE FROM DMS_DATA_MANAGEMENT_DEFINITION;

DELETE FROM DMS_DATA_PERMISSION_DEFINITION;

DELETE FROM DMS_DATA_READ_MARK;

DELETE FROM DMS_DATA_VERSION;

DELETE FROM DMS_DOC_EXC_CONTACT_BOOK;

DELETE FROM DMS_DOC_EXC_CONTACT_BOOK_UNIT;

DELETE FROM DMS_DOC_EXC_EXTRA_SEND_DETAIL;

DELETE FROM DMS_DOC_EXC_FEEDBACK_DETAIL;

DELETE FROM DMS_DOC_EXC_RECORD_FORWARD;

DELETE FROM DMS_DOC_EXC_SIGN_DETAIL;

DELETE FROM DMS_DOC_EXC_URGE_DETAIL;

DELETE FROM DMS_DOC_EXCHANGE_LOG;

DELETE FROM DMS_DOC_EXCHANGE_RECORD;

DELETE FROM DMS_DOC_EXCHANGE_RECORD_DETAIL;

DELETE FROM DMS_FILE;

DELETE FROM DMS_FOLDER;

DELETE FROM DMS_FOLDER_CONFIGURATION;

DELETE FROM DMS_OBJECT_ASSIGN_ROLE;

DELETE FROM DMS_OBJECT_ASSIGN_ROLE_ITEM;

DELETE FROM DMS_OBJECT_IDENTITY;

DELETE FROM DMS_OPERATE_LOG;

DELETE FROM DMS_RECYCLE_BIN;

DELETE FROM DMS_ROLE;

DELETE FROM DMS_ROLE_ACTION;

DELETE FROM DMS_SHARE_INFO;

DELETE FROM DMS_TAG;

DELETE FROM DMS_TAG_DATA;

DELETE FROM SYS_IP_CONFIG;

DELETE FROM SYS_IP_CONFIG_USER;

DELETE FROM SYS_PARAM_ITEM;

DELETE FROM SYS_SYSTEM_ACCESS;

-------------------------------
----     任务数据清理      ----
-------------------------------
DELETE FROM TASK_FIRED_JOB_DETAILS;

DELETE FROM TASK_FIRED_JOB_DETAILS_HIS;

DELETE FROM TASK_JOB_DETAILS;

DELETE FROM ACL_ENTRY;

DELETE FROM ACL_OBJECT_IDENTITY;

DELETE FROM ACL_SID;

DELETE FROM ACL_SID_MEMBER;

DELETE FROM API_AUTHORIZE_ITEM;

DELETE FROM API_COMMAND;

DELETE FROM API_COMMAND_DETAIL;

DELETE FROM API_LOG;

DELETE FROM API_OUT_SYSTEM_CONFIG;

DELETE FROM API_OUT_SYSTEM_SERVICE_CONFIG;

DELETE FROM APP_DEFINE_CODE_HIS;

DELETE FROM APP_LOGIN_PAGE_CONFIG;

DELETE FROM APP_TIP_NO_LONGER_REMIND;

DELETE FROM APP_USER_WIDGET_DEFINITION;
