-- ----------------------------
-- Table structure for CD_PRINT_TEMPLATE_CATEGORY
-- ----------------------------
-- DROP TABLE "CD_PRINT_TEMPLATE_CATEGORY";
CREATE TABLE "CD_PRINT_TEMPLATE_CATEGORY" (
  "UUID" VARCHAR2(255 CHAR) NOT NULL,
  "CREATE_TIME" TIMESTAMP(6),
  "CREATOR" VARCHAR2(255 CHAR),
  "MODIFIER" VARCHAR2(255 CHAR),
  "MODIFY_TIME" TIMESTAMP(6),
  "REC_VER" NUMBER(10,0),
  "CODE" VARCHAR2(255 CHAR),
  "NAME" VARCHAR2(255 CHAR),
  "PARENT_UUID" VARCHAR2(255 CHAR),
  "SYSTEM_UNIT_ID" VARCHAR2(12 BYTE),
  "ICON" VARCHAR2(120 BYTE),
  "ICON_COLOR" VARCHAR2(12 BYTE),
  "REMARK" VARCHAR2(300 BYTE),
  constraint pk_cd_print_template_category primary key (UUID)
);
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."UUID" IS 'UUID，系统字段';
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."CREATOR" IS '创建人';
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."MODIFIER" IS '修改人';
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."MODIFY_TIME" IS '修改时间';
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."REC_VER" IS '版本号';
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."CODE" IS '编号';
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."NAME" IS '名称';
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."PARENT_UUID" IS '上级分类UUID';
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."SYSTEM_UNIT_ID" IS '归属系统单位';
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."ICON" IS '字体图标样式类';
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."ICON_COLOR" IS '图标颜色';
COMMENT ON COLUMN "CD_PRINT_TEMPLATE_CATEGORY"."REMARK" IS '描述';
COMMENT ON TABLE "CD_PRINT_TEMPLATE_CATEGORY" IS '打印模版分类';



ALTER TABLE "CD_PRINT_TEMPLATE" ADD ("CATEGORY" VARCHAR2(255));
COMMENT ON COLUMN "CD_PRINT_TEMPLATE"."CATEGORY" IS '打印模版分类UUID';