package com.wellsoft.pt.message.sms.skmas;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-02-04T13:49:19.501+08:00
 * Generated source version: 2.3.9
 */
@WebServiceClient(name = "SmsWebService",
        wsdlLocation = "file:SmsWebService.wsdl",
        targetNamespace = "http://localhost:8080/s-mas")
public class SmsWebServiceService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://localhost:8080/s-mas", "SmsWebService");
    public final static QName SmsWebServicePort = new QName("http://localhost:8080/s-mas", "SmsWebServicePort");
    private static Logger logger = LoggerFactory.getLogger(SmsWebServiceService.class);

    static {
        URL url = null;
        try {
            url = new URL("file:SmsWebService.wsdl");
        } catch (MalformedURLException e) {
            logger.debug("Can not initialize the default wsdl from {0}", "file:SmsWebService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SmsWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SmsWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmsWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }


    /**
     * @return returns SmsWebService
     */
    @WebEndpoint(name = "SmsWebServicePort")
    public SmsWebService getSmsWebServicePort() {
        return super.getPort(SmsWebServicePort, SmsWebService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns SmsWebService
     */
    @WebEndpoint(name = "SmsWebServicePort")
    public SmsWebService getSmsWebServicePort(WebServiceFeature... features) {
        return super.getPort(SmsWebServicePort, SmsWebService.class, features);
    }
}
