package com.wellsoft.pt.message.sms.skmas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-02-04T13:49:19.475+08:00
 * Generated source version: 2.3.9
 */
@WebService(targetNamespace = "http://localhost:8080/s-mas", name = "SmsWebService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SmsWebService {

    @WebResult(name = "rptResult", targetNamespace = "http://localhost:8080/s-mas", partName = "rptResult")
    @WebMethod(action = "http://localhost:8080/s-mas/recvRpt")
    public RptResult recvRpt(
            @WebParam(partName = "username", name = "username")
                    java.lang.String username,
            @WebParam(partName = "password", name = "password")
                    java.lang.String password,
            @WebParam(partName = "amount", name = "amount")
                    java.lang.String amount
    );

    @WebResult(name = "mtResult", targetNamespace = "http://localhost:8080/s-mas", partName = "mtResult")
    @WebMethod(action = "http://localhost:8080/s-mas/sendMt")
    public MtResult sendMt(
            @WebParam(partName = "username", name = "username")
                    java.lang.String username,
            @WebParam(partName = "password", name = "password")
                    java.lang.String password,
            @WebParam(partName = "phoneNumbers", name = "phoneNumbers")
                    java.lang.String phoneNumbers,
            @WebParam(partName = "smsContent", name = "smsContent")
                    java.lang.String smsContent,
            @WebParam(partName = "smsId", name = "smsId")
                    java.lang.String smsId,
            @WebParam(partName = "sendTime", name = "sendTime")
                    java.lang.String sendTime
    );

    @WebResult(name = "moResult", targetNamespace = "http://localhost:8080/s-mas", partName = "moResult")
    @WebMethod(action = "http://localhost:8080/s-mas/recvMo")
    public MoResult recvMo(
            @WebParam(partName = "username", name = "username")
                    java.lang.String username,
            @WebParam(partName = "password", name = "password")
                    java.lang.String password,
            @WebParam(partName = "amount", name = "amount")
                    java.lang.String amount
    );
}
