CREATE TABLE DMS_OBJECT_ASSIGN_ACTION
(
    "UUID"                 NUMBER(20, 0) NOT NULL,
    "CREATOR"              VARCHAR2(20 CHAR),
    "CREATE_TIME"          TIMESTAMP(6),
    "MODIFIER"             VARCHAR2(20 CHAR),
    "MODIFY_TIME"          TIMESTAMP(6),
    "REC_VER"              NUMBER(10, 0),
    "OBJECT_IDENTITY_UUID" VARCHAR2(50),
    "OBJECT_ID_IDENTITY"   VARCHAR2(50),
    "ORG_ID"               VARCHAR2(50),
    "ACTION"               VARCHAR2(50),
    PRIMARY KEY ("UUID")
);
COMMENT
    ON TABLE DMS_OBJECT_ASSIGN_ACTION IS '对象授权操作信息';
COMMENT
    ON COLUMN DMS_OBJECT_ASSIGN_ACTION.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN DMS_OBJECT_ASSIGN_ACTION.CREATOR IS '创建人';
COMMENT
    ON COLUMN DMS_OBJECT_ASSIGN_ACTION.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN DMS_OBJECT_ASSIGN_ACTION.MODIFIER IS '修改人';
COMMENT
    ON COLUMN DMS_OBJECT_ASSIGN_ACTION.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN DMS_OBJECT_ASSIGN_ACTION.OBJECT_IDENTITY_UUID IS '授权对象实体UUID';
COMMENT
    ON COLUMN DMS_OBJECT_ASSIGN_ACTION.OBJECT_ID_IDENTITY IS '对象数据标识';
COMMENT
    ON COLUMN DMS_OBJECT_ASSIGN_ACTION.ORG_ID IS '分配的组织相关ID';
COMMENT
    ON COLUMN DMS_OBJECT_ASSIGN_ACTION.ACTION IS '操作权限';

CREATE index DMS_OAA_OBJECT_ID_IDENTITY on DMS_OBJECT_ASSIGN_ACTION (OBJECT_ID_IDENTITY);