CREATE TABLE DMS_LIBRARY_CATEGORY
(
    "UUID"        NUMBER(20, 0) NOT NULL,
    "CREATE_TIME" TIMESTAMP(6),
    "CREATOR"     VARCHAR2(50 CHAR),
    "MODIFIER"    VARCHAR2(50 CHAR),
    "MODIFY_TIME" TIMESTAMP(6),
    "REC_VER"     NUMBER(10, 0),
    "SYSTEM"      VARCHAR2(64 CHAR),
    "TENANT"      VARCHAR2(64 CHAR),
    "NAME"        VARCHAR2(120 char),
    "CODE"        VARCHAR2(50 char),
    "ICON"        VARCHAR2(120),
    "ICON_COLOR"  VARCHAR2(12),
    "REMARK"      VARCHAR2(200),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE DMS_LIBRARY_CATEGORY IS '库分类';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.CREATOR IS '创建人';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.MODIFIER IS '修改人';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.REC_VER IS '版本号';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.SYSTEM IS '归属系统';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.TENANT IS '归属租户';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.NAME IS '名称';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.CODE IS '编码';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.ICON IS '图标';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.ICON_COLOR IS '图标颜色';
COMMENT
    ON COLUMN DMS_LIBRARY_CATEGORY.REMARK IS '备注';


alter table DMS_TAG
    add SYSTEM VARCHAR2(64 CHAR);
alter table DMS_TAG
    add TENANT VARCHAR2(64 CHAR);
COMMENT
    ON COLUMN DMS_TAG.SYSTEM IS '归属系统';
COMMENT
    ON COLUMN DMS_TAG.TENANT IS '归属租户';


CREATE TABLE DMS_LIBRARY_SETTING
(
    "UUID"            NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"     TIMESTAMP(6),
    "CREATOR"         VARCHAR2(50 CHAR),
    "MODIFIER"        VARCHAR2(50 CHAR),
    "MODIFY_TIME"     TIMESTAMP(6),
    "REC_VER"         NUMBER(10, 0),
    "SYSTEM"          VARCHAR2(64 CHAR),
    "TENANT"          VARCHAR2(64 CHAR),
    "DEFINITION_JSON" CLOB,
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE DMS_LIBRARY_SETTING IS '库设置';
COMMENT
    ON COLUMN DMS_LIBRARY_SETTING.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN DMS_LIBRARY_SETTING.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN DMS_LIBRARY_SETTING.CREATOR IS '创建人';
COMMENT
    ON COLUMN DMS_LIBRARY_SETTING.MODIFIER IS '修改人';
COMMENT
    ON COLUMN DMS_LIBRARY_SETTING.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN DMS_LIBRARY_SETTING.REC_VER IS '版本号';
COMMENT
    ON COLUMN DMS_LIBRARY_SETTING.SYSTEM IS '归属系统';
COMMENT
    ON COLUMN DMS_LIBRARY_SETTING.TENANT IS '归属租户';
COMMENT
    ON COLUMN DMS_LIBRARY_SETTING.DEFINITION_JSON IS '定义JSON信息';


CREATE TABLE DMS_ROLE_MODEL
(
    "UUID"        NUMBER(20, 0) NOT NULL,
    "CREATE_TIME" TIMESTAMP(6),
    "CREATOR"     VARCHAR2(50 CHAR),
    "MODIFIER"    VARCHAR2(50 CHAR),
    "MODIFY_TIME" TIMESTAMP(6),
    "REC_VER"     NUMBER(10, 0),
    "SYSTEM"      VARCHAR2(64 CHAR),
    "TENANT"      VARCHAR2(64 CHAR),
    "NAME"        VARCHAR2(120),
    "ID"          VARCHAR2(50),
    "CODE"        VARCHAR2(50),
    "BUILT_IN"    NUMBER(1, 0),
    "ROLE_UUIDS"  VARCHAR2(1000),
    "REMARK"      VARCHAR2(200),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE DMS_ROLE_MODEL IS '权限模型';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.CREATOR IS '创建人';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.MODIFIER IS '修改人';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.REC_VER IS '版本号';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.SYSTEM IS '归属系统';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.TENANT IS '归属租户';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.NAME IS '名称';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.ID IS 'ID';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.CODE IS '编号';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.BUILT_IN IS '是否内置';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.ROLE_UUIDS IS '权限组定义UUID，多个以分号分隔';
COMMENT
    ON COLUMN DMS_ROLE_MODEL.REMARK IS '备注';


CREATE TABLE DMS_LIBRARY_TEMPLATE
(
    "UUID"            NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"     TIMESTAMP(6),
    "CREATOR"         VARCHAR2(50 CHAR),
    "MODIFIER"        VARCHAR2(50 CHAR),
    "MODIFY_TIME"     TIMESTAMP(6),
    "REC_VER"         NUMBER(10, 0),
    "SYSTEM"          VARCHAR2(64 CHAR),
    "TENANT"          VARCHAR2(64 CHAR),
    "NAME"            VARCHAR2(120),
    "ID"              VARCHAR2(50),
    "CODE"            VARCHAR2(50),
    "ICON"            VARCHAR2(300),
    "DEFINITION_JSON" CLOB,
    "USED_COUNT"      NUMBER(10, 0),
    "REMARK"          VARCHAR2(200),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE DMS_LIBRARY_TEMPLATE IS '库模板';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.CREATOR IS '创建人';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.MODIFIER IS '修改人';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.REC_VER IS '版本号';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.SYSTEM IS '归属系统';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.TENANT IS '归属租户';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.NAME IS '名称';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.ID IS 'ID';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.CODE IS '编号';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.ICON IS '图标';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.DEFINITION_JSON IS '定义JSON信息';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.USED_COUNT IS '使用次数';
COMMENT
    ON COLUMN DMS_LIBRARY_TEMPLATE.REMARK IS '备注';


alter table DMS_FOLDER
    add icon varchar2(300);
alter table DMS_FOLDER
    add category_uuid NUMBER(20, 0);
COMMENT
    ON COLUMN DMS_FOLDER.ICON IS '图标';
COMMENT
    ON COLUMN DMS_FOLDER.category_uuid IS '分类UUID';

alter table DMS_ROLE
    add DEFINITION_JSON CLOB;
alter table DMS_ROLE
    add BUILT_IN NUMBER(1, 0);
alter table DMS_ROLE
    add SYSTEM VARCHAR2(64 CHAR);
alter table DMS_ROLE
    add TENANT VARCHAR2(64 CHAR);
COMMENT ON COLUMN DMS_ROLE.DEFINITION_JSON IS '定义JSON信息';
COMMENT ON COLUMN DMS_ROLE.BUILT_IN IS '是否内置';
COMMENT ON COLUMN DMS_ROLE.SYSTEM IS '归属系统';
COMMENT ON COLUMN DMS_ROLE.TENANT IS '归属租户';
update DMS_ROLE t
set t.SYSTEM = (
    select SYSTEM
    from (
             select distinct t1.ROLE_UUID, t3.SYSTEM, t3.TENANT
             from DMS_OBJECT_ASSIGN_ROLE t1
                      left join DMS_OBJECT_IDENTITY t2 on t1.OBJECT_IDENTITY_UUID = t2.UUID
                      left join dms_folder t3 on t2.OBJECT_ID_IDENTITY = t3.UUID
             where t1.CREATE_TIME > to_date('2024-01-01', 'yyyy-MM-dd')
         ) t1
    where t1.ROLE_UUID = t.UUID
),
    t.TENANT = 'T001'
where t.SYSTEM is null
  and t.TENANT is null;
commit;

