/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wellsoft.pt.message.sms.tamas;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-09-24T17:06:55.897+08:00
 * Generated source version: 2.3.9
 */

@javax.jws.WebService(serviceName = "SmsTonganService", portName = "SmsTonganServicePort", wsdlLocation = "file:SmsTonganService.wsdl", targetNamespace = "http://localhost:8080/webservice",

        endpointInterface = "com.wellsoft.pt.message.sms.tamas.SmsTonganService")
public class SmsTonganServiceImpl implements SmsTonganService {

    private static final Logger LOG = Logger.getLogger(SmsTonganServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see test.SmsTonganService#sendMt(java.lang.String  username ,)java.lang.String  password ,)java.lang.String  appName ,)java.lang.String  source ,)java.lang.String  phoneNumbers ,)java.lang.String  datas ,)java.lang.String  smsId ,)java.lang.String  sendTime )*
     */
    public MtResult sendMt(java.lang.String username, java.lang.String password, java.lang.String appName,
                           java.lang.String source, java.lang.String phoneNumbers, java.lang.String datas, java.lang.String smsId,
                           java.lang.String sendTime) {
        LOG.info("Executing operation sendMt");
        System.out.println(username);
        System.out.println(password);
        System.out.println(appName);
        System.out.println(source);
        System.out.println(phoneNumbers);
        System.out.println(datas);
        System.out.println(smsId);
        System.out.println(sendTime);
        try {
            MtResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
