package com.wellsoft.pt.message.sms.tamas;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-09-24T17:06:55.944+08:00
 * Generated source version: 2.3.9
 */

public class SmsTonganService_SmsTonganServicePort_Server {

    protected SmsTonganService_SmsTonganServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SmsTonganServiceImpl();
        String address = "http://192.168.158.199:7611/webservice/SmsTonganService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new SmsTonganService_SmsTonganServicePort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
