package com.wellsoft.pt.message.sms.tamas;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.xml.namespace.QName;
import java.net.URL;
import java.util.Date;
import java.util.UUID;


/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-09-24T17:06:55.835+08:00
 * Generated source version: 2.3.9
 */
public final class SmsTonganService_SmsTonganServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://localhost:8080/webservice",
            "SmsTonganService");
    protected Logger logger = LoggerFactory.getLogger(getClass());

    public SmsTonganService_SmsTonganServicePort_Client() {
    }

    public MtResult tongAnSendMessage(String userName, String passWord, String appName,
                                      String source,
                                      String phoneNumbers, String datas, String smsId,
                                      String sendTime) {
        Date begin = null;
        Date end = null;
        String uuid = UUID.randomUUID().toString();
        MtResult _sendMt__return = new MtResult();
        try {
            URL wsdlURL = SmsTonganService_Service.WSDL_LOCATION;
            SmsTonganService_Service ss = new SmsTonganService_Service(wsdlURL, SERVICE_NAME);
            SmsTonganService port = ss.getSmsTonganServicePort();
            //begin = new Date();
            //logger.error("********" + uuid + "sendMt begin：" + begin.getTime());
            _sendMt__return = port.sendMt(userName, passWord, appName, source, phoneNumbers, datas,
                    smsId, sendTime);
            //logger.error("*****************MtResult result startCode:" + _sendMt__return.getReturnStateCode());
            //logger.error("*****************MtResult result Message:" + _sendMt__return.getReturnStateIntro());
            //end = new Date();
            //logger.error("********" + uuid + "sendMt end success：" + (end.getTime() - begin.getTime()));
        } catch (Exception ex) {
            end = new Date();
            logger.error("同安短信接口问题:" + ex.getMessage());
        }
        return _sendMt__return;
    }
}
