package com.wellsoft.pt.message.sms.tamas;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-09-24T17:06:55.944+08:00
 * Generated source version: 2.3.9
 */
@WebServiceClient(name = "SmsTonganService", wsdlLocation = "http://192.168.158.199:7611/webservice/SmsTonganService?wsdl", targetNamespace = "http://localhost:8080/webservice")
public class SmsTonganService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost:8080/webservice", "SmsTonganService");
    public final static QName SmsTonganServicePort = new QName("http://localhost:8080/webservice",
            "SmsTonganServicePort");

    static {
        URL url = null;
        try {
            url = new URL("http://192.168.158.199:7611/webservice/SmsTonganService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SmsTonganService_Service.class.getName()).log(
                    java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
                    "http://192.168.158.199:7611/webservice/SmsTonganService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SmsTonganService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SmsTonganService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmsTonganService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * @return returns SmsTonganService
     */
    @WebEndpoint(name = "SmsTonganServicePort")
    public SmsTonganService getSmsTonganServicePort() {
        return super.getPort(SmsTonganServicePort, SmsTonganService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns SmsTonganService
     */
    @WebEndpoint(name = "SmsTonganServicePort")
    public SmsTonganService getSmsTonganServicePort(WebServiceFeature... features) {
        return super.getPort(SmsTonganServicePort, SmsTonganService.class, features);
    }

}
