package com.wellsoft.pt.message.sms.tamas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.9
 * 2015-09-24T17:06:55.929+08:00
 * Generated source version: 2.3.9
 */
@WebService(targetNamespace = "http://localhost:8080/webservice/", name = "SmsTonganService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SmsTonganService {

    @WebResult(name = "mtResult", targetNamespace = "http://localhost:8080/webservice/", partName = "mtResult")
    @WebMethod(action = "http://localhost:8080/webservice/sendMt")
    public MtResult sendMt(@WebParam(partName = "username", name = "username") java.lang.String username,
                           @WebParam(partName = "password", name = "password") java.lang.String password,
                           @WebParam(partName = "appName", name = "appName") java.lang.String appName,
                           @WebParam(partName = "source", name = "source") java.lang.String source,
                           @WebParam(partName = "phoneNumbers", name = "phoneNumbers") java.lang.String phoneNumbers,
                           @WebParam(partName = "datas", name = "datas") java.lang.String datas,
                           @WebParam(partName = "smsId", name = "smsId") java.lang.String smsId,
                           @WebParam(partName = "sendTime", name = "sendTime") java.lang.String sendTime);
}
