-- new object type path: SCHEMA_EXPORT/TABLE/TABLE

CREATE TABLE "CD_DATA_DICT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "PARENT_UUID" VARCHAR2(255 CHAR), 
  "SOURCE_UUID" VARCHAR2(255 CHAR), 
  "SOURCE_TYPE" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_DATA_DICT_ATTR" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ATTR_ORDER" NUMBER(10,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "VALUE" VARCHAR2(255 CHAR), 
  "DATA_DICT_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "CD_EXCEL_COLUMN_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ATTRIBUTE_NAME" VARCHAR2(255 CHAR), 
  "ATTRIBUTE_TYPE" VARCHAR2(255 CHAR), 
  "COLUMN_NUM" NUMBER(10,0), 
  "EXCEL_IMPORT_RULE_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_EXCEL_IMPORT_RULE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ENTITY" VARCHAR2(255 CHAR), 
  "ENTITY_NAME" VARCHAR2(255 CHAR), 
  "FILE_UUID" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "SORT_ORDER" NUMBER(10,0), 
  "START_ROW" NUMBER(10,0), 
  "TYPE" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_ID_GENERATOR" 
   (  "ENTITY_CLASS_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "POINTER" NUMBER(19,0), 
  "UUID" VARCHAR2(255 CHAR), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "CREATE_TIME" TIMESTAMP (6), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_PINYIN" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ENTITY_UUID" VARCHAR2(255 CHAR), 
  "PINYIN" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_PRINT_RECORD" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "PRINT_OBJECT" VARCHAR2(255 CHAR), 
  "PRINT_OBJECT_TYPE" VARCHAR2(255 CHAR), 
  "PRINT_TIMES" NUMBER(10,0), 
  "USER_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_PRINT_TEMPLATE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "FILE_NAME_FORMAT" VARCHAR2(255 CHAR), 
  "FILE_UUID" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "IS_READ_ONLY" NUMBER(1,0), 
  "IS_SAVE_PRINT_RECORD" NUMBER(1,0), 
  "IS_SAVE_SOURCE" NUMBER(1,0), 
  "IS_SAVE_TRACE" NUMBER(1,0), 
  "KEY_WORDS" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "PRINT_INTERVAL" VARCHAR2(255 CHAR), 
  "ROW_NUMBER" NUMBER(10,0), 
  "TEMPLATE_TYPE" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_READ_MARKER" 
   (  "ENTITY_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "USER_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "READ_TIME" TIMESTAMP (6), 
  "UUID" VARCHAR2(255 CHAR), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "CREATE_TIME" TIMESTAMP (6), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0)
   ) ;
CREATE TABLE "CD_RTX" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "IS_ENABLE" NUMBER(1,0), 
  "IS_ENABLE_ABBREVIATION" NUMBER(1,0), 
  "MESSAGE_SEND_WAY" VARCHAR2(255 CHAR), 
  "RTX_APPLICATION_SERVER_IP" VARCHAR2(255 CHAR), 
  "RTX_APPLICATION_SERVER_PORT" NUMBER(10,0), 
  "RTX_CLIENT_DOWNLOAD_ADDRESS" VARCHAR2(255 CHAR), 
  "RTX_SERVER_IP" VARCHAR2(255 CHAR), 
  "RTX_SERVER_PORT" NUMBER(10,0), 
  "SDK_SERVER_IP" VARCHAR2(255 CHAR), 
  "SDK_SERVER_PORT" NUMBER(10,0), 
  "SYNCHRONIZATION_OPERATION" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_SERIAL_NUMBER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "HEAD_PART" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "INCREMENTAL" NUMBER(10,0), 
  "INITIAL_VALUE" VARCHAR2(255 CHAR), 
  "IS_EDITOR" NUMBER(1,0), 
  "IS_FILL_NUMBER" NUMBER(1,0), 
  "IS_FILL_POSITION" NUMBER(1,0), 
  "KEY_PART" VARCHAR2(255 CHAR), 
  "LAST_PART" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "POINTER" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "SERIAL_NUM" VARCHAR2(255 CHAR), 
  "START_DATE" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_SERIAL_NUMBER_MAINTAIN" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "HEAD_PART" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "IS_EDITOR" NUMBER(1,0), 
  "KEY_PART" VARCHAR2(255 CHAR), 
  "LAST_PART" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "POINTER" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_SYSTEM_TABLE_ENTITY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CHINESE_NAME" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "FULL_ENTITY_NAME" VARCHAR2(255 CHAR), 
  "MODULE_NAME" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "TABLE_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_SYSTEM_TABLE_ENTITY_ATTR" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ATTRIBUTE_NAME" VARCHAR2(255 CHAR), 
  "CHINESE_NAME" VARCHAR2(255 CHAR), 
  "COLUMN_ALIASES" VARCHAR2(255 CHAR), 
  "COLUMN_TYPE" VARCHAR2(255 CHAR), 
  "CONSTANT" VARCHAR2(255 CHAR), 
  "DATA_DICTIONARY" VARCHAR2(255 CHAR), 
  "ENTITY_NAME" VARCHAR2(255 CHAR), 
  "FIELD_NAME" VARCHAR2(255 CHAR), 
  "IS_ORGANIZE_SELECTION_BOX" NUMBER(1,0), 
  "IS_SYNCHRONIZATION" NUMBER(1,0), 
  "REMARK" VARCHAR2(255 CHAR), 
  "SYSTEM_TABLE_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_SYSTEM_TABLE_RELATIONSHIP" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ASSOCIATED_ATTRIBUTES" VARCHAR2(255 CHAR), 
  "MAIN_TABLE_NAME" VARCHAR2(255 CHAR), 
  "SECONDARY_TABLE_NAME" VARCHAR2(255 CHAR), 
  "TABLE_RELATIONSHIP" VARCHAR2(255 CHAR), 
  "SYSTEM_TABLE_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_WORK_HOUR" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "FROM_DATE" VARCHAR2(255 CHAR), 
  "FROM_TIME1" VARCHAR2(255 CHAR), 
  "FROM_TIME2" VARCHAR2(255 CHAR), 
  "IS_WORKDAY" NUMBER(1,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "SORT_ORDER" NUMBER(10,0), 
  "TO_DATE" VARCHAR2(255 CHAR), 
  "TO_TIME1" VARCHAR2(255 CHAR), 
  "TO_TIME2" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_CODE_GENERATOR_CONFIG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "MACHINE_NAME" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "AUTHOR" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "TEMPLATE_TYPE" VARCHAR2(255 CHAR), 
  "CUSTOM_TEMPLATE_DIR" VARCHAR2(255 CHAR), 
  "JAVA_FILE_OUTPUT_DIR" VARCHAR2(255 CHAR), 
  "JAVA_PACKAGE" VARCHAR2(255 CHAR), 
  "JSP_FILE_OUTPUT_DIR" VARCHAR2(255 CHAR), 
  "JS_FILE_OUTPUT_DIR" VARCHAR2(255 CHAR), 
  "GENERATE_TYPE" VARCHAR2(255 CHAR), 
  "CONFIG_JSON" VARCHAR2(4000 CHAR), 
  "MODULE_REQUEST_PATH" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "CD_DATA_DEPENDENCY" 
   (  "UUID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 BYTE), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "MODIFIER" VARCHAR2(255 BYTE), 
  "REC_VER" NUMBER(10,0) NOT NULL ENABLE, 
  "DATA_UUID" VARCHAR2(255 BYTE), 
  "DATA_NAME" VARCHAR2(255 BYTE), 
  "DATA_TYPE" VARCHAR2(255 BYTE), 
  "DATA_REC_VER" NUMBER(10,0), 
  "DEPENDENCY_UUID" VARCHAR2(255 BYTE), 
  "DEPENDENCY_NAME" VARCHAR2(255 BYTE), 
  "DEPENDENCY_TYPE" VARCHAR2(255 BYTE), 
  "DEPENDENCY_REC_VER" NUMBER(10,0)
   ) ;

   

CREATE TABLE "DATA_SOURCE_COLUMN" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "COLUMN_ALIASE" VARCHAR2(255 CHAR), 
  "COLUMN_DATA_TYPE" VARCHAR2(255 CHAR), 
  "COLUMN_NAME" VARCHAR2(255 CHAR), 
  "DEFAULT_SORT" VARCHAR2(255 CHAR), 
  "ENTITY_NAME" VARCHAR2(255 CHAR), 
  "FIELD_NAME" VARCHAR2(255 CHAR), 
  "IS_EXPORT" VARCHAR2(255 CHAR), 
  "TITLE_NAME" VARCHAR2(255 CHAR), 
  "SOURCE_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "DATA_SOURCE_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ACL_HQL_DATA_TEXT" VARCHAR2(255 CHAR), 
  "CHOOSE_DATA_ID" VARCHAR2(255 CHAR), 
  "CHOOSE_DATA_TEXT" VARCHAR2(255 CHAR), 
  "DATA_INTERFACE_ID" VARCHAR2(255 CHAR), 
  "DATA_INTERFACE_NAME" VARCHAR2(255 CHAR), 
  "DATA_SOURCE_ID" VARCHAR2(255 CHAR), 
  "DATA_SOURCE_NAME" VARCHAR2(255 CHAR), 
  "DATA_SOURCE_NUM" VARCHAR2(255 CHAR), 
  "DATA_SOURCE_TYPE_ID" VARCHAR2(255 CHAR), 
  "DATA_SOURCE_TYPE_NAME" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "IN_DATA_SCOPE" VARCHAR2(255 CHAR), 
  "OUT_DATA_SCOPE" VARCHAR2(255 CHAR), 
  "OUT_DATA_SOURCE_ID" VARCHAR2(255 CHAR), 
  "OUT_DATA_SOURCE_NAME" VARCHAR2(255 CHAR), 
  "SEARCH_CONDITION" VARCHAR2(3000 CHAR), 
  "SQL_OR_HQL_TEXT" VARCHAR2(3999 BYTE), 
  "ROLE_VALUE" VARCHAR2(255 CHAR), 
  "ROLE_TYPE" VARCHAR2(255 CHAR), 
  "ROLE_NAME" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "CATE_UUID" VARCHAR2(255 CHAR), 
  "CATE_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "DATA_SOURCE_PROFILE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "DATA_SOURCE_PROFILE_ID" VARCHAR2(255 CHAR), 
  "DATA_SOURCE_PROFILE_NAME" VARCHAR2(255 CHAR), 
  "DATA_SOURCE_PROFILE_NUM" VARCHAR2(255 CHAR), 
  "DATABASE_SID" VARCHAR2(255 CHAR), 
  "DATABASE_TYPE" VARCHAR2(255 CHAR), 
  "HOST" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "OUT_DATA_SOURCE_TYPE" VARCHAR2(255 CHAR), 
  "PASS_WORD" VARCHAR2(255 CHAR), 
  "PORT" VARCHAR2(255 CHAR), 
  "USER_NAME" VARCHAR2(255 CHAR), 
  "OWNER" VARCHAR2(255 CHAR), 
  "CHARACTER_SET" VARCHAR2(255 BYTE)
   ) ;
CREATE TABLE "EXCEL_EXPORT_COLUMN_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ATTRIBUTE_NAME" VARCHAR2(255 CHAR), 
  "COLUMN_ALIASE" VARCHAR2(255 CHAR), 
  "COLUMN_DATA_TYPE" VARCHAR2(255 CHAR), 
  "COLUMN_NUM" NUMBER(10,0), 
  "ENTITY_NAME" VARCHAR2(255 CHAR), 
  "TITLE_NAME" VARCHAR2(255 CHAR), 
  "VALUE_TYPE" VARCHAR2(255 CHAR), 
  "EXCEL_EXPORT_DEFINITION_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "EXCEL_EXPORT_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "FILE_UUID" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "START_ROW" NUMBER(10,0), 
  "VIEW_NAME" VARCHAR2(255 CHAR), 
  "VIEW_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "LOG_LOG" 
   (  "UUID" VARCHAR2(255 BYTE), 
  "CLASS_NAME" VARCHAR2(255 BYTE), 
  "METHOD" VARCHAR2(255 BYTE), 
  "CREATE_TIME" VARCHAR2(255 BYTE), 
  "LOG_LEVEL" VARCHAR2(255 BYTE), 
  "LOG_MSG" CLOB, 
  "USER_ID" VARCHAR2(255 BYTE), 
  "LOG_CODE" VARCHAR2(255 BYTE), 
  "LINE_NUM" VARCHAR2(255 BYTE)
   ) ;

-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/INDEX
CREATE INDEX "CD_DATA_DICT_PARENT_UUID_IDX" ON "CD_DATA_DICT" ("PARENT_UUID");
ALTER INDEX "CD_DATA_DICT_PARENT_UUID_IDX" NOPARALLEL;
CREATE INDEX "CD_DDA_DATA_DICT_UUID_IDX" ON "CD_DATA_DICT_ATTR" ("DATA_DICT_UUID");
ALTER INDEX "CD_DDA_DATA_DICT_UUID_IDX" NOPARALLEL;
CREATE INDEX "CD_ECD_EIR_UUID_IDX" ON "CD_EXCEL_COLUMN_DEFINITION" ("EXCEL_IMPORT_RULE_UUID");
ALTER INDEX "CD_ECD_EIR_UUID_IDX" NOPARALLEL;
CREATE INDEX "CD_STEA_SYSTEM_TABLE_UUID_IDX" ON "CD_SYSTEM_TABLE_ENTITY_ATTR" ("SYSTEM_TABLE_UUID");
ALTER INDEX "CD_STEA_SYSTEM_TABLE_UUID_IDX" NOPARALLEL;
CREATE INDEX "CD_STR_SYSTEM_TABLE_UUID_IDX" ON "CD_SYSTEM_TABLE_RELATIONSHIP" ("SYSTEM_TABLE_UUID");
ALTER INDEX "CD_STR_SYSTEM_TABLE_UUID_IDX" NOPARALLEL;
CREATE UNIQUE INDEX "CD_DATA_DEPENDENCY_UUID" ON "CD_DATA_DEPENDENCY" ("UUID");
ALTER INDEX "CD_DATA_DEPENDENCY_UUID" NOPARALLEL;
CREATE INDEX "DATA_SC_SOURCE_DEF_UUID_IDX" ON "DATA_SOURCE_COLUMN" ("SOURCE_DEF_UUID");
ALTER INDEX "DATA_SC_SOURCE_DEF_UUID_IDX" NOPARALLEL;
CREATE INDEX "EXCEL_ECD_EED_UUID_IDX" ON "EXCEL_EXPORT_COLUMN_DEFINITION" ("EXCEL_EXPORT_DEFINITION_UUID");
ALTER INDEX "EXCEL_ECD_EED_UUID_IDX" NOPARALLEL;


-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT
ALTER TABLE "CD_DATA_DEPENDENCY" ADD CONSTRAINT "CD_DATA_DEPENDENCY_UUID" PRIMARY KEY ("UUID")
  USING INDEX "CD_DATA_DEPENDENCY_UUID"  ENABLE;