-- Create table
CREATE TABLE BIZ_CATEGORY
(
    "UUID"        VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"     VARCHAR2(20 CHAR),
    "CREATE_TIME" TIMESTAMP(6),
    "MODIFIER"    VARCHAR2(20 CHAR),
    "MODIFY_TIME" TIMESTAMP(6),
    "REC_VER"     NUMBER(10, 0),
    "NAME"        VARCHAR2(100 CHAR),
    "ID"          VARCHAR2(50 CHAR),
    "CODE"        VARCHAR2(20 CHAR),
    "PARENT_UUID" VARCHAR2(50 CHAR),
    "REMARK"      VARCHAR2(200 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE BIZ_CATEGORY IS '业务流程分类';
COMMENT
ON COLUMN BIZ_CATEGORY.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_CATEGORY.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_CATEGORY.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_CATEGORY.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_CATEGORY.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_CATEGORY.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_CATEGORY.NAME IS '名称';
COMMENT
ON COLUMN BIZ_CATEGORY.ID IS 'ID';
COMMENT
ON COLUMN BIZ_CATEGORY.CODE IS '编号';
COMMENT
ON COLUMN BIZ_CATEGORY.PARENT_UUID IS '上级分类UUID';
COMMENT
ON COLUMN BIZ_CATEGORY.REMARK IS '备注';



CREATE TABLE BIZ_BUSINESS
(
    "UUID"          VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"       VARCHAR2(20 CHAR),
    "CREATE_TIME"   TIMESTAMP(6),
    "MODIFIER"      VARCHAR2(20 CHAR),
    "MODIFY_TIME"   TIMESTAMP(6),
    "REC_VER"       NUMBER(10, 0),
    "NAME"          VARCHAR2(100 CHAR),
    "ID"            VARCHAR2(50 CHAR),
    "CODE"          VARCHAR2(20 CHAR),
    "CATEGORY_UUID" VARCHAR2(50 CHAR),
    "REMARK"        VARCHAR2(200 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE BIZ_BUSINESS IS '业务';
COMMENT
ON COLUMN BIZ_BUSINESS.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_BUSINESS.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_BUSINESS.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_BUSINESS.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_BUSINESS.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_BUSINESS.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_BUSINESS.NAME IS '名称';
COMMENT
ON COLUMN BIZ_BUSINESS.ID IS 'ID';
COMMENT
ON COLUMN BIZ_BUSINESS.CODE IS '编号';
COMMENT
ON COLUMN BIZ_BUSINESS.CATEGORY_UUID IS '业务分类UUID';
COMMENT
ON COLUMN BIZ_BUSINESS.REMARK IS '备注';



CREATE TABLE BIZ_PROCESS_DEFINITION
(
    "UUID"            VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"         VARCHAR2(20 CHAR),
    "CREATE_TIME"     TIMESTAMP(6),
    "MODIFIER"        VARCHAR2(20 CHAR),
    "MODIFY_TIME"     TIMESTAMP(6),
    "REC_VER"         NUMBER(10, 0),
    "NAME"            VARCHAR2(100 CHAR),
    "ID"              VARCHAR2(50 CHAR),
    "CODE"            VARCHAR2(20 CHAR),
    "VERSION"         NUMBER(10, 1),
    "ENABLED"         NUMBER(1),
    "BUSINESS_ID"     VARCHAR2(50 CHAR),
    "TAG_ID"          VARCHAR2(100 CHAR),
    "DEFINITION_JSON" CLOB,
    "REMARK"          VARCHAR2(200 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE BIZ_PROCESS_DEFINITION IS '业务流程定义';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.NAME IS '名称';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.ID IS 'ID';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.CODE IS '编号';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.VERSION IS '版本';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.ENABLED IS '是否启用';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.BUSINESS_ID IS '业务ID';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.TAG_ID IS '业务标签ID';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.DEFINITION_JSON IS '定义JSON信息';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION.REMARK IS '备注';



CREATE TABLE BIZ_PROCESS_DEFINITION_HIS
(
    "UUID"             VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"          VARCHAR2(20 CHAR),
    "CREATE_TIME"      TIMESTAMP(6),
    "MODIFIER"         VARCHAR2(20 CHAR),
    "MODIFY_TIME"      TIMESTAMP(6),
    "REC_VER"          NUMBER(10, 0),
    "PROCESS_DEF_UUID" VARCHAR2(50 CHAR),
    "NAME"             VARCHAR2(100 CHAR),
    "ID"               VARCHAR2(50 CHAR),
    "CODE"             VARCHAR2(20 CHAR),
    "VERSION"          NUMBER(10, 1),
    "ENABLED"          NUMBER(1),
    "BUSINESS_ID"      VARCHAR2(50 CHAR),
    "TAG_ID"           VARCHAR2(100 CHAR),
    "DEFINITION_JSON"  CLOB,
    "REMARK"           VARCHAR2(200 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE BIZ_PROCESS_DEFINITION_HIS IS '业务流程定义历史版本';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.PROCESS_DEF_UUID IS '过程定义UUID';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.NAME IS '名称';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.ID IS 'ID';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.CODE IS '编号';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.VERSION IS '版本';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.ENABLED IS '是否启用';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.BUSINESS_ID IS '业务ID';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.TAG_ID IS '业务标签ID';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.DEFINITION_JSON IS '定义JSON信息';
COMMENT
ON COLUMN BIZ_PROCESS_DEFINITION_HIS.REMARK IS '备注';



CREATE TABLE BIZ_TAG
(
    "UUID"        VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"     VARCHAR2(20 CHAR),
    "CREATE_TIME" TIMESTAMP(6),
    "MODIFIER"    VARCHAR2(20 CHAR),
    "MODIFY_TIME" TIMESTAMP(6),
    "REC_VER"     NUMBER(10, 0),
    "NAME"        VARCHAR2(100 CHAR),
    "ID"          VARCHAR2(50 CHAR),
    "CODE"        VARCHAR2(20 CHAR),
    "SCOPE"       VARCHAR2(100 CHAR),
    "REMARK"      VARCHAR2(200 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE BIZ_TAG IS '业务标签';
COMMENT
ON COLUMN BIZ_TAG.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_TAG.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_TAG.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_TAG.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_TAG.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_TAG.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_TAG.NAME IS '名称';
COMMENT
ON COLUMN BIZ_TAG.ID IS 'ID';
COMMENT
ON COLUMN BIZ_TAG.CODE IS '编号';
COMMENT
ON COLUMN BIZ_TAG.SCOPE IS '使用范围，由数据字典配置，例如全部、业务流程、过程节点、事项、事项工作日、事项材料、其他';
COMMENT
ON COLUMN BIZ_TAG.REMARK IS '备注';



CREATE TABLE BIZ_PROCESS_INSTANCE
(
    "UUID"             VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"          VARCHAR2(20 CHAR),
    "CREATE_TIME"      TIMESTAMP(6),
    "MODIFIER"         VARCHAR2(20 CHAR),
    "MODIFY_TIME"      TIMESTAMP(6),
    "REC_VER"          NUMBER(10, 0),
    "NAME"             VARCHAR2(100 CHAR),
    "ID"               VARCHAR2(50 CHAR),
    "TITLE"            VARCHAR2(200 CHAR),
    "ENTITY_NAME"      VARCHAR2(150 CHAR),
    "ENTITY_ID"        VARCHAR2(100 CHAR),
    "FORM_UUID"        VARCHAR2(50 CHAR),
    "DATA_UUID"        VARCHAR2(50 CHAR),
    "START_TIME"       TIMESTAMP(6),
    "END_TIME"         TIMESTAMP(6),
    "STATE"            VARCHAR2(10 CHAR),
    "PROCESS_DEF_UUID" VARCHAR2(50 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE BIZ_PROCESS_INSTANCE IS '业务流程实例';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.NAME IS '业务流程名称';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.ID IS '业务流程ID';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.TITLE IS '标题';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.ENTITY_NAME IS '业务主体名称';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.ENTITY_ID IS '业务主体ID';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.FORM_UUID IS '表单定义UUID';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.DATA_UUID IS '表单数据UUID';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.START_TIME IS '开始时间';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.END_TIME IS '结束时间';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.STATE IS '当前状态，10运行中，20暂停，30已结束';
COMMENT
ON COLUMN BIZ_PROCESS_INSTANCE.PROCESS_DEF_UUID IS '业务流程定义UUID';



CREATE TABLE BIZ_PROCESS_NODE_INSTANCE
(
    "UUID"                  VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"               VARCHAR2(20 CHAR),
    "CREATE_TIME"           TIMESTAMP(6),
    "MODIFIER"              VARCHAR2(20 CHAR),
    "MODIFY_TIME"           TIMESTAMP(6),
    "REC_VER"               NUMBER(10, 0),
    "NAME"                  VARCHAR2(100 CHAR),
    "ID"                    VARCHAR2(50 CHAR),
    "TITLE"                 VARCHAR2(200 CHAR),
    "ENTITY_NAME"           VARCHAR2(150 CHAR),
    "ENTITY_ID"             VARCHAR2(100 CHAR),
    "FORM_UUID"             VARCHAR2(50 CHAR),
    "DATA_UUID"             VARCHAR2(50 CHAR),
    "START_TIME"            TIMESTAMP(6),
    "END_TIME"              TIMESTAMP(6),
    "TIME_LIMIT_TYPE"       NUMBER(10),
    "TIME_LIMIT"            NUMBER(10),
    "TOTAL_TIME"            NUMBER(10, 1),
    "IS_MILESTONE"          NUMBER(1),
    "STATE"                 VARCHAR2(10 CHAR),
    "PARENT_NODE_INST_UUID" VARCHAR2(50 CHAR),
    "PROCESS_INST_UUID"     VARCHAR2(50 CHAR),
    "PROCESS_DEF_UUID"      VARCHAR2(50 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE BIZ_PROCESS_NODE_INSTANCE IS '业务流程过程节点实例';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.NAME IS '过程节点名称';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.ID IS '过程节点ID';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.TITLE IS '标题';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.ENTITY_NAME IS '业务主体名称';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.ENTITY_ID IS '业务主体ID';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.FORM_UUID IS '表单定义UUID';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.DATA_UUID IS '表单数据UUID';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.START_TIME IS '开始时间';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.END_TIME IS '结束时间';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.TIME_LIMIT_TYPE IS '时限类型1、工作日，2、自然日';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.TIME_LIMIT IS '时限标线';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.TOTAL_TIME IS '总用时';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.IS_MILESTONE IS '是否里程碑';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.STATE IS '当前状态，10运行中，20暂停，30已结束';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.PARENT_NODE_INST_UUID IS '上级过程节点实例UUID';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.PROCESS_INST_UUID IS '业务流程实例UUID';
COMMENT
ON COLUMN BIZ_PROCESS_NODE_INSTANCE.PROCESS_DEF_UUID IS '业务流程定义UUID';



CREATE TABLE BIZ_PROCESS_ITEM_INSTANCE
(
    "UUID"                   VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"                VARCHAR2(20 CHAR),
    "CREATE_TIME"            TIMESTAMP(6),
    "MODIFIER"               VARCHAR2(20 CHAR),
    "MODIFY_TIME"            TIMESTAMP(6),
    "REC_VER"                NUMBER(10, 0),
    "ITEM_DEF_NAME"          VARCHAR2(100 CHAR),
    "ITEM_DEF_ID"            VARCHAR2(50 CHAR),
    "ITEM_NAME"              VARCHAR2(2000 CHAR),
    "ITEM_CODE"              VARCHAR2(2000 CHAR),
    "ITEM_ID"                VARCHAR2(2000 CHAR),
    "ITEM_TYPE"              VARCHAR2(10 CHAR),
    "TITLE"                  VARCHAR2(200 CHAR),
    "ENTITY_NAME"            VARCHAR2(150 CHAR),
    "ENTITY_ID"              VARCHAR2(100 CHAR),
    "FORM_UUID"              VARCHAR2(50 CHAR),
    "DATA_UUID"              VARCHAR2(50 CHAR),
    "START_TIME"             TIMESTAMP(6),
    "END_TIME"               TIMESTAMP(6),
    "TIME_LIMIT_TYPE"        NUMBER(10),
    "TIME_LIMIT"             NUMBER(10),
    "TOTAL_TIME"             NUMBER(10, 1),
    "IS_MILESTONE"           NUMBER(1),
    "IS_DISPENSE_ITEM"       NUMBER(1),
    "STATE"                  VARCHAR2(10 CHAR),
    "TIMER_UUID"             VARCHAR2(50 CHAR),
    "TIMER_STATE"            NUMBER(1),
    "TIMING_STATE"           NUMBER(1),
    "DUE_TIME"               TIMESTAMP(6),
    "PARENT_ITEM_INST_UUID"  VARCHAR2(50 CHAR),
    "BELONG_ITEM_INST_UUID"  VARCHAR2(50 CHAR),
    "ITEM_DEF_UUID"          VARCHAR2(50 CHAR),
    "PROCESS_NODE_INST_UUID" VARCHAR2(50 CHAR),
    "PROCESS_INST_UUID"      VARCHAR2(50 CHAR),
    "PROCESS_DEF_UUID"       VARCHAR2(50 CHAR),
    "PROCESS_DEF_ID"         VARCHAR2(50 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE BIZ_PROCESS_ITEM_INSTANCE IS '业务流程事项实例';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.ITEM_DEF_NAME IS '事项定义名称';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.ITEM_DEF_ID IS '事项定义ID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.ITEM_NAME IS '事项名称';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.ITEM_CODE IS '事项编码';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.ITEM_ID IS '事项ID，业务流程事项配置自动生成的ID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.ITEM_TYPE IS '事项类型，10单个事项，20串联事项，30并联事项';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.TITLE IS '标题';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.ENTITY_NAME IS '业务主体名称';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.ENTITY_ID IS '业务主体ID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.FORM_UUID IS '表单定义UUID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.DATA_UUID IS '表单数据UUID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.START_TIME IS '开始时间';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.END_TIME IS '结束时间';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.TIME_LIMIT_TYPE IS '时限类型1、工作日，2、自然日';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.TIME_LIMIT IS '时限';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.TOTAL_TIME IS '总用时';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.IS_MILESTONE IS '是否里程碑';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.IS_DISPENSE_ITEM IS '是否分发事项';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.STATE IS '当前状态，10运行中，20暂停，30已结束';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.TIMER_UUID IS '计时器UUID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.TIMER_STATE IS '计时器状态，0未启动、1已启动、2暂停、3结束';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.TIMING_STATE IS '计时状态， 0正常、1预警、2到期、3逾期';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.DUE_TIME IS '到期时间';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.PARENT_ITEM_INST_UUID IS '上级事项实例UUID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.BELONG_ITEM_INST_UUID IS '归属事项实例UUID，事项拆分时归属的事项实例';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.ITEM_DEF_UUID IS '事项定义UUID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.PROCESS_NODE_INST_UUID IS '过程节点实例UUID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.PROCESS_INST_UUID IS '业务流程实例UUID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.PROCESS_DEF_UUID IS '业务流程定义UUID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.PROCESS_DEF_ID IS '业务流程定义ID';


CREATE TABLE BIZ_PROCESS_ITEM_INST_DISPENSE
(
    "UUID"                  VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"               VARCHAR2(20 CHAR),
    "CREATE_TIME"           TIMESTAMP(6),
    "MODIFIER"              VARCHAR2(20 CHAR),
    "MODIFY_TIME"           TIMESTAMP(6),
    "REC_VER"               NUMBER(10, 0),
    "PARENT_ITEM_INST_UUID" VARCHAR2(50 CHAR),
    "ITEM_INST_UUID"        VARCHAR2(50 CHAR),
    "ITEM_NAME"             VARCHAR2(150 CHAR),
    "ITEM_CODE"             VARCHAR2(50 CHAR),
    "SORT_ORDER"            NUMBER(10),
    "COMPLETION_STATE"      NUMBER(10),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE BIZ_PROCESS_ITEM_INST_DISPENSE IS '业务流程事项实例分发';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INST_DISPENSE.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INST_DISPENSE.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INST_DISPENSE.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INST_DISPENSE.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INST_DISPENSE.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INST_DISPENSE.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INST_DISPENSE.PARENT_ITEM_INST_UUID IS '上级事项实例UUID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INST_DISPENSE.ITEM_INST_UUID IS '当前事项实例UUID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INST_DISPENSE.ITEM_NAME IS '事项名称';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INST_DISPENSE.ITEM_CODE IS '事项编码';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INST_DISPENSE.SORT_ORDER IS '排序号';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INST_DISPENSE.COMPLETION_STATE IS '完成状态，0未分发，1已分发';



CREATE TABLE BIZ_PROCESS_ITEM_OPERATION
(
    "UUID"                   VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"                VARCHAR2(20 CHAR),
    "CREATE_TIME"            TIMESTAMP(6),
    "MODIFIER"               VARCHAR2(20 CHAR),
    "MODIFY_TIME"            TIMESTAMP(6),
    "REC_VER"                NUMBER(10, 0),
    "OPERATOR_NAME"          VARCHAR2(100 CHAR),
    "OPERATOR_ID"            VARCHAR2(20 CHAR),
    "OPERATE_TYPE"           VARCHAR2(50 CHAR),
    "OPERATE_TIME"           TIMESTAMP(6),
    "OPINION_TEXT"           VARCHAR2(2000 CHAR),
    "REPO_FILE_UUIDS"        VARCHAR2(2000 CHAR),
    "ITEM_INST_UUID"         VARCHAR2(50 CHAR),
    "PROCESS_NODE_INST_UUID" VARCHAR2(50 CHAR),
    "PROCESS_INST_UUID"      VARCHAR2(50 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE BIZ_PROCESS_ITEM_OPERATION IS '业务流程事项实例操作表';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.OPERATOR_NAME IS '操作人名称';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.OPERATOR_ID IS '操作人ID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.OPERATE_TYPE IS '操作类型';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.OPERATE_TIME IS '操作时间';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.OPINION_TEXT IS '办理意见';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.REPO_FILE_UUIDS IS '办理附件UUID列表，多个以分号隔开';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.ITEM_INST_UUID IS '事项实例UUID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.PROCESS_NODE_INST_UUID IS '过程节点实例UUID';
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_OPERATION.PROCESS_INST_UUID IS '业务流程实例UUID';



CREATE TABLE BIZ_ITEM_DEFINITION
(
    "UUID"                    VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"                 VARCHAR2(20 CHAR),
    "CREATE_TIME"             TIMESTAMP(6),
    "MODIFIER"                VARCHAR2(20 CHAR),
    "MODIFY_TIME"             TIMESTAMP(6),
    "REC_VER"                 NUMBER(10, 0),
    "NAME"                    VARCHAR2(100 CHAR),
    "ID"                      VARCHAR2(50 CHAR),
    "CODE"                    VARCHAR2(20 CHAR),
    "TYPE"                    VARCHAR2(10 CHAR),
    "BUSINESS_ID"             VARCHAR2(50 CHAR),
    "FORM_ID"                 VARCHAR2(50 CHAR),
    "ITEM_NAME_FIELD"         VARCHAR2(30 CHAR),
    "ITEM_CODE_FIELD"         VARCHAR2(30 CHAR),
    "TIME_LIMIT_SUBFORM_ID"   VARCHAR2(30 CHAR),
    "TIME_LIMIT_FIELD"        VARCHAR2(30 CHAR),
    "MATERIAL_SUBFORM_ID"     VARCHAR2(30 CHAR),
    "MATERIAL_NAME_FIELD"     VARCHAR2(30 CHAR),
    "MATERIAL_CODE_FIELD"     VARCHAR2(30 CHAR),
    "MATERIAL_REQUIRED_FIELD" VARCHAR2(30 CHAR),
    "INCLUDE_ITEM_SUBFORM_ID" VARCHAR2(30 CHAR),
    "INCLUDE_ITEM_NAME_FIELD" VARCHAR2(30 CHAR),
    "INCLUDE_ITEM_CODE_FIELD" VARCHAR2(30 CHAR),
    "FRONT_ITEM_CODE_FIELD"   VARCHAR2(30 CHAR),
    "MUTEX_ITEM_SUBFORM_ID"   VARCHAR2(30 CHAR),
    "MUTEX_ITEM_CODE_FIELD"   VARCHAR2(30 CHAR),
    "RELATE_ITEM_SUBFORM_ID"  VARCHAR2(30 CHAR),
    "RELATE_ITEM_CODE_FIELD"  VARCHAR2(30 CHAR),
    "REMARK"                  VARCHAR2(200 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE BIZ_ITEM_DEFINITION IS '业务事项定义';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.NAME IS '名称';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.ID IS 'ID';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.CODE IS '编号';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.TYPE IS '事项类型，10单个事项，20串联事项，30并联事项';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.BUSINESS_ID IS '业务ID';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.FORM_ID IS '使用定义单ID';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.ITEM_NAME_FIELD IS '事项名称字段';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.ITEM_CODE_FIELD IS '事项编码字段';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.TIME_LIMIT_SUBFORM_ID IS '时限从表ID';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.TIME_LIMIT_FIELD IS '时限从表的时限字段';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.MATERIAL_SUBFORM_ID IS '材料从表ID';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.MATERIAL_NAME_FIELD IS '材料从表的材料名称字段';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.MATERIAL_CODE_FIELD IS '材料从表的材料编码字段';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.MATERIAL_REQUIRED_FIELD IS '材料从表的材料是否必填字段';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.INCLUDE_ITEM_SUBFORM_ID IS '包含事项从表ID';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.INCLUDE_ITEM_NAME_FIELD IS '包含事项从表的事项名称字段';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.INCLUDE_ITEM_CODE_FIELD IS '包含事项从表的事项编码字段';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.FRONT_ITEM_CODE_FIELD IS '包含事项从表的前置事项编码';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.MUTEX_ITEM_SUBFORM_ID IS '互斥事项从表ID';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.MUTEX_ITEM_CODE_FIELD IS '互斥事项从表的事项编码字段，字段值多个以分号隔开';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.RELATE_ITEM_SUBFORM_ID IS '关联事项从表ID';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.RELATE_ITEM_CODE_FIELD IS '关联事项从表的事项编码字段，字段值多个以分号隔开';
COMMENT
ON COLUMN BIZ_ITEM_DEFINITION.REMARK IS '备注';


-- Create table
CREATE TABLE BIZ_NEW_ITEM_RELATION
(
    "UUID"                  VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"               VARCHAR2(20 CHAR),
    "CREATE_TIME"           TIMESTAMP(6),
    "MODIFIER"              VARCHAR2(20 CHAR),
    "MODIFY_TIME"           TIMESTAMP(6),
    "REC_VER"               NUMBER(10, 0),
    "SOURCE_ITEM_INST_UUID" VARCHAR2(50 CHAR),
    "SOURCE_BIZ_INST_UUID"  VARCHAR2(50 CHAR),
    "ITEM_INST_UUID"        VARCHAR2(50 CHAR),
    "EXTRA_DATA"            VARCHAR2(500),
    PRIMARY KEY ("UUID")
);
COMMENT
ON TABLE BIZ_NEW_ITEM_RELATION IS '业务事项发起新业务事项关系';
COMMENT
ON COLUMN BIZ_NEW_ITEM_RELATION.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_NEW_ITEM_RELATION.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_NEW_ITEM_RELATION.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_NEW_ITEM_RELATION.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_NEW_ITEM_RELATION.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_NEW_ITEM_RELATION.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_NEW_ITEM_RELATION.SOURCE_ITEM_INST_UUID IS '源事项实例UUID';
COMMENT
ON COLUMN BIZ_NEW_ITEM_RELATION.SOURCE_BIZ_INST_UUID IS '源业务实例UUID';
COMMENT
ON COLUMN BIZ_NEW_ITEM_RELATION.ITEM_INST_UUID IS '发起的事项实例UUID';
COMMENT
ON COLUMN BIZ_NEW_ITEM_RELATION.EXTRA_DATA IS '附加数据';
