-- Create table
CREATE TABLE WF_FLOW_BUSINESS_DEFINITION
(
    "UUID"            VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"         VARCHAR2(20 CHAR),
    "CREATE_TIME"     TIMESTAMP(6),
    "MODIFIER"        VARCHAR2(20 CHAR),
    "MODIFY_TIME"     TIMESTAMP(6),
    "REC_VER"         NUMBER(10, 0),
    "NAME"            VARCHAR2(100 CHAR),
    "ID"              VARCHAR2(50 CHAR),
    "CODE"            VARCHAR2(20 CHAR),
    "CATEGORY_UUID"   VARCHAR2(50 CHAR),
    "FLOW_DEF_UUID"   VARCHAR2(50 CHAR),
    "FLOW_DEF_ID"     VARCHAR2(100 CHAR),
    "DEFINITION_JSON" CLOB,
    "LISTENER"        VARCHAR2(100 CHAR),
    "REMARK"          VARCHAR2(200 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
    ON TABLE WF_FLOW_BUSINESS_DEFINITION IS '流程业务定义';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.CREATOR IS '创建人';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.MODIFIER IS '修改人';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.REC_VER IS '版本号';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.NAME IS '名称';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.ID IS 'ID';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.CODE IS '编号';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.CATEGORY_UUID IS '流程分类UUID';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.FLOW_DEF_UUID IS '流程定义UUID';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.FLOW_DEF_ID IS '流程定义ID';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.DEFINITION_JSON IS '定义JSON信息';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.LISTENER IS '状态变更监听器';
COMMENT
    ON COLUMN WF_FLOW_BUSINESS_DEFINITION.REMARK IS '备注';
