-- Create table
CREATE TABLE BIZ_BUSINESS_INTEGRATION
(
    "UUID"           VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"        VARCHAR2(20 CHAR),
    "CREATE_TIME"    TIMESTAMP(6),
    "MODIFIER"       VARCHAR2(20 CHAR),
    "MODIFY_TIME"    TIMESTAMP(6),
    "REC_VER"        NUMBER(10, 0),
    "TYPE"           VARCHAR2(10 CHAR),
    "ITEM_INST_UUID" VARCHAR2(50 CHAR),
    "BIZ_INST_UUID"  VARCHAR2(50 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
    ON TABLE BIZ_BUSINESS_INTEGRATION IS '业务集成';
COMMENT
    ON COLUMN BIZ_BUSINESS_INTEGRATION.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN BIZ_BUSINESS_INTEGRATION.CREATOR IS '创建人';
COMMENT
    ON COLUMN BIZ_BUSINESS_INTEGRATION.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN BIZ_BUSINESS_INTEGRATION.MODIFIER IS '修改人';
COMMENT
    ON COLUMN BIZ_BUSINESS_INTEGRATION.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN BIZ_BUSINESS_INTEGRATION.REC_VER IS '版本号';
COMMENT
    ON COLUMN BIZ_BUSINESS_INTEGRATION.TYPE IS '业务集成类型，1工作流';
COMMENT
    ON COLUMN BIZ_BUSINESS_INTEGRATION.ITEM_INST_UUID IS '事项实例UUID';
COMMENT
    ON COLUMN BIZ_BUSINESS_INTEGRATION.BIZ_INST_UUID IS '业务实例UUID';


-- Create table
CREATE TABLE BIZ_MILESTONE
(
    "UUID"           VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"        VARCHAR2(20 CHAR),
    "CREATE_TIME"    TIMESTAMP(6),
    "MODIFIER"       VARCHAR2(20 CHAR),
    "MODIFY_TIME"    TIMESTAMP(6),
    "REC_VER"        NUMBER(10, 0),
    "NAME"           VARCHAR2(100 CHAR),
    "ITEM_INST_UUID" VARCHAR2(50 CHAR),
    "REMARK"         VARCHAR2(500 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
    ON TABLE BIZ_MILESTONE IS '里程碑事件';
COMMENT
    ON COLUMN BIZ_MILESTONE.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN BIZ_MILESTONE.CREATOR IS '创建人';
COMMENT
    ON COLUMN BIZ_MILESTONE.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN BIZ_MILESTONE.MODIFIER IS '修改人';
COMMENT
    ON COLUMN BIZ_MILESTONE.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN BIZ_MILESTONE.REC_VER IS '版本号';
COMMENT
    ON COLUMN BIZ_MILESTONE.NAME IS '里程碑事件名称';
COMMENT
    ON COLUMN BIZ_MILESTONE.ITEM_INST_UUID IS '事项实例UUID';
COMMENT
    ON COLUMN BIZ_MILESTONE.REMARK IS '里程碑事件描述';


-- Create table
CREATE TABLE BIZ_MILESTONE_RESULT
(
    "UUID"            VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"         VARCHAR2(20 CHAR),
    "CREATE_TIME"     TIMESTAMP(6),
    "MODIFIER"        VARCHAR2(20 CHAR),
    "MODIFY_TIME"     TIMESTAMP(6),
    "REC_VER"         NUMBER(10, 0),
    "MILESTONE_UUID"  VARCHAR2(50 CHAR),
    "RESULT_TYPE"     VARCHAR2(10 CHAR),
    "CONTENT"         clob,
    "REPO_FILE_UUIDS" VARCHAR2(2000 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
    ON TABLE BIZ_MILESTONE_RESULT IS '里程碑事件交付物';
COMMENT
    ON COLUMN BIZ_MILESTONE_RESULT.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN BIZ_MILESTONE_RESULT.CREATOR IS '创建人';
COMMENT
    ON COLUMN BIZ_MILESTONE_RESULT.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN BIZ_MILESTONE_RESULT.MODIFIER IS '修改人';
COMMENT
    ON COLUMN BIZ_MILESTONE_RESULT.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN BIZ_MILESTONE_RESULT.REC_VER IS '版本号';
COMMENT
    ON COLUMN BIZ_MILESTONE_RESULT.MILESTONE_UUID IS '里程碑事件UUID';
COMMENT
    ON COLUMN BIZ_MILESTONE_RESULT.RESULT_TYPE IS '交付物类型，1结论，2附件';
COMMENT
    ON COLUMN BIZ_MILESTONE_RESULT.CONTENT IS '结论内容';
COMMENT
    ON COLUMN BIZ_MILESTONE_RESULT.REPO_FILE_UUIDS IS '附件UUID列表，多个以分号隔开';


CREATE TABLE BIZ_DEFINITION_TEMPLATE
(
    "UUID"             VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"          VARCHAR2(20 CHAR),
    "CREATE_TIME"      TIMESTAMP(6),
    "MODIFIER"         VARCHAR2(20 CHAR),
    "MODIFY_TIME"      TIMESTAMP(6),
    "REC_VER"          NUMBER(10, 0),
    "NAME"             VARCHAR2(100 CHAR),
    "TYPE"             VARCHAR2(10 CHAR),
    "PROCESS_DEF_UUID" VARCHAR2(50 CHAR),
    "DEFINITION_JSON"  CLOB,
    PRIMARY KEY ("UUID")
);
COMMENT
    ON TABLE BIZ_DEFINITION_TEMPLATE IS '业务流程配置项模板';
COMMENT
    ON COLUMN BIZ_DEFINITION_TEMPLATE.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN BIZ_DEFINITION_TEMPLATE.CREATOR IS '创建人';
COMMENT
    ON COLUMN BIZ_DEFINITION_TEMPLATE.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN BIZ_DEFINITION_TEMPLATE.MODIFIER IS '修改人';
COMMENT
    ON COLUMN BIZ_DEFINITION_TEMPLATE.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN BIZ_DEFINITION_TEMPLATE.REC_VER IS '版本号';
COMMENT
    ON COLUMN BIZ_DEFINITION_TEMPLATE.NAME IS '模板名称';
COMMENT
    ON COLUMN BIZ_DEFINITION_TEMPLATE.TYPE IS '模板类型，10业务流程表单配置模板、20过程节点表单配置模板、30事项表单配置模板、40事项集成工作流配置模板';
COMMENT
    ON COLUMN BIZ_DEFINITION_TEMPLATE.PROCESS_DEF_UUID IS '业务流程定义UUID';
COMMENT
    ON COLUMN BIZ_DEFINITION_TEMPLATE.DEFINITION_JSON IS '定义JSON信息';