CREATE TABLE BIZ_PROCESS_NODE_DEFINITION
(
    "UUID"             VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"          VARCHAR2(20 CHAR),
    "CREATE_TIME"      TIMESTAMP(6),
    "MODIFIER"         VARCHAR2(20 CHAR),
    "MODIFY_TIME"      TIMESTAMP(6),
    "REC_VER"          NUMBER(10, 0),
    "NAME"             VARCHAR2(100 CHAR),
    "ID"               VARCHAR2(50 CHAR),
    "CODE"             VARCHAR2(50 CHAR),
    "EXT_ATTRS_JSON"   VARCHAR2(4000 CHAR),
    "SORT_ORDER"       NUMBER(10, 0),
    "PARENT_ID"        VARCHAR2(50 CHAR),
    "PROCESS_DEF_UUID" VARCHAR2(50 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
    ON TABLE BIZ_PROCESS_NODE_DEFINITION IS '业务流程过程节点定义基本信息';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.CREATOR IS '创建人';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.MODIFIER IS '修改人';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.REC_VER IS '版本号';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.NAME IS '过程节点名称';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.ID IS '过程节点ID';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.CODE IS '过程节点编号';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.EXT_ATTRS_JSON IS '扩展定义JSON信息';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.SORT_ORDER IS '排序号';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.PARENT_ID IS '上级过程节点ID';
COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.PROCESS_DEF_UUID IS '过程定义UUID';



CREATE TABLE BIZ_PROCESS_ITEM_DEFINITION
(
    "UUID"             VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"          VARCHAR2(20 CHAR),
    "CREATE_TIME"      TIMESTAMP(6),
    "MODIFIER"         VARCHAR2(20 CHAR),
    "MODIFY_TIME"      TIMESTAMP(6),
    "REC_VER"          NUMBER(10, 0),
    "ITEM_DEF_NAME"    VARCHAR2(100 CHAR),
    "ITEM_DEF_ID"      VARCHAR2(50 CHAR),
    "ITEM_NAME"        VARCHAR2(512 CHAR),
    "ITEM_CODE"        VARCHAR2(50 CHAR),
    "ITEM_ID"          VARCHAR2(50 CHAR),
    "ITEM_TYPE"        VARCHAR2(10 CHAR),
    "SORT_ORDER"       NUMBER(10, 0),
    "PROCESS_NODE_ID"  VARCHAR2(50 CHAR),
    "PROCESS_DEF_UUID" VARCHAR2(50 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
    ON TABLE BIZ_PROCESS_ITEM_DEFINITION IS '业务流程事项定义基本信息';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.CREATOR IS '创建人';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.MODIFIER IS '修改人';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.REC_VER IS '版本号';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.ITEM_DEF_NAME IS '事项定义名称';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.ITEM_DEF_ID IS '事项定义ID';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.ITEM_NAME IS '事项名称';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.ITEM_CODE IS '事项编码';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.ITEM_ID IS '事项ID，业务流程事项配置自动生成的ID';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.ITEM_TYPE IS '事项类型';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.SORT_ORDER IS '排序号';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.PROCESS_NODE_ID IS '过程节点ID';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.PROCESS_DEF_UUID IS '过程定义UUID';
