ALTER TABLE `BIZ_PROCESS_ITEM_INSTANCE`
    ADD COLUMN `ITEM_FLOW_DEF_ID` VARCHAR(50) COMMENT '事项流定义ID，事项流定义ID为事项ID';
ALTER TABLE `BIZ_PROCESS_ITEM_INSTANCE`
    ADD COLUMN `ITEM_FLOW_INST_UUID` VARCHAR(50) COMMENT '事项流实例UUID，事项流实例UUID为发起的事项实例UUID';


ALTER TABLE BIZ_NEW_ITEM_RELATION
    CHANGE ITEM_INST_UUID TARGET_ITEM_INST_UUID varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '目标事项实例UUID';
ALTER TABLE BIZ_NEW_ITEM_RELATION
    CHANGE SOURCE_BIZ_INST_UUID ITEM_FLOW_INST_UUID varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT '事项流实例UUID';


ALTER TABLE `BIZ_PROCESS_INSTANCE`
    ADD COLUMN `ENTITY_FORM_ID` VARCHAR(50) COMMENT '业务主体表单ID';

ALTER TABLE BIZ_PROCESS_ITEM_INSTANCE
    CHANGE IS_DISPENSE_ITEM IS_MULTIPLE TINYINT(1) COLLATE utf8_bin NULL COMMENT '是否多事项';