ALTER TABLE BIZ_PROCESS_ITEM_INSTANCE
    ADD ITEM_FLOW_DEF_ID VARCHAR2(50 CHAR);

ALTER TABLE BIZ_PROCESS_ITEM_INSTANCE
    ADD ITEM_FLOW_INST_UUID VARCHAR2(50 CHAR);
COMMENT
ON COLUMN "BIZ_PROCESS_ITEM_INSTANCE"."ITEM_FLOW_DEF_ID" IS '事项流定义ID，事项流定义ID为事项ID';
COMMENT
ON COLUMN "BIZ_PROCESS_ITEM_INSTANCE"."ITEM_FLOW_INST_UUID" IS '事项流实例UUID，事项流实例UUID为发起的事项实例UUID';


ALTER TABLE "BIZ_NEW_ITEM_RELATION" RENAME COLUMN "ITEM_INST_UUID" TO "TARGET_ITEM_INST_UUID";
ALTER TABLE "BIZ_NEW_ITEM_RELATION" RENAME COLUMN "SOURCE_BIZ_INST_UUID" TO "ITEM_FLOW_INST_UUID";
COMMENT
ON COLUMN "BIZ_NEW_ITEM_RELATION"."TARGET_ITEM_INST_UUID" IS '目标事项实例UUID';
COMMENT
ON COLUMN "BIZ_NEW_ITEM_RELATION"."ITEM_FLOW_INST_UUID" IS '事项流实例UUID';


ALTER TABLE BIZ_PROCESS_INSTANCE
    ADD ENTITY_FORM_ID VARCHAR2(50 CHAR);
COMMENT
ON COLUMN "BIZ_PROCESS_INSTANCE"."ENTITY_FORM_ID" IS '业务主体表单ID';



ALTER TABLE BIZ_PROCESS_ITEM_INSTANCE RENAME COLUMN IS_DISPENSE_ITEM TO IS_MULTIPLE;
COMMENT
ON COLUMN BIZ_PROCESS_ITEM_INSTANCE.IS_MULTIPLE IS '是否多事项';

