-- Create table
CREATE TABLE APP_THEME_DEFINITION
(
    "UUID"                 VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"              VARCHAR2(20 CHAR),
    "CREATE_TIME"          TIMESTAMP(6),
    "MODIFIER"             VARCHAR2(20 CHAR),
    "MODIFY_TIME"          TIMESTAMP(6),
    "REC_VER"              NUMBER(10, 0),
    "SYSTEM_UNIT_ID"       VARCHAR2(12 CHAR),
    "NAME"                 VARCHAR2(100 CHAR),
    "ID"                   VARCHAR2(50 CHAR),
    "CODE"                 VARCHAR2(20 CHAR),
    "SORT_ORDER"           NUMBER(10, 0),
    "APPLY_TO"             VARCHAR2(50 CHAR),
    "ENABLED"              NUMBER(1),
    "DEFINITION_JSON_UUID" VARCHAR2(50 CHAR),
    "REMARK"               VARCHAR2(200 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
    ON TABLE APP_THEME_DEFINITION IS '应用主题定义';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.CREATOR IS '创建人';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.MODIFIER IS '修改人';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.REC_VER IS '版本号';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.SYSTEM_UNIT_ID IS '系统单位ID';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.NAME IS '名称';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.ID IS 'ID';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.CODE IS '编号';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.SORT_ORDER IS '排序号';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.APPLY_TO IS '作用范围';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.ENABLED IS '是否启用';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.DEFINITION_JSON_UUID IS '主题定义JSON UUID';
COMMENT
    ON COLUMN APP_THEME_DEFINITION.REMARK IS '备注';


CREATE TABLE APP_THEME_DEFINITION_JSON
(
    "UUID"            VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"         VARCHAR2(20 CHAR),
    "CREATE_TIME"     TIMESTAMP(6),
    "MODIFIER"        VARCHAR2(20 CHAR),
    "MODIFY_TIME"     TIMESTAMP(6),
    "REC_VER"         NUMBER(10, 0),
    "SYSTEM_UNIT_ID"  VARCHAR2(12 CHAR),
    "DEFINITION_JSON" CLOB,
    PRIMARY KEY ("UUID")
);
COMMENT
    ON TABLE APP_THEME_DEFINITION_JSON IS '应用主题定义JSON';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_JSON.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_JSON.CREATOR IS '创建人';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_JSON.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_JSON.MODIFIER IS '修改人';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_JSON.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_JSON.REC_VER IS '版本号';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_JSON.SYSTEM_UNIT_ID IS '系统单位ID';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_JSON.DEFINITION_JSON IS '定义JSON内容';


CREATE TABLE APP_THEME_DEFINITION_HIS
(
    "UUID"            VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CREATOR"         VARCHAR2(20 CHAR),
    "CREATE_TIME"     TIMESTAMP(6),
    "MODIFIER"        VARCHAR2(20 CHAR),
    "MODIFY_TIME"     TIMESTAMP(6),
    "REC_VER"         NUMBER(10, 0),
    "SYSTEM_UNIT_ID"  VARCHAR2(12 CHAR),
    "THEME_DEF_UUID"  VARCHAR2(50 CHAR),
    "NAME"            VARCHAR2(100 CHAR),
    "ID"              VARCHAR2(50 CHAR),
    "CODE"            VARCHAR2(20 CHAR),
    "SORT_ORDER"      NUMBER(10, 0),
    "APPLY_TO"        VARCHAR2(50 CHAR),
    "ENABLED"         NUMBER(1),
    "DEFINITION_JSON" CLOB,
    "REMARK"          VARCHAR2(200 CHAR),
    PRIMARY KEY ("UUID")
);
COMMENT
    ON TABLE APP_THEME_DEFINITION_HIS IS '应用主题定义历史记录';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.CREATOR IS '创建人';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.MODIFIER IS '修改人';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.REC_VER IS '版本号';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.SYSTEM_UNIT_ID IS '系统单位ID';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.THEME_DEF_UUID IS '主题定义UUID';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.NAME IS '名称';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.ID IS 'ID';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.CODE IS '编号';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.SORT_ORDER IS '排序号';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.APPLY_TO IS '作用范围';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.ENABLED IS '是否启用';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.DEFINITION_JSON IS '主题定义JSON';
COMMENT
    ON COLUMN APP_THEME_DEFINITION_HIS.REMARK IS '备注';
