CREATE TABLE BIZ_PROCESS_ASSEMBLE
(
    "UUID"             NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"      TIMESTAMP(6),
    "CREATOR"          VARCHAR2(50 CHAR),
    "MODIFIER"         VARCHAR2(50 CHAR),
    "MODIFY_TIME"      TIMESTAMP(6),
    "REC_VER"          NUMBER(10, 0),
    "SYSTEM"           VARCHAR2(64),
    "TENANT"           VARCHAR2(64),
    "PROCESS_DEF_UUID" VARCHAR2(50),
    "DEFINITION_JSON"  CLOB,
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE BIZ_PROCESS_ASSEMBLE IS '业务流程组装信息表';
COMMENT
    ON COLUMN BIZ_PROCESS_ASSEMBLE.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN BIZ_PROCESS_ASSEMBLE.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN BIZ_PROCESS_ASSEMBLE.CREATOR IS '创建人';
COMMENT
    ON COLUMN BIZ_PROCESS_ASSEMBLE.MODIFIER IS '修改人';
COMMENT
    ON COLUMN BIZ_PROCESS_ASSEMBLE.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN BIZ_PROCESS_ASSEMBLE.REC_VER IS '版本号';
COMMENT
    ON COLUMN BIZ_PROCESS_ASSEMBLE.SYSTEM IS '归属系统';
COMMENT
    ON COLUMN BIZ_PROCESS_ASSEMBLE.TENANT IS '归属租户';
COMMENT
    ON COLUMN BIZ_PROCESS_ASSEMBLE.PROCESS_DEF_UUID IS '业务流程定义UUID';
COMMENT
    ON COLUMN BIZ_PROCESS_ASSEMBLE.DEFINITION_JSON IS '组装定义JSON信息';
