CREATE TABLE BIZ_PROCESS_ENTITY_TIMER
(
    "UUID"              NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"       TIMESTAMP(6),
    "CREATOR"           VARCHAR2(50 CHAR),
    "MODIFIER"          VARCHAR2(50 CHAR),
    "MODIFY_TIME"       TIMESTAMP(6),
    "REC_VER"           NUMBER(10, 0),
    "NAME"              VARCHAR2(64),
    "ID"                VARCHAR2(50),
    "ENTITY_ID"         VARCHAR2(100),
    "STATE_FIELD"       VARCHAR2(30),
    "STATE_CODE"        VARCHAR2(100),
    "TIMER_UUID"        VARCHAR2(50 CHAR),
    "TIMER_STATE"       NUMBER(1),
    "TIMING_STATE"      NUMBER(1),
    "DUE_TIME"          TIMESTAMP(6),
    "OVER_DUE_TIME"     TIMESTAMP(6),
    "TOTAL_TIME"        NUMBER(10, 1),
    "PROCESS_INST_UUID" VARCHAR2(50 CHAR),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE BIZ_PROCESS_ENTITY_TIMER IS '业务主体计时器';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.CREATOR IS '创建人';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.MODIFIER IS '修改人';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.REC_VER IS '版本号';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.NAME IS '计时器名称';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.ID IS '计时器ID';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.ENTITY_ID IS '业务主体ID';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.STATE_FIELD IS '状态字段';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.STATE_CODE IS '状态代码';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.TIMER_UUID IS '计时器UUID';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.TIMER_STATE IS '计时器状态，0未启动、1计时中、2暂停、3结束';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.TIMING_STATE IS '计时状态， 0正常、1预警、2到期、3逾期';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.DUE_TIME IS '到期时间';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.OVER_DUE_TIME IS '逾期时间';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.TOTAL_TIME IS '总用时';
COMMENT
    ON COLUMN BIZ_PROCESS_ENTITY_TIMER.PROCESS_INST_UUID IS '业务流程实例UUID';

create index BIZ_PET_BATCH_INDEX on BIZ_PROCESS_ENTITY_TIMER (ENTITY_ID, PROCESS_INST_UUID);
