CREATE TABLE BIZ_FORM_STATE_HISTORY
(
    "UUID"                   NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"            TIMESTAMP(6),
    "CREATOR"                VARCHAR2(50 CHAR),
    "MODIFIER"               VARCHAR2(50 CHAR),
    "MODIFY_TIME"            TIMESTAMP(6),
    "REC_VER"                NUMBER(10, 0),
    "FORM_UUID"              VARCHAR2(50 CHAR),
    "DATA_UUID"              VARCHAR2(50 CHAR),
    "TYPE"                   NUMBER(10),
    "STATE_FIELD"            VARCHAR2(30 CHAR),
    "OLD_STATE"              CLOB,
    "NEW_STATE"              CLOB,
    "TRIGGER_TYPE"           VARCHAR2(30),
    "TRIGGER_INFO"           VARCHAR2(200),
    "ENTITY_ID"              VARCHAR2(100),
    "ITEM_INST_UUID"         VARCHAR2(50 CHAR),
    "PROCESS_NODE_INST_UUID" VARCHAR2(50 CHAR),
    "PROCESS_INST_UUID"      VARCHAR2(50 CHAR),
    PRIMARY KEY ("UUID")
);

COMMENT
ON TABLE BIZ_FORM_STATE_HISTORY IS '业务流程表单状态历史记录';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.UUID IS 'UUID，系统字段';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.CREATE_TIME IS '创建时间';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.CREATOR IS '创建人';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.MODIFIER IS '修改人';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.MODIFY_TIME IS '修改时间';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.REC_VER IS '版本号';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.FORM_UUID IS '计时器名称';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.DATA_UUID IS '计时器ID';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.TYPE IS '业务主体ID';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.STATE_FIELD IS '状态字段';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.OLD_STATE IS '旧状态值';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.NEW_STATE IS '新状态值';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.TRIGGER_TYPE IS '变更触发类型';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.TRIGGER_INFO IS '变更信息';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.ENTITY_ID IS '业务主体ID';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.ITEM_INST_UUID IS '事项实例UUID，类型为事项时有值';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.PROCESS_NODE_INST_UUID IS '过程节点实例UUID，类型为过程节点时有值';
COMMENT
ON COLUMN BIZ_FORM_STATE_HISTORY.PROCESS_INST_UUID IS '业务流程实例UUID';

