alter table BIZ_PROCESS_NODE_DEFINITION
    add REF_PROCESS_DEF_UUID varchar2(50 char);
alter table BIZ_PROCESS_ITEM_DEFINITION
    add REF_PROCESS_DEF_UUID varchar2(50 char);

COMMENT
    ON COLUMN BIZ_PROCESS_NODE_DEFINITION.REF_PROCESS_DEF_UUID IS '引用的过程定义UUID';
COMMENT
    ON COLUMN BIZ_PROCESS_ITEM_DEFINITION.REF_PROCESS_DEF_UUID IS '引用的过程定义UUID';
