ALTER TABLE "USR_PT_7_0_DEV"."USER_INFO" 
ADD ("USER_ID" VARCHAR2(32))
ADD ("AVATAR" VARCHAR2(64));

COMMENT ON COLUMN "USR_PT_7_0_DEV"."USER_INFO"."USER_ID" IS '用户ID';

COMMENT ON COLUMN "USR_PT_7_0_DEV"."USER_INFO"."AVATAR" IS '头像';


ALTER TABLE "USR_PT_7_0_DEV"."USER_ACCOUNT" 
ADD ("TYPE" NUMBER(1,0) DEFAULT 3)
ADD ("EXPIRED_TIME" TIMESTAMP)
ADD ("PASSWORD_EXPIRED_TIME" TIMESTAMP)
ADD ("EMAIL" VARCHAR2(64))
ADD ("TEL" VARCHAR2(16));

COMMENT ON COLUMN "USR_PT_7_0_DEV"."USER_ACCOUNT"."TYPE" IS '0 平台管理员 1 租户管理员  2 开发运维 3 业务用户';


ALTER TABLE "USR_PT_7_0_DEV"."USER_INFO" 
ADD ("EN_NAME" VARCHAR2(120));


 
ALTER TABLE "USR_PT_7_0_DEV"."USER_INFO" 
ADD ("GENDER" NUMBER(1));

ALTER TABLE "USR_PT_7_0_DEV"."USER_INFO" 
ADD ("REMARK" VARCHAR2(500));


ALTER TABLE "USR_PT_7_0_DEV"."USER_INFO" 
ADD ("USER_NO" VARCHAR(64));

 
COMMENT ON COLUMN "USR_PT_7_0_DEV"."USER_INFO"."USER_NO" IS '编号';


ALTER TABLE "USR_PT_7_0_DEV"."USER_INFO" 
ADD ("PIN_YIN" VARCHAR2(255));


ALTER TABLE "USR_PT_7_0_DEV"."ORG_DUTY_SEQ" 
ADD ("TENANT" VARCHAR2(64))
ADD ("SYSTEM" VARCHAR2(64));

COMMENT ON COLUMN "USR_PT_7_0_DEV"."ORG_DUTY_SEQ"."TENANT" IS '归属租户';

COMMENT ON COLUMN "USR_PT_7_0_DEV"."ORG_DUTY_SEQ"."SYSTEM" IS '归属系统';


ALTER TABLE "USR_PT_7_0_DEV"."MULTI_ORG_DUTY" 
ADD ("TENANT" VARCHAR2(64))
ADD ("SYSTEM" VARCHAR2(64));

COMMENT ON COLUMN "USR_PT_7_0_DEV"."MULTI_ORG_DUTY"."TENANT" IS '归属租户';

COMMENT ON COLUMN "USR_PT_7_0_DEV"."MULTI_ORG_DUTY"."SYSTEM" IS '归属系统';


ALTER TABLE "USR_PT_7_0_DEV"."MULTI_ORG_JOB_DUTY" 
ADD ("ORG_VERSION_UUID" NUMBER(19,0));

COMMENT ON COLUMN "USR_PT_7_0_DEV"."MULTI_ORG_JOB_DUTY"."ORG_VERSION_UUID" IS '组织版本UUID'
