 
/*==============================================================*/
/* Table: USER_ACCT_PASSWORD_RULE                               */
/*==============================================================*/
create table USER_ACCT_PASSWORD_RULE 
(
   UUID                 NUMBER(20)           not null,
   ATTR_KEY             VARCHAR2(120),
   ATTR_VAL             VARCHAR2(32),
   CREATE_TIME          TIMESTAMP,
   CREATOR              VARCHAR2(64),
   MODIFIER             VARCHAR2(64),
   MODIFY_TIME          TIMESTAMP,
   REMARK               VARCHAR2(300 CHAR),
   REC_VER              FLOAT(3)             default 1,
   constraint PK_USER_ACCT_PASSWORD_RULE primary key (UUID)
);

comment on table USER_ACCT_PASSWORD_RULE is
'账号密码规则';



ALTER TABLE USER_ACCOUNT ADD MODIFY_PASSWORD_TIME TIMESTAMP(6);
ALTER TABLE USER_ACCOUNT ADD LOCK_CAUSE NUMBER(1);
ALTER TABLE USER_ACCOUNT ADD PASSWORD_MODIFIED_BY_USER NUMBER(1) DEFAULT 0;
ALTER TABLE USER_ACCOUNT ADD LOCK_TIME TIMESTAMP(6);
ALTER TABLE USER_ACCOUNT ADD UNLOCK_TIME TIMESTAMP(6);
UPDATE USER_ACCOUNT SET PASSWORD_ERROR_NUM = 0 WHERE PASSWORD_ERROR_NUM IS NULL;
ALTER TABLE USER_ACCOUNT MODIFY PASSWORD_ERROR_NUM DEFAULT 0 NOT NULL;

 COMMENT ON COLUMN USER_ACCOUNT.MODIFY_PASSWORD_TIME
  IS '修改密码时间';
COMMENT ON COLUMN USER_ACCOUNT.LOCK_CAUSE
  IS '被锁定原因';
COMMENT ON COLUMN USER_ACCOUNT.PASSWORD_MODIFIED_BY_USER
  IS '是否账号归属者修改的密码';
ALTER TABLE USER_ACCOUNT ADD PASSWORD_ERROR_NUM NUMBER(3);
COMMENT ON COLUMN USER_ACCOUNT.LOCK_TIME
  IS '锁定时间';
COMMENT ON COLUMN USER_ACCOUNT.UNLOCK_TIME
  IS '解锁时间';
COMMENT ON COLUMN USER_ACCOUNT.PASSWORD_ERROR_NUM
  IS '密码输入错误次数';
