alter table ORG_ELEMENT modify name VARCHAR2(120 CHAR);
alter table ORG_ELEMENT modify short_name VARCHAR2(64 CHAR);
alter table ORG_ELEMENT modify remark VARCHAR2(300 CHAR);
alter table ORG_ELEMENT modify code VARCHAR2(64 CHAR);

DELETE FROM ORG_SETTING WHERE CATEGORY ='USER_UNIQUE_RULE'AND SYSTEM= 'PRD_PT' AND UUID > 1000;
DELETE FROM ORG_SETTING WHERE ATTR_KEY NOT LIKE '%_MOUNT_SET' AND CATEGORY IS NULL AND  SYSTEM='PRD_PT'
UPDATE  ORG_SETTING SET SYSTEM ='PRD_PT' , TENANT = 'T001' WHERE CATEGORY ='USER_UNIQUE_RULE'AND SYSTEM IS NULL;


update org_setting set enable = 1 where attr_key='ORG_CROSS_DATA_VISIBLE';