CREATE TABLE "APP_FUNCTION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "APP_FUNCTION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "APP_FUNCTION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "APP_FUNCTION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "APP_FUNCTION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "APP_FUNCTION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "APP_FUNCTION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "APP_FUNCTION"."CODE" IS '编号';
   COMMENT ON COLUMN "APP_FUNCTION"."ID" IS 'ID';
   COMMENT ON COLUMN "APP_FUNCTION"."NAME" IS '名称';
   COMMENT ON COLUMN "APP_FUNCTION"."TYPE" IS '类型';
   COMMENT ON COLUMN "APP_FUNCTION"."REMARK" IS '备注';
   


   