CREATE TABLE "AUDIT_USER_ATTEMPTS" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"LOGIN_NAME" VARCHAR2(255 CHAR), 
	"ATTEMPTS" NUMBER(10,0),
	"LATEST_ATTEMPT_TIME" TIMESTAMP (6)
   );
   
   COMMENT ON COLUMN "AUDIT_USER_ATTEMPTS"."UUID" IS 'UUID，系统字段';
 
   COMMENT ON COLUMN "AUDIT_USER_ATTEMPTS"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "AUDIT_USER_ATTEMPTS"."CREATOR" IS '创建人';
 
   COMMENT ON COLUMN "AUDIT_USER_ATTEMPTS"."MODIFIER" IS '修改人';
 
   COMMENT ON COLUMN "AUDIT_USER_ATTEMPTS"."MODIFY_TIME" IS '修改时间';
 
   COMMENT ON COLUMN "AUDIT_USER_ATTEMPTS"."REC_VER" IS '版本号';
 
   COMMENT ON COLUMN "AUDIT_USER_ATTEMPTS"."LOGIN_NAME" IS '登录名';
 
   COMMENT ON COLUMN "AUDIT_USER_ATTEMPTS"."ATTEMPTS" IS '尝试次数';
 
   COMMENT ON COLUMN "AUDIT_USER_ATTEMPTS"."LATEST_ATTEMPT_TIME" IS '最新尝试时间';
   