CREATE TABLE "DMS_DATA_VERSION" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"DATA_DEF_ID" VARCHAR2(255 CHAR), 
	"DATA_DEF_UUID" VARCHAR2(255 CHAR), 
	"DATA_TYPE" VARCHAR2(255 CHAR), 
	"DATA_UUID" VARCHAR2(255 CHAR), 
	"INIT_DATA_UUID" VARCHAR2(255 CHAR), 
	"INIT_DEF_ID" VARCHAR2(255 CHAR), 
	"INIT_DEF_UUID" VARCHAR2(255 CHAR), 
	"SOURCE_DATA_UUID" VARCHAR2(255 CHAR), 
	"SOURCE_DEF_ID" VARCHAR2(255 CHAR), 
	"SOURCE_DEF_UUID" VARCHAR2(255 CHAR), 
	"VERSION" VARCHAR2(255 CHAR), 
	"IS_LATEST_VERSION" NUMBER(1,0), 
	 PRIMARY KEY ("UUID")
   );
   COMMENT ON COLUMN "DMS_DATA_VERSION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."DATA_DEF_ID" IS '当前版本数据定义ID';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."DATA_DEF_UUID" IS '当前版本数据定义UUID';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."DATA_TYPE" IS '版本数据类型';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."DATA_UUID" IS '当前版本数据UUID';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."INIT_DATA_UUID" IS '初始化版本的数据UUID';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."INIT_DEF_ID" IS '初始化版本的定义ID';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."INIT_DEF_UUID" IS '初始化版本的定义UUID';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."SOURCE_DATA_UUID" IS '原版本版本数据UUID';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."SOURCE_DEF_ID" IS '原版本数据定义ID';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."SOURCE_DEF_UUID" IS '原版本数据定义UUID';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."VERSION" IS '当前版本号';
   COMMENT ON COLUMN "DMS_DATA_VERSION"."IS_LATEST_VERSION" IS '是否最新的版本';