CREATE TABLE "CD_SCRIPT_DEFINITION" 
   (  "UUID" VARCHAR2(64) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "REC_VER" NUMBER(10,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "CONTENT" CLOB, 
  "REMARK" VARCHAR2(500 CHAR), 
  "SYSTEM_UNIT_ID" VARCHAR2(12) NOT NULL ENABLE, 
   PRIMARY KEY ("UUID")
   ) ;
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."UUID" IS 'UUID，系统字段';
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."CREATE_TIME" IS '创建时间';
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."CREATOR" IS '创建人';
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."MODIFY_TIME" IS '修改时间';
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."MODIFIER" IS '修改人';
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."REC_VER" IS '版本号';
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."NAME" IS '名称';
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."ID" IS 'ID';
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."CODE" IS '编号';
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."TYPE" IS '类型';
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."CONTENT" IS '内容';
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."REMARK" IS '备注';
   COMMENT ON COLUMN "CD_SCRIPT_DEFINITION"."SYSTEM_UNIT_ID" IS '归属系统单位ID';
   COMMENT ON TABLE "CD_SCRIPT_DEFINITION"  IS '脚本定义';