ALTER TABLE "AUDIT_ROLE"
ADD ( "SYSTEM_UNIT_ID" VARCHAR2(12)  NULL  ) ;

UPDATE AUDIT_ROLE set SYSTEM_UNIT_ID = 'S0000000000';



ALTER TABLE "AUDIT_ROLE"
MODIFY ( "SYSTEM_UNIT_ID" VARCHAR2(12)  NOT NULL  ) ;

