ALTER TABLE "AUDIT_PRIVILEGE"
ADD ( "SYSTEM_UNIT_ID" VARCHAR2(12)  NULL  ) ;

UPDATE AUDIT_PRIVILEGE set SYSTEM_UNIT_ID = 'S0000000000';



ALTER TABLE "AUDIT_PRIVILEGE"
MODIFY ( "SYSTEM_UNIT_ID" VARCHAR2(12)  NOT NULL  ) ;

