ALTER TABLE "CD_DATA_STORE_DEFINITION"
ADD ( "SYSTEM_UNIT_ID" VARCHAR2(12)  NULL  ) ;

UPDATE CD_DATA_STORE_DEFINITION set SYSTEM_UNIT_ID = 'S0000000000';



ALTER TABLE "CD_DATA_STORE_DEFINITION"
MODIFY ( "SYSTEM_UNIT_ID" VARCHAR2(12)  NOT NULL  ) ;

