CREATE TABLE "MULTI_ORG_SYSTEM_UNIT_MEMBER" (
"UUID" VARCHAR2(255 CHAR) NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"CREATOR" VARCHAR2(255 CHAR) NULL ,
"MODIFIER" VARCHAR2(255 CHAR) NULL ,
"MODIFY_TIME" TIMESTAMP(6)  NULL ,
"REC_VER" NUMBER(10) NULL ,
"SYSTEM_UNIT_ID" VARCHAR2(12 BYTE) NULL ,
"MEMBER_UNIT_ID" VARCHAR2(12 BYTE) DEFAULT 0  NULL 
)
NOLOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "MULTI_ORG_SYSTEM_UNIT_MEMBER"."SYSTEM_UNIT_ID" IS '组ID';
COMMENT ON COLUMN "MULTI_ORG_SYSTEM_UNIT_MEMBER"."MEMBER_UNIT_ID" IS '组成员对象的ID';

-- ----------------------------
-- Indexes structure for table MULTI_ORG_SYSTEM_UNIT_MEMBER
-- ----------------------------
CREATE INDEX "idx_unitMember_unitId"
ON "MULTI_ORG_SYSTEM_UNIT_MEMBER" ("SYSTEM_UNIT_ID" ASC)
LOGGING
VISIBLE;