CREATE TABLE "TASK_FIRED_JOB_DETAILS" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"FIRED_TYPE" NUMBER(10,0), 
	"JOB_CLASS_NAME" VARCHAR2(255 CHAR), 
	"CONTENT" BLOB, 
	"SYSTEM_UNIT_ID" VARCHAR2(12), 
	 PRIMARY KEY ("UUID") 
   )  ;
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS"."UUID" IS 'UUID，系统字段';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS"."CREATOR" IS '创建人';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS"."MODIFIER" IS '修改人';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS"."MODIFY_TIME" IS '修改时间';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS"."REC_VER" IS '版本号';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS"."NAME" IS '任务名称';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS"."TYPE" IS '任务类型：timing定时、temporary临时';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS"."FIRED_TYPE" IS '触发类型';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS"."JOB_CLASS_NAME" IS '任务类名';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS"."CONTENT" IS 'JobDetail序列化内容';

   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS"."SYSTEM_UNIT_ID" IS '归属系统单位';

   
   
CREATE TABLE "TASK_FIRED_JOB_DETAILS_HIS" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"FIRED_TYPE" NUMBER(10,0), 
	"JOB_CLASS_NAME" VARCHAR2(255 CHAR), 
	"CONTENT" BLOB, 
	"RESULT" NUMBER(10,0), 
	"RESULT_MSG" VARCHAR2(255 CHAR), 
	"SYSTEM_UNIT_ID" VARCHAR2(12), 
	 PRIMARY KEY ("UUID")
   ) ;
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."UUID" IS 'UUID，系统字段';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."CREATOR" IS '创建人';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."MODIFIER" IS '修改人';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."MODIFY_TIME" IS '修改时间';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."REC_VER" IS '版本号';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."NAME" IS '任务名称';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."TYPE" IS '任务类型：timing定时、temporary临时';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."FIRED_TYPE" IS '触发类型';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."JOB_CLASS_NAME" IS '任务类名';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."CONTENT" IS 'JobDetail序列化内容';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."RESULT" IS '调度结果，1成功，0失败';
 
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."RESULT_MSG" IS '调度结果信息';
   
   COMMENT ON COLUMN "TASK_FIRED_JOB_DETAILS_HIS"."SYSTEM_UNIT_ID" IS '归属系统单位';
    
    
   