CREATE TABLE  "CD_DATA_IMPORT_LOG" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"DATA_UUID" VARCHAR2(255 CHAR), 
	"DATA_NAME" VARCHAR2(255 CHAR), 
	"DATA_TYPE" VARCHAR2(255 CHAR), 
	"LOGIN_NAME" VARCHAR2(255 CHAR), 
	"USER_NAME" VARCHAR2(255 CHAR), 
	"DEPARTMENT_JOB" VARCHAR2(255 CHAR), 
	"LOG_TIME" TIMESTAMP (6), 
	"CLIENT_IP" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("UUID") 
   ) ; 
   COMMENT ON COLUMN  "CD_DATA_IMPORT_LOG"."DATA_UUID" IS '数据UUID';
   COMMENT ON COLUMN  "CD_DATA_IMPORT_LOG"."DATA_NAME" IS '数据名称';
   COMMENT ON COLUMN  "CD_DATA_IMPORT_LOG"."DATA_TYPE" IS '数据类型';
   COMMENT ON COLUMN  "CD_DATA_IMPORT_LOG"."LOGIN_NAME" IS '登录名';
   COMMENT ON COLUMN  "CD_DATA_IMPORT_LOG"."USER_NAME" IS '用户名';
   COMMENT ON COLUMN  "CD_DATA_IMPORT_LOG"."DEPARTMENT_JOB" IS '部门职位';
   COMMENT ON COLUMN  "CD_DATA_IMPORT_LOG"."LOG_TIME" IS '导入时间';
   COMMENT ON COLUMN  "CD_DATA_IMPORT_LOG"."CLIENT_IP" IS '导入主机IP';
   
   
-- Create/Recreate indexes 
create index IDX_CDIL_DUT on CD_DATA_IMPORT_LOG (data_uuid, data_type);
