-- Create table APP_COLOR_SETTING
create table APP_COLOR_SETTING
(
  "UUID" VARCHAR2(255 CHAR) NOT NULL,
  "CREATOR" VARCHAR2(255 CHAR),
  "CREATE_TIME" TIMESTAMP(6),
  "MODIFIER" VARCHAR2(255 CHAR),
  "MODIFY_TIME" TIMESTAMP(6),
  "REC_VER" NUMBER(10,0),
  "SYSTEM_UNIT_ID" VARCHAR2(12 BYTE),
  "ID" VARCHAR2(255 CHAR),
  "NAME" VARCHAR2(255 BYTE),
  "COLOR" VARCHAR2(10 BYTE),
  "MODULE_CODE" VARCHAR2(40 BYTE),
  "TYPE" VARCHAR2(40 BYTE)
);
-- Add comments to the columns
COMMENT ON COLUMN "APP_COLOR_SETTING"."ID" IS 'id';
COMMENT ON COLUMN "APP_COLOR_SETTING"."NAME" IS '名称';
COMMENT ON COLUMN "APP_COLOR_SETTING"."COLOR" IS '颜色';
COMMENT ON COLUMN "APP_COLOR_SETTING"."MODULE_CODE" IS '模块编码';
COMMENT ON COLUMN "APP_COLOR_SETTING"."TYPE" IS '分类/类型';
alter table APP_COLOR_SETTING
  add primary key (UUID);

