-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
-- CONNECT SYSTEM
CREATE TABLE "QRTZ_CRON_TRIGGERS" 
   (	"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"CRON_EXPRESSION" VARCHAR2(120 BYTE) NOT NULL ENABLE, 
	"TIME_ZONE_ID" VARCHAR2(80 BYTE)
   ) ;
CREATE TABLE "QRTZ_JOB_LISTENERS" 
   (	"JOB_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"JOB_GROUP" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"JOB_LISTENER" VARCHAR2(200 BYTE) NOT NULL ENABLE
   ) ;
CREATE TABLE "QRTZ_PAUSED_TRIGGER_GRPS" 
   (	"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ENABLE
   ) ;
CREATE TABLE "QRTZ_TRIGGER_LISTENERS" 
   (	"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"TRIGGER_LISTENER" VARCHAR2(200 BYTE) NOT NULL ENABLE
   ) ;
CREATE TABLE "MT_ADMIN" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"ENABLED" NUMBER(1,0) NOT NULL ENABLE, 
	"LOGIN_NAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MT_DATABASE_CONFIG" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"CODE" VARCHAR2(255 CHAR), 
	"DATABASE_NAME" VARCHAR2(255 CHAR), 
	"HOST" VARCHAR2(255 CHAR), 
	"LOGIN_NAME" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"PORT" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"TYPE_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MT_ID_GENERATOR" 
   (	"ENTITY_CLASS_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"POINTER" NUMBER(19,0)
   ) ;
CREATE TABLE "MT_PINYIN" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"ENTITY_UUID" VARCHAR2(255 CHAR), 
	"PINYIN" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MT_TENANT" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"ACCOUNT" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(255 CHAR), 
	"BUSINESS_DEADLINE" VARCHAR2(255 CHAR), 
	"BUSINESS_DEADLINE_CHECK" NUMBER(1,0), 
	"BUSINESS_ID_CARD_NAME" VARCHAR2(255 CHAR), 
	"BUSINESS_ID_CARD_NUM" VARCHAR2(255 CHAR), 
	"BUSINESS_LICENSE_ADDRESS" VARCHAR2(255 CHAR), 
	"BUSINESS_LICENSE_NUM" VARCHAR2(255 CHAR), 
	"BUSINESS_LICENSE_PIC" VARCHAR2(255 CHAR), 
	"BUSINESS_SCOPE" VARCHAR2(255 CHAR), 
	"CODE" VARCHAR2(255 CHAR), 
	"DATABASE_CONFIG_UUID" VARCHAR2(255 CHAR), 
	"DEPATERMENT_TYPE" VARCHAR2(255 CHAR), 
	"EMAIL" VARCHAR2(255 CHAR), 
	"ID" VARCHAR2(255 CHAR), 
	"INSTITUTIONAL_CODE" VARCHAR2(255 CHAR), 
	"JDBC_DATABASE_NAME" VARCHAR2(255 CHAR), 
	"JDBC_PASSWORD" VARCHAR2(255 CHAR), 
	"JDBC_PORT" VARCHAR2(255 CHAR), 
	"JDBC_SERVER" VARCHAR2(255 CHAR), 
	"JDBC_TYPE" VARCHAR2(255 CHAR), 
	"JDBC_USERNAME" VARCHAR2(255 CHAR), 
	"MOBILE_NUM" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"POSITION" VARCHAR2(255 CHAR), 
	"POSTCODE" VARCHAR2(255 CHAR), 
	"REGISTER_FIGURE" VARCHAR2(255 CHAR), 
	"REMARK" VARCHAR2(255 CHAR), 
	"STATUS" NUMBER(10,0)
   ) ;
CREATE TABLE "QRTZ_FIRED_TRIGGERS" 
   (	"ENTRY_ID" VARCHAR2(95 BYTE) NOT NULL ENABLE, 
	"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"IS_VOLATILE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"INSTANCE_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"FIRED_TIME" NUMBER(13,0) NOT NULL ENABLE, 
	"PRIORITY" NUMBER(13,0) NOT NULL ENABLE, 
	"STATE" VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"JOB_NAME" VARCHAR2(200 BYTE), 
	"JOB_GROUP" VARCHAR2(200 BYTE), 
	"IS_STATEFUL" VARCHAR2(1 BYTE), 
	"REQUESTS_RECOVERY" VARCHAR2(1 BYTE)
   ) ;
CREATE TABLE "QRTZ_LOCKS" 
   (	"LOCK_NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE
   ) ;
CREATE TABLE "QRTZ_SCHEDULER_STATE" 
   (	"INSTANCE_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"LAST_CHECKIN_TIME" NUMBER(13,0) NOT NULL ENABLE, 
	"CHECKIN_INTERVAL" NUMBER(13,0) NOT NULL ENABLE
   ) ;
CREATE TABLE "QRTZ_SIMPLE_TRIGGERS" 
   (	"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"REPEAT_COUNT" NUMBER(7,0) NOT NULL ENABLE, 
	"REPEAT_INTERVAL" NUMBER(12,0) NOT NULL ENABLE, 
	"TIMES_TRIGGERED" NUMBER(10,0) NOT NULL ENABLE
   ) ;
CREATE TABLE "MT_NOTICE" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"TENANT_ID" VARCHAR2(255 CHAR), 
	"AUTHOR" VARCHAR2(255 CHAR), 
	"TOP_STATE" VARCHAR2(255 CHAR), 
	"DATA_UUID" VARCHAR2(255 CHAR), 
	"PUBLISH_TIME" TIMESTAMP (6), 
	"PUBLISHER" VARCHAR2(4000 CHAR), 
	"PUBLISHER_NAME" VARCHAR2(255 CHAR), 
	"READER" VARCHAR2(4000 CHAR), 
	"READER_NAME" VARCHAR2(4000 CHAR), 
	"CATEGORY_NAME" VARCHAR2(255 CHAR), 
	"CATEGORY_CODE" VARCHAR2(255 CHAR), 
	"TITLE_COLOR" VARCHAR2(255 CHAR), 
	"TITLE" VARCHAR2(255 CHAR), 
	"RETAIN_TIME" TIMESTAMP (6)
   ) ;
CREATE TABLE "MT_TENANT_USER" 
   (	"UUID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 BYTE), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"MODIFIER" VARCHAR2(255 BYTE), 
	"REC_VER" VARCHAR2(255 BYTE), 
	"TENANT_UUID" VARCHAR2(255 BYTE), 
	"TENANT_ID" VARCHAR2(255 BYTE), 
	"USER_UUID" VARCHAR2(255 BYTE), 
	"USER_ID" VARCHAR2(255 BYTE), 
	"USER_LOGIN_NAME" VARCHAR2(255 BYTE), 
	"USER_NAME" VARCHAR2(255 BYTE)
   ) ;
CREATE TABLE "MT_TENANT_GZ_USER" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"GZ_TENANT_ID" VARCHAR2(255 CHAR), 
	"GZ_TENANT_NAME" VARCHAR2(255 CHAR), 
	"USER_ID" VARCHAR2(255 CHAR), 
	"USER_LOGIN_NAME" VARCHAR2(255 CHAR), 
	"USER_NAME" VARCHAR2(255 CHAR), 
	"ZZ_TENANT_ID" VARCHAR2(255 CHAR), 
	"ZZ_TENANT_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MSG_SHORT_MESSAGE" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"BODY" VARCHAR2(255 CHAR), 
	"BUSINESS_LOGIC_ID" VARCHAR2(255 CHAR), 
	"IS_RE_SEND" NUMBER(1,0), 
	"ISREAD" NUMBER(1,0), 
	"REC_ID" NUMBER(10,0), 
	"REC_MSG" VARCHAR2(255 CHAR), 
	"RECEIVED" VARCHAR2(255 CHAR), 
	"RECEIVED_TIME" TIMESTAMP (6), 
	"RECIPIENT_MOBILE_PHONE" VARCHAR2(255 CHAR), 
	"RECIPIENT_NAME" VARCHAR2(255 CHAR), 
	"SEND" VARCHAR2(255 CHAR), 
	"SEND_MOBILE_PHONE" VARCHAR2(255 CHAR), 
	"SEND_STATUS" NUMBER(10,0), 
	"SEND_TIME" TIMESTAMP (6), 
	"SENDER_NAME" VARCHAR2(255 CHAR), 
	"SMID" NUMBER(19,0), 
	"TYPE" NUMBER(10,0), 
	"BUSINESSKEY1" VARCHAR2(255 CHAR), 
	"BUSINESSKEY2" VARCHAR2(255 CHAR), 
	"BUSINESSKEY3" VARCHAR2(255 CHAR), 
	"RESERVED_TEXT1" VARCHAR2(255 CHAR), 
	"RESERVED_TEXT2" VARCHAR2(255 CHAR), 
	"RESERVED_TEXT3" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MSG_MAS_CONFIG" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"API_CODE" VARCHAR2(255 CHAR), 
	"DB_NAME" VARCHAR2(255 CHAR), 
	"IM_IP" VARCHAR2(255 CHAR), 
	"IS_OPEN" NUMBER(1,0), 
	"LOGIN_NAME" VARCHAR2(255 CHAR), 
	"LOGIN_PASSWORD" VARCHAR2(255 CHAR), 
	"SEND_LIMIT" NUMBER(10,0)
   ) ;
CREATE TABLE "CD_READ_MARKER" 
   (	"ENTITY_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"READ_TIME" TIMESTAMP (6), 
	"UUID" VARCHAR2(255 CHAR), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"CREATE_TIME" TIMESTAMP (6), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0)
   ) ;
CREATE TABLE "EXCHANGE_LOG" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"BATCH_ID" VARCHAR2(255 CHAR), 
	"DATA_ID" VARCHAR2(255 CHAR), 
	"MSG" VARCHAR2(255 CHAR), 
	"NODE" NUMBER(10,0), 
	"STATUS" NUMBER(1,0), 
	"UNIT_ID" VARCHAR2(255 CHAR), 
	"FROM_UNIT_ID" VARCHAR2(255 CHAR), 
	"TO_UNIT_ID" VARCHAR2(255 CHAR), 
	"CODE" NUMBER(1,0), 
	"DATA_REC_VER" NUMBER(10,0)
   ) ;
CREATE TABLE "REPO_FILE" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CERTIFICATE" VARCHAR2(255 CHAR), 
	"CONTENT_TYPE" VARCHAR2(255 CHAR), 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"DIGEST_ALGORITHM" VARCHAR2(255 CHAR), 
	"DIGEST_VALUE" VARCHAR2(255 CHAR), 
	"FILE_NAME" VARCHAR2(255 CHAR), 
	"FILE_SIZE" NUMBER(19,0), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"PHYSICAL_FILE_ID" VARCHAR2(255 CHAR), 
	"REC_VER" NUMBER(10,0), 
	"SIGNATURE_VALUE" VARCHAR2(255 CHAR), 
	"SWF_UUID" VARCHAR2(255 CHAR), 
	"DB_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "REPO_FOLDER" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"REMARK" VARCHAR2(255 CHAR), 
	"DB_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "REPO_FILE_IN_FOLDER" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"FILE_UUID" VARCHAR2(255 CHAR), 
	"PURPOSE" VARCHAR2(255 CHAR), 
	"FOLDER_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "WF_GZ_DATA_SYNC" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"SOURCE_FLOW_INST_UUID" VARCHAR2(255 CHAR), 
	"TARGET_FLOW_INST_UUID" VARCHAR2(255 CHAR), 
	"TASK_INST_UUID" VARCHAR2(255 CHAR), 
	"USER_ID" VARCHAR2(255 CHAR), 
	"SOURCE_TENANT_ID" VARCHAR2(255 CHAR), 
	"TARGET_TENANT_ID" VARCHAR2(255 CHAR), 
	"SUSPENSION_STATE" NUMBER(10,0)
   ) ;
CREATE TABLE "WF_GZ_DATA_SYNC_HIS" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"SOURCE_FLOW_INST_UUID" VARCHAR2(255 CHAR), 
	"TARGET_FLOW_INST_UUID" VARCHAR2(255 CHAR), 
	"TASK_INST_UUID" VARCHAR2(255 CHAR), 
	"USER_ID" VARCHAR2(255 CHAR), 
	"SOURCE_TENANT_ID" VARCHAR2(255 CHAR), 
	"TARGET_TENANT_ID" VARCHAR2(255 CHAR), 
	"SUSPENSION_STATE" NUMBER(10,0)
   ) ;
CREATE TABLE "REPO_FOLDER_OPERATE_LOG" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"OPERATE_TYPE" VARCHAR2(255 CHAR), 
	"REC_VER" NUMBER(10,0), 
	"FOLDER_UUID" VARCHAR2(255 CHAR), 
	"FILE_JSON" CLOB
   ) ;
CREATE TABLE "QRTZ_BLOB_TRIGGERS" 
   (	"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"BLOB_DATA" BLOB
   ) ;
CREATE TABLE "QRTZ_CALENDARS" 
   (	"CALENDAR_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"CALENDAR" BLOB NOT NULL ENABLE
   ) ;
CREATE TABLE "QRTZ_JOB_DETAILS" 
   (	"JOB_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"JOB_GROUP" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"JOB_CLASS_NAME" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"IS_DURABLE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"IS_VOLATILE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"IS_STATEFUL" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"REQUESTS_RECOVERY" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"JOB_DATA" BLOB
   ) ;
CREATE TABLE "QRTZ_TRIGGERS" 
   (	"TRIGGER_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"TRIGGER_GROUP" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"JOB_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"JOB_GROUP" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"IS_VOLATILE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"NEXT_FIRE_TIME" NUMBER(13,0), 
	"PREV_FIRE_TIME" NUMBER(13,0), 
	"PRIORITY" NUMBER(13,0), 
	"TRIGGER_STATE" VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"TRIGGER_TYPE" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"START_TIME" NUMBER(13,0) NOT NULL ENABLE, 
	"END_TIME" NUMBER(13,0), 
	"CALENDAR_NAME" VARCHAR2(200 BYTE), 
	"MISFIRE_INSTR" NUMBER(2,0), 
	"JOB_DATA" BLOB
   ) ;
CREATE TABLE "API_ACCESS_LOG" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"API_SERVICE_NAME" VARCHAR2(255 CHAR), 
	"CLIENT_BROWSER" VARCHAR2(255 CHAR), 
	"CLIENT_IP" VARCHAR2(255 CHAR), 
	"REQUEST_JSON" CLOB, 
	"RESPONSE_BODY" CLOB, 
	"LOG_TIME" TIMESTAMP (6), 
	"TENANT_ID" VARCHAR2(255 CHAR), 
	"USER_ID" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MT_NOTICE_CONTENT_INFO" 
   (	"JOB" VARCHAR2(255 CHAR), 
	"PHONE" VARCHAR2(255 CHAR), 
	"CELL_PHONE" VARCHAR2(255 CHAR), 
	"REPLY_UNIT_NAME" VARCHAR2(255 CHAR), 
	"REPLY_UNIT_ID" VARCHAR2(255 CHAR), 
	"REPLY_USER_NAME" VARCHAR2(255 CHAR), 
	"REPLY_USER_ID" VARCHAR2(255 CHAR), 
	"BELONG_NOTICE_UUID" VARCHAR2(255 CHAR), 
	"REPLY_CONTENT" CLOB, 
	"REPLY_TIME" TIMESTAMP (6), 
	"UUID" VARCHAR2(255 CHAR), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"CREATE_TIME" TIMESTAMP (6), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0)
   ) ;
-- new object type path: SCHEMA_EXPORT/TABLE/COMMENT
 COMMENT ON COLUMN "MT_TENANT_USER"."USER_NAME" IS '用户名称';
-- new object type path: SCHEMA_EXPORT/FUNCTION/FUNCTION
-- CONNECT WELLSOFT_ADM
CREATE FUNCTION fn_parsejson(p_jsonstr varchar2, p_key varchar2)
  RETURN VARCHAR2 IS
  rtnVal    VARCHAR2(50);
  i         NUMBER(2);
  jsonkey   VARCHAR2(50);
  jsonvalue VARCHAR2(50);
  json      VARCHAR2(1000);
BEGIN
  IF p_jsonstr IS NOT NULL THEN
    json := REPLACE(p_jsonstr, '{', '');
    json := REPLACE(json, '}', '');
    json := replace(json, '"', '');
    FOR temprow IN (SELECT strvalue AS VALUE FROM TABLE(fn_split(json, ','))) LOOP
      IF temprow.VALUE IS NOT NULL THEN
        i         := 0;
        jsonkey   := '';
        jsonvalue := '';
        FOR tem2 IN (SELECT strvalue AS VALUE
                       FROM TABLE(fn_split(temprow.value, ':'))) LOOP
          IF i = 0 THEN
            jsonkey := tem2.VALUE;
          END IF;
          IF i = 1 THEN
            jsonvalue := tem2.VALUE;
          END IF;

          i := i + 1;
        END LOOP;

        IF (jsonkey = p_key) THEN
          rtnVal := jsonvalue;
        END if;
      END IF;
    END LOOP;
  END IF;

  RETURN rtnVal;
END fn_parsejson;

 
/
CREATE FUNCTION fn_split(p_str       IN VARCHAR2,
                                    p_delimiter IN VARCHAR2)
  RETURN ty_tbl_str_split IS
  j         INT := 0;
  i         INT := 1;
  len       INT := 0;
  len1      INT := 0;
  str       VARCHAR2(4000);
  str_split ty_tbl_str_split := ty_tbl_str_split();
BEGIN
  len  := LENGTH(p_str);
  len1 := LENGTH(p_delimiter);


  WHILE j < len LOOP
    j := INSTR(p_str, p_delimiter, i);


    IF j = 0 THEN
      j   := len;
      str := SUBSTR(p_str, i);
      str_split.EXTEND;
      str_split(str_split.COUNT) := ty_row_str_split(strValue => str);


      IF i >= len THEN
        EXIT;
      END IF;
    ELSE
      str := SUBSTR(p_str, i, j - i);
      i   := j + len1;
      str_split.EXTEND;
      str_split(str_split.COUNT) := ty_row_str_split(strValue => str);
    END IF;
  END LOOP;


  RETURN str_split;
END fn_split;

 
/
-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/INDEX
CREATE UNIQUE INDEX "UK_J82LI4VQG1ACQH7A39CX7OCD6" ON "MT_TENANT" ("ACCOUNT") 
  ;

  ALTER INDEX "UK_J82LI4VQG1ACQH7A39CX7OCD6" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_FT_JOB_NAME" ON "QRTZ_FIRED_TRIGGERS" ("JOB_NAME") 
  ;

  ALTER INDEX "IDX_QRTZ_FT_JOB_NAME" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_FT_JOB_GROUP" ON "QRTZ_FIRED_TRIGGERS" ("JOB_GROUP") 
  ;

  ALTER INDEX "IDX_QRTZ_FT_JOB_GROUP" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_FT_JOB_STATEFUL" ON "QRTZ_FIRED_TRIGGERS" ("IS_STATEFUL") 
  ;

  ALTER INDEX "IDX_QRTZ_FT_JOB_STATEFUL" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_FT_JOB_REQ_RECOVERY" ON "QRTZ_FIRED_TRIGGERS" ("REQUESTS_RECOVERY") 
  ;

  ALTER INDEX "IDX_QRTZ_FT_JOB_REQ_RECOVERY" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_FT_TRIG_NAME" ON "QRTZ_FIRED_TRIGGERS" ("TRIGGER_NAME") 
  ;

  ALTER INDEX "IDX_QRTZ_FT_TRIG_NAME" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_FT_TRIG_GROUP" ON "QRTZ_FIRED_TRIGGERS" ("TRIGGER_GROUP") 
  ;

  ALTER INDEX "IDX_QRTZ_FT_TRIG_GROUP" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_FT_TRIG_NM_GP" ON "QRTZ_FIRED_TRIGGERS" ("TRIGGER_NAME", "TRIGGER_GROUP") 
  ;

  ALTER INDEX "IDX_QRTZ_FT_TRIG_NM_GP" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_FT_TRIG_VOLATILE" ON "QRTZ_FIRED_TRIGGERS" ("IS_VOLATILE") 
  ;

  ALTER INDEX "IDX_QRTZ_FT_TRIG_VOLATILE" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_FT_TRIG_INST_NAME" ON "QRTZ_FIRED_TRIGGERS" ("INSTANCE_NAME") 
  ;

  ALTER INDEX "IDX_QRTZ_FT_TRIG_INST_NAME" NOPARALLEL;
CREATE INDEX "LOGIN_NAME_INDEX" ON "MT_TENANT_USER" ("USER_ID", "USER_UUID", "TENANT_ID", "USER_LOGIN_NAME") 
  ;

  ALTER INDEX "LOGIN_NAME_INDEX" NOPARALLEL;
CREATE INDEX "REPO_FOL_FOLDER_UUID_IDX" ON "REPO_FOLDER_OPERATE_LOG" ("FOLDER_UUID") 
  ;

  ALTER INDEX "REPO_FOL_FOLDER_UUID_IDX" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_J_REQ_RECOVERY" ON "QRTZ_JOB_DETAILS" ("REQUESTS_RECOVERY") 
  ;

  ALTER INDEX "IDX_QRTZ_J_REQ_RECOVERY" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_T_NEXT_FIRE_TIME" ON "QRTZ_TRIGGERS" ("NEXT_FIRE_TIME") 
  ;

  ALTER INDEX "IDX_QRTZ_T_NEXT_FIRE_TIME" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_T_STATE" ON "QRTZ_TRIGGERS" ("TRIGGER_STATE") 
  ;

  ALTER INDEX "IDX_QRTZ_T_STATE" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_T_NFT_ST" ON "QRTZ_TRIGGERS" ("NEXT_FIRE_TIME", "TRIGGER_STATE") 
  ;

  ALTER INDEX "IDX_QRTZ_T_NFT_ST" NOPARALLEL;
CREATE INDEX "IDX_QRTZ_T_VOLATILE" ON "QRTZ_TRIGGERS" ("IS_VOLATILE") 
  ;

  ALTER INDEX "IDX_QRTZ_T_VOLATILE" NOPARALLEL;
-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT
-- CONNECT SYSTEM
ALTER TABLE "MT_ADMIN" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "MT_DATABASE_CONFIG" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "MT_ID_GENERATOR" ADD PRIMARY KEY ("ENTITY_CLASS_NAME")
  USING INDEX  ENABLE;
ALTER TABLE "MT_PINYIN" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "MT_TENANT" ADD CONSTRAINT "UK_J82LI4VQG1ACQH7A39CX7OCD6" UNIQUE ("ACCOUNT")
  USING INDEX "UK_J82LI4VQG1ACQH7A39CX7OCD6"  ENABLE;
ALTER TABLE "MT_TENANT" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "QRTZ_FIRED_TRIGGERS" ADD PRIMARY KEY ("ENTRY_ID")
  USING INDEX  ENABLE;
ALTER TABLE "QRTZ_LOCKS" ADD PRIMARY KEY ("LOCK_NAME")
  USING INDEX  ENABLE;
ALTER TABLE "QRTZ_SCHEDULER_STATE" ADD PRIMARY KEY ("INSTANCE_NAME")
  USING INDEX  ENABLE;
ALTER TABLE "QRTZ_SIMPLE_TRIGGERS" ADD PRIMARY KEY ("TRIGGER_NAME", "TRIGGER_GROUP")
  USING INDEX  ENABLE;
ALTER TABLE "MT_NOTICE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "MT_TENANT_GZ_USER" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "REPO_FILE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "REPO_FOLDER" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "REPO_FILE_IN_FOLDER" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_GZ_DATA_SYNC" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "WF_GZ_DATA_SYNC_HIS" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "EXCHANGE_LOG" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "REPO_FOLDER_OPERATE_LOG" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "QRTZ_JOB_DETAILS" ADD PRIMARY KEY ("JOB_NAME", "JOB_GROUP")
  USING INDEX  ENABLE;
ALTER TABLE "QRTZ_TRIGGERS" ADD PRIMARY KEY ("TRIGGER_NAME", "TRIGGER_GROUP")
  USING INDEX  ENABLE;
-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/STATISTICS/INDEX_STATISTICS