
create table USER_BEHAVIOR_LOG  
(
  UUID                 NUMBER(20)           not null,
  USER_ID VARCHAR2(24),
  USER_NAME VARCHAR2(120 CHAR),
  BEHAVIOR_TYPE VARCHAR2(50),
  BEHAVIOR_DESC VARCHAR2(300 CHAR),
  ELEMENT_TAG VARCHAR2(24 CHAR),
  ELEMENT_TEXT VARCHAR2(255 CHAR),
  ELEMENT_XPATH VARCHAR2(1000),
  PAGE_ID VARCHAR2(64 CHAR),
  PAGE_URL VARCHAR2(1000),
  PAGE_TITLE VARCHAR2(255 CHAR),
  REFERRER VARCHAR2(1000),
  IP_ADDRESS VARCHAR2(45),
  USER_OS VARCHAR2(12),
  BROWSER VARCHAR2(32),
  EXTRA_INFO CLOB,
  BUSINESS_CODE VARCHAR2(64 CHAR),
  MODULE_ID VARCHAR2(64),
  MODULE_NAME VARCHAR2(120 CHAR),
  CREATE_TIME          TIMESTAMP,
  CREATOR              VARCHAR2(64),
  MODIFIER             VARCHAR2(64),
  MODIFY_TIME          TIMESTAMP,
  REC_VER              FLOAT(3)             default 1,
  SYSTEM               VARCHAR2(64),
  TENANT               VARCHAR2(64),

  constraint PK_USER_BEHAVIOR_LOG primary key (UUID)
);

comment on table USER_BEHAVIOR_LOG  is
'用户前端行为操作日志';

 
COMMENT ON COLUMN USER_BEHAVIOR_LOG.BEHAVIOR_TYPE IS '行为类型，如 click（点击）、view（浏览）、submit（提交）等';
COMMENT ON COLUMN USER_BEHAVIOR_LOG.BEHAVIOR_DESC IS '行为描述，例如“点击提交按钮”、“进入首页”等行为说明';
COMMENT ON COLUMN USER_BEHAVIOR_LOG.ELEMENT_TAG IS 'HTML 元素标签，如 BUTTON、A、INPUT、DIV 等';
COMMENT ON COLUMN USER_BEHAVIOR_LOG.ELEMENT_TEXT IS '元素上的可见文本，如按钮文字“提交订单”';
COMMENT ON COLUMN USER_BEHAVIOR_LOG.ELEMENT_XPATH IS '点击元素的 XPath 路径，用于精准定位页面上的哪个 UI 元素';
COMMENT ON COLUMN USER_BEHAVIOR_LOG.PAGE_URL IS '当前页面的完整 URL';
COMMENT ON COLUMN USER_BEHAVIOR_LOG.PAGE_TITLE IS '当前页面的标题，通常是 <title> 标签中的内容';
COMMENT ON COLUMN USER_BEHAVIOR_LOG.REFERRER IS '用户来源页面 URL，即从哪个页面跳转过来的（HTTP Referer）';
COMMENT ON COLUMN USER_BEHAVIOR_LOG.IP_ADDRESS IS '用户 IP 地址';
COMMENT ON COLUMN USER_BEHAVIOR_LOG.USER_OS IS '用户使用的操作系统，如 Windows、macOS、Android、iOS 等';
COMMENT ON COLUMN USER_BEHAVIOR_LOG.BROWSER IS '用户使用的浏览器信息，如 Chrome、Firefox、Safari、Edge 等';
COMMENT ON COLUMN USER_BEHAVIOR_LOG.EXTRA_INFO IS '附加信息字段，通常用于存储 JSON 格式的业务参数、表单内容等扩展信息';
COMMENT ON COLUMN USER_BEHAVIOR_LOG.BUSINESS_CODE IS '业务唯一标识，如订单号、工单号、流程 ID 等，用于关联具体业务场景'; 