--  Add/modify columns
ALTER TABLE DMS_DOC_EXCHANGE_CONFIG ADD COLUMN DEFAULT_ENCRYPTION_LEVEL varchar(64) COMMENT '默认文档密级';
ALTER TABLE DMS_DOC_EXCHANGE_CONFIG ADD COLUMN DEFAULT_URGE_LEVEL varchar(64) COMMENT '默认文档缓急程度';
