ALTER TABLE ORG_USER_LOGIN_LOG ADD COLUMN USER_OS VARCHAR(255);
ALTER TABLE ORG_USER_LOGIN_LOG ADD COLUMN BROWSER VARCHAR(255);
ALTER TABLE ORG_USER_LOGIN_LOG ADD COLUMN BROWSER_VERSION VARCHAR(255);
