create index CD_RU_BATCH_IDX ON cd_recent_use(object_id_identity, user_id, module_id);
create index CD_UP_BATCH_IDX ON cd_user_preferences(user_id, module_id);
create index SYS_PI_KEY_IDX ON sys_param_item (`KEY`(768) ASC);
create index WF_TOT_BATCH_IDX ON wf_task_operation_temp(assignee, flow_inst_uuid);
create index WF_DOC_CREATOR_IDX ON wf_def_opinion_category(creator);
create index WF_OCS_FLOW_DEF_ID_IDX ON wf_opinion_check_set(flow_def_id);
create index WF_TD_CONSIGNOR_IDX ON wf_task_delegation(consignor);
create index WF_TD_TASK_INST_UUID_IDX ON wf_task_delegation(task_inst_uuid);
create index WF_TD_COMPLETION_STATE_IDX ON wf_task_delegation(task_inst_uuid, completion_state);
create index WF_TB_PL_TASK_INST_UUID_IDX on WF_TASK_BRANCH (parallel_task_inst_uuid);
create index WF_TB_CR_TASK_INST_UUID_IDX on WF_TASK_BRANCH (current_task_inst_uuid);
create index WF_TB_FLOW_INST_UUID_IDX on WF_TASK_BRANCH (flow_inst_uuid);
create index WF_TSF_FIUUID_IDX ON WF_TASK_SUB_FLOW (flow_inst_uuid);
create index WF_TSF_PFIUUID_IDX ON WF_TASK_SUB_FLOW (parent_flow_inst_uuid);
create index WF_TI_P_TASK_INST_UUID_IDX ON wf_task_instance (parent_task_inst_uuid);
create index APP_MODULE_ID_IDX ON app_module(id);
create index USER_UI_LOGIN_NAME_IDX ON user_info(login_name);
create index LOG_BO_BATCH_IDX ON log_business_operation(data_def_id, data_def_type, data_id);
create index LOG_BD_BATCH_IDX ON log_business_details(data_def_id, data_def_type, data_id);
create index MULTI_ORG_JRL_USER_ID_IDX ON multi_org_job_rank_level(user_id);
create index ORG_UP_BATCH_IDX ON org_user_property(user_uuid, name);
create index MULTI_ORG_DUI_USER_ID_IDX ON multi_org_ding_user_info(user_id);
create index MULTI_ULS_SYSTEM_UNIT_ID_IDX ON multi_user_login_settings(system_unit_id);
create index AUDIT_UA_LOGIN_NAME_IDX ON audit_user_attempts(login_name);
create index AUDIT_RESOURCE_CODE_IDX ON audit_resource(code);
create index APP_LPC_SYSTEM_UNIT_ID_IDX ON app_login_page_config(system_unit_id);
create index APP_LSC_SYSTEM_UNIT_ID_IDX ON app_login_security_config(system_unit_id);
create index APP_PRODUCT_SYSTEM_UNIT_ID_IDX ON app_product(system_unit_id);
create index APP_MODULE_SYSTEM_UNIT_ID_IDX ON app_module(system_unit_id);
create index APP_PI_BATCH_IDX ON app_product_integration(data_uuid, data_type, data_path);
create index SYS_IC_APPLY_TO_IDX ON sys_ip_config(apply_to);