CREATE TABLE IMP_EXCEL_DATA_BATCH
(
  UUID          NUMBER(19) PRIMARY KEY,
  BATCH_NO      VARCHAR2(64) NOT NULL,
  CODE          VARCHAR2(64) NOT NULL,
  FILE_ID       VARCHAR2(64) NOT NULL,
  FILE_NAME     VARCHAR2(64),
  SUCCESS_COUNT NUMBER(6) DEFAULT 0,
  FAIL_COUNT    NUMBER(6) DEFAULT 0,
  CREATE_TIME   TIMESTAMP(6),
  CREATOR       VARCHAR2(64),
  MODIFIER      VARCHAR2(64),
  MODIFY_TIME   TIMESTAMP(6),
  SYSTEM        VARCHAR2(64),
  TENANT        VARCHAR2(64),
  REC_VER       FLOAT(3) DEFAULT 1
);

CREATE TABLE IMP_EXCEL_DATA_BATCH_DETAIL
(
  UUID        NUMBER(19) PRIMARY KEY,
  BATCH_UUID  NUMBER(19) NOT NULL,
  SHEET       VARCHAR2(64),
  SHEET_INDEX NUMBER(2),
  ROW_INDEX   NUMBER(2),
  SUCCESS     NUMBER(1) DEFAULT 0,
  REMARK      VARCHAR2(1000),
  DATA_JSON   CLOB,
  CREATE_TIME TIMESTAMP(6),
  CREATOR     VARCHAR2(64),
  MODIFIER    VARCHAR2(64),
  MODIFY_TIME TIMESTAMP(6),
  SYSTEM      VARCHAR2(64),
  TENANT      VARCHAR2(64),
  REC_VER     FLOAT(3) DEFAULT 1
);