package com.wellsoft.context.util.file;

import org.apache.commons.compress.archivers.zip.ZipArchiveEntry;
import org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream;
import org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.UnicodeExtraFieldPolicy;
import org.apache.commons.io.IOUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;

/**
 * Description: ArchiveUtils
 *
 * @author Asus
 * @version 1.0
 *
 * <pre>
 * 修改记录:
 * 修改后版本	修改人		修改日期			修改内容
 * 2015年12月23日.1	Asus		2015年12月23日		Create
 * </pre>
 * @date 2015年12月25日
 */
public class ArchiveUtils {
    private static Logger log = LoggerFactory.getLogger(ArchiveUtils.class);

    /**
     * Recursively create ZIP archive from directory
     */
    /**
     * 创建一个ZIP文件
     *
     * @param path
     * @param root
     * @param os
     * @throws IOException
     */
    public static void createZip(File path, String root, OutputStream os) throws IOException {
        log.debug("createZip({}, {}, {})", new Object[]{path, root, os});

        if (path.exists() && path.canRead()) {
            ZipArchiveOutputStream zos = new ZipArchiveOutputStream(os);
            zos.setComment("Generated by OpenKM");
            zos.setCreateUnicodeExtraFields(UnicodeExtraFieldPolicy.ALWAYS);
            zos.setUseLanguageEncodingFlag(true);
            zos.setFallbackToUTF8(true);
            zos.setEncoding("UTF-8");

            // Prevents java.util.zip.ZipException: ZIP file must have at least one entry
            ZipArchiveEntry ze = new ZipArchiveEntry(root + "/");
            zos.putArchiveEntry(ze);
            zos.closeArchiveEntry();

            createZipHelper(path, zos, root);

            zos.flush();
            zos.finish();
            zos.close();
        } else {
            throw new IOException("Can't access " + path);
        }

        log.debug("createZip: void");
    }

    /**
     * Recursively create ZIP archive from directory helper utility
     */
    private static void createZipHelper(File fs, ZipArchiveOutputStream zos, String zePath) throws IOException {
        log.debug("createZipHelper({}, {}, {})", new Object[]{fs, zos, zePath});
        File[] files = fs.listFiles();

        for (int i = 0; i < files.length; i++) {
            if (files[i].isDirectory()) {
                log.debug("DIRECTORY {}", files[i]);
                ZipArchiveEntry ze = new ZipArchiveEntry(zePath + "/" + files[i].getName() + "/");
                zos.putArchiveEntry(ze);
                zos.closeArchiveEntry();

                createZipHelper(files[i], zos, zePath + "/" + files[i].getName());
            } else {
                log.debug("FILE {}", files[i]);
                ZipArchiveEntry zae = new ZipArchiveEntry(zePath + "/" + files[i].getName());
                zos.putArchiveEntry(zae);
                FileInputStream fis = new FileInputStream(files[i]);
                IOUtils.copy(fis, zos);
                fis.close();
                zos.closeArchiveEntry();
            }
        }

        log.debug("createZipHelper: void");
    }
}
