-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
CREATE TABLE "ORG_DEPARTMENT_PRIVILEGE" 
   (  "DEPARTMENT_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "PRIVILEGE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_ENTITY_INFO" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "code" VARCHAR2(500 CHAR), 
  "name" VARCHAR2(255 CHAR), 
  "Creator_Name" VARCHAR2(32 CHAR), 
  "version_uuid" VARCHAR2(255 CHAR), 
  "parent_uuid" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_JOB_PRIVILEGE" 
   (  "JOB_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "PRIVILEGE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_UNIT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CATEGORY" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "PARENT_UUID" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_UNIT_MEMBER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BUSINESS_TYPE" VARCHAR2(255 CHAR), 
  "MEMBER" VARCHAR2(255 CHAR), 
  "MEMBER_TYPE" VARCHAR2(255 CHAR), 
  "UNIT_UUID" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_DUTY_AGENT_AUTH" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "AUTHORISED_CONSIGNOR" VARCHAR2(255 CHAR), 
  "AUTHORISED_CONSIGNOR_NAME" VARCHAR2(255 CHAR), 
  "BUSINESS_TYPE" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "CONSIGNOR" VARCHAR2(255 CHAR), 
  "CONSIGNOR_NAME" VARCHAR2(255 CHAR), 
  "CONTENT" VARCHAR2(255 CHAR), 
  "CONTENT_NAME" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_JOB_LEADER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "JOB_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "LEADER_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_JOB_FUNCTION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "JOB_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "FUNCTION_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_EMPLOYEE_JOB" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "EMPLOYEE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "JOB_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "JOB_NAME" VARCHAR2(255 CHAR), 
  "IS_MAJOR" NUMBER(1,0) NOT NULL ENABLE, 
  "EMPLOYEE_NUMBER" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_DEPARTMENT_FUNCTION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "DEPARTMENT_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "FUNCTION_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;


CREATE TABLE "ORG_CONTACT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "DATA_UUID" VARCHAR2(255 CHAR), 
  "DEPARTMENT_NAME" VARCHAR2(255 CHAR), 
  "EMAIL" VARCHAR2(255 CHAR), 
  "HOME_PHONE" VARCHAR2(255 CHAR), 
  "MOBILE_PHONE" VARCHAR2(255 CHAR), 
  "OFFICE_PHONE" VARCHAR2(255 CHAR), 
  "SEX" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "USER_NAME" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_GROUP_PRIVILEGE" 
   (  "GROUP_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "PRIVILEGE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_GROUP_ROLE" 
   (  "GROUP_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ROLE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_JOB_PRINCIPAL" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "TYPE" VARCHAR2(255 CHAR), 
  "JOB_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ORG_ID" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_OPTION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "OWNER" VARCHAR2(4000 CHAR), 
  "OWNER_NAME" VARCHAR2(4000 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "SHOW" NUMBER(1,0), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_USER_MINOR_JOB" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "DEPUTY_UUID" VARCHAR2(255 CHAR), 
  "USER_UUID" VARCHAR2(255 CHAR), 
  "ORG_ID" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_UNIT_SYNCHRONOUS" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "SHORT_NAME" VARCHAR2(255 CHAR), 
  "PARENT_UNIT_ID" VARCHAR2(255 CHAR), 
  "VER" NUMBER(10,0), 
  "ACTION_TYPE" NUMBER(10,0), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_USER_TRACE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "USER_ID" VARCHAR2(255 CHAR), 
  "TRACE_ID" VARCHAR2(255 CHAR), 
  "TRACE_TYPE" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_USER_TRACE_PLAN" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "USER_ID" VARCHAR2(255 CHAR), 
  "START_TIME" TIMESTAMP (6), 
  "END_TIME" TIMESTAMP (6), 
  "TRACE" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "OPERATE_ID" VARCHAR2(255 CHAR), 
  "STATUS" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_USER_ROLE" 
   (  "USER_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ROLE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_USER_PROPERTY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "NAME" VARCHAR2(255 CHAR), 
  "USER_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "VALUE" VARCHAR2(255 CHAR), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "CREATE_TIME" TIMESTAMP (6), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_USER_PRIVILEGE" 
   (  "USER_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "PRIVILEGE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_USER_LOGIN_LOG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "LOGIN_IP" VARCHAR2(255 CHAR), 
  "LOGIN_TIME" TIMESTAMP (6), 
  "LOGOUT_TIME" TIMESTAMP (6), 
  "USER_UUID" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_USER_LEADER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "LEADER_UUID" VARCHAR2(255 CHAR), 
  "USER_UUID" VARCHAR2(255 CHAR), 
  "ORG_ID" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_USER_JOB" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "USER_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "JOB_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "JOB_NAME" VARCHAR2(255 CHAR), 
  "USER_LOGIN_NAME" VARCHAR2(255 CHAR), 
  "IS_MAJOR" NUMBER(1,0) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_USER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ACCOUNT_NON_EXPIRED" NUMBER(1,0), 
  "ACCOUNT_NON_LOCKED" NUMBER(1,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "CREDENTIALS_NON_EXPIRED" NUMBER(1,0), 
  "DEPARTMENT_NAME" VARCHAR2(255 CHAR), 
  "DEPUTY_NAMES" VARCHAR2(255 CHAR), 
  "EMPLOYEE_NUMBER" VARCHAR2(255 CHAR), 
  "ENABLED" NUMBER(1,0), 
  "FAX" VARCHAR2(255 CHAR), 
  "GROUP_NAMES" VARCHAR2(3999 BYTE), 
  "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ID_NUMBER" VARCHAR2(255 CHAR), 
  "IS_ALLOWED_BACK" NUMBER(1,0), 
  "ISSYS" NUMBER(1,0), 
  "JOB_NAME" VARCHAR2(255 CHAR), 
  "LAST_LOGIN_TIME" TIMESTAMP (6), 
  "LEADER_NAMES" VARCHAR2(255 CHAR), 
  "LOGIN_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "MOBILE_PHONE" VARCHAR2(255 CHAR), 
  "OFFICE_PHONE" VARCHAR2(255 CHAR), 
  "PASSWORD" VARCHAR2(255 CHAR), 
  "PHOTO_UUID" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "ROLE_NAMES" VARCHAR2(255 CHAR), 
  "SEX" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR), 
  "TRACE" VARCHAR2(255 CHAR), 
  "USER_NAME" VARCHAR2(255 CHAR), 
  "HOME_PHONE" VARCHAR2(255 CHAR), 
  "PERSONNEL_AREA" VARCHAR2(255 CHAR), 
  "MAJOR_JOB_NAME" VARCHAR2(255 CHAR), 
  "OTHER_JOB_NAMES" VARCHAR2(255 CHAR), 
  "PRINCIPAL_COMPANY" VARCHAR2(255 CHAR), 
  "EXTERNAL_ID" VARCHAR2(255 CHAR), 
  "BOUSER" VARCHAR2(50 BYTE), 
  "BOPWD" VARCHAR2(50 BYTE), 
  "ENGLISH_NAME" VARCHAR2(255 CHAR), 
  "OTHER_MOBILE_PHONE" VARCHAR2(255 CHAR), 
  "MAIN_EMAIL" VARCHAR2(255 CHAR), 
  "OTHER_EMAIL" VARCHAR2(255 CHAR), 
  "SMALL_PHOTO_UUID" VARCHAR2(255 BYTE), 
  "TRACE_DATE" TIMESTAMP (6), 
  "LOGIN_NAME_BAK" VARCHAR2(255 BYTE), 
  "NOT_ALLOWED_TENANT_ID" NUMBER(1,0), 
  "ONLY_LOGON_WIDTH_CERTIFICATE" NUMBER(1,0)
   ) ;
CREATE TABLE "ORG_JOB_ROLE" 
   (  "JOB_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ROLE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_JOB" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CODE" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "EXTERNAL_ID" VARCHAR2(255 CHAR), 
  "DEPARTMENT_NAME" VARCHAR2(255 CHAR), 
  "DEPARTMENT_UUID" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "DUTY_UUID" VARCHAR2(255 CHAR), 
  "DUTY_NAME" VARCHAR2(255 CHAR), 
  "LEADER_NAMES" VARCHAR2(255 CHAR), 
  "FUNCTION_NAMES" VARCHAR2(255 CHAR), 
  "ORG_ID" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_GROUP_USER" 
   (  "GROUP_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "USER_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "IS_ADMIN" NUMBER(1,0), 
  "ISWARNMSG" NUMBER(1,0), 
  "ISREMANFID" NUMBER(1,0), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_GROUP_NESTED_GROUP" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "GROUP_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "NESTED_GROUP_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_GROUP_MEMBER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "GROUP_UUID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
  "USER_UUID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
  "IS_ADMIN" NUMBER(1,0), 
  "ISWARNMSG" NUMBER(1,0), 
  "REMANFID" VARCHAR2(255 BYTE), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_GROUP_JOB" 
   (  "GROUP_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "JOB_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_GROUP_DUTY" 
   (  "GROUP_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "DUTY_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_GROUP_DEPARTMENT" 
   (  "GROUP_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "DEPARTMENT_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_EMPLOYEE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "DEPARTMENT_NAME" VARCHAR2(255 CHAR), 
  "DEPUTY_NAMES" VARCHAR2(255 CHAR), 
  "EMPLOYEE_NUMBER" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ENABLED" NUMBER(1,0), 
  "FAX" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ID_NUMBER" VARCHAR2(255 CHAR), 
  "JOB_NAME" VARCHAR2(255 CHAR), 
  "LEADER_NAMES" VARCHAR2(255 CHAR), 
  "LOGIN_NAME" VARCHAR2(255 CHAR), 
  "MOBILE_PHONE" VARCHAR2(255 CHAR), 
  "OFFICE_PHONE" VARCHAR2(255 CHAR), 
  "PASSWORD" VARCHAR2(255 CHAR), 
  "PHOTO_UUID" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "SEX" VARCHAR2(255 CHAR), 
  "HOME_PHONE" VARCHAR2(255 CHAR), 
  "PERSONNEL_AREA" VARCHAR2(255 CHAR), 
  "MAJOR_JOB_NAME" VARCHAR2(255 CHAR), 
  "OTHER_JOB_NAMES" VARCHAR2(255 CHAR), 
  "PRINCIPAL_COMPANY" VARCHAR2(255 CHAR), 
  "EXTERNAL_ID" VARCHAR2(255 CHAR), 
  "ENGLISH_NAME" VARCHAR2(255 CHAR), 
  "OTHER_MOBILE_PHONE" VARCHAR2(255 CHAR), 
  "MAIN_EMAIL" VARCHAR2(255 CHAR), 
  "OTHER_EMAIL" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_DUTY_ROLE" 
   (  "DUTY_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ROLE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_DUTY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "DUTY_LEVEL" VARCHAR2(255 CHAR), 
  "SERIES_NAME" VARCHAR2(255 CHAR), 
  "SERIES_UUID" VARCHAR2(255 CHAR), 
  "EXTERNAL_ID" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ILEVEL" NUMBER(5,0), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_DEPT_PRINCIPAL" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "TYPE" VARCHAR2(255 CHAR), 
  "DEPARTMENT_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ORG_ID" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_DEPARTMENT_USER_JOB" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "IS_MAJOR" NUMBER(1,0), 
  "JOB_CODE" VARCHAR2(255 CHAR), 
  "JOB_NAME" VARCHAR2(255 CHAR), 
  "DEPARTMENT_UUID" VARCHAR2(255 CHAR), 
  "USER_UUID" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_DEPARTMENT_ROLE" 
   (  "DEPARTMENT_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ROLE_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_DEPARTMENT_PRINCIPAL" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "IS_BRANCHED" NUMBER(1,0), 
  "IS_MANAGER" NUMBER(1,0), 
  "IS_PRINCIPAL" NUMBER(1,0), 
  "DEPARTMENT_UUID" VARCHAR2(255 CHAR), 
  "USER_UUID" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_DEPARTMENT_EMPLOYEE_JOB" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "IS_MAJOR" NUMBER(1,0), 
  "JOB_CODE" VARCHAR2(255 CHAR), 
  "JOB_NAME" VARCHAR2(255 CHAR), 
  "DEPARTMENT_UUID" VARCHAR2(255 CHAR), 
  "EMPLOYEE_UUID" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_DEPARTMENT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BRANCHED_LEADER_NAMES" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "COMMON_UNIT_ID" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "IS_VISIBLE" NUMBER(1,0), 
  "MANAGER_NAMES" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "PATH" VARCHAR2(255 CHAR), 
  "PRINCIPAL_LEADER_NAMES" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "SHORT_NAME" VARCHAR2(255 CHAR), 
  "PARENT_UUID" VARCHAR2(255 CHAR), 
  "EXTERNAL_ID" VARCHAR2(255 CHAR), 
  "DEPARTMENT_LEVEL" VARCHAR2(255 CHAR), 
  "FUNCTION_NAMES" VARCHAR2(255 CHAR), 
  "ORG_ID" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_ORGANIZATION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "IS_DEFAULT" NUMBER(1,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "TYPE_CODE" VARCHAR2(255 CHAR), 
  "TYPE_NAME" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_GROUP_UNIT" 
   (  "GROUP_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "UNIT_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "ORG_VERSION_INFO" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "NAME" VARCHAR2(500 CHAR), 
  "VER" VARCHAR2(255 CHAR), 
  "STATUS" VARCHAR2(32 CHAR), 
  "ORG_TYPE" VARCHAR2(255 CHAR), 
  "CREATOR_NAME" VARCHAR2(255 CHAR), 
  "BEGIN_DATE" VARCHAR2(255 CHAR), 
  "END_DATE" VARCHAR2(255 CHAR), 
  "TREE_JSON" CLOB, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_USER_SYNCHRONOUS" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "LOGIN_NAME" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "USER_NAME" VARCHAR2(255 CHAR), 
  "SEX" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "ENGLISH_NAME" VARCHAR2(255 CHAR), 
  "FAX" VARCHAR2(255 CHAR), 
  "PRINCIPAL_COMPANY" VARCHAR2(255 CHAR), 
  "PHOTO" CLOB, 
  "EMPLOYEE_NUMBER" VARCHAR2(255 CHAR), 
  "DEPARTMENT_NAME" VARCHAR2(255 CHAR), 
  "JOB_NAME" VARCHAR2(255 CHAR), 
  "LEADER_NAMES" VARCHAR2(255 CHAR), 
  "DEPUTY_NAMES" VARCHAR2(255 CHAR), 
  "GROUP_NAMES" VARCHAR2(255 CHAR), 
  "MOBILE_PHONE" VARCHAR2(255 CHAR), 
  "OTHER_MOBILE_PHONE" VARCHAR2(255 CHAR), 
  "OFFICE_PHONE" VARCHAR2(255 CHAR), 
  "HOME_PHONE" VARCHAR2(255 CHAR), 
  "MAIN_EMAIL" VARCHAR2(255 CHAR), 
  "OTHER_EMAIL" VARCHAR2(255 CHAR), 
  "VER" NUMBER(10,0), 
  "UNIT_ID" VARCHAR2(255 CHAR), 
  "ID_NUMBER" VARCHAR2(255 CHAR), 
  "PASS_WORD" VARCHAR2(255 CHAR), 
  "ACTION_TYPE" NUMBER(10,0), 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_DUTY_AGENT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BUSINESS_TYPE" VARCHAR2(255 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "CONDITION" VARCHAR2(255 CHAR), 
  "CONSIGNOR" VARCHAR2(255 CHAR), 
  "CONSIGNOR_NAME" VARCHAR2(255 CHAR), 
  "CONTENT_BAK" VARCHAR2(4000 CHAR), 
  "FROM_TIME" TIMESTAMP (6), 
  "STATUS" NUMBER(10,0), 
  "TO_TIME" TIMESTAMP (6), 
  "TRUSTEE" VARCHAR2(255 CHAR), 
  "TRUSTEE_NAME" VARCHAR2(255 CHAR), 
  "DISPLAY_CONTENT_BAK" VARCHAR2(4000 CHAR), 
  "INCLUDE_CURRENT_WORK" NUMBER(1,0), 
  "DUE_TO_TAKE_BACK_WORK" NUMBER(1,0), 
  "CONTENT" CLOB, 
  "CONTENT_NAME" CLOB, 
  "CONTENT_ID" CLOB, 
  "DISPLAY_CONTENT" VARCHAR2(4000 CHAR), 
  "CONDITION_JSON" VARCHAR2(255 CHAR), 
  "CONTENT_NEW" CLOB, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "ORG_GROUP" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "NAME" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "PARENT_UUID" VARCHAR2(255 CHAR), 
  "CATEGORY" VARCHAR2(255 CHAR), 
  "ITYPE" NUMBER(10,0), 
  "RANGE_NAMES" VARCHAR2(3999 BYTE), 
  "RANGE_IDS" VARCHAR2(3999 BYTE), 
  "MEMBER_NAMES" CLOB, 
  "MEMBER_IDS" CLOB, 
  "TENANT_ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "UNIT_BUSINESS_TREE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BUSINESS_MANAGER_USER_ID" VARCHAR2(255 CHAR), 
  "BUSINESS_RECEIVER_ID" VARCHAR2(2000 CHAR), 
  "BUSINESS_SENDER_ID" VARCHAR2(2000 CHAR), 
  "CODE" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "BUSINESS_TYPE_UUID" VARCHAR2(255 CHAR), 
  "PARENT_UUID" VARCHAR2(255 CHAR), 
  "UNIT_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "UNIT_BUSINESS_TREE_ROLE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BUSINESS_ROLE_ID" VARCHAR2(255 CHAR), 
  "BUSINESS_ROLE_NAME" VARCHAR2(255 CHAR), 
  "BUSINESS_UNIT_TREE_UUID" VARCHAR2(255 CHAR), 
  "MEMBER_ID" VARCHAR2(255 CHAR), 
  "MEMBER_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "UNIT_BUSINESS_TYPE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "UNIT_MANAGER_USER_ID" VARCHAR2(255 CHAR), 
  "UNIT_MANAGER_USER_NAME" VARCHAR2(255 CHAR), 
  "UNIT_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "UNIT_COMMON_DEPARTMENT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "IS_VISIBLE" NUMBER(1,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "PARENT_UUID" VARCHAR2(255 CHAR), 
  "UNIT_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "UNIT_COMMON_UNIT" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "EMAIL" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "REMARK" VARCHAR2(255 CHAR), 
  "SHORT_NAME" VARCHAR2(255 CHAR), 
  "TENANT_ID" VARCHAR2(255 CHAR), 
  "UNIT_ID" VARCHAR2(255 CHAR), 
  "COMMUNITY_ID" VARCHAR2(255 CHAR), 
  "ORG_CODE" VARCHAR2(255 BYTE)
   ) ;
CREATE TABLE "UNIT_COMMON_UNIT_TREE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "PARENT_UUID" VARCHAR2(255 CHAR), 
  "UNIT_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "UNIT_COMMON_USER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "CODE" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "SEX" VARCHAR2(255 CHAR), 
  "UNIT_UUID" VARCHAR2(255 CHAR)
   ) ;
   
-- new object type path: SCHEMA_EXPORT/TABLE/COMMENT
 COMMENT ON COLUMN "ORG_USER_MINOR_JOB"."ORG_ID" IS '所属组织ID';
 COMMENT ON COLUMN "ORG_USER_LEADER"."ORG_ID" IS '所属组织ID';
 COMMENT ON COLUMN "ORG_USER"."NOT_ALLOWED_TENANT_ID" IS '不允许登陆此系统';
 COMMENT ON COLUMN "ORG_USER"."ONLY_LOGON_WIDTH_CERTIFICATE" IS '只能以证书登录';
 COMMENT ON COLUMN "ORG_JOB"."ORG_ID" IS '所属组织ID';
 COMMENT ON COLUMN "ORG_DEPARTMENT"."ORG_ID" IS '所属组织ID';
 COMMENT ON COLUMN "ORG_ORGANIZATION"."UUID" IS 'UUID';
 COMMENT ON COLUMN "ORG_ORGANIZATION"."CREATE_TIME" IS '创建时间';
 COMMENT ON COLUMN "ORG_ORGANIZATION"."CREATOR" IS '创建人';
 COMMENT ON COLUMN "ORG_ORGANIZATION"."MODIFIER" IS '修改人';
 COMMENT ON COLUMN "ORG_ORGANIZATION"."MODIFY_TIME" IS '修改时间';
 COMMENT ON COLUMN "ORG_ORGANIZATION"."REC_VER" IS '版本号';
 COMMENT ON COLUMN "ORG_ORGANIZATION"."CODE" IS '编号';
 COMMENT ON COLUMN "ORG_ORGANIZATION"."ID" IS 'ID';
 COMMENT ON COLUMN "ORG_ORGANIZATION"."IS_DEFAULT" IS '默认管理型组织';
 COMMENT ON COLUMN "ORG_ORGANIZATION"."NAME" IS '名称';
 COMMENT ON COLUMN "ORG_ORGANIZATION"."TYPE_CODE" IS '组织类型编码';
 COMMENT ON COLUMN "ORG_ORGANIZATION"."TYPE_NAME" IS '组织类型名称';

 -- new object type path: SCHEMA_EXPORT/TABLE/INDEX/INDEX
CREATE INDEX "ORG_GP_PRIVILEGE_UUID_IDX" ON "ORG_GROUP_PRIVILEGE" ("PRIVILEGE_UUID");
ALTER INDEX "ORG_GP_PRIVILEGE_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_GR_ROLE_UUID_IDX" ON "ORG_GROUP_ROLE" ("ROLE_UUID");
ALTER INDEX "ORG_GR_ROLE_UUID_IDX" NOPARALLEL;
CREATE UNIQUE INDEX "UK_33447WNQNPXXGRY9GGA1FNRSY" ON "ORG_OPTION" ("NAME");
ALTER INDEX "UK_33447WNQNPXXGRY9GGA1FNRSY" NOPARALLEL;
CREATE INDEX "ORG_UMJ_DEPUTY_UUID_IDX" ON "ORG_USER_MINOR_JOB" ("DEPUTY_UUID");
ALTER INDEX "ORG_UMJ_DEPUTY_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_UMJ_USER_UUID_IDX" ON "ORG_USER_MINOR_JOB" ("USER_UUID");
ALTER INDEX "ORG_UMJ_USER_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_UR_ROLE_UUID_IDX" ON "ORG_USER_ROLE" ("ROLE_UUID");
ALTER INDEX "ORG_UR_ROLE_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_UP_PRIVILEGE_UUID_IDX" ON "ORG_USER_PRIVILEGE" ("PRIVILEGE_UUID");
ALTER INDEX "ORG_UP_PRIVILEGE_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_UL_USER_UUID_IDX" ON "ORG_USER_LEADER" ("USER_UUID");
ALTER INDEX "ORG_UL_USER_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_UL_LEADER_UUID_IDX" ON "ORG_USER_LEADER" ("LEADER_UUID");
ALTER INDEX "ORG_UL_LEADER_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_UJ_USER_UUID_IDX" ON "ORG_USER_JOB" ("USER_UUID");
ALTER INDEX "ORG_UJ_USER_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_UJ_JOB_UUID_IDX" ON "ORG_USER_JOB" ("JOB_UUID");
ALTER INDEX "ORG_UJ_JOB_UUID_IDX" NOPARALLEL;
CREATE UNIQUE INDEX "UK_8UNA2HPJ3D0G9VEFJHFLF9LDC" ON "ORG_USER" ("ID");
ALTER INDEX "UK_8UNA2HPJ3D0G9VEFJHFLF9LDC" NOPARALLEL;
CREATE INDEX "ORG_JR_ROLE_UUID_IDX" ON "ORG_JOB_ROLE" ("ROLE_UUID");
ALTER INDEX "ORG_JR_ROLE_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_JOB_DUTY_UUID_IDX" ON "ORG_JOB" ("DUTY_UUID");
ALTER INDEX "ORG_JOB_DUTY_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_GU_USER_UUID_IDX" ON "ORG_GROUP_USER" ("USER_UUID");
ALTER INDEX "ORG_GU_USER_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_GNG_NESTED_GROUP_UUID_IDX" ON "ORG_GROUP_NESTED_GROUP" ("NESTED_GROUP_UUID");
ALTER INDEX "ORG_GNG_NESTED_GROUP_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_GJ_JOB_UUID_IDX" ON "ORG_GROUP_JOB" ("JOB_UUID");
ALTER INDEX "ORG_GJ_JOB_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_GDY_DUTY_UUID_IDX" ON "ORG_GROUP_DUTY" ("DUTY_UUID");
ALTER INDEX "ORG_GDY_DUTY_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_GDN_DEPARTMENT_UUID_IDX" ON "ORG_GROUP_DEPARTMENT" ("DEPARTMENT_UUID");
ALTER INDEX "ORG_GDN_DEPARTMENT_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_DUR_ROLE_UUID_IDX" ON "ORG_DUTY_ROLE" ("ROLE_UUID");
ALTER INDEX "ORG_DUR_ROLE_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_DUJ_USER_UUID_IDX" ON "ORG_DEPARTMENT_USER_JOB" ("USER_UUID");
ALTER INDEX "ORG_DUJ_USER_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_DUJ_DEPARTMENT_UUID_IDX" ON "ORG_DEPARTMENT_USER_JOB" ("DEPARTMENT_UUID");
ALTER INDEX "ORG_DUJ_DEPARTMENT_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_DR_ROLE_UUID_IDX" ON "ORG_DEPARTMENT_ROLE" ("ROLE_UUID");
ALTER INDEX "ORG_DR_ROLE_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_DPL_USER_UUID_IDX" ON "ORG_DEPARTMENT_PRINCIPAL" ("USER_UUID");
ALTER INDEX "ORG_DPL_USER_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_DPL_DEPARTMENT_UUID_IDX" ON "ORG_DEPARTMENT_PRINCIPAL" ("DEPARTMENT_UUID");
ALTER INDEX "ORG_DPL_DEPARTMENT_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_DEJ_EMPLOYEE_UUID_IDX" ON "ORG_DEPARTMENT_EMPLOYEE_JOB" ("EMPLOYEE_UUID");
ALTER INDEX "ORG_DEJ_EMPLOYEE_UUID_IDX" NOPARALLEL;
CREATE INDEX "ORG_DEJ_DEPARTMENT_UUID_IDX" ON "ORG_DEPARTMENT_EMPLOYEE_JOB" ("DEPARTMENT_UUID");
ALTER INDEX "ORG_DEJ_DEPARTMENT_UUID_IDX" NOPARALLEL;
CREATE UNIQUE INDEX "UK_K8MTRN0GB50SUQT6JLSH63DU2" ON "ORG_DEPARTMENT" ("ID");
ALTER INDEX "UK_K8MTRN0GB50SUQT6JLSH63DU2" NOPARALLEL;
CREATE INDEX "ORG_DEPARTMENT_PARENT_UUID_IDX" ON "ORG_DEPARTMENT" ("PARENT_UUID");
ALTER INDEX "ORG_DEPARTMENT_PARENT_UUID_IDX" NOPARALLEL;
CREATE UNIQUE INDEX "UK_Q5UNQ1Y61H7AER5TH007CF5WA" ON "ORG_GROUP" ("ID");
ALTER INDEX "UK_Q5UNQ1Y61H7AER5TH007CF5WA" NOPARALLEL;

-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT
ALTER TABLE "ORG_GROUP_UNIT" ADD PRIMARY KEY ("GROUP_UUID", "UNIT_UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ORG_GROUP_DUTY" ADD PRIMARY KEY ("GROUP_UUID", "DUTY_UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ORG_UNIT_SYNCHRONOUS" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ORG_USER_TRACE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ORG_USER_TRACE_PLAN" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ORG_DUTY_AGENT_AUTH" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ORG_CONTACT" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ORG_GROUP_PRIVILEGE" ADD PRIMARY KEY ("GROUP_UUID", "PRIVILEGE_UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ORG_GROUP_ROLE" ADD PRIMARY KEY ("GROUP_UUID", "ROLE_UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ORG_JOB_PRINCIPAL" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ORG_OPTION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ORG_OPTION" ADD CONSTRAINT "UK_33447WNQNPXXGRY9GGA1FNRSY" UNIQUE ("NAME")
  USING INDEX "UK_33447WNQNPXXGRY9GGA1FNRSY"  ENABLE;
ALTER TABLE "ORG_USER_MINOR_JOB" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "ORG_ENTITY_INFO" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;