-- Add/modify columns 
alter table CD_FIELD_EXT_DEFINITION add TENANT_ID VARCHAR2(64);
alter table CD_FIELD_EXT_DEFINITION add REMARK VARCHAR2(512);




-- Add/modify columns 
alter table CD_FIELD_EXT_DEFINITION modify CFG_KEY VARCHAR2(128);
alter table CD_FIELD_EXT_DEFINITION modify CFG_KEY_NAME VARCHAR2(512);
alter table CD_FIELD_EXT_DEFINITION modify VALIDATION_RULE VARCHAR2(1024);
alter table CD_FIELD_EXT_DEFINITION modify CONSTRAINT_VALUE VARCHAR2(2048);