ALTER TABLE APP_SYSTEM_LOGIN_PAGE_DEF ADD PROD_VERSION_UUID NUMBER(19);
COMMENT ON COLUMN APP_SYSTEM_LOGIN_PAGE_DEF.PROD_VERSION_UUID
  IS '归属产品版本';
 ALTER TABLE APP_SYSTEM_LOGIN_PAGE_DEF MODIFY ENABLED DEFAULT 0;



ALTER TABLE APP_SYSTEM_LOGIN_PAGE_DEF ADD IS_DEFAULT NUMBER(1) DEFAULT 0;
COMMENT ON COLUMN APP_SYSTEM_LOGIN_PAGE_DEF.IS_DEFAULT
  IS '是否默认';



INSERT INTO APP_SYSTEM_LOGIN_PAGE_DEF (
UUID,ENABLED,IS_PC,DEF_JSON,NAME,TITLE,REMARK,CREATE_TIME,CREATOR,MODIFIER , MODIFY_TIME,REC_VER,PROD_VERSION_UUID,IS_DEFAULT
)
SELECT UUID,0,IS_PC,DEF_JSON,NAME,TITLE,REMARK,CREATE_TIME,CREATOR,MODIFIER , MODIFY_TIME,REC_VER,PROD_VERSION_UUID,0 FROM APP_PROD_VERSION_LOGIN;


 ALTER TABLE USER_ACCOUNT ADD LAST_LOGIN_TIME TIMESTAMP(6);
 COMMENT ON COLUMN USER_ACCOUNT.LAST_LOGIN_TIME
  IS '最后一次登录时间';
