 INSERT INTO ORG_SETTING O (UUID ,ATTR_KEY,ATTR_VAL,REMARK)
   VALUES (24,'MY_ORG_FORCE_ASYNC_FETCH_THRESHOLD','{"num":1000}','当组织下的组织单元实例达到阈值, 将强制以异步加载组织树层级节点数据');
   
 INSERT INTO ORG_SETTING O (UUID ,ATTR_KEY,ATTR_VAL,REMARK)
   VALUES (25,'MY_ORG_USER_FORCE_ASYNC_FETCH_THRESHOLD','{"num":500}','当组织下的用户数达到阈值, 将强制以异步加载组织树下的用户数据');
   
   
   
CREATE INDEX IDX_ORG_USER_ID_VERSION_UUID ON ORG_USER (ORG_VERSION_UUID, USER_ID,ORG_ELEMENT_ID);
CREATE INDEX IDX_ID_ORG_VER_UUID ON ORG_ELEMENT (ID, ORG_VERSION_UUID, ORG_VERSION_ID);
CREATE INDEX IDX_OEPC_ID_VERSION_UUID ON ORG_ELEMENT_PATH_CHAIN (ORG_ELEMENT_ID, ORG_VERSION_UUID, SUB_ORG_ELEMENT_ID);
CREATE INDEX IDX_OEP_ID_VERSION ON ORG_ELEMENT_PATH (ORG_ELEMENT_ID, ORG_VERSION_UUID);

ALTER TABLE USER_INFO ADD WORK_STATE VARCHAR2(64) DEFAULT 'OD';
COMMENT ON COLUMN USER_INFO.WORK_STATE
  IS '工作状态';
