/*
Navicat Oracle Data Transfer
Oracle Client Version : 10.2.0.5.0

Source Server         : OA_6.0_USR_DEV
Source Server Version : 110200
Source Host           : 192.168.0.123:1521
Source Schema         : OA_USR_6_0_DEV

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2018-05-22 16:24:17
*/


-- ----------------------------
-- Table structure for OA_MY_CALENDAR_EVENT
-- ----------------------------

CREATE TABLE "OA_MY_CALENDAR_EVENT" (
"UUID" VARCHAR2(255 CHAR) NOT NULL ,
"CREATOR" VARCHAR2(255 CHAR) NULL ,
"CREATE_TIME" TIMESTAMP(6)  NULL ,
"MODIFIER" VARCHAR2(255 CHAR) NULL ,
"MODIFY_TIME" TIMESTAMP(6)  NULL ,
"REC_VER" NUMBER(10) NULL ,
"TITLE" VARCHAR2(255 CHAR) NULL ,
"START_TIME" TIMESTAMP(6)  NULL ,
"END_TIME" TIMESTAMP(6)  NULL ,
"CONTENT" CLOB NULL ,
"BELONG_OBJ_ID" VARCHAR2(255 BYTE) NULL ,
"SYSTEM_UNIT_ID" VARCHAR2(12 BYTE) NULL ,
"ADDRESS" VARCHAR2(255 BYTE) NULL ,
"REMARK" VARCHAR2(255 BYTE) NULL ,
"FILE_UUIDS" CLOB NULL ,
"JOIN_USERS" VARCHAR2(255 BYTE) NULL ,
"PUBLIC_RANGE" VARCHAR2(255 BYTE) NULL ,
"NOTICE_TYPES" VARCHAR2(255 BYTE) NULL ,
"NOTICE_OBJS" VARCHAR2(255 BYTE) NULL ,
"REPEAT_MARK_ID" VARCHAR2(255 BYTE) NULL ,
"IS_ALL" NUMBER(1) DEFAULT 0  NULL ,
"IS_REMIND" NUMBER(1) DEFAULT 0  NULL ,
"IS_REPEAT" NUMBER(1) DEFAULT 0  NULL ,
"REPEAT_CONF" VARCHAR2(255 BYTE) NULL ,
"REMIND_CONF" VARCHAR2(255 BYTE) NULL ,
"IS_FINISH" NUMBER(1) DEFAULT 0  NULL ,
"REPEAT_PERIOD_START_TIME" TIMESTAMP(0)  NULL ,
"REPEAT_PERIOD_END_TIME" TIMESTAMP(0)  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."TITLE" IS '标题';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."START_TIME" IS '开始时间';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."END_TIME" IS '结束时间';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."CONTENT" IS '事项内容';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."BELONG_OBJ_ID" IS '事项归属对象ID';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."ADDRESS" IS '地址';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."REMARK" IS '备注说明';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."FILE_UUIDS" IS '附件UUID';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."JOIN_USERS" IS '参与人ID';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."PUBLIC_RANGE" IS '公开范围';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."NOTICE_TYPES" IS '通知方式';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."NOTICE_OBJS" IS '通知对象';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."REPEAT_MARK_ID" IS '重复对象的UUID';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."IS_ALL" IS '是否全天';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."IS_REMIND" IS '是否提醒';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."IS_REPEAT" IS '是否重复';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."REPEAT_CONF" IS '重复的配置';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."REMIND_CONF" IS '提醒的配置选项';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."IS_FINISH" IS '是否完成';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."REPEAT_PERIOD_START_TIME" IS '周期开始时间';
COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."REPEAT_PERIOD_END_TIME" IS '周期结束时间';

-- ----------------------------
-- Indexes structure for table OA_MY_CALENDAR_EVENT
-- ----------------------------
CREATE INDEX "idx_repeatMarkId"
ON "OA_MY_CALENDAR_EVENT" ("REPEAT_MARK_ID" ASC)
LOGGING
VISIBLE;

-- ----------------------------
-- Checks structure for table OA_MY_CALENDAR_EVENT
-- ----------------------------
ALTER TABLE "OA_MY_CALENDAR_EVENT" ADD CHECK ("UUID" IS NOT NULL);
ALTER TABLE "OA_MY_CALENDAR_EVENT" ADD CHECK ("UUID" IS NOT NULL);
ALTER TABLE "OA_MY_CALENDAR_EVENT" ADD CHECK ("UUID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table OA_MY_CALENDAR_EVENT
-- ----------------------------
ALTER TABLE "OA_MY_CALENDAR_EVENT" ADD PRIMARY KEY ("UUID");
