ALTER TABLE "OA_MY_CALENDAR_EVENT"
ADD ( "PART_USERS" VARCHAR2(255) NULL  ) ;

COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."PART_USERS" IS '部分用户可见';

ALTER TABLE "OA_MY_CALENDAR_EVENT"
ADD ( "CALENDAR_CREATOR_NAME" VARCHAR2(255) NULL  ) ;

COMMENT ON COLUMN "OA_MY_CALENDAR_EVENT"."CALENDAR_CREATOR_NAME" IS '日历本创建者用户名';



