CREATE TABLE SN_SERIAL_NUMBER_CATEGORY
(
    "UUID"           VARCHAR2(50 CHAR),
    "CREATE_TIME"    TIMESTAMP(6),
    "CREATOR"        VARCHAR2(50 CHAR),
    "MODIFIER"       VARCHAR2(50 CHAR),
    "MODIFY_TIME"    TIMESTAMP(6),
    "REC_VER"        NUMBER(10, 0),
    "SYSTEM_UNIT_ID" VARCHAR2(12),
    "NAME"           VARCHAR2(200 CHAR),
    "CODE"           VARCHAR2(50 CHAR),
    "ICON"           VARCHAR2(120),
    "ICON_COLOR"     VARCHAR2(12),
    "REMARK"         VARCHAR2(300),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE SN_SERIAL_NUMBER_CATEGORY IS '流水号分类';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_CATEGORY.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_CATEGORY.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_CATEGORY.CREATOR IS '创建人';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_CATEGORY.MODIFIER IS '修改人';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_CATEGORY.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_CATEGORY.REC_VER IS '版本号';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_CATEGORY.SYSTEM_UNIT_ID IS '归属系统单位';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_CATEGORY.NAME IS '名称';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_CATEGORY.CODE IS '编号';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_CATEGORY.ICON IS '字体图标样式类';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_CATEGORY.ICON_COLOR IS '图标颜色';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_CATEGORY.REMARK IS '描述';



CREATE TABLE SN_SERIAL_NUMBER_DEFINITION
(
    "UUID"                 VARCHAR2(50 CHAR),
    "CREATE_TIME"          TIMESTAMP(6),
    "CREATOR"              VARCHAR2(50 CHAR),
    "MODIFIER"             VARCHAR2(50 CHAR),
    "MODIFY_TIME"          TIMESTAMP(6),
    "REC_VER"              NUMBER(10, 0),
    "SYSTEM_UNIT_ID"       VARCHAR2(12),
    "NAME"                 VARCHAR2(200 CHAR),
    "ID"                   VARCHAR2(50 CHAR),
    "CODE"                 VARCHAR2(50 CHAR),
    "CATEGORY_UUID"        VARCHAR2(50 CHAR),
    "MODULE_ID"            VARCHAR2(50 CHAR),
    "PREFIX"               VARCHAR2(100 CHAR),
    "INITIAL_VALUE"        VARCHAR2(10 CHAR),
    "INCREMENTAL"          NUMBER(10),
    "DEFAULT_DIGITS"       NUMBER(10),
    "SUFFIX"               VARCHAR2(100 CHAR),
    "ENABLE_POINTER_RESET" NUMBER(1),
    "POINTER_RESET_TYPE"   VARCHAR2(10 CHAR),
    "POINTER_RESET_RULE"   VARCHAR2(100 CHAR),
    "NEXT_YEAR_START_DATE" VARCHAR2(10 CHAR),
    "OWNER_IDS"            VARCHAR2(500 CHAR),
    "OWNER_NAMES"          VARCHAR2(500 CHAR),
    "REMARK"               VARCHAR2(300 CHAR),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE SN_SERIAL_NUMBER_DEFINITION IS '流水号定义';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.CREATOR IS '创建人';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.MODIFIER IS '修改人';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.REC_VER IS '版本号';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.SYSTEM_UNIT_ID IS '归属系统单位';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.NAME IS '名称';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.ID IS 'ID';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.CODE IS '编号';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.CATEGORY_UUID IS '分类UUID';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.MODULE_ID IS '模块ID';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.PREFIX IS '前缀';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.INITIAL_VALUE IS '指针初始值';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION."INCREMENTAL" IS '指针增量';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.DEFAULT_DIGITS IS '指针默认位数';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.SUFFIX IS '后缀';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.ENABLE_POINTER_RESET IS '是否启用指针自动重置';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.POINTER_RESET_TYPE IS '1按周期重置、2按变量重置';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.POINTER_RESET_RULE IS '指针重置规则';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.NEXT_YEAR_START_DATE IS '下一年新年度开始日期，默认值为 01-01';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.OWNER_IDS IS '使用人ID，多个以分号隔开';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.OWNER_NAMES IS '使用人名称，多个以分号隔开';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_DEFINITION.REMARK IS '描述';



CREATE TABLE SN_SERIAL_NUMBER_MAINTAIN
(
    "UUID"                     VARCHAR2(50 CHAR),
    "CREATE_TIME"              TIMESTAMP(6),
    "CREATOR"                  VARCHAR2(50 CHAR),
    "MODIFIER"                 VARCHAR2(50 CHAR),
    "MODIFY_TIME"              TIMESTAMP(6),
    "REC_VER"                  NUMBER(10, 0),
    "SYSTEM_UNIT_ID"           VARCHAR2(12),
    "SERIAL_NUMBER_DEF_UUID"   VARCHAR2(50 CHAR),
    "INITIAL_VALUE"            VARCHAR2(10 CHAR),
    "POINTER"                  VARCHAR2(100 CHAR),
    "POINTER_RESET_TYPE"       VARCHAR2(10 CHAR),
    "POINTER_RESET_RULE"       VARCHAR2(100 CHAR),
    "POINTER_RESET_RULE_VALUE" VARCHAR2(100 CHAR),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE SN_SERIAL_NUMBER_MAINTAIN IS '流水号定义';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.CREATOR IS '创建人';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.MODIFIER IS '修改人';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.REC_VER IS '版本号';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.SYSTEM_UNIT_ID IS '归属系统单位';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.SERIAL_NUMBER_DEF_UUID IS '流水号定义UUID';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.INITIAL_VALUE IS '指针初始值';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.POINTER IS '指针';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.POINTER_RESET_TYPE IS '1按周期重置、2按变量重置';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.POINTER_RESET_RULE IS '指针重置规则';
COMMENT
    ON COLUMN SN_SERIAL_NUMBER_MAINTAIN.POINTER_RESET_RULE_VALUE IS '指针重置规则值';



CREATE TABLE SN_SERIAL_NUMBER_RELATION
(
    "UUID"           VARCHAR2(50),
    "CREATE_TIME"    TIMESTAMP(6),
    "CREATOR"        VARCHAR2(50),
    "MODIFIER"       VARCHAR2(50),
    "MODIFY_TIME"    TIMESTAMP(6),
    "REC_VER"        NUMBER(10, 0),
    "SYSTEM_UNIT_ID" VARCHAR2(64),
    "SN_ID"          VARCHAR2(50)  NOT NULL ENABLE,
    "OBJECT_TYPE"    NUMBER(1, 0)  NOT NULL ENABLE,
    "OBJECT_NAME"    VARCHAR2(255) NOT NULL ENABLE,
    "FIELD_NAME"     VARCHAR2(255) NOT NULL ENABLE,
    PRIMARY KEY ("UUID")
);

COMMENT ON TABLE SN_SERIAL_NUMBER_RELATION IS '流水号关联表字段记录';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RELATION.UUID IS 'UUID，系统字段';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RELATION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RELATION.CREATOR IS '创建人';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RELATION.MODIFIER IS '更新人';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RELATION.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RELATION.REC_VER IS '数据版本';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RELATION.SYSTEM_UNIT_ID IS '系统单位ID';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RELATION.SN_ID IS '流水号定义ID';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RELATION.OBJECT_TYPE IS '对象类型：1：数据库表';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RELATION.OBJECT_NAME IS '对象名';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RELATION.FIELD_NAME IS '字段名';



CREATE TABLE SN_SERIAL_NUMBER_RECORD
(
    "UUID"           VARCHAR2(50),
    "CREATE_TIME"    TIMESTAMP(6),
    "CREATOR"        VARCHAR2(50),
    "MODIFIER"       VARCHAR2(50),
    "MODIFY_TIME"    TIMESTAMP(6),
    "REC_VER"        NUMBER(10, 0),
    "SYSTEM_UNIT_ID" VARCHAR2(64),
    "RELATION_UUID"  VARCHAR2(50)  NOT NULL ENABLE,
    "MAINTAIN_UUID"  VARCHAR2(50)  NOT NULL ENABLE,
    "PREFIX"         VARCHAR2(100),
    "POINTER"        NUMBER(16)    NOT NULL ENABLE,
    "SUFFIX"         VARCHAR2(100),
    "SERIAL_NO"      VARCHAR2(255) NOT NULL ENABLE,
    PRIMARY KEY ("UUID")
);

COMMENT ON TABLE SN_SERIAL_NUMBER_RECORD IS '流水号记录';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.UUID IS 'UUID，系统字段';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.CREATOR IS '创建人';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.MODIFIER IS '更新人';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.MODIFY_TIME IS '更新时间';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.REC_VER IS '数据版本';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.SYSTEM_UNIT_ID IS '系统单位ID';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.RELATION_UUID IS '流水号关联表字段记录UUID';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.MAINTAIN_UUID IS '流水号关联表字段记录UUID';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.PREFIX IS '前缀';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.POINTER IS '指针';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.SUFFIX IS '后缀';
COMMENT ON COLUMN SN_SERIAL_NUMBER_RECORD.SERIAL_NO IS '流水号';
