CREATE TABLE DYFORM_CATEGORY
(
    "UUID"        NUMBER(20, 0) NOT NULL,
    "CREATE_TIME" TIMESTAMP(6),
    "CREATOR"     VARCHAR2(50 CHAR),
    "MODIFIER"    VARCHAR2(50 CHAR),
    "MODIFY_TIME" TIMESTAMP(6),
    "REC_VER"     NUMBER(10, 0),
    "SYSTEM"      VARCHAR2(64),
    "TENANT"      VARCHAR2(64),
    "NAME"        VARCHAR2(64 CHAR),
    "CODE"        VARCHAR2(50 CHAR),
    "ICON"        VARCHAR2(100),
    "ICON_COLOR"  VARCHAR2(10),
    "REMARK"      VARCHAR2(300 CHAR),
    "PARENT_UUID" NUMBER(20, 0) NULL,
    "MODULE_ID"   VARCHAR2(64),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE DYFORM_CATEGORY IS '表单分类';
COMMENT
    ON COLUMN DYFORM_CATEGORY.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN DYFORM_CATEGORY.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN DYFORM_CATEGORY.CREATOR IS '创建人';
COMMENT
    ON COLUMN DYFORM_CATEGORY.MODIFIER IS '修改人';
COMMENT
    ON COLUMN DYFORM_CATEGORY.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN DYFORM_CATEGORY.REC_VER IS '版本号';
COMMENT
    ON COLUMN DYFORM_CATEGORY.SYSTEM IS '归属系统';
COMMENT
    ON COLUMN DYFORM_CATEGORY.TENANT IS '归属租户';
COMMENT
    ON COLUMN DYFORM_CATEGORY.NAME IS '名称';
COMMENT
    ON COLUMN DYFORM_CATEGORY.CODE IS '编号';
COMMENT
    ON COLUMN DYFORM_CATEGORY.ICON IS '字体图标样式类';
COMMENT
    ON COLUMN DYFORM_CATEGORY.ICON_COLOR IS '图标颜色';
COMMENT
    ON COLUMN DYFORM_CATEGORY.REMARK IS '描述';
COMMENT
    ON COLUMN DYFORM_CATEGORY.PARENT_UUID IS '上级分类UUID';
COMMENT
    ON COLUMN DYFORM_CATEGORY.MODULE_ID IS '模块ID';

alter table dyform_form_definition
    add category_uuid NUMBER(20, 0);
comment on column dyform_form_definition.category_uuid is '分类UUID';