alter table CD_DATA_STORE_DEFINITION
    add DATA_INTERFACE_PARAM_CLOB clob;
update CD_DATA_STORE_DEFINITION t1
set t1.DATA_INTERFACE_PARAM_CLOB = t1.DATA_INTERFACE_PARAM;
commit;
alter table CD_DATA_STORE_DEFINITION rename column DATA_INTERFACE_PARAM to DATA_INTERFACE_PARAM_BAK;
alter table CD_DATA_STORE_DEFINITION rename column DATA_INTERFACE_PARAM_CLOB to DATA_INTERFACE_PARAM;
