alter table TS_TIMER
    add OVER_DUE_TIME TIMESTAMP(6);

alter table TS_TIMER
    add ENABLE_ALARM NUMBER(1);

COMMENT
    ON COLUMN TS_TIMER.OVER_DUE_TIME IS '逾期时间';
COMMENT
    ON COLUMN TS_TIMER.ENABLE_ALARM IS '是否启用预警';


CREATE TABLE TS_TIMER_ALARM
(
    "UUID"                NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"         TIMESTAMP(6),
    "CREATOR"             VARCHAR2(50 CHAR),
    "MODIFIER"            VARCHAR2(50 CHAR),
    "MODIFY_TIME"         TIMESTAMP(6),
    "REC_VER"             NUMBER(10, 0),
    "ID"                  VARCHAR2(50),
    "TIME_LIMIT"          NUMBER(10, 1),
    "TIMING_MODE"         VARCHAR2(6 char),
    "TOTAL_ALARM_COUNT"   NUMBER(10),
    "CURRENT_ALARM_COUNT" NUMBER(10),
    "ALARM_TIME"          TIMESTAMP(6),
    "ALARM_DOING_DONE"    NUMBER(1),
    "DELETE_STATUS"       NUMBER(1),
    "TIMER_UUID"          VARCHAR2(50 char),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE TS_TIMER_ALARM IS '计时器预警';
COMMENT
    ON COLUMN TS_TIMER_ALARM.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN TS_TIMER_ALARM.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN TS_TIMER_ALARM.CREATOR IS '创建人';
COMMENT
    ON COLUMN TS_TIMER_ALARM.MODIFIER IS '修改人';
COMMENT
    ON COLUMN TS_TIMER_ALARM.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN TS_TIMER_ALARM.REC_VER IS '版本号';
COMMENT
    ON COLUMN TS_TIMER_ALARM.ID IS '预警ID';
COMMENT
    ON COLUMN TS_TIMER_ALARM.TIME_LIMIT IS '预警时限';
COMMENT
    ON COLUMN TS_TIMER_ALARM.TIMING_MODE IS '计时方式';
COMMENT
    ON COLUMN TS_TIMER_ALARM.TOTAL_ALARM_COUNT IS '提醒总次数';
COMMENT
    ON COLUMN TS_TIMER_ALARM.CURRENT_ALARM_COUNT IS '当前已提醒次数';
COMMENT
    ON COLUMN TS_TIMER_ALARM.ALARM_TIME IS '预警时间';
COMMENT
    ON COLUMN TS_TIMER_ALARM.ALARM_DOING_DONE IS '预警处理是否已经处理完成';
COMMENT
    ON COLUMN TS_TIMER_ALARM.DELETE_STATUS IS '预警删除状态,0正常，1删除';
COMMENT
    ON COLUMN TS_TIMER_ALARM.TIMER_UUID IS '计时器UUID';

create index TS_TA_TIMER_UUID on TS_TIMER_ALARM (TIMER_UUID);