-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
CREATE TABLE "MAIL_CLEAN" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "DAYS" NUMBER(10,0), 
  "STATUS" VARCHAR2(2 CHAR), 
  "USER_NAME" VARCHAR2(64 CHAR)
   ) ;
CREATE TABLE "MAIL_DISPLAYSET" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ADD_TO" VARCHAR2(2 CHAR), 
  "AUTO_SEND_OTHER_FLAG" VARCHAR2(2 CHAR), 
  "AUTO_SENDTO" VARCHAR2(64 CHAR), 
  "HAS_AUTO_SEND_FLAG" VARCHAR2(2 CHAR), 
  "LIST_VIEW" VARCHAR2(2 CHAR), 
  "REPLY_FLAG" VARCHAR2(2 CHAR), 
  "REPLY_TITLE_FLAG" VARCHAR2(2 CHAR), 
  "SEND_FLAG1" VARCHAR2(2 CHAR), 
  "SEND_FLAG2" VARCHAR2(2 CHAR), 
  "SEND_FLAG3" VARCHAR2(2 CHAR), 
  "SIGN" VARCHAR2(255 CHAR), 
  "USER_NAME" VARCHAR2(64 CHAR)
   ) ;
CREATE TABLE "MAIL_FETCH_HISTORY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "M_ID" VARCHAR2(255 CHAR), 
  "USER_NO" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MAIL_FOLDERS" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "COLOR" VARCHAR2(20 CHAR), 
  "FNAME" VARCHAR2(255 CHAR), 
  "STATUS" VARCHAR2(2 CHAR)
   ) ;
CREATE TABLE "MAIL_GROUP_USER" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "GROUP_ID" VARCHAR2(255 CHAR), 
  "GTYPE" NUMBER(10,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "USERNAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MAIL_LABEL_RELATION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "LABEL_UUID" VARCHAR2(255 CHAR), 
  "MAIL_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MAIL_OPERATION_HISTORY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "GROUP_NAME" VARCHAR2(255 CHAR), 
  "OPERATION" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MAIL_OTHER_CONFIG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ADDRESS" VARCHAR2(255 CHAR), 
  "ALIES_NAME" VARCHAR2(255 CHAR), 
  "IMAP" VARCHAR2(255 CHAR), 
  "IMAP_PORT" NUMBER(10,0), 
  "KEEP_ON_SERVER" NUMBER(1,0), 
  "MAILSPACE" NUMBER(10,0), 
  "METHOD" NUMBER(1,0), 
  "PASSWORD" VARCHAR2(255 CHAR), 
  "POP3" VARCHAR2(255 CHAR), 
  "POP3PORT" NUMBER(10,0), 
  "SMTP" VARCHAR2(255 CHAR), 
  "SMTP_PORT" NUMBER(10,0), 
  "USER_ID" VARCHAR2(64 CHAR), 
  "USERNAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MAIL_OTHER_RECEIVE_HISTORY" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "MAIL_NAME" VARCHAR2(255 CHAR), 
  "METHOD" VARCHAR2(255 CHAR), 
  "RECEIVE_MSG" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MAIL_POPNAME" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "IMAP_NAME" VARCHAR2(255 CHAR), 
  "IMAP_PORT" VARCHAR2(255 CHAR), 
  "POP_NAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MAIL_TEMP_FILES" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "FILE_MID" VARCHAR2(255 CHAR), 
  "FILE_NAME" VARCHAR2(255 CHAR), 
  "FILE_SIZE" VARCHAR2(15 CHAR), 
  "FILE_TYPE" VARCHAR2(10 CHAR)
   ) ;
CREATE TABLE "MAIL_CONFIG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ADDRESS" VARCHAR2(255 CHAR), 
  "KEEP_ON_SERVER" NUMBER(1,0), 
  "MAILSPACE" NUMBER(10,0), 
  "PASSWORD" VARCHAR2(255 CHAR), 
  "POP3" VARCHAR2(255 CHAR), 
  "POP3PORT" NUMBER(10,0), 
  "SMTP" VARCHAR2(255 CHAR), 
  "SMTP_PORT" NUMBER(10,0), 
  "USERNAME" VARCHAR2(255 CHAR), 
  "IMAP" VARCHAR2(255 CHAR), 
  "IMAP_PORT" NUMBER(10,0)
   ) ;
CREATE TABLE "MAIL_FILES" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "FILE_MID" VARCHAR2(255 CHAR), 
  "FILE_NAME" VARCHAR2(255 CHAR), 
  "FILE_SIZE" VARCHAR2(15 CHAR), 
  "FILE_STATUS" VARCHAR2(2 CHAR), 
  "FILE_TYPE" VARCHAR2(10 CHAR), 
  "USER_NAME" VARCHAR2(64 CHAR)
   ) ;
CREATE TABLE "MAIL_USERS" 
   (  "USERNAME" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
  "ALIAS" VARCHAR2(255 CHAR), 
  "CONFIG_ID" VARCHAR2(255 CHAR), 
  "DISPLAY_SET_ID" VARCHAR2(255 CHAR), 
  "FORWARD_DESTINATION" VARCHAR2(255 CHAR), 
  "PWD_ALGORITHM" VARCHAR2(255 CHAR), 
  "PWD_HASH" VARCHAR2(255 CHAR), 
  "REAL_NAME" VARCHAR2(255 CHAR), 
  "STATUS" NUMBER(5,0), 
  "USE_ALIAS" NUMBER(5,0), 
  "USE_FORWARDING" NUMBER(5,0), 
  "USERPASS" VARCHAR2(255 CHAR), 
  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0)
   ) ;
CREATE TABLE "MAIL_USER_CONTACTOR" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "MAIL_NAME" VARCHAR2(255 CHAR), 
  "USER_NO" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "JAMES_MAIL_ASYNC" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "MAILBOX_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "MAIL_UID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "MAIL_GBOX" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ADD_TIP" CLOB, 
  "ATTACHMENT" CLOB, 
  "BCC" CLOB, 
  "CC" CLOB, 
  "DINGSHI" VARCHAR2(2 CHAR), 
  "ERROR_MESSAGE" VARCHAR2(255 CHAR), 
  "FILE_MID" CLOB, 
  "SENDER" VARCHAR2(255 CHAR), 
  "FROM_USERNAME" VARCHAR2(255 CHAR), 
  "GROUP_NAME" VARCHAR2(255 CHAR), 
  "IS_READ" VARCHAR2(255 CHAR), 
  "MAIL_TYPE" VARCHAR2(2 CHAR), 
  "MID" VARCHAR2(255 CHAR), 
  "MNUM" VARCHAR2(255 CHAR), 
  "MTYPE" VARCHAR2(2 CHAR), 
  "NYMDHS" VARCHAR2(30 CHAR), 
  "SCOLOR" VARCHAR2(20 CHAR), 
  "SEND_DATE" VARCHAR2(255 CHAR), 
  "SEND_STATUS" VARCHAR2(2 CHAR), 
  "STAR" VARCHAR2(255 CHAR), 
  "MSTATUS" VARCHAR2(255 CHAR), 
  "SUBJECT" VARCHAR2(255 CHAR), 
  "SUID" VARCHAR2(255 CHAR), 
  "TEXT" CLOB, 
  "RECIPIENTS" CLOB, 
  "TO_USERNAME" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MAIL_JAMES_INBOX" 
   (  "MESSAGE_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
  "REPOSITORY_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "ERROR_MESSAGE" VARCHAR2(255 CHAR), 
  "LAST_UPDATED" TIMESTAMP (6), 
  "MESSAGE_ATTRIBUTES" BLOB, 
  "MESSAGE_BODY" BLOB, 
  "MESSAGE_STATE" VARCHAR2(255 CHAR), 
  "RECIPIENTS" VARCHAR2(255 CHAR), 
  "REMOTE_ADDR" VARCHAR2(255 CHAR), 
  "REMOTE_HOST" VARCHAR2(255 CHAR), 
  "SENDER" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "MAIL_RULE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "MAIL_SIZE1" VARCHAR2(2 CHAR), 
  "MAIL_SIZE2" VARCHAR2(2 CHAR), 
  "MAIL_SIZE3" VARCHAR2(15 CHAR), 
  "MOVE_FILE1" VARCHAR2(2 CHAR), 
  "MOVE_FILE2" VARCHAR2(255 CHAR), 
  "OPERATION" VARCHAR2(2 CHAR), 
  "QIYONG" VARCHAR2(2 CHAR), 
  "RECEIVE_PERSON1" VARCHAR2(2 CHAR), 
  "RECEIVE_PERSON2" VARCHAR2(2 CHAR), 
  "RECEIVE_PERSON3" VARCHAR2(64 CHAR), 
  "RECEIVE_TIME1" VARCHAR2(2 CHAR), 
  "RECEIVE_TIME2" VARCHAR2(8 CHAR), 
  "RECEIVE_TIME3" VARCHAR2(8 CHAR), 
  "REPLY" VARCHAR2(2 CHAR), 
  "REPLY_TEXT" CLOB, 
  "RULE_NAME" VARCHAR2(255 CHAR), 
  "SEND_DOMAIN1" VARCHAR2(2 CHAR), 
  "SEND_DOMAIN2" VARCHAR2(2 CHAR), 
  "SEND_DOMAIN3" VARCHAR2(64 CHAR), 
  "SEND_OTHER1" VARCHAR2(2 CHAR), 
  "SEND_OTHER2" VARCHAR2(64 CHAR), 
  "SEND_OTHER3" VARCHAR2(2 CHAR), 
  "SEND_PERSON1" VARCHAR2(2 CHAR), 
  "SEND_PERSON2" VARCHAR2(2 CHAR), 
  "SEND_PERSON3" VARCHAR2(64 CHAR), 
  "SET_READ" VARCHAR2(2 CHAR), 
  "SET_STAR" VARCHAR2(2 CHAR), 
  "TITLE1" VARCHAR2(2 CHAR), 
  "TITLE2" VARCHAR2(2 CHAR), 
  "TITLE3" VARCHAR2(64 CHAR), 
  "USER_NAME" VARCHAR2(64 CHAR)
   ) ;
CREATE TABLE "MAIL_SIGN" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "SIGN_NAME" VARCHAR2(255 CHAR), 
  "SIGN_TEXT" CLOB, 
  "USER_NAME" VARCHAR2(64 CHAR)
   ) ;
CREATE TABLE "MAIL_BOX" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ATTACHMENT" CLOB, 
  "BCC" CLOB, 
  "CC" CLOB, 
  "DINGSHI" VARCHAR2(2 CHAR), 
  "ERROR_MESSAGE" VARCHAR2(255 CHAR), 
  "FILE_MID" CLOB, 
  "SENDER" VARCHAR2(255 CHAR), 
  "FROM_USERNAME" VARCHAR2(255 CHAR), 
  "GROUP_NAME" VARCHAR2(255 CHAR), 
  "IS_READ" VARCHAR2(255 CHAR), 
  "LABEL_COLOR" VARCHAR2(255 CHAR), 
  "LABEL_NAME" VARCHAR2(255 CHAR), 
  "LABEL_UUID" VARCHAR2(4000 CHAR), 
  "MAIL_TYPE" VARCHAR2(255 CHAR), 
  "MID" VARCHAR2(255 CHAR), 
  "MNUM" VARCHAR2(255 CHAR), 
  "MTYPE" VARCHAR2(2 CHAR), 
  "NYMDHS" VARCHAR2(30 CHAR), 
  "OTHER_MAILNAME" VARCHAR2(255 CHAR), 
  "SCOLOR" VARCHAR2(20 CHAR), 
  "SEND_DATE" VARCHAR2(255 CHAR), 
  "SEND_STATUS" VARCHAR2(2 CHAR), 
  "STAR" VARCHAR2(255 CHAR), 
  "MSTATUS" VARCHAR2(255 CHAR), 
  "SUBJECT" VARCHAR2(255 CHAR), 
  "SUID" VARCHAR2(255 CHAR), 
  "TEXT" CLOB, 
  "RECIPIENTS" CLOB, 
  "TO_USERNAME" VARCHAR2(255 CHAR), 
  "RECEIVERS" VARCHAR2(2000 CHAR)
   ) ;   
CREATE TABLE "JAMES_MAIL" 
   (  "MAILBOX_ID" NUMBER NOT NULL ENABLE, 
  "MAIL_UID" NUMBER NOT NULL ENABLE, 
  "MAIL_IS_ANSWERED" NUMBER NOT NULL ENABLE, 
  "MAIL_BODY_START_OCTET" NUMBER NOT NULL ENABLE, 
  "MAIL_CONTENT_OCTETS_COUNT" NUMBER NOT NULL ENABLE, 
  "MAIL_IS_DELETED" NUMBER NOT NULL ENABLE, 
  "MAIL_IS_DRAFT" NUMBER NOT NULL ENABLE, 
  "MAIL_IS_FLAGGED" NUMBER NOT NULL ENABLE, 
  "MAIL_DATE" TIMESTAMP (6), 
  "MAIL_MIME_TYPE" VARCHAR2(200 BYTE), 
  "MAIL_MODSEQ" NUMBER, 
  "MAIL_IS_RECENT" NUMBER NOT NULL ENABLE, 
  "MAIL_IS_SEEN" NUMBER NOT NULL ENABLE, 
  "MAIL_MIME_SUBTYPE" VARCHAR2(200 BYTE), 
  "MAIL_TEXTUAL_LINE_COUNT" NUMBER, 
  "MAIL_BYTES" BLOB NOT NULL ENABLE, 
  "HEADER_BYTES" BLOB NOT NULL ENABLE, 
  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0)
   ) ;
   
CREATE TABLE "JAMES_MAILBOX" 
   (  "MAILBOX_ID" NUMBER NOT NULL ENABLE, 
  "MAILBOX_HIGHEST_MODSEQ" NUMBER NOT NULL ENABLE, 
  "MAILBOX_LAST_UID" NUMBER NOT NULL ENABLE, 
  "MAILBOX_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
  "MAILBOX_NAMESPACE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
  "MAILBOX_UID_VALIDITY" NUMBER NOT NULL ENABLE, 
  "USER_NAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0)
   ) ;
   
-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/INDEX
CREATE INDEX "MAIL_USERS_CONFIG_ID_IDX" ON "MAIL_USERS" ("CONFIG_ID");
ALTER INDEX "MAIL_USERS_CONFIG_ID_IDX" NOPARALLEL;

CREATE INDEX "MAIL_USERS_DISPLAY_SET_ID_IDX" ON "MAIL_USERS" ("DISPLAY_SET_ID");
ALTER INDEX "MAIL_USERS_DISPLAY_SET_ID_IDX" NOPARALLEL;

ALTER TABLE "MAIL_CONFIG" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "MAIL_FILES" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "MAIL_USERS" ADD PRIMARY KEY ("USERNAME")
  USING INDEX  ENABLE;
ALTER TABLE "MAIL_USER_CONTACTOR" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;