
--------------------------用户中文登录-------------------------------------
CREATE TABLE MULTI_USER_LOGIN_SETTINGS
(
  UUID                   VARCHAR2(64) NOT NULL,
  ACCOUNT_ALIAS          VARCHAR2(100),
  ACCOUNT_ZH_ENABLE      CHAR(1),
  ACCOUNT_ZH_ALIAS       VARCHAR2(100),
  REC_VER                NUMBER(10,2),
  CREATE_TIME            TIMESTAMP(6),
  CREATOR                VARCHAR2(255),
  MODIFIER               VARCHAR2(255),
  MODIFY_TIME            TIMESTAMP(6),
  SYSTEM_UNIT_ID         VARCHAR2(64),
  NAME_EN_ENABLE         CHAR(1),
  NAME_EN_ALIAS          VARCHAR2(100),
  TELL_ENABLE            CHAR(1),
  TELL_ALIAS             VARCHAR2(100),
  IDENTIFIER_CODE_ENABLE CHAR(1),
  IDENTIFIER_CODE_ALIAS  VARCHAR2(100),
  EMAIL_ENABLE           CHAR(1),
  EMAIL_ALIAS            VARCHAR2(100),
  EMP_CODE_ENABLE        CHAR(1),
  EMP_CODE_ALIAS         VARCHAR2(100),
  CONSTRAINT PK_MULTI_USER_LOGIN_SETTINGS PRIMARY KEY (UUID)
);

COMMENT ON TABLE MULTI_USER_LOGIN_SETTINGS
  IS '用户登录配置';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.ACCOUNT_ALIAS
  IS '账户别名';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.ACCOUNT_ZH_ENABLE
  IS '是否启用中文账户';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.ACCOUNT_ZH_ALIAS
  IS '中文账户别名';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.REC_VER
  IS '版本号';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.CREATE_TIME
  IS '创建时间';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.CREATOR
  IS '创建人';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.MODIFIER
  IS '更新人';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.MODIFY_TIME
  IS '更新时间';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.SYSTEM_UNIT_ID
  IS '系统单位ID';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.NAME_EN_ENABLE
  IS '是否启用英文名';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.NAME_EN_ALIAS
  IS '英文名别名';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.TELL_ENABLE
  IS '是否启用手机号';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.TELL_ALIAS
  IS '手机号别名';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.IDENTIFIER_CODE_ENABLE
  IS '是否启用身份证号';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.IDENTIFIER_CODE_ALIAS
  IS '身份证号别名';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.EMAIL_ENABLE
  IS '是否启用邮箱';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.EMAIL_ALIAS
  IS '邮箱别名';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.EMP_CODE_ENABLE
  IS '是否启用员工编号';
COMMENT ON COLUMN MULTI_USER_LOGIN_SETTINGS.EMP_CODE_ALIAS
  IS '员工编号别名';
  
  
-- Add/modify columns 
ALTER TABLE MULTI_ORG_USER_ACCOUNT ADD LOGIN_NAME_ZH VARCHAR2(255);
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN MULTI_ORG_USER_ACCOUNT.LOGIN_NAME_ZH
  IS '中文用户名';
  
UPDATE MULTI_ORG_USER_ACCOUNT SET LOGIN_NAME_ZH = USER_NAME;