
ALTER TABLE `MULTI_ORG_JOB_RANK` ADD COLUMN `JOB_RANK` VARCHAR(30) COMMENT '职级',
                                 ADD COLUMN `DESCRIBE` VARCHAR(1000) COMMENT '描述',
                                 ADD COLUMN `DUTY_SEQ_UUID` VARCHAR(64) COMMENT '职务序列UUID',
								 ADD COLUMN `JOB_GRADE` NUMBER(4) COMMENT '职等',
								 ADD COLUMN `JOB_LEVEL` VARCHAR2(10) COMMENT '职档';

ALTER TABLE `MULTI_ORG_DUTY` ADD COLUMN `DUTY_SEQ_UUID` VARCHAR(64) COMMENT '职务序列UUID',
							 ADD COLUMN `DUTY_SEQ_NAME` VARCHAR(255) COMMENT '职务序列名称',
							 ADD COLUMN `JOB_RANK` VARCHAR(1000) COMMENT '职级',
							 ADD COLUMN `JOB_GRADE` VARCHAR(1000) COMMENT '职等';
  
  
 -- ADD/MODIFY COLUMNS 
ALTER TABLE `MULTI_ORG_USER_WORK_INFO` ADD COLUMN `JOB_RANK` VARCHAR(30) COMMENT '职级',
									 ADD COLUMN `JOB_LEVEL` VARCHAR(255) COMMENT '职档';
 
drop table if exists `UNIT_PARAM`;
CREATE TABLE `UNIT_PARAM`
(
	`UUID`           VARCHAR(64)   NOT NULL COMMENT 'UUID',
	`Param_KEY`            VARCHAR(255) COMMENT '保存KEY',
	`Param_VALUE`          VARCHAR(500) COMMENT '保存VALUE',
	`REMARK`         VARCHAR(1000) COMMENT '备注',
	`REC_VER`       DECIMAL(10,2) COMMENT '版本号',
	`SYSTEM_UNIT_ID` VARCHAR(255) COMMENT '系统单位Id',
	`CREATE_TIME`         TIMESTAMP COMMENT '创建时间',
	`CREATOR`              VARCHAR(255) COMMENT '创建人',
	`MODIFIER`             VARCHAR(255) COMMENT '修改人',
	`MODIFY_TIME`         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`UUID`)
)COMMENT='单位参数表';

 
drop table if exists `ORG_DUTY_SEQ`;
  -- CREATE TABLE
CREATE TABLE `ORG_DUTY_SEQ`
(
  `UUID`           VARCHAR(64)   NOT NULL COMMENT '主键UUID',
  `DUTY_SEQ_CODE`           VARCHAR(50) COMMENT '职务序列编号',
  `DUTY_SEQ_NAME`           VARCHAR(50) COMMENT '职务序列名称',
  `ICON`           VARCHAR(200) COMMENT '图标',
  `BACKGROUND_COLOR`     VARCHAR(255) COMMENT '背景色',
  `DESCRIBE`       VARCHAR(1000) COMMENT '描述',
  `PARENT_UUID`    VARCHAR(64) COMMENT '父类UUID',
  `REC_VER`       DECIMAL(10,2) COMMENT '版本号',
  `SYSTEM_UNIT_ID` VARCHAR(255) COMMENT '系统单位ID',
  `CREATE_TIME`    TIMESTAMP COMMENT '创建时间',
  `CREATOR`        VARCHAR(255) COMMENT '创建人',
  `MODIFY_TIME`    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `MODIFIER`       VARCHAR(255) COMMENT '更新人',
   PRIMARY KEY (`UUID`)
)COMMENT ='职务序列';

  
drop table if exists `ORG_JOB_GRADE`;
  
CREATE TABLE `ORG_JOB_GRADE`
(
   `UUID`                 VARCHAR(255)   NOT NULL COMMENT '唯一主键',
   `JOB_GRADE`            int(4) COMMENT '职等',
   `JOB_GRADE_NAME`       VARCHAR(50) COMMENT '职等名字',
   `DESCRIBE`            VARCHAR(1000) COMMENT '描述',
   `IS_VALID`       CHAR(1) comment '是否有效：1有效,0无效',
   `IS_EXCEPTION`   CHAR(1) comment '是否异常：1异常，0无异常',
   `REC_VER`       DECIMAL(10,2) COMMENT '版本号',
   `SYSTEM_UNIT_ID`       VARCHAR(255) COMMENT '系统单位ID',
   `CREATE_TIME`          TIMESTAMP COMMENT '创建时间',
   `CREATOR`              VARCHAR(255) COMMENT '创建人',
   `MODIFIER`             VARCHAR(255) COMMENT '更新人',
   `MODIFY_TIME`          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   PRIMARY KEY (`UUID`)
)COMMENT ='职等表';


drop table if exists `MULTI_ORG_JOB_LEVEL`;

CREATE TABLE `MULTI_ORG_JOB_LEVEL`
(
	`UUID`                 VARCHAR(64)    NOT NULL COMMENT '唯一主键',
	`JOB_RANK_UUID`        VARCHAR(64) COMMENT '职级UUID',
	`JOB_LEVEL`       VARCHAR(30) COMMENT '职档';,
	`JOB_LEVEL_SEQ`        INT(4) COMMENT '职档序号',
	`REC_VER`       DECIMAL(10,2) COMMENT '版本号',
	`SYSTEM_UNIT_ID` VARCHAR(255) COMMENT '系统单位ID',
	`CREATE_TIME`          TIMESTAMP COMMENT '创建时间',
	`CREATOR`              VARCHAR(255) COMMENT '创建人',
	`MODIFIER`             VARCHAR(255) COMMENT '更新人',
	`MODIFY_TIME`          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
     PRIMARY KEY (`UUID`)
)COMMENT = '职档表';

drop table if exists `MULTI_ORG_JOB_RANK_LEVEL_RELAT`;

CREATE TABLE `MULTI_ORG_JOB_RANK_LEVEL`
(
   `UUID`                 VARCHAR(64)    NOT NULL COMMENT '唯一主键',
   `USER_ID`			VARCHAR(64)    NOT NULL COMMENT '用户ID',
   `JOB_ID`               VARCHAR(64) COMMENT '职位ID',
   `JOB_RANK_ID`    VARCHAR(1000) COMMENT '职级',
   `JOB_LEVEL`            VARCHAR(30) COMMENT '职档',     
   `REC_VER`       DECIMAL(10,2) COMMENT '版本号',
   `SYSTEM_UNIT_ID` VARCHAR(255) COMMENT'系统单位ID',
   `CREATE_TIME`          TIMESTAMP COMMENT '创建时间',
   `CREATOR`              VARCHAR(255) COMMENT '创建人',
   `MODIFIER`            VARCHAR(255) COMMENT '更新人',
   `MODIFY_TIME`          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`UUID`)
)COMMENT = '用户职位职级职档关联表';