
ALTER TABLE MULTI_ORG_JOB_RANK MODIFY NAME NULL;
ALTER TABLE MULTI_ORG_JOB_RANK ADD JOB_RANK VARCHAR2(30 CHAR);
ALTER TABLE MULTI_ORG_JOB_RANK ADD DESCRIBE VARCHAR2(1000 CHAR);
ALTER TABLE MULTI_ORG_JOB_RANK ADD DUTY_SEQ_UUID VARCHAR2(64 CHAR);
ALTER TABLE MULTI_ORG_JOB_RANK ADD JOB_GRADE NUMBER(4);
ALTER TABLE MULTI_ORG_JOB_RANK ADD JOB_LEVEL VARCHAR2(10 CHAR);
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN MULTI_ORG_JOB_RANK.JOB_RANK
  IS '职级';
COMMENT ON COLUMN MULTI_ORG_JOB_RANK.DESCRIBE
  IS '描述';
COMMENT ON COLUMN MULTI_ORG_JOB_RANK.DUTY_SEQ_UUID
  IS '职务序列UUID';
COMMENT ON COLUMN MULTI_ORG_JOB_RANK.JOB_GRADE
  IS '职等';
COMMENT ON COLUMN MULTI_ORG_JOB_RANK.JOB_LEVEL
  IS '职档';
---修改职级有约束
create table table_temp(
     constraint_name  varchar2(1000),
     search_condition CLOB
);

----金仓数据库请替换下面sql   insert into  table_temp select constraint_name, search_condition aa from sys.user_constraints where table_name='MULTI_ORG_JOB_RANK' ;
insert into  table_temp select constraint_name, to_lob(search_condition) aa from sys.user_constraints where table_name='MULTI_ORG_JOB_RANK' ;
begin
  for  t in (select  constraint_name as c_name from table_temp WHERE to_char(search_condition)='"NAME" IS NOT NULL') loop
   execute immediate 'ALTER TABLE MULTI_ORG_JOB_RANK DROP CONSTRAINT '||t.c_name;
  end loop;
end; 
drop table table_temp;  
  
-- ADD/MODIFY COLUMNS 
ALTER TABLE MULTI_ORG_DUTY ADD DUTY_SEQ_UUID VARCHAR2(64 CHAR);
-- ADD/MODIFY COLUMNS 
ALTER TABLE MULTI_ORG_DUTY ADD DUTY_SEQ_NAME VARCHAR2(255 CHAR);

ALTER TABLE MULTI_ORG_DUTY ADD JOB_RANK VARCHAR2(1000 CHAR);
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN MULTI_ORG_DUTY.DUTY_SEQ_UUID
  IS '职务序列UUID';
  -- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN MULTI_ORG_DUTY.DUTY_SEQ_NAME
  IS '职务序列名称';
COMMENT ON COLUMN MULTI_ORG_DUTY.JOB_RANK
  IS '职级';
  -- Add/modify columns 
ALTER TABLE MULTI_ORG_DUTY ADD JOB_GRADE VARCHAR2(1000 CHAR);
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN MULTI_ORG_DUTY.JOB_GRADE
  IS '职等';  
  
  
 -- ADD/MODIFY COLUMNS 
ALTER TABLE MULTI_ORG_USER_WORK_INFO ADD JOB_RANK VARCHAR2(30 CHAR);
ALTER TABLE MULTI_ORG_USER_WORK_INFO ADD JOB_LEVEL VARCHAR2(255 CHAR);
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN MULTI_ORG_USER_WORK_INFO.JOB_RANK IS '职级';
COMMENT ON COLUMN MULTI_ORG_USER_WORK_INFO.JOB_LEVEL  IS '职档';
  

CREATE TABLE UNIT_PARAM
(
  UUID           VARCHAR2(64 CHAR)   NOT NULL,
  Param_KEY            VARCHAR2(255 CHAR),
  Param_VALUE          VARCHAR2(500 CHAR),
  REMARK         VARCHAR2(1000 CHAR),
  REC_VER       NUMBER(10,2),
  SYSTEM_UNIT_ID VARCHAR2(255 CHAR),
	CREATE_TIME          TIMESTAMP,
	CREATOR              VARCHAR2(255 BYTE),
	MODIFIER             VARCHAR2(255 BYTE),
	MODIFY_TIME          TIMESTAMP,
  CONSTRAINT UNIT_PARAM_PK PRIMARY KEY (UUID)
);
COMMENT ON TABLE UNIT_PARAM
  IS '单位参数表';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN UNIT_PARAM.UUID
  IS 'UUID';
COMMENT ON COLUMN UNIT_PARAM.Param_KEY
  IS '保存KEY';
COMMENT ON COLUMN UNIT_PARAM.Param_VALUE
  IS '保存VALUE';
COMMENT ON COLUMN UNIT_PARAM.REMARK
  IS '备注';
COMMENT ON COLUMN UNIT_PARAM.SYSTEM_UNIT_ID
  IS '系统单位';
  
  
  -- CREATE TABLE
CREATE TABLE ORG_DUTY_SEQ
(
  UUID           VARCHAR2(64 CHAR)   NOT NULL,
  DUTY_SEQ_CODE           VARCHAR2(50 CHAR),
  DUTY_SEQ_NAME           VARCHAR2(50 CHAR),
  ICON           VARCHAR2(100 CHAR),
  BACKGROUND_COLOR     VARCHAR2(255 CHAR),
  DESCRIBE       VARCHAR2(1000 CHAR),
  PARENT_UUID    VARCHAR2(64 CHAR),
  REC_VER       NUMBER(10,2),
  SYSTEM_UNIT_ID VARCHAR2(255 CHAR),
  CREATE_TIME    TIMESTAMP,
  CREATOR        VARCHAR2(255 CHAR),
  MODIFY_TIME    TIMESTAMP,
  MODIFIER       VARCHAR2(255 CHAR),
  CONSTRAINT ORG_DUTY_SEQ_PK PRIMARY KEY (UUID)
)
;
-- ADD COMMENTS TO THE TABLE 
COMMENT ON TABLE ORG_DUTY_SEQ
  IS '职务序列';
-- ADD COMMENTS TO THE COLUMNS 
COMMENT ON COLUMN ORG_DUTY_SEQ.UUID
  IS '主键UUID';
COMMENT ON COLUMN ORG_DUTY_SEQ.DUTY_SEQ_CODE
  IS '职务序列编号';
COMMENT ON COLUMN ORG_DUTY_SEQ.DUTY_SEQ_NAME
  IS '职务序列名称';
COMMENT ON COLUMN ORG_DUTY_SEQ.ICON
  IS '图标';
COMMENT ON COLUMN ORG_DUTY_SEQ.DESCRIBE
  IS '描述';
COMMENT ON COLUMN ORG_DUTY_SEQ.PARENT_UUID
  IS '父类UUID';
COMMENT ON COLUMN ORG_DUTY_SEQ.SYSTEM_UNIT_ID
  IS '系统单位';
COMMENT ON COLUMN ORG_DUTY_SEQ.CREATE_TIME
  IS '创建时间';
COMMENT ON COLUMN ORG_DUTY_SEQ.CREATOR
  IS '创建人';
COMMENT ON COLUMN ORG_DUTY_SEQ.MODIFY_TIME
  IS '更新时间';
COMMENT ON COLUMN ORG_DUTY_SEQ.MODIFIER
  is '更新人';

  
CREATE TABLE ORG_JOB_GRADE 
(
   UUID                 VARCHAR2(255 BYTE)   NOT NULL,
   JOB_GRADE            NUMBER(4),
   JOB_GRADE_NAME       VARCHAR2(50 BYTE),
   DESCRIBE             VARCHAR2(1000 BYTE),
   IS_VALID       CHAR(1),
   IS_EXCEPTION   CHAR(1),
   REC_VER       NUMBER(10,2),
   SYSTEM_UNIT_ID       VARCHAR2(255 BYTE),
   CREATE_TIME          TIMESTAMP,
   CREATOR              VARCHAR2(255 BYTE),
   MODIFIER             VARCHAR2(255 BYTE),
   MODIFY_TIME          TIMESTAMP,
   CONSTRAINT PK_ORG_JOB_GRADE PRIMARY KEY (UUID)
);

COMMENT ON TABLE ORG_JOB_GRADE IS
'职等表';

COMMENT ON COLUMN ORG_JOB_GRADE.UUID IS
'唯一主键';

COMMENT ON COLUMN ORG_JOB_GRADE.JOB_GRADE IS
'职等';

COMMENT ON COLUMN ORG_JOB_GRADE.JOB_GRADE_NAME IS '职等名字';
COMMENT ON COLUMN ORG_JOB_GRADE.DESCRIBE IS '描述';
comment on column ORG_JOB_GRADE.IS_VALID is '是否有效：1有效,0无效';
comment on column ORG_JOB_GRADE.IS_VALID is '是否异常：1异常，0无异常';
COMMENT ON COLUMN ORG_JOB_GRADE.SYSTEM_UNIT_ID IS
'系统单位ID';

COMMENT ON COLUMN ORG_JOB_GRADE.CREATE_TIME IS
'创建时间';

COMMENT ON COLUMN ORG_JOB_GRADE.CREATOR IS
'创建人';

COMMENT ON COLUMN ORG_JOB_GRADE.MODIFIER IS
'更新人';

COMMENT ON COLUMN ORG_JOB_GRADE.MODIFY_TIME IS
'更新时间';


CREATE TABLE MULTI_ORG_JOB_LEVEL 
(
   UUID                 VARCHAR2(64 BYTE)    NOT NULL,
   JOB_RANK_UUID        VARCHAR2(64 BYTE),
   JOB_LEVEL       VARCHAR2(30 BYTE),
   JOB_LEVEL_SEQ        NUMBER(4),
   REC_VER       NUMBER(10,2),
  SYSTEM_UNIT_ID VARCHAR2(255 CHAR),
	CREATE_TIME          TIMESTAMP,
	CREATOR              VARCHAR2(255 BYTE),
	MODIFIER             VARCHAR2(255 BYTE),
	MODIFY_TIME          TIMESTAMP,
   CONSTRAINT PK_MULTI_ORG_JOB_LEVEL PRIMARY KEY (UUID)
);

COMMENT ON TABLE MULTI_ORG_JOB_LEVEL IS
'职档表';

COMMENT ON COLUMN MULTI_ORG_JOB_LEVEL.UUID IS
'唯一主键';

COMMENT ON COLUMN MULTI_ORG_JOB_LEVEL.JOB_RANK_UUID IS
'职级';

COMMENT ON COLUMN MULTI_ORG_JOB_LEVEL.JOB_LEVEL IS
'职档';

COMMENT ON COLUMN MULTI_ORG_JOB_LEVEL.JOB_LEVEL_SEQ IS
'职档序号';


CREATE TABLE MULTI_ORG_JOB_RANK_LEVEL
(
   UUID                 VARCHAR2(64 BYTE)    NOT NULL,
   USER_ID			VARCHAR2(64 BYTE)    NOT NULL,
   JOB_ID               VARCHAR2(64 BYTE),
   JOB_RANK_ID    VARCHAR2(1000),
   JOB_LEVEL            VARCHAR2(30 BYTE),     
   REC_VER       NUMBER(10,2),
   SYSTEM_UNIT_ID VARCHAR2(255 CHAR),
   CREATE_TIME          TIMESTAMP,
   CREATOR              VARCHAR2(255 BYTE),
   MODIFIER             VARCHAR2(255 BYTE),
   MODIFY_TIME          TIMESTAMP,
   CONSTRAINT PK_MULTI_ORG_JOB_RANK_LEVEL_RE PRIMARY KEY (UUID)
);

COMMENT ON TABLE MULTI_ORG_JOB_RANK_LEVEL IS
'用户职位职级职档关联表';

COMMENT ON COLUMN MULTI_ORG_JOB_RANK_LEVEL.USER_ID IS
'用户ID';

COMMENT ON COLUMN MULTI_ORG_JOB_RANK_LEVEL.JOB_ID IS
'职位ID';

COMMENT ON COLUMN MULTI_ORG_JOB_RANK_LEVEL.JOB_RANK_ID IS
'职级';

COMMENT ON COLUMN MULTI_ORG_JOB_RANK_LEVEL.JOB_LEVEL IS
'职档';