-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
CREATE TABLE "PSI_BUSINESS_ROLE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "ROLE_NAME" VARCHAR2(255 CHAR), 
  "ROLE_VALUE" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "PSI_PLACEFILE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "FILE_CONTENT" VARCHAR2(255 CHAR), 
  "FILE_DATE" TIMESTAMP (6), 
  "FILE_PLACE" VARCHAR2(255 CHAR), 
  "FILE_TYPE" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "PSI_STOCK" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "BALANCE" NUMBER(19,0) NOT NULL ENABLE, 
  "FROM_DYTABLE" VARCHAR2(255 CHAR), 
  "FROM_DYTABLE_ID" VARCHAR2(255 CHAR), 
  "ID" VARCHAR2(255 CHAR), 
  "LOWLIMIT" NUMBER(19,0) NOT NULL ENABLE, 
  "STOCK_CIRCLE" VARCHAR2(255 CHAR), 
  "STOCK_NAME" VARCHAR2(255 CHAR), 
  "STOCK_NUMBER" VARCHAR2(255 CHAR), 
  "STOCK_TYPE" VARCHAR2(255 CHAR), 
  "STOCK_UNIT" VARCHAR2(255 CHAR), 
  "TOPLIMIT" NUMBER(19,0) NOT NULL ENABLE
   ) ;
CREATE TABLE "PSI_STOCKFIELD" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "DESC_NAME" VARCHAR2(255 CHAR), 
  "FIELD_NAME" VARCHAR2(255 CHAR), 
  "FIELD_TYPE" VARCHAR2(255 CHAR), 
  "FIELD_VALUE1" TIMESTAMP (6), 
  "FIELD_VALUE2" VARCHAR2(255 CHAR), 
  "STOCK_NAME" VARCHAR2(255 CHAR), 
  "STOCK_UUID" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "PSI_VOLTAGE" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "VOLTAGE_ID" VARCHAR2(255 CHAR), 
  "VOLTAGE_INDEX" NUMBER(10,0) NOT NULL ENABLE, 
  "VOLTAGE_PARENT_ID" VARCHAR2(255 CHAR), 
  "VOLTAGE_TYPE" VARCHAR2(255 CHAR)
   ) ;
CREATE TABLE "PSI_ITEM_OPERATE_LOG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "DO_NUM" NUMBER(19,0), 
  "ITEM_NAME" VARCHAR2(255 CHAR), 
  "ITEM_UUID" VARCHAR2(255 CHAR), 
  "OPERATE_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;
CREATE TABLE "PSI_OPERATE_DEFINITION" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "FLOW_UUID" VARCHAR2(255 CHAR), 
  "FORM_UUID" VARCHAR2(255 CHAR), 
  "IS_USE_FLOW" NUMBER(1,0), 
  "NAME" VARCHAR2(255 CHAR), 
  "TYPE" NUMBER(10,0)
   ) ;
CREATE TABLE "PSI_OPERATE_LOG" 
   (  "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATE_TIME" TIMESTAMP (6), 
  "CREATOR" VARCHAR2(255 CHAR), 
  "MODIFIER" VARCHAR2(255 CHAR), 
  "MODIFY_TIME" TIMESTAMP (6), 
  "REC_VER" NUMBER(10,0), 
  "DATA_UUID" VARCHAR2(255 CHAR), 
  "DO_CREAT_TIME" TIMESTAMP (6), 
  "DO_PERSON" VARCHAR2(255 CHAR), 
  "DO_STATUS" VARCHAR2(255 CHAR), 
  "FLOW_INTANCE_UUID" VARCHAR2(255 CHAR), 
  "OPERATE_DEF_UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) ;

-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT
ALTER TABLE "PSI_OPERATE_LOG" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "PSI_ITEM_OPERATE_LOG" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "PSI_OPERATE_DEFINITION" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;
ALTER TABLE "PSI_BUSINESS_ROLE" ADD PRIMARY KEY ("UUID")
  USING INDEX  ENABLE;  