ALTER TABLE  APP_MODULE 
ADD (ICON VARCHAR(120));

COMMENT ON COLUMN  APP_MODULE.ICON IS '图标';
ALTER TABLE  APP_MODULE 
ADD (CATEGORY_UUID NUMBER(19));
 
  
ALTER TABLE  APP_PAGE_DEFINITION 
ADD (APP_ID VARCHAR(64));
ALTER TABLE APP_PAGE_DEFINITION DROP COLUMN CATEGORY_CODE;
ALTER TABLE APP_PAGE_DEFINITION DROP COLUMN CATEGORY_NAME;
CREATE INDEX  IDX_APP_PAGE_ID   ON  APP_PAGE_DEFINITION (ID);



ALTER TABLE APP_PAGE_RESOURCE DROP COLUMN CODE;
ALTER TABLE APP_PAGE_RESOURCE DROP COLUMN TYPE;
ALTER TABLE APP_PAGE_RESOURCE DROP COLUMN DEFINITION_JSON;
ALTER TABLE APP_PAGE_RESOURCE DROP COLUMN EXPORTABLE;
ALTER TABLE APP_PAGE_RESOURCE DROP COLUMN EXPORT_TYPE;
ALTER TABLE APP_PAGE_RESOURCE DROP COLUMN REMARK;


ALTER TABLE  APP_MODULE  ADD CONSTRAINT  IDX_UQ_APP_MODULE_ID  UNIQUE (ID);


ALTER TABLE APP_USER_WIDGET_DEFINITION ADD APP_ID VARCHAR2(64);
ALTER TABLE APP_USER_WIDGET_DEFINITION ADD TITLE VARCHAR2(120);
ALTER TABLE APP_USER_WIDGET_DEFINITION ADD REMARK VARCHAR2(300);
ALTER TABLE APP_USER_WIDGET_DEFINITION ADD ENABLED NUMBER(1) DEFAULT 1;




ALTER TABLE APP_PRODUCT ADD ICON VARCHAR2(64);
ALTER TABLE APP_PRODUCT ADD VERSION_NAME VARCHAR2(64);
ALTER TABLE APP_PRODUCT ADD CATEGORY_UUID NUMBER(19);
ALTER TABLE APP_PRODUCT ADD STATUS NUMBER(1) default 0;

COMMENT ON COLUMN APP_PRODUCT.VERSION_NAME
  IS '产品版本名(如标准版\专业版\企业版)';
COMMENT ON COLUMN APP_PRODUCT.CATEGORY_UUID
  IS '产品分类';
  COMMENT ON COLUMN APP_PRODUCT.STATUS
  IS '状态: 0 构建中 1 已上线 2 已下线';




alter table AUDIT_PRIVILEGE
  drop constraint UK_8C43GP1X16UR7NM6TJ5Q15O8F cascade;
drop index UK_8C43GP1X16UR7NM6TJ5Q15O8F;
alter table APP_PAGE_DEFINITION add layout_fixed number(1) default 0;
comment on column APP_PAGE_DEFINITION.layout_fixed
  is '是否是固定布局的页面';



alter table APP_WIDGET_DEFINITION add main number(1) default 0;
alter table APP_WIDGET_DEFINITION add app_id varchar2(120);
comment on column APP_WIDGET_DEFINITION.main
  is '是否主组件';
comment on column APP_WIDGET_DEFINITION.app_id
  is '归属模块/产品版本ID';


alter table APP_PAGE_DEFINITION modify theme VARCHAR2(120 CHAR);

alter table APP_PAGE_DEFINITION add tenant VARCHAR2(120 CHAR);


alter table WF_DEF_CATEGORY add MODULE_ID varchar2(120);
COMMENT ON COLUMN WF_DEF_CATEGORY.MODULE_ID
  IS '归属模块';
  
  
alter table APP_PAGE_DEFINITION add is_anonymous NUMBER(1) default 0;
 comment on column APP_PAGE_DEFINITION.is_anonymous
  is '是否匿名访问页面';


-- Add/modify columns 
alter table APP_PAGE_RESOURCE add resource_id VARCHAR2(255 CHAR);
alter table APP_PAGE_RESOURCE add resource_type VARCHAR2(255 CHAR);
-- Add comments to the columns 
comment on column APP_PAGE_RESOURCE.resource_id
  is '关系资源：例如导航关联了页面';
comment on column APP_PAGE_RESOURCE.resource_type
  is '关系资源类型';
