-- Add/modify columns 
alter table APP_PAGE_DEFINITION add version VARCHAR2(50 CHAR) default '1.0';
alter table APP_PAGE_DEFINITION add app_pi_uuid VARCHAR2(255 CHAR);
-- Add comments to the columns 
comment on column APP_PAGE_DEFINITION.version
  is '版本号，默认1.0';
  
update APP_PAGE_DEFINITION t set t.code = t.id where t.code is null;
commit;
  
-- Add/modify columns 
alter table APP_PRODUCT_INTEGRATION add is_protected NUMBER(1) default 1;
-- Add comments to the columns 
comment on column APP_PRODUCT_INTEGRATION.is_protected
  is '功能资源是否受保护';

-- Create/Recreate indexes 
create index APP_WD_ID_IDX on APP_WIDGET_DEFINITION (id);


CREATE TABLE "APP_PAGE_RESOURCE" 
   (    "UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
    "CREATE_TIME" TIMESTAMP (6), 
    "CREATOR" VARCHAR2(255 CHAR), 
    "MODIFIER" VARCHAR2(255 CHAR), 
    "MODIFY_TIME" TIMESTAMP (6), 
    "REC_VER" NUMBER(10,0), 
    "IS_PROTECTED" NUMBER(1,0),
    "CONFIG_TYPE" VARCHAR2(255 CHAR), 
    "APP_PI_UUID" VARCHAR2(255 CHAR), 
    "APP_PAGE_UUID" VARCHAR2(255 CHAR), 
    "APP_FUNCTION_UUID" VARCHAR2(255 CHAR), 
     PRIMARY KEY ("UUID")
   );
 
   COMMENT ON COLUMN "APP_PAGE_RESOURCE"."UUID" IS 'UUID，系统字段';
 
   COMMENT ON COLUMN "APP_PAGE_RESOURCE"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "APP_PAGE_RESOURCE"."CREATOR" IS '创建人';
 
   COMMENT ON COLUMN "APP_PAGE_RESOURCE"."MODIFIER" IS '修改人';
 
   COMMENT ON COLUMN "APP_PAGE_RESOURCE"."MODIFY_TIME" IS '修改时间';
 
   COMMENT ON COLUMN "APP_PAGE_RESOURCE"."REC_VER" IS '版本号';
 
   COMMENT ON COLUMN "APP_PAGE_RESOURCE"."IS_PROTECTED" IS '资源是否受保护';
 
   COMMENT ON COLUMN "APP_PAGE_RESOURCE"."CONFIG_TYPE" IS '配置类型1、配置资源，2、开发资源';
   
   COMMENT ON COLUMN "APP_PAGE_RESOURCE"."APP_PI_UUID" IS '资源归属产品集成的UUID';
   
   COMMENT ON COLUMN "APP_PAGE_RESOURCE"."APP_PAGE_UUID" IS '资源归属页面的UUID';
   
   COMMENT ON COLUMN "APP_PAGE_RESOURCE"."APP_FUNCTION_UUID" IS '资源引用的功能UUID';
 
alter table APP_PAGE_RESOURCE add REMARK VARCHAR2(255 CHAR);
   
CREATE TABLE "APP_PAGE_DEFINITION_REF" 
   (    "UUID" VARCHAR2(50), 
    "CREATE_TIME" TIMESTAMP (6), 
    "CREATOR" VARCHAR2(50), 
    "MODIFY_TIME" TIMESTAMP (6), 
    "REC_VER" NUMBER(10,0), 
    "MODIFIER" VARCHAR2(50),
    "SYSTEM_UNIT_ID" VARCHAR2(50), 
    "REF_UUID" VARCHAR2(50), 
    "APP_PI_UUID" VARCHAR2(50 CHAR), 
     PRIMARY KEY ("UUID")
   );
   COMMENT ON COLUMN "APP_PAGE_DEFINITION_REF"."UUID" IS 'UUID，系统字段';
 
   COMMENT ON COLUMN "APP_PAGE_DEFINITION_REF"."CREATE_TIME" IS '创建时间';
 
   COMMENT ON COLUMN "APP_PAGE_DEFINITION_REF"."CREATOR" IS '创建人';
 
   COMMENT ON COLUMN "APP_PAGE_DEFINITION_REF"."MODIFIER" IS '修改人';
 
   COMMENT ON COLUMN "APP_PAGE_DEFINITION_REF"."MODIFY_TIME" IS '修改时间';
 
   COMMENT ON COLUMN "APP_PAGE_DEFINITION_REF"."REC_VER" IS '版本号';
 
   COMMENT ON COLUMN "APP_PAGE_DEFINITION_REF"."SYSTEM_UNIT_ID" IS '系统单位ID';
 
   COMMENT ON COLUMN "APP_PAGE_DEFINITION_REF"."REF_UUID" IS '引用的页面定义UUID';
 
   COMMENT ON COLUMN "APP_PAGE_DEFINITION_REF"."APP_PI_UUID" IS '所在产品集成UUID';
 
