CREATE TABLE "WF_TASK_FORM_ATTACHMENT" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"FLOW_INST_UUID" VARCHAR2(255 CHAR), 
	"DATA_UUID" VARCHAR2(255 CHAR), 
	"FIELD_NAME" VARCHAR2(255 CHAR), 
	"CONTENT" VARCHAR2(4000 CHAR), 
	 PRIMARY KEY ("UUID")
   );
   
COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT"."UUID" IS 'UUID，系统字段';
 
COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT"."CREATOR" IS '创建人';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT"."MODIFIER" IS '修改人';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT"."REC_VER" IS '版本号';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT"."FLOW_INST_UUID" IS '流程实例UUID';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT"."DATA_UUID" IS '表单数据UUID';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT"."FIELD_NAME" IS '表单附件域字段名';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT"."CONTENT" IS '表单附件域内容';




CREATE TABLE "WF_TASK_FORM_ATTACHMENT_LOG" 
   (	"UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATE_TIME" TIMESTAMP (6), 
	"CREATOR" VARCHAR2(255 CHAR), 
	"MODIFIER" VARCHAR2(255 CHAR), 
	"MODIFY_TIME" TIMESTAMP (6), 
	"REC_VER" NUMBER(10,0), 
	"FLOW_INST_UUID" VARCHAR2(255 CHAR), 
	"TASK_INST_UUID" VARCHAR2(255 CHAR), 
	"TASK_OPERATION_UUID" VARCHAR2(255 CHAR), 
	"TASK_FORM_ATTACHMENT_UUID" VARCHAR2(255 CHAR), 
	"FIELD_NAME" VARCHAR2(255 CHAR), 
	"CONTENT" VARCHAR2(2000 CHAR), 
	"OPERATE_TYPE" VARCHAR2(2 CHAR),
	 PRIMARY KEY ("UUID")
   );
   
COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."UUID" IS 'UUID，系统字段';
 
COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."CREATOR" IS '创建人';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."MODIFIER" IS '修改人';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."MODIFY_TIME" IS '修改时间';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."REC_VER" IS '版本号';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."FLOW_INST_UUID" IS '流程实例UUID';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."TASK_INST_UUID" IS '环节实例UUID';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."TASK_OPERATION_UUID" IS '环节操作UUID';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."TASK_FORM_ATTACHMENT_UUID" IS '附件记录UUID';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."FIELD_NAME" IS '表单附件域字段名';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."CONTENT" IS '表单附件域内容';

COMMENT ON COLUMN "WF_TASK_FORM_ATTACHMENT_LOG"."OPERATE_TYPE" IS '操作类型';

-- Create/Recreate indexes 
create index WF_TFA_FIFN_IDX_BATCH on WF_TASK_FORM_ATTACHMENT (flow_inst_uuid, field_name);

-- Create/Recreate indexes 
create index WF_TFO_FIDUFN_IDX_BATCH on WF_TASK_FORM_OPINION (flow_inst_uuid, data_uuid, field_name);
