ALTER TABLE WF_FLOW_INSTANCE ADD SYSTEM VARCHAR2(64);
ALTER TABLE WF_FLOW_INSTANCE ADD TENANT VARCHAR2(64);
 COMMENT ON COLUMN WF_FLOW_INSTANCE.SYSTEM
  IS '归属系统';
COMMENT ON COLUMN WF_FLOW_INSTANCE.TENANT
  IS '归属租户';

-- 更新流程实例归属系统同组织版本
UPDATE WF_FLOW_INSTANCE F SET F.SYSTEM = (SELECT V.SYSTEM FROM ORG_VERSION V WHERE V.ID=F.ORG_VERSION_ID) , F.TENANT ='T001';
