CREATE TABLE WF_FLOW_SIMULATION_SETTING
(
    "UUID"            NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"     TIMESTAMP(6),
    "CREATOR"         VARCHAR2(50 CHAR),
    "MODIFIER"        VARCHAR2(50 CHAR),
    "MODIFY_TIME"     TIMESTAMP(6),
    "REC_VER"         NUMBER(10, 0),
    "FLOW_DEF_UUID"   VARCHAR2(50 CHAR),
    "DEFINITION_JSON" CLOB,
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE WF_FLOW_SIMULATION_SETTING IS '流程仿真设置';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_SETTING.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_SETTING.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_SETTING.CREATOR IS '创建人';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_SETTING.MODIFIER IS '修改人';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_SETTING.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_SETTING.REC_VER IS '版本号';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_SETTING.FLOW_DEF_UUID IS '流程定义UUID';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_SETTING.DEFINITION_JSON IS '仿真设置JSON信息';



CREATE TABLE WF_FLOW_SIMULATION_RECORD
(
    "UUID"            NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"     TIMESTAMP(6),
    "CREATOR"         VARCHAR2(50 CHAR),
    "MODIFIER"        VARCHAR2(50 CHAR),
    "MODIFY_TIME"     TIMESTAMP(6),
    "REC_VER"         NUMBER(10, 0),
    "FLOW_INST_UUID"  VARCHAR2(50 CHAR),
    "FLOW_DEF_UUID"   VARCHAR2(50 CHAR),
    "FORM_UUID"       VARCHAR2(50 CHAR),
    "DATA_UUID"       VARCHAR2(50 CHAR),
    "OPERATOR_NAME"   VARCHAR2(150),
    "OPERATOR_ID"     VARCHAR2(50 CHAR),
    "OPERATOR_TIME"   TIMESTAMP(6),
    "START_USER_NAME" VARCHAR2(150),
    "START_USER_ID"   VARCHAR2(50 CHAR),
    "CONTENT_JSON"    CLOB,
    "STATE"           VARCHAR2(10 CHAR),
    "DELETE_STATUS"   NUMBER(10),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE WF_FLOW_SIMULATION_RECORD IS '流程仿真记录';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.CREATOR IS '创建人';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.MODIFIER IS '修改人';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.REC_VER IS '版本号';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.FLOW_INST_UUID IS '流程实例UUID';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.FLOW_DEF_UUID IS '流程定义UUID';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.FORM_UUID IS '表单定义UUID';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.DATA_UUID IS '表单数据UUID';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.OPERATOR_NAME IS '操作人名称';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.OPERATOR_ID IS '操作人ID';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.OPERATOR_TIME IS '操作时间';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.START_USER_NAME IS '发起人名称';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.START_USER_ID IS '发起人ID';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.CONTENT_JSON IS '操作内容JSON信息';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.STATE IS '仿真状态，running仿真中、pause暂停、success成功';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.DELETE_STATUS IS '删除状态,0正常，1逻辑删除';


CREATE TABLE WF_FLOW_SIMULATION_RECORD_ITEM
(
    "UUID"               NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"        TIMESTAMP(6),
    "CREATOR"            VARCHAR2(50 CHAR),
    "MODIFIER"           VARCHAR2(50 CHAR),
    "MODIFY_TIME"        TIMESTAMP(6),
    "REC_VER"            NUMBER(10, 0),
    "RECORD_UUID"        NUMBER(20, 0),
    "FLOW_INST_UUID"     VARCHAR2(50 CHAR),
    "TASK_INST_UUID"     VARCHAR2(50 CHAR),
    "TASK_NAME"          VARCHAR2(150),
    "TASK_ID"            VARCHAR2(50 CHAR),
    "PRE_TASK_INST_UUID" VARCHAR2(50 CHAR),
    "DETAILS"            CLOB,
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE WF_FLOW_SIMULATION_RECORD_ITEM IS '流程仿真记录';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.CREATOR IS '创建人';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.MODIFIER IS '修改人';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.REC_VER IS '版本号';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.RECORD_UUID IS '仿真记录UUID';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.FLOW_INST_UUID IS '流程实例UUID';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.TASK_INST_UUID IS '环节实例UUID';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.TASK_NAME IS '环节名称';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.TASK_ID IS '环节ID';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.PRE_TASK_INST_UUID IS '前一环节实例UUID';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD_ITEM.DETAILS IS '详细信息';


alter table WF_TASK_ACTIVITY
    add PRE_GATEWAY_IDS VARCHAR2(200 char);
COMMENT
    ON COLUMN WF_TASK_ACTIVITY.PRE_GATEWAY_IDS IS '前一网关ID节点，多个以分号隔开';


alter table WF_FLOW_SIMULATION_RECORD
    add SYSTEM VARCHAR2(50 char);
alter table WF_FLOW_SIMULATION_RECORD
    add TENANT VARCHAR2(50 char);
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.SYSTEM IS '归属系统';
COMMENT
    ON COLUMN WF_FLOW_SIMULATION_RECORD.TENANT IS '归属租户';