CREATE TABLE ACL_TASK_READ_MARKER
(
    "UUID"          NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"   TIMESTAMP(6),
    "CREATOR"       VARCHAR2(50 CHAR),
    "MODIFIER"      VARCHAR2(50 CHAR),
    "MODIFY_TIME"   TIMESTAMP(6),
    "REC_VER"       NUMBER(10, 0),
    "ACL_TASK_UUID" VARCHAR2(50 CHAR),
    "USER_ID"       VARCHAR2(50 CHAR),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE ACL_TASK_READ_MARKER IS '流程权限大于用户颗粒度的已阅用户信息';
COMMENT
    ON COLUMN ACL_TASK_READ_MARKER.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN ACL_TASK_READ_MARKER.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN ACL_TASK_READ_MARKER.CREATOR IS '创建人';
COMMENT
    ON COLUMN ACL_TASK_READ_MARKER.MODIFIER IS '修改人';
COMMENT
    ON COLUMN ACL_TASK_READ_MARKER.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN ACL_TASK_READ_MARKER.REC_VER IS '版本号';
COMMENT
    ON COLUMN ACL_TASK_READ_MARKER.ACL_TASK_UUID IS '权限数据UUID';
COMMENT
    ON COLUMN ACL_TASK_READ_MARKER.USER_ID IS '已阅用户ID';

CREATE INDEX ACL_TRM_ACL_TASK_UUID_IDX ON ACL_TASK_READ_MARKER (ACL_TASK_UUID);


CREATE TABLE ACL_TASK_DONE_MARKER
(
    "UUID"          NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"   TIMESTAMP(6),
    "CREATOR"       VARCHAR2(50 CHAR),
    "MODIFIER"      VARCHAR2(50 CHAR),
    "MODIFY_TIME"   TIMESTAMP(6),
    "REC_VER"       NUMBER(10, 0),
    "ACL_TASK_UUID" VARCHAR2(50 CHAR),
    "USER_ID"       VARCHAR2(50 CHAR),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE ACL_TASK_DONE_MARKER IS '流程权限大于用户颗粒度的已办用户信息';
COMMENT
    ON COLUMN ACL_TASK_DONE_MARKER.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN ACL_TASK_DONE_MARKER.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN ACL_TASK_DONE_MARKER.CREATOR IS '创建人';
COMMENT
    ON COLUMN ACL_TASK_DONE_MARKER.MODIFIER IS '修改人';
COMMENT
    ON COLUMN ACL_TASK_DONE_MARKER.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN ACL_TASK_DONE_MARKER.REC_VER IS '版本号';
COMMENT
    ON COLUMN ACL_TASK_DONE_MARKER.ACL_TASK_UUID IS '权限数据UUID';
COMMENT
    ON COLUMN ACL_TASK_DONE_MARKER.USER_ID IS '已办用户ID';

CREATE INDEX ACL_TDM_ACL_TASK_UUID_IDX ON ACL_TASK_DONE_MARKER (ACL_TASK_UUID);
