CREATE TABLE "ACL_TASK_ENTRY"
   ("UUID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"READ_AUTH" NUMBER(1,0) DEFAULT 0,
	"SID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"OBJECT_ID_IDENTITY" VARCHAR2(64 CHAR),
	"REC_VER" NUMBER,
	"CREATOR" VARCHAR2(255),
	"CREATE_TIME" TIMESTAMP (6),
	"MODIFIER" VARCHAR2(255),
	"MODIFY_TIME" TIMESTAMP (6),
	"IS_SYN_BACK" VARCHAR2(255 CHAR),
	"TODO_AUTH" NUMBER(1,0) DEFAULT 0,
	"DONE_AUTH" NUMBER(1,0) DEFAULT 0,
	"ATTENTION_AUTH" NUMBER(1,0) DEFAULT 0,
	"UNREAD_AUTH" NUMBER(1,0) DEFAULT 0,
	"FLAG_READ_AUTH" NUMBER(1,0) DEFAULT 0,
	"SUPERVISE_AUTH" NUMBER(1,0) DEFAULT 0,
	"MONITOR_AUTH" NUMBER(1,0) DEFAULT 0,
	  PRIMARY KEY ("UUID")
   ) ;

COMMENT ON COLUMN ACL_TASK_ENTRY.READ_AUTH IS '查阅';
COMMENT ON COLUMN ACL_TASK_ENTRY.SID IS '身份标识';
COMMENT ON COLUMN ACL_TASK_ENTRY.OBJECT_ID_IDENTITY IS '环节实例ID';
COMMENT ON COLUMN ACL_TASK_ENTRY.TODO_AUTH IS '待办';
COMMENT ON COLUMN ACL_TASK_ENTRY.DONE_AUTH IS '已办';
COMMENT ON COLUMN ACL_TASK_ENTRY.ATTENTION_AUTH IS '关注';
COMMENT ON COLUMN ACL_TASK_ENTRY.UNREAD_AUTH IS '未阅';
COMMENT ON COLUMN ACL_TASK_ENTRY.FLAG_READ_AUTH IS '已阅';
COMMENT ON COLUMN ACL_TASK_ENTRY.SUPERVISE_AUTH IS '督办';
COMMENT ON COLUMN ACL_TASK_ENTRY.MONITOR_AUTH IS '监控';

CREATE INDEX "ACL_TASK_ENTRY_IDENTITY_IDX" ON "ACL_TASK_ENTRY" ("OBJECT_ID_IDENTITY", "SID") ;

CREATE INDEX "ACL_TASK_ENTRY_SID_IDX" ON "ACL_TASK_ENTRY" ("SID")  ;

