CREATE TABLE WF_COMMON_DELEGATION_SETTING
(
    "UUID"            NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"     TIMESTAMP(6),
    "CREATOR"         VARCHAR2(50 CHAR),
    "MODIFIER"        VARCHAR2(50 CHAR),
    "MODIFY_TIME"     TIMESTAMP(6),
    "REC_VER"         NUMBER(10, 0),
    "SYSTEM"          VARCHAR2(64 CHAR),
    "TENANT"          VARCHAR2(64 CHAR),
    "NAME"            VARCHAR2(100),
    "USER_ID"         VARCHAR2(50 CHAR),
    "DEFINITION_JSON" CLOB,
    "USED_COUNT"      NUMBER(10, 0),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE WF_COMMON_DELEGATION_SETTING IS '流程常用工作委托设置';
COMMENT
    ON COLUMN WF_COMMON_DELEGATION_SETTING.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN WF_COMMON_DELEGATION_SETTING.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN WF_COMMON_DELEGATION_SETTING.CREATOR IS '创建人';
COMMENT
    ON COLUMN WF_COMMON_DELEGATION_SETTING.MODIFIER IS '修改人';
COMMENT
    ON COLUMN WF_COMMON_DELEGATION_SETTING.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN WF_COMMON_DELEGATION_SETTING.REC_VER IS '版本号';
COMMENT
    ON COLUMN WF_COMMON_DELEGATION_SETTING.SYSTEM IS '归属系统';
COMMENT
    ON COLUMN WF_COMMON_DELEGATION_SETTING.TENANT IS '归属租户';
COMMENT
    ON COLUMN WF_COMMON_DELEGATION_SETTING.NAME IS '常用委托名称';
COMMENT
    ON COLUMN WF_COMMON_DELEGATION_SETTING.USER_ID IS '用户ID';
COMMENT
    ON COLUMN WF_COMMON_DELEGATION_SETTING.DEFINITION_JSON IS '委托定义JSON';
COMMENT
    ON COLUMN WF_COMMON_DELEGATION_SETTING.USED_COUNT IS '使用次数';
