alter table WF_FLOW_DELEGATION_SETTINGS
    add SYSTEM varchar(64);
alter table WF_FLOW_DELEGATION_SETTINGS
    add TENANT varchar(64);
COMMENT
    ON COLUMN WF_FLOW_DELEGATION_SETTINGS.SYSTEM IS '归属系统';
COMMENT
    ON COLUMN WF_FLOW_DELEGATION_SETTINGS.TENANT IS '归属租户';