CREATE TABLE WF_TASK_TODO_TEMP
(
    "UUID"              NUMBER(20, 0) NOT NULL,
    "CREATE_TIME"       TIMESTAMP(6),
    "CREATOR"           VARCHAR2(50 CHAR),
    "MODIFIER"          VARCHAR2(50 CHAR),
    "MODIFY_TIME"       TIMESTAMP(6),
    "REC_VER"           NUMBER(10, 0),
    "SYSTEM"            VARCHAR2(64 CHAR),
    "TENANT"            VARCHAR2(64 CHAR),
    "TITLE"             VARCHAR2(255 CHAR),
    "FLOW_INST_UUID"    VARCHAR2(50 CHAR),
    "TASK_INST_UUID"    VARCHAR2(50 CHAR),
    "TASK_INST_REC_VER" NUMBER(10, 0),
    "USER_ID"           VARCHAR2(50 CHAR),
    "FORM_UUID"         VARCHAR2(50 CHAR),
    "DATA_UUID"         VARCHAR2(50 CHAR),
    "FORM_DATA"         CLOB,
    "OPINION_LABEL"     VARCHAR2(50 CHAR),
    "OPINION_VALUE"     VARCHAR2(50 CHAR),
    "OPINION_TEXT"      VARCHAR2(4000 CHAR),
    "OPINION_FILE_IDS"  VARCHAR2(4000 CHAR),
    PRIMARY KEY ("UUID")
);

COMMENT
    ON TABLE WF_TASK_TODO_TEMP IS '用户待办临时数据';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.UUID IS 'UUID，系统字段';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.CREATE_TIME IS '创建时间';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.CREATOR IS '创建人';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.MODIFIER IS '修改人';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.MODIFY_TIME IS '修改时间';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.REC_VER IS '版本号';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.SYSTEM IS '归属系统';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.TENANT IS '归属租户';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.TITLE IS '流程标题';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.FLOW_INST_UUID IS '流程实例UUID';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.TASK_INST_UUID IS '环节实例UUID';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.TASK_INST_REC_VER IS '环节实例版本号';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.USER_ID IS '用户ID';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.FORM_UUID IS '表单定义UUID';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.DATA_UUID IS '表单数据UUID';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.FORM_DATA IS '表单数据';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.OPINION_LABEL IS '意见立场文本';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.OPINION_VALUE IS '意见立场值';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.OPINION_TEXT IS '意见内容';
COMMENT
    ON COLUMN WF_TASK_TODO_TEMP.OPINION_FILE_IDS IS '意见附件ID';

